### ISSUE TITLE
Potion doesn't work while silenced

### ISSUE THREAD

**Issue by Inames** [torilmud/issues#1001]
This potion works fine.

![image](https://github.com/torilmud/issues/assets/24944665/abfa4565-32d8-4e93-9299-f9f67c80e20d)

--------------------------------

This potion completely fails, you don't get the dispel, you don't get the other spells, the game spams you with 3 lines saying "You need to be able to speak to do that." or whatever the message is, I forgot to grab a screenshot of it, but just try using it while silenced and you'll see.

![image](https://github.com/torilmud/issues/assets/24944665/01ab25bc-b2ac-4db0-b250-b70b2f8376c3)

**Comment by Inames** [comment]
This potion when not silenced, applies the dispelmagic effect, but then fails to apply the reduce and bless effects afterward, saying "You're not ready to perform another action!"

![image](https://github.com/torilmud/issues/assets/24944665/a42be00d-7afe-47cd-92bf-4c83a533ef65)

**Comment by shevarash** [comment]
This has been fixed in [today's update](https://discord.com/channels/341000942881341443/576443400925085717/1303884727316647977). 

Thank you!
