### ISSUE TITLE
bash's vs hex AWG showing as misses, still hitting

### ISSUE THREAD

**Issue by xanza-tey** [torilmud/issues#1006]
bashes from mobs on hexblades, with AWG up are showing as missed, but still landing. Think this is the damage reduction from AWG?

< |ms   +|ws   +|mb   +|      |      |mm   +|ff   +|      |dm  10|awg 11| >
< |ss   2|tg   +|tt   +|      |ht   +|hf   +|hm  15|      |sv   +|er   +| >
< 807h/807H 155v/155V (3) [Tank: Teyashigo  100%] [Target: duergar  87%] EP: std P: std >     

Your massive bludgeon barely wounds the duergar war master.
Your massive slash barely wounds the duergar war master.
Your massive bludgeon barely wounds the duergar war master.
Your massive bludgeon brutally wounds the duergar war master.
The duergar war master misses you with his hit.
You dodge a bash from the duergar war master, who loses his balance and falls.

< |ms   +|ws   +|mb   +|      |      |mm   +|ff   +|      |dm  10|awg 11| >
< |ss   2|tg   +|tt   +|      |ht   +|hf   +|hm  15|      |sv   +|er   +| >
< 807h/807H 155v/155V (3) [Tank: Teyashigo  100%  sit] [Target: duergar  85%] EP: std P: sit >

**Comment by Inames** [comment]
this has nothing to do with AWG, this is a known issue and referenced in 3 other open issues #910 #953 and #962

**Comment by xanza-tey** [comment]
> this has nothing to do with AWG, this is a known issue and referenced in 3 other open issues #910 #953 and #962

I mention AWG because it has a damage resistance modifier to it. So does wild magic shield, etc, which are up in those other posts.

It looks a lot like the damage reduction from the effects are reducing the damage of the power to zero, making it display as a miss, while still modifying position as a secondary effect.

It was also easily repeatable for me with awg, I tested it with and without to confirm that it was likely contributing in some way.

**Comment by marthammor** [comment]
Yes, if something does 0 damage you get a miss message while the status
effect goes through. Not sure what shev has planned to try to fix that.

**Comment by shevarash** [comment]
This was fixed. Thanks for the report!
