### ISSUE TITLE
Protect Undead / Protection from Undead

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#101]
Protection from undead is 2nd circle. Protect undead is 7th circle

The 2nd circle spell is better by far. It has more ac, and is castable on anyone (including undead). The 7th circle spell is castable on undead only, for less protection then the 2nd circle pfu.

Perhaps change protect undead to blur, undead only?

Name             : Protection From Undead   
Alias            : pfu                      
Type             : Spell                    
Source           : Arcane                   
Prepare          : Study                    
Target           : Character in room
Activation Time  : 6 seconds 
Related Skill    : spellcast necromancy
Restrictions     : Autofire, Garrote, Standing, Can Speak
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Target Effect    : Add protection from undead for 6 minutes 2 seconds 1 pulse  
Target Effect    : Modify armor by -54 for 6 minutes 2 seconds 1 pulse  

Name             : Protect Undead           
Alias            : pu                       
Type             : Spell                    
Source           : Arcane                   
Prepare          : Study                    
Target           : Character in room
Activation Time  : 6 seconds 
Related Skill    : spellcast necromancy
Conflicts        : Protection From Undead
Restrictions     : Autofire, Garrote, Standing, Can Speak, Target Undead
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Target Effect    : Add protection from undead for 6 minutes 2 seconds 1 pulse  
Target Effect    : Modify armor by -24 for 6 minutes 2 seconds 1 pulse

**Comment by Nyyrazzilyss** [comment]
Perhaps change protect undead to blur, undead only?

**Comment by Alurissi** [comment]
i do believe the protection from undead is incorrect, as it should not be granting armor to the target, merely making it harder for undeads to hit the affected.  Protect undead does read correctly, wherein it should be giving armor spell to the undead target, but i'm also thinking it is susposed to begiving the undead pfg and pfe as well, and some sv_spell, i could be incorrect, been a while since i found necromancer being in my generally played list

**Comment by shevarash** [comment]
This will be addressed in an upcoming Necromancer class overhaul.
