### ISSUE TITLE
things about anti-paladin

### ISSUE THREAD

**Issue by Alurissi** [torilmud/issues#103]
Plz, remove the following:

Spellcast teleportation
Spellcast spirit
spellcast nature

the class doesn't get any spells for these spellcasts

requesting: the ability to kick while mounted

also requesting a new mounted combat skill: trample -- wherein, a target that is on the ground is inflicted extra damage from the ap's mount running over or stomping upon it

ap's are evil.....after all

power heal mount, doesn't work

**Comment by shevarash** [comment]
What's wrong with power heal mount?

**Comment by ghost** [comment]
< 669h/669H 110v/110V >
< P: std > 
A vicious nightmare answers your summons!
A vicious nightmare starts following you.

< 669h/669H 110v/110V >
< P: std > hm
You don't see them here!

< 669h/669H 110v/110V >
< P: std > hm nightmare
You may not cast offensive spells on other players.

**Comment by beshaba-toril** [comment]
Harm and Heal Mount are both "hm" and it's defaulting to Harm.

**Comment by ghost** [comment]
seems that power dark wrath, is giving anti 3dam and -5spell, pretty sure that paladin's holy shroud is set to 3dam -3spell, might wanna balance these 2 out

**Comment by shevarash** [comment]
This class has been removed/overhauled/renamed. :)
