### ISSUE TITLE
Avatars not loading in Crypt of Dragons

### ISSUE THREAD

**Issue by Lilithelle** [torilmud/issues#1042]
Not certain, it could just be chance, but we haven't seen an avatar load in quite some time.  It might be that deaths triggered by powers don't always trigger the on death summoning of an avatar when priest of chronepsis and faluzure die.   This seems to happen with Tiamat consorts fairly often with molydeus not getting summoned, baby reds not getting summoned, and green not reappearing after "death".  I would appreciate this get a looking at please.

**Comment by shevarash** [comment]
I looked into the Tiamat consort issue and found the problem there. Those consorts have rather bespoke procs that left a moderate chance for some powers to bypass the procs. That'll be fixed shortly.

I'll look at the DCrypt issues next.

**Comment by shevarash** [comment]
I tested this by changing the percentage chance, and it seems to load fine for me on my development machine. I've added some logging so I can monitor it closer on the live game.

**Comment by shevarash** [comment]
```
*** D [ZONE]: Hook triggered for a dragon priest of Faluzure
*** D [ZONE]:  Rolled 96 with a 50 chance
*** D [ZONE]: ---> Exiting trigger due to failed chance roll
```

**Note**: This is not the actual chance, just an example I put in. This will log to disk each time the priest is killed. So now all you have to do is go kill him. 😈

**Comment by Lilithelle** [comment]
Cool, thanks so much!
    On Monday, April 22, 2024 at 06:08:17 p.m. PDT, shevarash ***@***.***> wrote:  
 
 

*** D [ZONE]: Hook triggered for a dragon priest of Faluzure
*** D [ZONE]:  Rolled 96 with a 50 chance
*** D [ZONE]: ---> Exiting trigger due to failed chance roll

Note: This is not the actual chance, just an example I put in. This will log to disk each time the priest is killed. So now all you have to do is go kill him. 😈

**Comment by shevarash** [comment]
This seems to be working, as it loaded the next time a group went in. We have the logs to inspect for future attempts as well. Closing.
