### ISSUE TITLE
Message when trying to put a bound weapon into a container

### ISSUE THREAD

**Issue by byzanthia** [torilmud/issues#1056]
```
< 936h/922H 180v/180V P: std >
< |ss +|sk +|ua +|ros +|sod +|cv +|cc +|wu +|nop +|ub +|ut +|hd +|dsd +|iw +|vip +| >     
put twilight hole
You can't put Twilight, the Harbinger of Destruction into an account bound container.

```
Hmm, the portable hole is not an account bound container. Should that read "into a container that is not account bound" instead?

**Comment by shevarash** [comment]
This has been fixed in [today's update](https://discord.com/channels/341000942881341443/576443400925085717/1303884727316647977). 

Thank you!
