### ISSUE TITLE
Hellstrike aoe component uses spellpower, not attack power

### ISSUE THREAD

**Issue by GeneralGormal** [torilmud/issues#1069]
Name             : Hellstrike [hs]
Type             : Melee                    
Attack Type      : Armor                    
Target           : Offense
Recharge         : 12 seconds 
Implements       : Weapon, Two handed
Restrictions     : Standing, Can See

Effects:
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Target Effect    : Deal 25% of attack power (179) as fire damage      
Target Effect    : Deal 50% of spell power (170) as fire damage       Radius: Small 
Target Effect    : Apply power Hellish Impact                         
Self Effect      : Generate 2.00 Combo

**Comment by shevarash** [comment]
This has been fixed in [today's update](https://discord.com/channels/341000942881341443/576443400925085717/1300534363859058729). 

Thank you!
