### ISSUE TITLE
Scornubel Vault

### ISSUE THREAD

**Issue by Adriorn** [torilmud/issues#108]
Can someone check if the chests and mobs inside are working as is?  There are 0 items that load in the chests...

**Comment by shevarash** [comment]
It's been awhile since I've been in Scornubel Vault. Has it always been that way, or has something changed recently?

**Comment by Adriorn** [comment]
No idea, it's been years.  There are 4 chests that load in there, with no items inside except 50 silver and 50 copper.  Makes no sense; almost as if something used to load but stopped loading or something.

**Comment by Inames** [comment]
I didn't even know scorn had a vault... 13 years into the game and still learning!

**Comment by ghost** [comment]
so like, i'm the one who told you about scorn vault, from what i can remember, there was something rare in there, possibly dealing with black eyepatch quest, on a rare named mob.....which seems to be gone from scorn as well as the quest and eq on body parts, and as far as the chests, something needs to be done with them, first off, they need to be made !pick, and 2ndly, the weak cash is a joke, need some actual funness in there, as you get keys doing the not so fun fights, nifty trinkets should be shoved in those things, so when a group goes to scorn, they can clear crypts and the vault, and get eqs, perhaps new stuff, or just some older stuff, or even copies of stuff, such as, maybe 1 chest has a 30% chance to load a cuendillar heartstone of magic........or maybe a fiery crown, or somethng else special enough to see it done.............as far as a recent change, no, i'm fairly certain vault was messed up when black eyepatch was removed, gruumsh found an error a while ago that dark dagger tattoo was never loading, i wouldn't be surprised to see other things were fubar'd in scorn files YEARS ago

**Comment by gruumsh** [comment]
> Can someone check if the chests and mobs inside are working as is? There are 0 items that load in the chests...

Verified, working correctly. What's supposed to load in there is loading.

But it does seem underwhelming, needs to be redone or revisited by other quests.
