### ISSUE TITLE
Torins - Request to add to Ranger and Hexblade

### ISSUE THREAD

**Issue by torkur** [torilmud/issues#1082]
With all the epic weapons in the class re-working I figured I'd ask if Torins (an ancient mithril warhammer) can be reviewed again on the "can't use as a ranger or Hexblade" decision. It looks cool, as a good theme and quest, but the chain lightning is far from powerful compared to some of the new weapons and procs. It also is dwarf only and currently only dual wieldable by warriors....which get no powers for dual wielding. I'd love to be able to dual wield them to match the mithril set for fun/options even if they aren't BIS though, hence the ask.

**Comment by shevarash** [comment]
This has been added in [today's update](https://discord.com/channels/341000942881341443/576443400925085717/1300534408436125798). 

Thank you!
