### ISSUE TITLE
No message when Impulsive Dread if applied from Dominating Smite no 

### ISSUE THREAD

**Issue by mrizzalazzrazzi** [torilmud/issues#1100]
From Dominating Smite power info,

Name             : Dominating Smite [ds]
Type             : Melee                    
Attack Type      : Armor                    
Target           : Offense, Character in room
Recharge         : 12 seconds 
Implements       : Weapon, Shield, One handed
Restrictions     : Standing, Can See
To-Hit Mods      : Level Diff +1, Str 25%, Hit Roll 300%

Effects:
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Target Effect    : Strike with all weapons for 100% (Weapon, Shield, One handed) 
Target Effect    : Change position to Prone                           
                   Restrictions: Ground, Immaterial, Size 1, Target Standing
Target Effect    : Wait for 12 seconds                                
Target Effect    : Strike with all weapons for 200% (Weapon, Shield, One handed) Radius: Large 
Self Effect      : 33% chance to Apply power Impulsive Dread          
Miss Effect      : Strike with all weapons for 100% (Weapon, Shield, One handed) 

Appreciate if to have special message shown when Impulsive Dread successfully applied.

**Comment by byzanthia** [comment]
Screenshot, if it helps:

![image](https://github.com/user-attachments/assets/e6960e0c-895d-49f0-a5c9-ece0e1c26299)


When it wears off,  there is a message, but you never get one when it is applied.

![image](https://github.com/user-attachments/assets/0583bb74-7dd7-4fba-a333-9d241f930499)

**Comment by shevarash** [comment]
This has been fixed in [today's update](https://discord.com/channels/341000942881341443/576443400925085717/1303884727316647977).  You'll now see a custom message when this power procs. This is also applied to the Paladin version for Divine Inspiration.

Thank you!
