### ISSUE TITLE
sorc - prismatic reaction

### ISSUE THREAD

**Issue by xanza-tey** [torilmud/issues#1104]
it appears that prismatic reaction is stacking on itself, but once expended it clears all copies. If not expended you get multiple copies of the buff wearing off

Effects
---------------------------------------------------------------------------
aware                     detect invisible          detect magic              
farsee                    infravision               no summon                 
protection from good      sneak                     

Spells
---------------------------------------------------------------------------
Prismatic Reaction        (  1:18)   Prismatic Shield          (  2:20)   
Arcane Sight              ( 29:24)   

< 975h/782H 250v/250V (1) P: std >	

Your Prismatic Reaction has expired.

< 940h/782H 250v/250V (1) P: std >	

Your Prismatic Reaction has expired.

< 936h/782H 250v/250V (1) P: std >	

Your Prismatic Reaction has expired.

< 921h/782H 250v/250V (1) P: std >	

Your prismatic shield explodes in a shower of multicolored sparks.

< 880h/782H 250v/250V (1) P: std >

**Comment by shevarash** [comment]
Is this still happening after the 10/28 bug fix patch? I'm hoping this was related to some memory corruptions that were fixed then.

**Comment by xanza-tey** [comment]
Your Prismatic Reaction has expired.

< 990h/990H 250v/250V (4) P: std >	

Your Prismatic Reaction has expired.

< 990h/990H 250v/250V (4) P: std >	

Your Prismatic Reaction has expired.


Still happening after combat and memory patch :(

**Comment by shevarash** [comment]
This is _hopefully_ fixed now. Hopefully. Please re-open if you see it again.
