### ISSUE TITLE
enhance: followers name (targeting)

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#117]
The followers name command targets based on all mobs in your current room, not just your followers.
followers pause, unpause, and stop however only target followers.

Would it be possible to change followers name to identical targeting?

Example: ( there are 3 merchants in this room)

dom 3.merchant
An opulent merchant starts following you.

followers

Follower summary for Nyyrazzilyss:
Number of Followers: 1

NPC:
   240/240   HP  159/159  MV      + an opulent merchant (merchant opulent)

followers name merchant test
You can only name your own pets!

followers name 3.merchant test
Name (test) added to an opulent merchant successfully.

---

followers pause merchant
You have paused an opulent merchant in following you.

followers unpause merchant
You have un-paused an opulent merchant in following you.

---

followers stop merchant
An opulent merchant hates your guts!

**Comment by shevarash** [comment]
👍
