### ISSUE TITLE
Consent while Grouping (Enhancement Request)

### ISSUE THREAD

**Issue by Inames** [torilmud/issues#122]
Make all things that require consent ignore that check if being done by the group leader.
Make a designation for groups that allows an assistant-leader to also benefit from that effect.

There's no risk of eq being stolen off of corpses anymore, so it should be a non-issue.

**Comment by Nyyrazzilyss** [comment]
While consent always starts on the group leader, it often moves around between enchanter/cleric/or rogues. Knowing who has consent and moving it as needed to the correct player (my opinion) should probably remain as it is: Something that requires action by the player giving consent, and checking by the 2nd player to make sure they have consent prior to completing an action. A better request perhaps might be specific spellcast/actions to not require consent to complete?

**Comment by beshaba-toril** [comment]
I like the idea that since eq stealing isn't a thing any more, some
spells/skills be changed to check "if in group" before "has individual
consent" (drag, resu, enlarge/reduce, etc) .

Realistically, if you've consented the group leader, you've also consented
to being with the other people in the group and trust them as well.

I think it's worth examining for feasibility.

Beshaba

**Comment by Inames** [comment]
I considered both the idea of not requiring consent, and the "if in group" idea as well, I figured both leave the possibility of abuse/trolling on the table with certain things, but I'd lean toward the 'if in group' idea if it made this happen. I'm just tired of having to spam people for consent to drag/ress in Tia. I know it would be more work to change up the grouping code to accommodate an 'assistant-leader' or some such, but i figured it'd be a decent compromise to the likely concerns about people trolling if anyone in the group could drag a corpse or incap'd player around, etc..

I like the 'if in group' idea more than removing the need for consent, because removing the need for consent isn't feasible for things like reduce/enlarge, because that's how we were abusing them on mobs... some things need to require explicit consent still or at least be restricted to players/group members. The 'if in group' check would be a nice blanketed fix for a lot of consent issues...

**Comment by Inames** [comment]
All that being said, I just had a stroke of brilliance... It could be possible to alter the way consent works to allow you to consent multiple people. Where re-consenting them revokes it, and if you type consent, it lists who you are currently consenting, and typing 'consent me' it would revoke all consents...

Just an idea! It would solve the issue without allowing for the possibility of blatant abuse by trolling group-mates.

**Comment by beshaba-toril** [comment]
...maybe it'd force the function of kicking people from the group that
troll.

**Comment by shevarash** [comment]
* I agree that we should evaluate some actions that currently require consent to see if we can lift the restrictions.

* Based on that evaluation, it could turn out that implying it from group makes sense, or it may not.

I'm filing this as an enhancement for further analysis.
