### ISSUE TITLE
powers bug: life drain

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#131]
Powers life drain from lich doesn't backfire when you use it against undead.

( powers)

< 625h/770H 266p/266P 130v/130V T: Aynep TC: small wounds E: ghost EC: few wounds EP: std P: std > 
You complete your spell...[Completed spell: ld (Life Drain)]
You drain the ghost of a human noble of some of its life energy.
< 687h/770H 266p/266P 130v/130V T: Aynep TC: small wounds E: ghost EC: few wounds EP: std P: std > 

(non-powers)

< 750h/770H 266p/266P 130v/130V T: Aynep TC: few scratches E: ghost EC: excellent EP: std P: std > 
You complete your spell...[Completed spell: c 'life drain' ghost]
You double over in pain as your spell backfires on you!
Perhaps you shouldn't try to life drain dead things?
< 375h/770H 266p/266P 130v/130V T: Aynep TC: nasty wounds E: ghost EC: excellent EP: std P: std > 

It would also appear that killing someone by (powers) life drain doesn't heal you?

< 677h/770H 266p/266P 130v/130V T: Aynep TC: small wounds E: dragor EC: awful EP: std P: std > 

You complete your spell...[Completed spell: ld (Life Drain)]
Dragor Keenblade is stunned!
Dragor Keenblade slumps to the ground.
Dragor Keenblade crumples as you kill him by draining his life energy.
Dragor Keenblade is dead! R.I.P.
Dragor Keenblade slumps to the ground.
You receive 318,289 XP (0.58%) experience.
Your blood freezes as you hear the rattling death cry of Dragor Keenblade.

< 677h/770H 266p/266P 130v/130V P: std >

**Comment by shevarash** [comment]
The lack of backfire is intended. However, I think it probably shouldn't work on undead. I'll fix that aspect of it.
