### ISSUE TITLE
bug: pets follow with movealone

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#134]
Using the movealone command doesn't prevent pets from following.

movealone n
Ghostwalk
Exits: -N -E -S -W     [48603] 
A lanky commoner dawdles here.
The ghost of a human noble flies in from the south.
The spectre of a human noble flies in from the south.

**Comment by shevarash** [comment]
This is intentional. From the helpfile:

```
MOVEALONE
Syntax: movealone <direction>

This command allows you to move without bringing any PC's who are
following you along.  Pets will still stay with you however.
```

If you think it should be changed, I'm open to hearing the reasoning.

**Comment by Nyyrazzilyss** [comment]
Sorry, I hadn't read the help entry / realized this was by design. I can't think of any reason it should be changed.
