### ISSUE TITLE
How zones reset/reload gear....

### ISSUE THREAD

**Issue by elscint** [torilmud/issues#135]
So I start from the premise that many of the top tier items and big quests revolve around rares or invasions that only load at the time of a reboot or crash.  I'm not saying the game is unplayable or undesirable in it's current form I'm simply offering what I believe would be an improvement.  As time moves forward many people who enjoy this game do not have the time they once did to dedicate to the game.  They can't stay online forever just hoping it reboots or crashes and their item loads and they get there first.  And I believe the mud becoming more stable is a good thing.  But it seems to me these things are at odds with each other the mud being more stable and the desire to have the mud crash due to wanting items that only show up at that time are 100% opposites.  Airship long ago proved my idea is possible I think all zones should be similiar to how airship works with some variations.  Let's use Jot as an example I think if we made Jot's repop dependant upon a couple things like say Thrym has to be dead and Loki has to be dead and the code checks for that and the zone has to be empty.  Okay now those 3 conditions are met and it's been x number of hours/minutes whatever staff decides is appropriate then Jot essentially purges and reloads with a chance for all it's rares and invasion to start over.  It would offer someone the opportunity when they are on to go ahead and 'farm' these zones to try to get the item they are after rather than having to stay online as much as they possibly can just to be around when reboot/crash happens.  In my example let's say someone really wanted a gut bag you know I mean that one guy has been just hammering them for weeks now he's gotten there first every time man because I have a job, kids, other interests and I just want a darn bag cuz it looks cool.  Well with my improvement now i can go in with my group do the zone kill loki and thrym and in an hour or whatever I have a chance again.  Anyhow I think you can understand my example.  I think all zones should work like that it would allow for a more relaxed environment and if you want something to be rare that's fine, it can continue to be rare make it's percentage even more rare if you think this change would impact the mud in a negative way.  I see the pitfalls, but as it stands right now I think an impediment to new players is that a person who might be drawn to a game of this style is of an age group that isn't going to spend every waking second on the game in order to get the 'best gear' they are going to find something that offers enjoyment that doesn't require that.

**Comment by Nyyrazzilyss** [comment]
I'm not sure, but it wouldn't surprise me if having a single zone purge/reload itself might actually be a bit more difficult then expected.

Something i'd suggested previously is perhaps giving Havorr a 'quest' where giving it 50 or 100k plat initiates a reboot in 30 minutes? It would obviously need to world echo a timer maybe every 5 minutes, and perhaps initiate a secondary 'quest' where giving it 10k plat aborts the reboot.

**Comment by shevarash** [comment]
Zone reloading mid-boot is a complex issue. I agree that it's important to work towards though. Thanks for the ideas. I'll file this under enhancement.

**Comment by shevarash** [comment]
The updated Zone structure (documentation is in the docs repository) address these issues, but people need to use them to make zones.
