### ISSUE TITLE
Unarmed Resistance items, What happened?

### ISSUE THREAD

**Issue by Inames** [torilmud/issues#140]
It seems like all items that previously had resistance to unarmed have had it removed. Why? For what reason? Will they be fixed/returned to their previous state?

**Comment by shevarash** [comment]
They were broken accidentally, I believe. We have a fix in the works to restore the functionality, but I'm not 100% sure of the status of the items and if they will all be getting the same amount of unarmed resists back. Unarmed resistance is pretty powerful.

**Comment by marthammor** [comment]
I'll chime in on this as I'm the one that broke them, sort of. Unarmed resist was never actually able to be set on items either on purpose, or by a bug. A couple area makers found out a way to make it work by setting all physical resist. This was broken by me awhile back when I wrote some flag converters for objects and one of the side effects was that the physical resist flag was broken into slashing, bludgeon, ect, and that included unarmed. As the unarmed flag is not read and recognized by itself, its not showing or used by the game currently. It is still on every item that had it before, however, and there is a fix being worked on that will re-enable it along with add some more functionality that will tone down some of its overpoweredness. As shevarash said though, some items may still need the stat reduced or removed.

**Comment by shevarash** [comment]
This has been fixed.
