### ISSUE TITLE
Powers Locate Remains doesn't work.

### ISSUE THREAD

**Issue by Inames** [torilmud/issues#143]
c 'locate remains'
You start chanting...

< 240h/215H 184p/184P 106v/130V >
< P: std > 
Casting: Locate Remains ***

< 240h/215H 184p/184P 107v/130V >
< P: std > 
Casting: Locate Remains **

< 240h/215H 184p/184P 108v/130V >
< P: std > 
Casting: Locate Remains *

< 240h/215H 184p/184P 108v/130V >
< P: std > 
You complete your spell...
corpse of a human noble in At Moonway and Ghostwalk.
corpse of a human noble in At Moonway and Ghostwalk.
corpse of a human noble in At Moonway and Ghostwalk.
corpse of a human noble in At Moonway and Ghostwalk.
corpse of a dockhand in The Docks.
corpse of a human noble in At Moonway and Ghostwalk.
corpse of a human noble in At Moonway and Ghostwalk.
corpse of a human noble in At Moonway and Ghostwalk.
corpse of a human noble in At Moonway and Ghostwalk.
corpse of a human noble in At Moonway and Ghostwalk.
corpse of a human noble in At Moonway and Ghostwalk.
corpse of a human noble in At Moonway and Ghostwalk.
corpse of a human noble in At Moonway and Ghostwalk.
corpse of a human noble in At Moonway and Ghostwalk.
corpse of a human noble in At Moonway and Ghostwalk.
corpse of a human noble in At Moonway and Ghostwalk.
corpse of Dexes in Wayward House Inn.

-----------------------------------------------------------------------------------------------------------

pow 'locate remains'
You start chanting...

< 228h/215H 184p/184P 130v/130V >
< P: std > 
Casting: Locate Remains ***

< 228h/215H 184p/184P 130v/130V >
< P: std > 
Casting: Locate Remains **

< 228h/215H 184p/184P 130v/130V >
< P: std > 
Casting: Locate Remains *

< 228h/215H 184p/184P 130v/130V >
< P: std > 
You complete your spell...
No such object.

**Comment by shevarash** [comment]
Looks like it doesn't work with no arguments. I'll see what we can do to fix that.
