### ISSUE TITLE
Summoned mounts movement points

### ISSUE THREAD

**Issue by CountVooku** [torilmud/issues#144]
Can you take a look at summoned mounts movement points? Their movement points seem to run out way too fast. I can walk on foot to certain areas easy but I cannot make it on my mount (nightmare) without stopping/rest.

Maybe this is because I'm flied. Though it does say my nightmare and hell hound 'flies' in from the XXXX.

**Comment by Inames** [comment]
Mounts consume like 5mv per room when mounted, but their mv is infinite when they follow, it's always been like that, just dismount between fights/running. or just use the mount to supplement your movement.... like run around on foot, and if you run out of moves, mount up, then when your mount is out of moves, get off and walk again (horse will have infinite ability to follow whilst regen'ing its moves to use again the next time).

**Comment by shevarash** [comment]
Nothing has changed in some time, but I think it's fair to treat this as an enhancement request to improve mounted movement points.

**Comment by shevarash** [comment]
I'm reducing the mounted movement cost from 3 to 2.  That makes it better than it is now, but not quite as nice as fly. We'll see how that works out and evaluate again if needed.
