### ISSUE TITLE
Incorrect room names

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#152]
While to my knowledge there isn't a defined format for room names, almost the entire map matches the format: The initial letter of a room name is capitalized, and the line doesn't end in a period.

There are some rooms however that don't match this format:

(edit) found that some of these were fixed in the past. Removing as I find them.

[              Dark Forest] the River of Cu'L Torik (Water)
[              Dark Forest]   an Ogrillonian Hut
[              Dark Forest] the River of Cu'L Torik (Water)

[Beluir - City of Halflings] Southeast end of West Square.
[ The Waterdeep Coast Road] A Wagon Track through the Dense Forest.
[ The Waterdeep Coast Road] A Wagon Track leading up the Slope.
[      Cityguard's Armoury] Halfway Through a Narrow Corridor Beneath the Bazaar.
[The Plane of Fire Part Two] Intersection of Royal Way and Imix Avenue.
[            The Rat Hills] A Trampled Path around the Base of a Trash Heap. (x5)
[       The Plane of Smoke] A Roiling Pocket of Smoke.
[      Fire Giants Village] On the Bottom of the Cave.
[             Pirate Isles] A Small Island Beach.  (x2)
[             Pirate Isles] A Small Mountain Plateau. (x7)
[             Pirate Isles] A Muddy Gravel Road. (x10)
[             Pirate Isles] A Switchback On A Muddy Gravel Road. (x3) 
[             Pirate Isles] A Widening of The Road.
[             Pirate Isles] A Worn Roadway Through the Grass. (x7)
[             Pirate Isles] An Arcane Laboratory.
[             Pirate Isles] Before An Ancient Stone Castle.
[             Pirate Isles] A Brightly Lit room in A Cave.
[               Muspelhiem] A Huge Laboratory With Beakers and Vials All Over The Place.
[             Evermeet Bay] A Lush Kelp Grove at the Base of the Steep Slope.
[             The Darktree] Traders Demise & Co.
[             The Darktree]      Carnivore & Co.
[            Castle Drulak] Inside a Tree Trunk.
[    New Moonshae Island I] The West Beach of Gwynneth.
[Demiplane of Artimus Nevarlith] Between Peaks in the Hills.
[Demiplane of Artimus Nevarlith] A Valley in the Rolling Hills.
[Demiplane of Artimus Nevarlith] Piles of Giant-Sized Boulders.
[        Spiderhaunt Woods] A Cramped Tunnel Under a Fallen Tree. (x2)
[        Spiderhaunt Woods] A Damp Tunnel Under a Huge Fallen Tree.

**Comment by Nyyrazzilyss** [comment]
Another room with a broken name is in Skullport,  .2sus2e4se from the entry room (
At a Pillar of Stone Embedded with Skulls)

Above���Tradeway
Exits: -N -E -W        [81350]

**Comment by shevarash** [comment]
Thanks! We'll get these fixed. Feel free to keep adding to this issue until we close it.

**Comment by OghmaToril** [comment]
These have all been resolved with the exception of the bad characters in the Skullport rooms.  I have also resolved all of the other room names and object names with periods in their short descriptions.

The Skullport rooms are also reported in #173 so I will keep that issue open.
