### ISSUE TITLE
Enhance: Show profilenames on who list

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#157]
I've altered the who list to show profile names at the end of each line. The colour I used is slate_grey

Example:

 Listing of the Mortals!
-=-=-=-=-=-=-=-=-=-=-=-=-
[50 War] Gurru  (Troll) [@Lilithelle]
[50 Rog] Evse  (Human) [@Wobb]
[50 Inv] Dizag  (Drow Elf) [@Jasix]
[50 War] Adud  (Ogre) [@Nyyrazzilyss]

Perhaps incorporate something similar back into the mud code?

**Comment by Inames** [comment]
I support this 100%

**Comment by shevarash** [comment]
One concern - this clutters up the who list a little. Does anyone else have this concern? Should it be a toggle?

**Comment by Inames** [comment]
I'm all for the toggle option. I would personally like this addition very
much.

**Comment by Nyyrazzilyss** [comment]
Sure, a toggle is never a bad thing since it gives the user the choice to enable or disable the option.

It does take up more space on the screen when you type 'who' yes. I'm not sure how much I would consider it as clutter though, it may however be that i'm just used to it.

![wholist](https://user-images.githubusercontent.com/11463043/29720558-4ab5bd9c-8988-11e7-861b-db58d779092a.jpg)

**Comment by Nyyrazzilyss** [comment]
Just going to bump this for you Shev. There was a discussion today on NHC/GCC regarding this and something related to. My script will send a 'who charname' command when someone types 'who' alone anytime there's an unknown character to find out the profile associated with it. Someone using paging was asking why the who list kept on getting interrupted (script problem).

In the process of explaining why that was happening, a conversation developed on gcc including comments from Oghma. He'd commented that on a godchar, the who command looks similar to my screenshot. I'd assume then it's really just a single line level restriction in the code.

The only concern would be regarding 'anon' characters, and whether the profilename should be shown for all levels or not regardless of them being anon.

Other then that, hoping to see this incorporated back to the mud sometime soon!

**Comment by shevarash** [comment]
This was added awhile ago.
