### ISSUE TITLE
Air Plane fix - make spark piece always load on Yan

### ISSUE THREAD

**Issue by torkur** [torilmud/issues#158]
Air Plane isn't getting done a lot because of the low number of rewards.  From discussing it with lilithelle, we still only do it when elvenkind is up because people need that.  The Ashtone quest with the earring was designed to help and make people do it more, but that's not the case because it doesn't load with Elvenkind.  To add a larger reason to go, but not really make anything overpowered, I'd suggest making the piece always load.  That way we can push interest in going without it being a straight "dice cloak to group" type zone.

**Comment by ghost** [comment]
veto, spark loads when cloak doesn't, you're still getting rewarded for efforts, adding another reward to the zone when cloak loads isn't what i think a 3 man zone needs

**Comment by torkur** [comment]
All of the planes are 3 man zones.  FP and Astral have more rewards, depending on rares, which causes us to bring other people instead of just hoarding items.  While I'd like more rares on Air, it doesn't get done now unless it's a few people doing it for the cloak and this was an easy fix to help that.  If not gonna happen we'll just continue to twink it for the cloak I guess.

**Comment by Inames** [comment]
I think making planes rewards completely hidden so we don't know what we are getting will make it more reasonable to do the planes in hopes of good surprises. I think that the rewards in air are lacking compared to fire or smoke invasion or earth invasion, but making it worth the hour and a half clear time and making it impossible for us to pick and choose when we do the zone based on what loaded will give us more incentive to do it whenever we can to try and get the items we need from it.
