### ISSUE TITLE
Feeb does not stop Mephits from casting

### ISSUE THREAD

**Issue by DuardPeb** [torilmud/issues#16]
< 504h/635H 97v/97V P: std > 
feeb mephit
They are already affected by that spell!

< 507h/635H 97v/97V P: std > 
kill mephit
Your average bludgeon barely wounds a gem mephit.
A gem mephit misses you with its smash.
A gem mephit misses you with its smash.
You miss a gem mephit with your bludgeon.
< 512h/635H 97v/97V T: Biyepeple TC: small wounds E: mephit EC: few scratches EP: std P: std > 
A gem mephit misses you with its smash.
A gem mephit misses you with its smash.
Your average bludgeon barely wounds a gem mephit.
< 512h/635H 97v/97V T: Biyepeple TC: small wounds E: mephit EC: few scratches EP: std P: std > 
A gem mephit starts casting an offensive spell called 'Chromatic Orb'
< 512h/635H 97v/97V T: Biyepeple TC: small wounds E: mephit EC: few scratches EP: std P: std > 
feeb mephit
They are already affected by that spell!
< 512h/635H 97v/97V T: Biyepeple TC: small wounds E: mephit EC: few scratches EP: std P: std > 
You miss a gem mephit with your bludgeon.
< 512h/635H 97v/97V T: Biyepeple TC: small wounds E: mephit EC: few scratches EP: std P: std > 
A gem mephit completes its spell...

**Comment by Alurissi** [comment]
pretty sure earth plane uses power spells, not cast spells, so it would be an issue of feeb not affecting using power spells, same thing is true for silence rooms, you can still use power spells

**Comment by shevarash** [comment]
The spell being cast here is actually from a power proc that bypasses the feeb issue, so is intended.
