### ISSUE TITLE
Enhance: Remove quit command

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#160]
There really doesn't seem to be an obvious reason to have the quit command. Perhaps remove it, or change it to just show instructions about camp/rent?

**Comment by Ruagh** [comment]
There is a reason to drop all the cursed items you grab.
Imagine a newb with all his eq slots filled by cursed items?
But yes, sometimes newbs do QUIT instead of RENT, and lose eq... well, there are pretty clear warning messages, right?

**Comment by Nyyrazzilyss** [comment]
I'm not sure if it's that easy to get (or even find) cursed items at a low level.

There are however other ways to remove a cursed item from a character without quiting: Cleric or using a scroll to cast remove curse, or placing the item in a storage cache.

From the number of times i've seen people reconnect in the past and NHC about where their equipment went, some people don't read the warning message on 'quit'

**Comment by Ruagh** [comment]
Some people are just idiots, it wont help if you will make it more idiot-proof. 
This all is about reading texts, aint it? Maybe change the warning to be a bit more clear, thats all.

You have to write quit - no less, to quit!
WARNING: by quitting you drop all of your worn and carried equipment
on the ground.  If you wish to leave the game with your equipment in
tact, rent at an Inn or lose link.
Please confirm that you wish to quit (Yes/No) [No]:
Action has been aborted!

**Comment by Inames** [comment]
almost every other mud uses quit as a safe exit method for logging out, we are one of the few muds that uses an inn that I've seen... I'd rather see people who quit be forced into a waiting room like the fugue room with a portal that takes them to their hometown guildmaster than drop all their items and be logged out in their current room.

Hell... I think even forcing them TO fugue when they use the quit command would be a good option. because then there's a penalty for quitting out instead of renting(item damage/fatigue from entering the portal), and it's less likely (though not impossible) to be used for easy recalling.

**Comment by Nyyrazzilyss** [comment]
quit moving the player to fugue and dropping link sounds good to me

**Comment by Ruagh** [comment]
Well, yes, thats a nice idea to move to fugue. And cursed items on the newb could be treated by a cleric. This is a multi-player game, after all.

**Comment by shevarash** [comment]
I fully support removing or updating the quit command.

**Comment by Ruagh** [comment]
Quit moving player to fugue, dropping only cursed items - forgot if they can be picked there, they should be in this case - will be a nice addition to SillyNewb... Err, NYYbot Safety (tm :)

**Comment by feyder213** [comment]
Yirdaek 'So, I just found out all of my inventory and equipment 
are gone. '
You 'did you quit? or rent/camp?'
Yirdaek 'I think I quit last night, yeah.'

**Comment by Gyrx** [comment]
Please make it so that when you type quit, it gives you information about how destructive quit can be (dropping all gear, etc.) and that camping/renting is preferred, but if you REALLY want to quit then you need to type a 2nd, new command to complete the quit.  "quitconfirm" or something something.

**Comment by Nyyrazzilyss** [comment]
*bump*

Nivzal 'if I quit, do I have to remake the character?'
Lilabipple 'no'
Rargas 'typing 'quit' will drop all your stuff and log you out. 
 you want to just drop link or rent in an inn'
Lilabipple 'it saves'
Nivzal 'so the newbie book will go away?'
Lilabipple 'if you drop link, no'
Lilabipple 'if you quit, yes'
You 'You'll want to either camp, drop link, or rent. Never type 
quit'
Nivzal 'what is the difference between all?'

**Comment by marthammor** [comment]
I believe this has been taken care of now. Closing.
