### ISSUE TITLE
bad exit in tiamat

### ISSUE THREAD

**Issue by ghost** [torilmud/issues#162]
there's a bad exit, on first grid of tiamat, far east side, which leads to a wrap around 1 further south, i know it's caused me some headaches, anyone else?

**Comment by shevarash** [comment]
That's embarrassing. 

The room is #24120 and has a bad east exit. It should go to #24121

**Comment by Inames** [comment]
I always assumed it was intended to screw with us, but i'll agree that it's slightly annoying sometimes and I'll appreciate it being fixed! just let us know when that is so I can fix my map accordingly!

**Comment by torilmud-silvanus** [comment]
Fixed pending move to mainmud
