### ISSUE TITLE
stiletto of bane

### ISSUE THREAD

**Issue by ghost** [torilmud/issues#165]
can we reduce the weight on bane dagger?  the only rogues this is an issue for is gnome and halfling, as bane dagger is typically an offhand weapon for any rogue with something pretty to mainhand, when in fatigue, or reduced, halfling and gnome, can not wield bane off hand due to weight.  do we really need to be forced to fight pidibeple to quest a rimi for haste?

**Comment by torilmud-silvanus** [comment]
We will be keeping this item dynamic as is for now
