### ISSUE TITLE
Can't start auctions > 100k plat

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#167]
auction sell leggings 130000 5000 6
An auctioneer says 'That's just a little high in price don't ya think?'

< 824h/824H 911p/911P 110v/110V P: std > 
auction sell leggings 129000 5000 6
An auctioneer says 'That's just a little high in price don't ya think?'

< 824h/824H 911p/911P 110v/110V P: std > 
auction sell leggings 128000 5000 6
An auctioneer says 'That's just a little high in price don't ya think?'

< 824h/824H 911p/911P 110v/110V P: std > 
auction sell leggings 120000 5000 6
An auctioneer says 'That's just a little high in price don't ya think?'

< 824h/824H 911p/911P 110v/110V P: std > 
auction sell leggings 101000 10000 6
An auctioneer says 'That's just a little high in price don't ya think?'

< 824h/824H 911p/911P 110v/110V P: std > 
auction sell leggings 100000 10000 6
An auctioneer says 'Ok your a pair of silver dragonscale leggings is now on the auction block. Good Luck!'
Auction: Nyyrazzilyss just put 128947 a pair of silver dragonscale leggings on the auction block with starting bid at 100000
platinum!

**Comment by shevarash** [comment]
Seems reasonable to raise the maximum.
