### ISSUE TITLE
Ranger Updates

### ISSUE THREAD

**Issue by Inames** [torilmud/issues#168]
Firstly I'd like to say thank you for finally addressing this issue.
Secondly, I'd like to give some feedback and provide this thread for reporting issues that we have found and will undoubtedly continue to find.

```
< 464h/464H 215p/215P 130v/130V |ts 2|ev 6|ap 3|ss +|bs +| >
< T: Senaror TC: excellent E: elaith EC: awful P: std > 
Senaror knocks Elaith Waterstill backwards several feet with a powerful kick.
Elaith Waterstill is mortally wounded, and will die soon, if not aided.

< 464h/464H 215p/215P 130v/130V |ts 1|ev 5|ap 2|ss +|bs +| >
< E: elaith EC: awful P: std > bs
That can only be done in combat!

< 464h/464H 215p/215P 130v/130V |ts 1|ev 5|ap 2|ss +|bs +| >
< E: elaith EC: awful P: std > 
Vivizaza crushes Elaith Waterstill's skull.  Elaith Waterstill instantly collapses.
Elaith Waterstill is dead! R.I.P.
collect
You receive 60,870 XP (0.16%) experience.
Your blood freezes as you hear the rattling death cry of Elaith Waterstill.

```

My first issue is the fact that you cannot engage with these skills... I don't see a particular reason for this, but it also raises some issues... Such as the fact that once a mob becomes incapacitated, it no longer counts you in combat, even though the combat prompt is still active. So you fail to execute one of these skills if this creature is incapacitated... This issue extends to para'd mobs as well, you cannot execute one of these skills if the creature is affected by major para.

**Comment by Inames** [comment]
Can we change this up a bit?

`
You attack a graceful commoner with both weapons and land twin precision strikes.
`

The way it's worded seems clunky if you know what I mean... 'and land twin precision strikes' 

Perhaps:

```
You strike with precision at a graceful commoner, landing two powerful blows.
-OR-
You attack a graceful commoner with both weapons, landing two precision strikes.
```
These simply read better in my opinion. I  can see trying to use the skills' name in the resulting text, but it just doesn't roll off the tongue very well. If you want to use the words "twin" and "strike" without compromise, perhaps:

`
Your twin strikes connect fiercely with a graceful commoner visibly wounding them.
`

Some ANSI flavoring might be nice too. The skills' messages seem a little dull/not very aesthetically pleasing.

Just some feedback/ideas.

**Comment by Inames** [comment]
Not sure it was intended for both the standard message and a separate kill message to display here? Seems redundant. Sweeping Strike, Bladestorm, and Armor Splinter have different kill messages, but they only display the kill message, not the standard AND kill message.

Eviscerate:
```
< 230h/464H 215p/215P 130v/130V |ts +|ev +|ap 6|ss +|bs 4| >
< T: Aninen TC: nasty wounds E: colorful EC: nasty wounds EP: std P: std > ev
You swing your weapons in lethal arcs, dousing the area with a colorful commoner's blood.
A colorful commoner is stunned!
A colorful commoner slumps to the ground.
You swing your weapons in a killing arc, eviscerating a colorful commoner in a spray of gore.
a colorful commoner is dead! R.I.P.
collect
A colorful commoner slumps to the ground.
You receive 9,600 XP (0.03%) experience.
Your blood freezes as you hear the rattling death cry of a colorful commoner.
```


Twin Strike:
```
< 464h/464H 215p/215P 130v/130V |ts +|ev +|ap +|ss +|bs +| >
< T: Aninen TC: excellent E: noble EC: awful EP: std P: std > ts
You attack a dapper noble with both weapons and land twin precision strikes.
A dapper noble is incapacitated and will slowly die, if not aided.
A dapper noble slumps to the ground.
You strike a dapper noble down with a barrage of blows from both weapons.
a dapper noble is dead! R.I.P.
collect
A dapper noble slumps to the ground.
You receive 270 XP (0.00%) experience.
Your blood freezes as you hear the rattling death cry of a dapper noble.
```

**Comment by shevarash** [comment]
Thanks for the feedback. My thoughts:

1) The inability to engage with these powers is to prevent having to add player lag to them. I'm not a fan of lagging the player and I'm trying to move away from it wherever possible. There are some other potential benefits as well, like the fact that it requires a little more engagement to make sure you are targeting the correct mob. That said, I agree that the inability to use them on an incapped mob is unfortunate, and there may be another way to accomplish the same goals. I'll keep working on it and asking for feedback, and this isn't written in stone yet.

2) Hey, I agree on the twin strike message. I had it the other way and then I changed it at the last minute. Should have gone with my gut. I'll change it back. :)

3) ANSI wise, I try to keep combat powers relatively spartan since everyone has to look at them so much. They do look a little bit better in 256 mode, but I'll go over them again and see where they can be spruced about. I appreciate the feedback on aesthetics too.

4) The extra death message is a little odd. What's happening there is that you're always hitting with _both_ weapons, but to reduce spam we only show one combined message. When the second hit kills the mob though, it has to show a death message. I'll see if there's a more graceful way to handle that.

**Comment by Inames** [comment]
Regarding the extra message on kill, I'm fine with whats happening if we
change the description/text a bit. I'd rather see individual messages for
each weapon strike anyways. It would allow for some more flavor in the
message delivery, I'll respond with some ideas about this when i get home
from work tonight.

**Comment by torkur** [comment]
The out of combat to force targeting makes sense above, but that seems a little weird in today's game of huge group fights.  Not sure if there is a compromise on making it targetable, but not initiating combat in the room with it somehow?

Two example problems come to mind from our guild discussions:

(1)
Lilithelle group-says 'target dragon.  Dire Charge 1.mage. Rogue trip 2.mage'   No problem currently.
Lilithelle group-says 'target dragon.  Dire Charge 1.mage. Ranger Sweeping Strike 2.mage'   Currently you can't do it.  We'd need to swap the ranger to a rogue/Dire/Warrior if this is important.

(2)
Ranger is attacking and assigned Sweeping Strike on 2.Cleric (warrior/cleric class mob).  Tank rescues Ranger.  Cleric casts unholy word on group. Ranger has to reengage and is rescued from 2.cleric in the round of combat lag.  Cleric casts unholy word on group. Ranger can't Sweeping Strike, so reengages again and is rescued from 2.cleric in the round of combat lag again.  Cleric casts unholy word on group. At this point the Ranger hasn't been able to trip as expected so others in the group have to pick it up or Ranger is replaced by a Rogue/Dire (with Charge)/Warrior to stop the spellcaster.

**Comment by Nyyrazzilyss** [comment]
Lilithelle group-says 'target dragon. Dire Charge 1.mage. Ranger Sweeping Strike 2.mage'

If you globe the ranger however, it could target 2.mage / use sweeping strike to keep in bashed (And likely have the mage dead in a couple rounds).

As in: While it's nice to see the new powers added to ranger, they're also a bit excessive on the amount of damage they do. Perhaps change the global melee cooldown from 1 round to 2?

**Comment by Inames** [comment]
Id rather see a damage nerf over increasing the cooldown. Otherwise you
cant keep the effects up as consistently and sweeping strike would become
much less reliable. That being said, I dont believe rangers are any more
broken for damage than rogues still are.

**Comment by torkur** [comment]
Nyyr, targeting the wrong mob completely misses the point.  It also leads to spanks when you don't listen and the fight is anywhere near close.  It's why we complain about your bots.

**Comment by shevarash** [comment]
We added the ability to target mobs out of combat with ranger powers, so I'm closing this now. Please feel free to open a new issue if there were further problems with Rangers.
