### ISSUE TITLE
Evilrace blades - Windsong for non-evil drow

### ISSUE THREAD

**Issue by Ruagh** [torilmud/issues#169]
Theres a definite lack of decent warrior blades on the Dark Side. 

a glittering elven scimitar (Wield) Dam:3 Hit:4 * (Weapon) Dice:3D4 Crit:9% Multi:2x (Class: Martial, Type: Scimitar) * Procs: Blur * Bless Float Magic No_Burn No_Loc No_Sleep !Barb !Drow !Duergar !Dwarf !Evil !Gnome !Halfling !Human !Lich !Mage !Ogre !Priest !Squid !Thief !Troll !Yuan * Wt:4 Val:100p * Zone: Sylvan Glades (Q) * Last ID: 2013-05-08'

Why should it be flagged !drow? Yep this is historic, but it is !evil, thats logical and enough. 
Its the same elven blood, and it should proc as well in the hands of a non-evil drow. Go Drizzt!

**Comment by Inames** [comment]
nah, completely different. drow and surface elves use different magics and materials in crafting/enchanting their weapons. there's no reason a blade of the surface elves should react the same way in the hands of a drow. "same elven blood"? nah... not even... closely related sure, not the same...

**Comment by shevarash** [comment]
I think it's fair that this elven weapon is !drow. I do agree that it'd be nice to have _other_ weapon options for non-evil drow though. Perhaps we'll address this in that manner...
