### ISSUE TITLE
Dual wielding tanking

### ISSUE THREAD

**Issue by Ruagh** [torilmud/issues#171]
Warriors now are doomed to use a shield. Why a drow (or a gray, whatever) can not tank - ok, technically they may, but its a joke - with two swords?

Logically thinking, that gives at least a dual chance to parry/riposte, to compensate for the loss of the shieldblock, and also makes you more agile since youre not encumbered by a huge shield, so dodge should be better too, but it is just basically "a total loss of shieldblock" now.

To balance this, since we're adding some damage - defensive skills may be SLIGHTLY worse than 1h+shield to offset, but still reasonable enough to use in zones, unlike now.

**Comment by Adriorn** [comment]
I just checked and I can still dual wield as a warrior.  Check again man.

**Comment by Ruagh** [comment]
Alas... ok. Surely technically warriors MAY dual. But, first, in this case theyre losing shieldblock, which is currently vital, and getting nothing for the lost of it (look above). Second, dual wield skill cap for warriors (even drow/grey) is 50, and for rangers is 99. Pretty different, aint it?

Making dual wield tanking less of a joke would benefit rangers too, making them backup warriors, and will add more versatility. Although im unsure if now, with recentpy buffed rangers melee, it wont make TANKS even more TANKS.

**Comment by shevarash** [comment]
We'll be addressing Warriors in the near future. I'm not sure that dual wield will be a component of their upgrades or not, but we'll keep it in mind. Thanks for the feedback.
