### ISSUE TITLE
Rangers vs. warriors, esp. with modern changes.

### ISSUE THREAD

**Issue by Ruagh** [torilmud/issues#177]
HELP WARRIOR states - They possess skills of fighting that are unequaled by members of any other class... They are, in essence, the ultimate fighter 

HELP RANGER states - Rangers are good aligned woodland survivalists who excel at dual-weapon combat. Rangers are granted limited magical abilities that progress in abundance and strength as they live their lives.

What are you doing, strategy-wise? In my opinion, rangers are melee spellcasters and archers, who excel in forest tricks - sneak, ambush, etc, and also can use archery to fight mobs without close contact. It is pretty much questionable that rangers should "excel at dual-weapon combat", compared to dualling warriors. Tell that to drow weaponsmasters. Equal, maybe, but not excel. 

And lets see the facts. Warriors are just meatshield tanks, dressed in bloated hp gear. They deal less melee damage than rangers and Torils Sacred Cow - rogues, outdamaging only spellcasters, and in the battleclerics case - not by far. Further imbalancing this, youre happily adding more melee skills to rangers, twice raising their melee capability. 

You want balance? Think about it this way - give finally a decent melee to warriors (also fix dual wield tanking - which will benefit the rangers too! -  and 2h dice issues), leave trickery melee to rogues - backstab, traps etc, and wilderness melee to rangers - ambush, sneak, etc. Why do those 2 classes outdamage warriors in pure general melee, warriors prime specialization field? You want rangers to be more attractive - yes, thats prolly needed - then make dual wield tanking less of a joke, give them more wilderness spellcasting, or change their archery in some way, thats their field, but dont hurt the fields of other classes, please.

**Comment by shevarash** [comment]
To answer your question about strategy, the intent for Rangers is to make them a strong damage dealing class. We'll be working on Warriors as well in the future, and I'll comment more on their strategic role when that time is closer. Thank you for your feedback.
