### ISSUE TITLE
!bash and discreet sizes - items?

### ISSUE THREAD

**Issue by Ruagh** [torilmud/issues#178]
Since now it is all about +/- size, things like cloak of faeriekind and band of deformities are pretty much broken. Why not to change them to be +/- size, unlike what they are now? Its pretty easy to fix. And reduced drow wearing cloak of faeriekind will finally be !bash, which will finally address the issue that "every caster must be smurf or hobbit nowadays"

Katumi tells you 'a cloak of faeriekind (About) AC:15 Hp:40 Ht:-25 * Procs: faer
iekind * Magic No_Charm No_Sleep !Barb !Fighter !Ogre !Thief !Troll * Wt:1 Val:7
72p * Zone: Faerie Realms (Q) * Last ID: 2012-11-26'

Katumi tells you 'a band of deformities (Finger) AC:0 Wt:40 * Wt:0 Val:3p * Zone
: Ashstone * Last ID: 2007-08-29'

**Comment by torilmud-silvanus** [comment]
Fixed
