### ISSUE TITLE
Change colour: Powers prompt

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#179]
When using powers cool downs in the prompt, the colour used when it's counting back is red. This is distracting in the prompt, where if I see something red there (or any colour matching hp levels) it's automatically a bad thing.

Would it be possible to change this to a non-hp colour?

**Comment by Inames** [comment]
Well that takes away half of the basic colors... bold red was suggested in gcc conversation today, but I wouldn't be opposed to bold green as an option as well, or white... but that wouldn't go well with people who's default text color is white... I also like the idea of broader prompt customization, which shev said might be interesting. so seems like everything is up in the air at the moment.

**Comment by Nyyrazzilyss** [comment]
Sounds like there's going to be disagreement regardless of colour chosen. Ideal would likely be the option for the user to assign the colour used (If need be, I can just add a trigger to do that myself)

**Comment by shevarash** [comment]
I was thinking of standardizing on black instead of red as a first step, and then working on customization down the road.

**Comment by Inames** [comment]
Sounds fair enough.

**Comment by Nyyrazzilyss** [comment]
Sounds good to me - I'm honestly mostly concerned about any colour other then red in the prompt. 

Black would actually be a good one to allow for easy change by the user. I don't think it's used anywhere in the mud = It's easy for most clients to change black to a different colour.

**Comment by Nyyrazzilyss** [comment]
Will have to see how things feel with red again. While black could be changeable in the client to another colour, it might have worked better if it also included instructions mentioning that.

Past that, however, most people don't read instructions = It just looking like a blank space on the prompt.

**Comment by Nyyrazzilyss** [comment]
Been awhile, and haven't thought of this - closing.
