### ISSUE TITLE
Disarmtrap should inform the user which item is being disarmed

### ISSUE THREAD

**Issue by Gyrx** [torilmud/issues#18]
Precondition:
1. User has a "chest" container in their inventory
2. User is trying to disarm a "chest" on the ground/in the zone

Steps:
1. disarmtrap chest

Expected Result:
User is given feedback which item is being disarmtrap'd - so they can validate the proper item is being disarmed as intended

Actual Result:
1. User using disarmtrap does not know which item is being disarmed
2. Observes in the room see which item is being disarmed

Log snippet:
< 905h/796H 117v/117V P: std > 
disarmtrap chest
You cannot concentrate enough at the moment...rest a bit.

< 904h/796H 117v/117V P: std > 

< 902h/796H 117v/117V P: std > 
disarmtrap chest
Nothing seems to happen..

< 902h/796H 117v/117V P: std > 

Pidibeple group-says 'ahpa'
who
Lilabipple group-says 'Ahpa tries to disarm a trap on a silver treasure chest of the Valkurian 
Blades, but nothing seems to happen..'

**Comment by marthammor** [comment]
Fixed. Awaiting move. Closing ticket.
