### ISSUE TITLE
Rangers and alignment

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#183]
Not sure if you'd think of this as a bug or not (I wasn't penalized on spellcasting), however:

You give an order for poison to a wandering cleric of Cyric.
He takes a small bit of the poison to his lips, and after tasting it, grins
wickedly.

"Oh yes, this will do nicely.  No taste at all.  That cleric of Mystra will not
know what has happened to her until it is too late.  Cyric smiles upon you.
Receive his blessing."

As the cleric places his hand upon your head in benediction, a dark chilling
aura covers your body.  You feel the constraints of your conscience removed,
no longer caring about the results of your actions.

"I have other issues to attend to."

< 786h/836H 132v/138V |ss +|ap +|ts +|ev +|bs +| P: std > 
att

          Character attributes for Tutenef

Level: 50   Race: Human   Class: Ranger      
Age: 65 yrs / 14 mths  Size: Medium
STR:  90  AGI: 119  DEX:  88  CON:  98
POW:  56  INT:  60  WIS:  83  CHA:  46
Armor Class: -89  (100 to -100)  Agility Bonus: -22
Magic Resistance: 5 percent
Hitroll: 38   Damroll: 45
Alignment: Chaotic Neutral

**Comment by shevarash** [comment]
Are you asking if it's bug that your alignment was able to shift?

**Comment by Nyyrazzilyss** [comment]
Yes - Wasn't ranger similar to paladin in that they were restricted on alignment / supposed to be penalized for changing it?

**Comment by Inames** [comment]
It was the case in the past, but I largely disagree with it. In some sense it might make sense to restrict rangers to lawful alignments but rangers should be able to draw power from their gods in the range of good/neutral/evil. At this moment it doesn't really matter, but if/when choosing gods becomes a thing I think it would make sense to restrict rangers to the alignments accepted by their god. But that would mean getting back into Toril 2.0 stuff from 10 years ago.

**Comment by torkur** [comment]
Rangers don't have to be good aligned.  Spellcasts don't work (for some spells), but powers spells all do so far:


< 438h/438H 141p/141P 110v/110V |ts +|ss +|ap +|ev +|bs +| >
< P: std > att

                Character attributes for Sukzik

Level: 31   Race: Half-Orc   Class: Ranger      
Age: 17 yrs / 7 mths  Size: Medium
STR: 107  AGI: 100  DEX:  96  CON: 103
POW:  70  INT:  70  WIS:  70  CHA:  70
Armor Class: -81  (100 to -100)  Agility Bonus: -22
Magic Resistance: 0 percent
Hitroll: 34   Damroll: 68
Spell Focus: [Nature: --5%] 
Alignment: Neutral Evil
Saving Throws: PAR[0]  ROD[0]  PET[-6]  BRE[0]  SPE[0]
   Wimpy: not set
Load carried: Paltry
Damage Resistance:
Unarmd:    0% Slash :    0% Bludgn:    0% Pierce:    0% Range :    0% 
Spells:    0% Fire  :   30% Cold  :   15% Elect :   10% Acid  :   15% 
Sonic :    0% Poison:   10% Pos   :    0% Neg   :    0% Psi   :    0% 
Mental:    0% Good  :    0% Evil  :    0% Law   :    0% Chaos :    0% 
Force :    0%

**Comment by OghmaToril** [comment]
Ranger alignment restrictions to use spellcasting have been removed.
