### ISSUE TITLE
Powers pwb hitting the wrong target

### ISSUE THREAD

**Issue by Lilithelle** [torilmud/issues#184]
< 804h/801H 153v/162V > w
A Stone Bridge Over River Cesh
Exits: -E -W
Corpse of an elven fisherwoman is lying here.
An ogre slave mopes here with a frown.
A pretty wild-elf fishes off the side of the bridge.

< 804h/801H 153v/162V > 
pwb fisher
An ogre slave misses you with his bludgeon.

< 804h/801H 154v/162V T: Lilippople TC: excellent E: ogre EC: excellent > You start chanting...

< 804h/801H 155v/162V T: Lilippople TC: excellent E: ogre EC: excellent > 
You complete your spell...
An ogre slave gropes around, blinded after hearing Lilippople's word!

< 804h/801H 155v/162V T: Lilippople TC: excellent E: ogre EC: excellent > 
Flee
An ogre slave parries your futile lunge at him.
An ogre slave misses you with his bludgeon.

< 804h/801H 158v/162V T: Lilippople TC: excellent E: ogre EC: excellent > A Limestone Forest
Exits: -E -W
You flee westward!
e

< 804h/801H 157v/162V > A Stone Bridge Over River Cesh
Exits: -E -W
Corpse of an elven fisherwoman is lying here.
An ogre slave mopes here with a frown.
A pretty wild-elf fishes off the side of the bridge.

< 804h/801H 156v/162V > pwb fisher
You start chanting...

< 804h/801H 157v/162V > 
You complete your spell...
An elven fisherwoman is unaffected by your powerful word.

< 804h/801H 157v/162V > pwb fisher
You start chanting...

< 804h/801H 159v/162V > 
An elven fisherwoman misses you with his hit.
An elven fisherwoman misses you with his hit.

< 804h/801H 159v/162V T: Lilippople TC: excellent E: fisherwoman EC: excellent > 
You complete your spell...
An elven fisherwoman is unaffected by your powerful word.
Theshial GCC: 'wouldn't mind engaging with ss tho. Is that in the works'

< 804h/801H 160v/162V T: Lilippople TC: excellent E: fisherwoman EC: excellent > pwb
You start chanting...

< 804h/801H 161v/162V T: Lilippople TC: excellent E: fisherwoman EC: excellent > 
You complete your spell...
An elven fisherwoman gropes around, blinded after hearing Lilippople's word!

**Comment by Inames** [comment]
Yeah I've noticed that too, seems a lot of powers force targeting to whatever you are engaged on rather than the target you specify in the syntax. Totally forgot about that.

**Comment by Inames** [comment]
This happens with powers shieldpunch as well:

sp rutterkin

< 822h/822H 131v/131V >
< T: Amori TC: excellent E: warrior EC: small wounds EP: std P: std >
(Spam)
(Spam)
Wobb slams her shield into a demonic warrior in a an awesome display of brute force!
**_You slam your shield into a demonic warrior and it staggers in pain!_**

< 822h/822H 131v/131V >
< T: Amori TC: excellent E: warrior EC: small wounds EP: std P: std >

**Comment by shevarash** [comment]
This is fixed.
