### ISSUE TITLE
Ranger Powers Skills blocking casting?

### ISSUE THREAD

**Issue by torkur** [torilmud/issues#187]
Hi,  not sure if this is intended, but looks like a bug.  I tried casting Nature's Blessing after using one of the new skills and it ate the spell and then blocked the effects.

< 478h/438H 141p/141P 110v/110V |ts +|ss +|ap 6|ev +|bs +| >
< T: Sukzik TC: excellent E: miner EC: small wounds EP: std P: std > You swing your weapons in lethal arcs, dousing the area with a duergar miner's blood.
A duergar miner is weakened!

< 478h/438H 141p/141P 110v/110V |ts +|ss +|ap 5|ev 9|bs +| >
< T: Sukzik TC: excellent E: miner EC: few wounds EP: std P: std > You're not ready to perform another action!

< 478h/438H 141p/141P 110v/110V |ts +|ss +|ap 5|ev 9|bs +| >
< T: Sukzik TC: excellent E: miner EC: few wounds EP: std P: std > You're not ready to perform another action!

< 478h/438H 141p/141P 110v/110V |ts +|ss +|ap 5|ev 9|bs +| >
< T: Sukzik TC: excellent E: miner EC: few wounds EP: std P: std > pow 'natures blessing'
You have learned something new about quick chant!
You start chanting...

< 478h/438H 141p/141P 110v/110V |ts +|ss +|ap 5|ev 9|bs +| >
< T: Sukzik TC: excellent E: miner EC: few wounds EP: std P: std > 
You complete your spell...
You're not ready to perform another action!

**Comment by shevarash** [comment]
This is fixed - spells aren't blocked by the cool down for now.
