### ISSUE TITLE
Half Orc eating/drinking never uses up the item?

### ISSUE THREAD

**Issue by torkur** [torilmud/issues#189]
My evil ranger Half Orc cast powers goodberry and has been eating the same berry for a couple days.  I'd say about 20 hungry messages or so at this point with each message being "You eat part of a partially eaten a goodberry. You feel comfortably sated."   

From asking around, it might just be that Half Orcs aren't setup fully on eating/drinking?  While I love 1 partially eaten goodberry in inventory will always take care of it, it seems a little broken. ;)

**Comment by shevarash** [comment]
That's odd. We had some reports of this awhile back but I couldn't recreate the issue. I'll try it again, and thanks for the detailed explanation. That should help a lot.
