### ISSUE TITLE
Cleric can't forget curse from prayed spells

### ISSUE THREAD

**Issue by Adriorn** [torilmud/issues#19]

**Comment by shevarash** [comment]
This seems to be an issue with multiple spells. Full harm and full heal have the same issue.

The problem here is the interplay between the aliases and names of like-named spells.

**Comment by Alurissi** [comment]
as it is, if you use the alias for "curse"   cr, it allows you to forget and mem the spell, if you use the word curse, it automatically assumes you are talking about curse item, i'm sure the same is true with full heal and full harm, mud reads the full h, as one, but if you use the alias for them, it works fine

**Comment by shevarash** [comment]
No longer an issue.
