### ISSUE TITLE
Powers moonwell doesn't check !tele

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#190]
says 'wow that's wellable?'
says 'what a scam'
says 'erryting is wellable now'
says 'well doesn't check !tele flag'
says 'dum'
says 'shev knows about it, refuses to fix'

From scrollback. It doesn't appear however that a ticket was created for it. Powers moonwell doesn't check !tele,  and allows you do to things like teleport into SPOB with full equipment.

**Comment by shevarash** [comment]
I thought we fixed this already - I'll take another look.

**Comment by Nyyrazzilyss** [comment]
I don't believe it lets you well out of, however, druids can well into !tele areas.

I took Adud into SPOB the other day, and had a druid well into me and give me my equipment.

**Comment by shevarash** [comment]
Fixed.
