### ISSUE TITLE
Mostly missing...

### ISSUE THREAD

**Issue by Gogk** [torilmud/issues#196]
So, as Gogk, I've done SM exp train, even solo without ever an issue. Having a rune graven and all. But, on 9/11, 
after the reboot for range stuff. I noticed I wasn't hitting the same mobs as much. I noticed it on the second mob
Where I was missing 9-11 times before a single hit. I almost died, which never happens... at least during SM exp...
I wasn't hitting enough for the rune graven to vamp me up to continue the train.
Ohgma checked it out with me and witnessed the string of misses. Just thought you might want to know and check it out.

Thanks.
Love,
Gogk.

**Comment by Nyyrazzilyss** [comment]
Tested, this looks to be blind related.

Wielding a valhalla, there's no issues with hitting the mob. Wielding a rune graven, however, as soon as it procs blind on the mob I also can't hit it until blind wears off.

**Comment by shevarash** [comment]
This was indeed an accidental change to blind. Fixed, and thank you for the help debugging.
