### ISSUE TITLE
Pick lock impacts powers bs and trip cooldown?

### ISSUE THREAD

**Issue by Hibbidy** [torilmud/issues#197]
Please see below - even tried it without a pickable target and same issue.  Same thing happens with trip as well (can't trip after pick lock for a long time due to "You're not ready to perform another action" message).  Non-powers backstab does not seem to be impacted.

A Noble's Home
Exits: -W         
Corpse of a human noble is lying here.
An ornate gilded metal cage hangs here.
A human noble stands here haughtily.

< 1081h/598H 166v/171V P: std > 
time
It is 5pm, on the Day of the Deception
The 9th Day of the Month of Marpenoth (Leafall), Year 997.
Time elapsed since boot-up: 9:53:44
Current time is: Mon Sep 11 08:36:51 2017

< 1077h/598H 167v/171V P: std > 

You stop using a red dragon fanged dagger.

< 1074h/598H 168v/171V P: std > 
You get a squirming metallic string from a portable hole.

< 1074h/598H 168v/171V P: std >

You hold a squirming metallic string.

< 1073h/598H 168v/171V P: std >

Silly - it ain't even closed!

< 1073h/598H 169v/171V P: std > 
You stop using a squirming metallic string.

< 1072h/598H 169v/171V P: std >

You put a squirming metallic string into a portable hole on your person.

< 1072h/598H 169v/171V P: std >

You wield a red dragon fanged dagger.

< 1071h/598H 169v/171V P: std > 
bs noble
You're not ready to perform another action!

< 1065h/598H 171v/171V P: std > 
time
It is 5pm, on the Day of the Deception
The 9th Day of the Month of Marpenoth (Leafall), Year 997.
Time elapsed since boot-up: 9:53:50
Current time is: Mon Sep 11 08:36:57 2017

< 1062h/598H 171v/171V P: std > 
bs noble
You're not ready to perform another action!

< 1058h/598H 171v/171V P: std > 
time
It is 5pm, on the Day of the Deception
The 9th Day of the Month of Marpenoth (Leafall), Year 997.
Time elapsed since boot-up: 9:53:53
Current time is: Mon Sep 11 08:37:00 2017

< 1055h/598H 171v/171V P: std > 
bs noble
You're not ready to perform another action!

< 1048h/598H 171v/171V P: std > 
time
It is 5pm, on the Day of the Deception
The 9th Day of the Month of Marpenoth (Leafall), Year 997.
Time elapsed since boot-up: 9:53:57
Current time is: Mon Sep 11 08:37:04 2017

< 1044h/598H 171v/171V P: std > 
bs noble
You're not ready to perform another action!

< 1039h/598H 171v/171V P: std > 

< 1038h/598H 171v/171V P: std > 
time
It is 5pm, on the Day of the Deception
The 9th Day of the Month of Marpenoth (Leafall), Year 997.
Time elapsed since boot-up: 9:54:00
Current time is: Mon Sep 11 08:37:07 2017

< 1035h/598H 171v/171V P: std > 
bs noble
You're not ready to perform another action!

< 1030h/598H 171v/171V P: std > 

< 1029h/598H 171v/171V P: std > 
time
It is 6pm, on the Day of the Deception
The 9th Day of the Month of Marpenoth (Leafall), Year 997.
Time elapsed since boot-up: 9:54:03
Current time is: Mon Sep 11 08:37:10 2017

< 1026h/598H 171v/171V P: std > 
bs noble;time
You're not ready to perform another action!

< 1019h/598H 171v/171V P: std >

It is 6pm, on the Day of the Deception
The 9th Day of the Month of Marpenoth (Leafall), Year 997.
Time elapsed since boot-up: 9:54:06
Current time is: Mon Sep 11 08:37:13 2017

< 1019h/598H 171v/171V P: std > 

The human noble struts about trying to look regal.

< 1014h/598H 171v/171V P: std > 
time;bs noble
It is 6pm, on the Day of the Deception
The 9th Day of the Month of Marpenoth (Leafall), Year 997.
Time elapsed since boot-up: 9:54:09
Current time is: Mon Sep 11 08:37:16 2017

< 1011h/598H 171v/171V P: std >

You're not ready to perform another action!

< 1010h/598H 171v/171V P: std > 

< 1010h/598H 171v/171V P: std > 
time;bs noble
It is 6pm, on the Day of the Deception
The 9th Day of the Month of Marpenoth (Leafall), Year 997.
Time elapsed since boot-up: 9:54:11
Current time is: Mon Sep 11 08:37:18 2017

< 1004h/598H 171v/171V P: std >

You're not ready to perform another action!

< 1003h/598H 171v/171V P: std > 
time;bs noble
It is 6pm, on the Day of the Deception
The 9th Day of the Month of Marpenoth (Leafall), Year 997.
Time elapsed since boot-up: 9:54:14
Current time is: Mon Sep 11 08:37:21 2017

< 998h/598H 171v/171V P: std >

You're not ready to perform another action!

< 998h/598H 171v/171V P: std > 

< 997h/598H 171v/171V P: std > 
time;bs noble
It is 6pm, on the Day of the Deception
The 9th Day of the Month of Marpenoth (Leafall), Year 997.
Time elapsed since boot-up: 9:54:17
Current time is: Mon Sep 11 08:37:24 2017

< 991h/598H 171v/171V P: std > 
You're not ready to perform another action!

< 989h/598H 171v/171V P: std > 
time;BS noble
It is 6pm, on the Day of the Deception
The 9th Day of the Month of Marpenoth (Leafall), Year 997.
Time elapsed since boot-up: 9:54:21
Current time is: Mon Sep 11 08:37:28 2017

< 979h/598H 171v/171V P: std >

You're not ready to perform another action!

< 978h/598H 171v/171V P: std > 
time;BS noble
It is 6pm, on the Day of the Deception
The 9th Day of the Month of Marpenoth (Leafall), Year 997.
Time elapsed since boot-up: 9:54:23
Current time is: Mon Sep 11 08:37:30 2017

< 974h/598H 171v/171V P: std >

You're not ready to perform another action!

< 973h/598H 171v/171V P: std > 
time;BS noble
It is 6pm, on the Day of the Deception
The 9th Day of the Month of Marpenoth (Leafall), Year 997.
Time elapsed since boot-up: 9:54:25
Current time is: Mon Sep 11 08:37:32 2017

< 968h/598H 171v/171V P: std > 
You're not ready to perform another action!

< 967h/598H 171v/171V P: std > 
time;BS noble
It is 6pm, on the Day of the Deception
The 9th Day of the Month of Marpenoth (Leafall), Year 997.
Time elapsed since boot-up: 9:54:27
Current time is: Mon Sep 11 08:37:34 2017

< 963h/598H 171v/171V P: std >

You're not ready to perform another action!

< 962h/598H 171v/171V P: std > 

< 961h/598H 171v/171V P: std > 
time;BS noble
It is 6pm, on the Day of the Deception
The 9th Day of the Month of Marpenoth (Leafall), Year 997.
Time elapsed since boot-up: 9:54:30
Current time is: Mon Sep 11 08:37:37 2017

< 958h/598H 171v/171V P: std > 
You're not ready to perform another action!

< 958h/598H 171v/171V P: std > 
time;BS noble
It is 6pm, on the Day of the Deception
The 9th Day of the Month of Marpenoth (Leafall), Year 997.
Time elapsed since boot-up: 9:54:32
Current time is: Mon Sep 11 08:37:39 2017

< 955h/598H 171v/171V P: std >

You're not ready to perform another action!

< 955h/598H 171v/171V P: std > 
time;BS noble
It is 6pm, on the Day of the Deception
The 9th Day of the Month of Marpenoth (Leafall), Year 997.
Time elapsed since boot-up: 9:54:34
Current time is: Mon Sep 11 08:37:41 2017

< 952h/598H 171v/171V P: std >

You're not ready to perform another action!

< 952h/598H 171v/171V P: std > 

recharge
< 950h/598H 171v/171V P: std > 
You do not have any powers recharging.

< 949h/598H 171v/171V P: std > 
time;BS noble
It is 6pm, on the Day of the Deception
The 9th Day of the Month of Marpenoth (Leafall), Year 997.
Time elapsed since boot-up: 9:54:38
Current time is: Mon Sep 11 08:37:45 2017

< 945h/598H 171v/171V P: std >

A human noble makes a strange sound, as you place a glittering dagger of the Nurturing Matriarch in 
his back.
A human noble makes a strange sound, as you place a red dragon fanged dagger in his back.

**Comment by shevarash** [comment]
Fixed:

* The weapon cool down is now limited to rangers while it's in beta.
* The weapon cool down was doubled outside of combat. Fixed.
