### ISSUE TITLE
Ranger Powers: Ranged Shot

### ISSUE THREAD

**Issue by Dhelindel** [torilmud/issues#198]
**1.** The Alias does not work
682h/682H 210p/210P 129v/129V |sp +|cn +|ks +|kc +| P: std > rs noble d
Sorry, but that command has yet to be implemented...

**2.** The cooldown on powers prompt does not work.

Cover doesnt show on status like backstab and circle.

**Comment by Nyyrazzilyss** [comment]
You also don't need to be using a bow (just wielding a weapon) to use this power.

power 'ranged shot' commoner n
Your carefully aimed shot hits a graceful commoner to the north.

primary weapon:     a rune graven adamantine longsword

**Comment by shevarash** [comment]
This has all been fixed. Thanks!
