### ISSUE TITLE
Enhance: Generic vs Special Arrows

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#200]
With the new archery code, quivers have an unlimited supply of generic arrows.

Many people however have spent a lot of time and plat questing and collecting 'special' arrows.

Suggestions:

1)

Change the archery commands (whether attacking, or just entering the power name) to always use the generic arrow. If a specific name is provided (example: ks vrock) use the vrock arrow from your quiver to send a knockdown shot at your target.

2)

Replace hit/dam with a spell effect on quested arrows. Also, make them 1 time use. Or perhaps, give them a number of charges before they break (assuming you collect them afterwards).

For instance: Give tiamat arrows !fail silence with 3 charges. After 3 uses, it breaks/you can't collect it.

**Comment by Dhelindel** [comment]
Adding charges and spells to arrows is just stupid!
Adding arrow name to powers is also just stupid! 

No one wants those changes.

**Comment by Nyyrazzilyss** [comment]
Could you perhaps be more detailed in saying what would be wrong with that? Why it would be wrong, and what you would suggest as a replacement?

The intent of the suggestion was moving quested arrows to a more consumable structure (similar to poisons). There were also gcc complaints about having to switch quivers to switch arrows being 'clunky'. Being able to specify the arrow used from the quiver would solve that, and allow selecting for use of potentially numerous 'enhanced' arrows.

**Comment by shevarash** [comment]
We're working on some changes here...more to come soon.

**Comment by shevarash** [comment]
This has been addressed with arrow enchantments. Thanks for the feedback!
