### ISSUE TITLE
Ranged Specialist Skill

### ISSUE THREAD

**Issue by sekfarok** [torilmud/issues#201]
Can someone look into this skill? It's not notching as much as archery does. It happen to others as well.

**Comment by CountVooku** [comment]
I noticed this also. Archery has notched over 20 skills points and ranged specialist hasn't notched once. They were notching at a similar rate before the power changes.

**Comment by shevarash** [comment]
It isn't notching because it doesn't do anything under the new system. This may just get removed.

**Comment by shevarash** [comment]
This skill has been removed.
