### ISSUE TITLE
NPC stab immediately after i power kick?

### ISSUE THREAD

**Issue by sekfarok** [torilmud/issues#203]
This happen in bugbear area in CM.

< 575h/575H 109v/110V P: std > kk bugbear
You knock a crafty bugbear back several feet with a powerful kick!
Out of nowhere, a crafty bugbear stabs you in the back.
YIKES!  Another hit like that, and you've had it!!

and now the bugbear see invis too?

**Comment by shevarash** [comment]
What happened here is:

You broke invis when you kicked the bugbear. He initiated his attack with a backstab, because you weren't yet set to fighting. This is working as intended, though a little unfortunate for you in this situation.
