### ISSUE TITLE
Bows and critical hits... 

### ISSUE THREAD

**Issue by CountVooku** [torilmud/issues#204]
Warbow is 3% crit range for 3x damage... Have yet to see critical hit in hundreds of shots. Are critical hits broke now?

**Comment by sekfarok** [comment]
i got crit. but suddenly my shot was not flamed.

You score a CRITICAL HIT!
Your massive shot wounds a lithe commoner harshly.

**Comment by CountVooku** [comment]
Oh ok. I must have been having bad luck.

**Comment by sekfarok** [comment]
i do believe something is wrong. out of almost 200-300 shots, only 1 crit?

**Comment by shevarash** [comment]
It looks the critical hit chance for bows is working fine, but you're right that the warbow does not proc at all on criticals. If you still think this is an issue please feel free to re-open.
