### ISSUE TITLE
Crossbow Issues

### ISSUE THREAD

**Issue by sekfarok** [torilmud/issues#205]
Ok due to the new change on archery, crossbow no longer recognize either quiver or ammo belt.

You wield a steel crossbow studded with sapphires.

< 560h/560H 110v/110V T: Disha TC: excellent E: merchant EC: small wounds EP: std P: std > 
You don't have a quiver to draw from!
You don't have a quiver to draw from!
An opulent merchant misses you with his hit.

Then i fled, and swap quiver with ammo belt.

rem quiver
You stop using an ancient tooled dragonhide quiver.

< 560h/560H 110v/110V P: std > 
get ammo cache
You get a black leather ammo belt from a winged cache of Goufa.

< 560h/560H 110v/110V P: std > 
l in ammo
A black leather ammo belt (carried) : 
[89] a bronze tipped heavy crossbow quarrel (magic)

< 560h/560H 110v/110V P: std > 
wear ammo
You strap on the a black leather ammo belt.

< 560h/560H 109v/110V T: Disha TC: excellent E: merchant EC: pretty hurt EP: std P: std > 

You don't have a quiver to draw from!
You don't have a quiver to draw from!
An opulent merchant misses you with his hit.
An opulent merchant misses you with his hit.

And please upgrade Tia Crossbow. It is Tia loot and the stats are horrible!

You feel informed:
Name 'a steel crossbow studded with sapphires'
Keyword 'crossbow double heavy sapphires', Item type: WEAPON
Item can be worn on:  WIELD 
Item will give you following abilities:  NOBITS
Item is: MAGIC FLOAT NOBURN NOLOCATE TWOHANDS NOBITS
Weight: 5, Value: 1000000
Type: Heavy Crossbow Class: Simple
**Damage:  2D4  Crit Range: 6%  Crit Bonus: 2x**
Can affect you as :
    Affects : HITROLL by 5
    Affects : DAMROLL by 5
Special Effects : Sonic Bolt

**Comment by CountVooku** [comment]
And 2d4 seems a bit low for a Tia item.

**Comment by shevarash** [comment]
The dice and proc have been updated on the Tia crossbow, and there is now an crossbow quiver in BG at the fletcher.
