### ISSUE TITLE
Elementalist's Lava spell hit my fire elemental

### ISSUE THREAD

**Issue by Jasix13** [torilmud/issues#207]
A fire elemental blackens and burns as your burst of 
lava coats its body.

Shouldn't affect a fire mental? Was fighting the giant spider in GN

**Comment by shevarash** [comment]
I can't recreate this. If it happens again, please re-open with a log. 

It could have been caused from some previous issues with spell radii, or it might have been something unlreated, like the elemental expiring and losing charm just before your spell went off.

**Comment by Jasix13** [comment]
cool, thanks for looking into it.

Jasix
