### ISSUE TITLE
Web client doesn't allow creating new characters

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#208]
It looks like it might take some effort to fix, however, the web client requires a pre-existing character to function.

The log in screen however just asks for username/password, doesn't indicate that or provide alternatives.

It wouldn't hurt to put instructions on that page indicating that it does require a pre-existing character. I'd probably also place a link with that to telnet to toril for new character creation.

**Comment by shevarash** [comment]
This requires some work, but would be a nice enhancement for new players.

**Comment by Nyyrazzilyss** [comment]
The actual new character creation part quite likely would require real effort. I wouldn't call it something worth the time nearterm.

Updating the login screen however with clearer instructions shouldn't be to difficult, and should really be done for now.

**Comment by cmoncrief** [comment]
This has been added via an anonymous web client mode. You can use the web client to create new accounts by clicking the "Play now" button on the homepage.
