### ISSUE TITLE
Suggestion: SPOB portal entry

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#209]
It was kind of interesting taking an equipped character into SPOB.

Suggestion:

Change the SPOB entry portal to allow a single equipped character to enter it -if- no other players are currently inside the zone. On entry by an equipped player, the portal would poof/ no other players could enter. The zone does repop when no-one is inside it (i.e. they got killed) - That could repop the entry portal also.

I don't know if it would be possible even with equipment for a single player to solo the zone. I attempted a couple times with a warrior and got a bit further each time/ still uncertain if i'd be able to complete the zone. Even with that uncertainty, I wouldn't suggest any changes to the interior zone mechanics.

It would also need to be somewhat monitored just in case it shows up that a cleric or rogue (or other class) was easily able to complete the zone.

Two edge cases that would also need to be prevented:

1) People entering with equip and dying/staying in fugue, and an equipped cleric following up to res the (equipped) corpses.
2) A cleric entering the portal dragging equipped corpses (that's likely already addressed in the portal itself)

**Comment by Ruagh** [comment]
How nice of Adud... Just restrict the portal to "Adud-only" and ignore all the suggestions on small team content i have ever made.
