### ISSUE TITLE
Dragonhunter bow

### ISSUE THREAD

**Issue by jokkmeister** [torilmud/issues#212]
Nice to see it having a crit again but unfortunatly crit is useless. It is the second hardest bow in game to get and proc should reflect that. Also it doesn't seem to add any enchantment to its arrows?

Suggestion from me would be make the baby heal the enchantement on every arrow and add a useful proc. If it gets a regular enchantment for flair it's healing proc needs to heal way more to be of any use.

**Comment by shevarash** [comment]
The bow's proc was just ported to the new system - it doesn't do anything new. I'll pass this to the Areas teams for evaluation.

**Comment by marthammor** [comment]
Due to the number of items and the stats on those other items rewarded, this bow does not warrant any changes. Closing ticket.
