### ISSUE TITLE
Half Orc Shaman Cant Initiate Group Heal quest

### ISSUE THREAD

**Issue by sekfarok** [torilmud/issues#213]
Currently i am trying to do group heal quest. but failing mightily. here's what happen:

Since i dont have barbarian shaman, i started the quest using ogre shaman to pop the pool to spirit world.
Thinking that i need to do goodie version, i killed render and gave it's heart to unicorn but nothing happen.
Killed myself thinking the zone pop so i could kill unicorn and give the heart to render but it never pop.

Now i have to wait for another boot to do this. Please take a look at this. Kinda PITA to do the quest for those who doesnt know what is happening.

**Comment by marthammor** [comment]
For this quest, half-orcs are considered evil race and must do the evil side of this quest. There is a quest giver in Ghore, Faang, and Bloodtusk that give the quest.
