### ISSUE TITLE
a bluish silver longbow sculpted with jagged icicles

### ISSUE THREAD

**Issue by jokkmeister** [torilmud/issues#214]
By far the hardest bow to get in game and perhaps the hardest item to get of everything. Why has celestial bow been upped to be better hit/dam wise than icicles bow? If anything icicles bow should be upped alot to reflect how much harder it is to get. Even if it was upped to 6d6 10 10 it wouldn't be too much when compared to the difference of how hard they are to quest.

**Comment by shevarash** [comment]
The celestial bow wasn't changed. I'll tag this as areas for future consideration.

**Comment by marthammor** [comment]
Added Icy Burst enchantment to this bow.
Celestial Warbow from Magma was made good only and had Holy Burst added to it.
With the addition of the enchantment, being able to be used by more alignments, and with the higher damage on the proc, this bow is better than the Magma bow, even though it has one hitroll less.
Changes are done and pending move. Closing ticket.
