### ISSUE TITLE
Crystal Caverns incomplete?

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#215]
Katumi has nothing on file as coming from this zone.

I took a quick look at it, and it appears to be 61 rooms / 2 grids, with a lot of 50+ aggro elementals. There doesn't however appear to be any equipment that loads in the zone, or particular reason to ever return to it. Is the zone incomplete?

Crystal Caverns ------------------ levels 40-50          Maker: Vhaeraun/Waukeen

**Comment by marthammor** [comment]
Might have been a supporting zone for something else from homeland containing stuff not seen by players.

**Comment by shevarash** [comment]
It's not the best zone for sure, but it appears to be working as intended.
