### ISSUE TITLE
Suggestion: Give Havorr a reboot quest

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#216]
How would you feel about giving Havorr a platinum based quest to reboot the mud?

As an example, three types of Havorr could exist.

Havorr1 - The existing Havorr. It replaces itself with Havorr2 after having existed for 48 (?) hrs.
Havorr2 - Would have a quest that giving it 50k (?) plat loads Havorr3
Havorr3 - This mob initiates a 15 minute mud reboot timer when it loads. It should also global echo at 15,10,5,4,3,2,1,30sec,10sec the impending reboot. It would have a quest that giving it 5k (?) plat cancels the pending reboot, and reloads Havorr1. Requesting again for reboot wouldn't be possible until Havorr2 reloads.

This might work well as a money sink.

**Comment by shevarash** [comment]
I don't think this is something we want to add, though I'm looking into some alternative solutions to long boot times. Thanks for the idea.
