### ISSUE TITLE
Shooting Bronze quarrels command...Shouldn't be Bronze..

### ISSUE THREAD

**Issue by Gogk** [torilmud/issues#220]
When I typed "Ammo Bronze" the message I got was...You will now fire a supple pair of bronze dragonscale gloves ammunition.

Followed by..You have run out of a supple pair of bronze dragonscale gloves ammunition.

I should mention that neither myself nor Oghma who was observing were wearing such gloves...

**Comment by shevarash** [comment]
Well that doesn't seem right.
