### ISSUE TITLE
rangering with arrows

### ISSUE THREAD

**Issue by Awlan** [torilmud/issues#222]
currently only need one arrow in your quiver and you can continuosly shoot
ranged shot doesnt seem to aggro tracking mobs

**Comment by OghmaToril** [comment]
> currently only need one arrow in your quiver and you can continuosly shoot

This is how new archery was designed.  If you don't have ammunition in your quiver, you will be able to shoot unlimited normal arrows with 0/0 bonus.

> ranged shot doesnt seem to aggro tracking mobs

Do you have an example of this?  Or a log?  I haven't heard anything about this.
