### ISSUE TITLE
an iron hammer provided as newbie cleric weapon is unusable by the class

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#223]
(dwarf cleric)

an iron hammer

< 32h/29H 106v/105V P: std > 
wield hammer
You can't wield that.

Nonog tells you 'Item is: NOSELL NO-THIEF NO-MAGE NOBITS'
Nonog tells you 'says throwing hammer'

**Comment by shevarash** [comment]
Should be re-flagged as type hammer.

**Comment by marthammor** [comment]
Fixed, awaiting move. Closing ticket.
