### ISSUE TITLE
Restrictions: Cloak of the Elvenkind

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#225]
a cloak of the elvenkind (About) AC:0 SNEAK * Magic No_Loc !Barb !Drow !Duergar !Dwarf !Evil !Evilrace !Gnome !Halfling !Human !Lich !Ogre 
!Squid !Troll !Yuan * Wt:2 Val:100p * Zone: Air (UR) * Last ID: 2013-05-08

The existing restricts on this item are really about making it elf only. To give a bit of a downside to neutral elven rangers, perhaps add !neutral / or good-only to it?

**Comment by marthammor** [comment]
After discussing it with the rest of the staff, we're okay with making it good only. If anyone has objections, now is the time to speak up.

**Comment by marthammor** [comment]
Updated to good only. Awaiting move. Closing ticket.
