### ISSUE TITLE
Rangers: Checking Spells Cooldown Breaks Hide

### ISSUE THREAD

**Issue by Dhelindel** [torilmud/issues#227]
Both 'Spells' and 'Slots' command breaks ranger hide,

< > slots
> You stop trying to hide.
You have the following spells available:
( 1st circle )   [ 3/3 ]
( 2nd circle )   [ 3/3 ]
( 3rd circle )   [ 3/3 ]
( 4th circle )   [ 3/3 ]
( 5th circle )   [ 1/2 ] Next recharge in: 6 minutes 43 seconds 2 pulses 

< > spells
You stop trying to hide.
You have the following spells available:
( 1st circle )   [ 3/3 ]
 - Cloak of Vigor
 - Hunters Mark
 - Longstrider
( 2nd circle )   [ 2/3 ] Next recharge in: 2 minutes 20 seconds 3 pulses

**Comment by CountVooku** [comment]
Same for me.

**Comment by marthammor** [comment]
Fixed, awaiting move. Closing ticket.
