### ISSUE TITLE
fire elementals aren't rescuing

### ISSUE THREAD

**Issue by Adriorn** [torilmud/issues#23]

**Comment by cmoncrief** [comment]
Log?

(You can attach files here, or paste in text. Formatting it with the "insert code" helper in the editor makes it look nice too.)

**Comment by Adriorn** [comment]
An Elegant Home
Exits: -S
A fire elemental stands, inches above the surface here, fighting a lithe commoner.
A lithe commoner stands here, fighting YOU!
A graceful commoner stands here proudly.

< 878h/858H 127v/122V >
< T: Thammos TC: excellent E: lithe EC: excellent > 
A fire elemental attacks a lithe commoner, landing a single hit.
A lithe commoner attacks you, landing a single hit.
A lithe commoner, in a show of awesome skill, manages to trip up herself!
You attack a lithe commoner, landing a single hit.

< 856h/858H 127v/122V >
< T: Thammos TC: few scratches E: lithe EC: few scratches > 
A fire elemental attacks a lithe commoner, landing two hits.

< 855h/858H 127v/122V >
< T: Thammos TC: few scratches E: lithe EC: few scratches > order fire rescue thammos
Ok.

< 855h/858H 127v/122V >
< T: Thammos TC: few scratches E: lithe EC: few scratches > 
A fire elemental attacks a lithe commoner, landing two hits.
OUCH!  That really did HURT!
A lithe commoner attacks you, landing a single hit.
A lithe commoner clambers to her feet.

< 770h/858H 127v/122V >
< T: Thammos TC: small wounds E: lithe EC: few scratches > order fire rescue thammos
Ok.

< 770h/858H 127v/122V >
< T: Thammos TC: small wounds E: lithe EC: few scratches > order fire rescue thammos
Ok.

< 770h/858H 127v/122V >
< T: Thammos TC: small wounds E: lithe EC: few scratches > order fire rescue thammos
Ok.

< 770h/858H 126v/122V >
< T: Thammos TC: small wounds E: lithe EC: few scratches > 
A fire elemental attacks a lithe commoner, landing a single hit.
A lithe commoner attacks you, landing a single hit.

< 738h/858H 126v/122V >
< T: Thammos TC: small wounds E: lithe EC: few scratches > order fire rescue thammos
Ok.


Earth elementals do it just fine btw.

**Comment by shevarash** [comment]
I believe this has been fixed.

**Comment by Inames** [comment]
@shevarash this has not been fixed, just FYI. It's probably a class issue on the npc's summoned by powers conjure ele, it only affects powers version of conjure ele pets, not cast version.

Air/Fire ele's affected, Water/Earth I believe are fine.
