### ISSUE TITLE
Possible new Classes

### ISSUE THREAD

**Issue by SasukeUchiha1** [torilmud/issues#230]
I would like to know if it will be possible to add an oriental set of classes for example Ninja and Samurai

**Comment by CountVooku** [comment]
Omg please no.

**Comment by SasukeUchiha1** [comment]
Just wanna play a Samurai or Ninja

**Comment by marthammor** [comment]
While it is certainly not off the table, those two classes do not currently fit with the theme of the game. You are more than welcome to role play a rogue or a ranger as either one of them though.
