### ISSUE TITLE
I know no one cares but please... paladins.. Mount & Mounted Charge.

### ISSUE THREAD

**Issue by i982** [torilmud/issues#231]
i know another class overhaul is probably not in the cards for awhile but PLEASE PLEASE fix just these two things for paladins.. 

1.their mounts. they ARE flying. when riding you still have to wear fly gear to do flying stuff. it makes no sense at all. this was changed or broken definitely. cannot cross water while on a flying mount. and im almost 100% sure its movement points do NOT represent that it is in fact flying.

Status of griffon zealous mount paladinmount
---------------------------------------------------------------------------
Effects
---------------------------------------------------------------------------
charm                     detect evil               detect invisible          
**fly**                       infravision               protection from evil 

2.and lastly PLEASE PLEASE PLEASE make mounted charge a bash. the entire class is designed around riding the griffon in order to tank so please give us a working bash while mounted PLEASE. it does NOT work right for casters and puts the paladin in the exposed position of being able to be tripped non-stop and knocked to the ground. please do something.

**Comment by i982** [comment]
ok yeah using mounted charge is pointless. it doesnt stop casters (since the stun is super rare on casters) keeps you from rescuing. and does 2d5 damage compared to bash 4d5.. please do something to make this aspect of the class work in a useful manner so it can at least be played for something.

**Comment by shevarash** [comment]
Thanks for the feedback. We do care, and class updates are high on the list right now.

**Comment by i982** [comment]
thanks shev

**Comment by shevarash** [comment]
Resolved by this update: http://www.torilmud.com/news/paladin-upgrades-phase-1
