### ISSUE TITLE
Still able to pray old spells on ranger when using 'pre'....

### ISSUE THREAD

**Issue by CountVooku** [torilmud/issues#233]
pre
You continue your praying.

< 722h/704H 122v/122V |fa +|ap +|ev +|ss +|ts +|bs +| |3|3|3|0|2| P: sit > 

You have finished praying for Shillelagh.

< 722h/704H 122v/122V |fa +|ap +|ev +|ss +|ts +|bs +| |3|3|3|1|2| P: sit > 

You have finished praying for Shillelagh.

**Comment by marthammor** [comment]
Fixed, awaiting move. Closing ticket.
