### ISSUE TITLE
BUG (cosmetic) a gnarled and ancient walking staff proc

### ISSUE THREAD

**Issue by otebski** [torilmud/issues#235]
When the proc goes off it informs about armor being memorized. Happens every time.

Your staff sends a shock racing through your arm and into your head, causing
 your body to momentarily go numb.
**You have memorized armor.**
You have finished memorizing Teleport.

Your staff sends a shock racing through your arm and into your head, causing
 your body to momentarily go numb.
**You have memorized armor.**
You have finished memorizing Gate.

**Comment by marthammor** [comment]
Fixed, awaiting move. Closing ticket.
