### ISSUE TITLE
No error message for slots command

### ISSUE THREAD

**Issue by otebski** [torilmud/issues#236]
Class: **Rogue** 

< 476h/476H 122v/122V P: std > 
slots

You can pray for 11 1st, 10 2nd, 9 3rd, 8 4th, 7 5th, 7 6th, 6 7th, 5 8th, 4 9th, and 3 10th circle
spell(s).

**Comment by Inames** [comment]
That's only funnier cuz there was a crash bug a while back where somehow a rogue got slotted with some invoker spells on death, so every time he logged in it crashed the mud, we had like 2 hours of constant crashing.
