### ISSUE TITLE
Powers Earthquake is STILL knocking down consenting targets with 100% consistency.

### ISSUE THREAD

**Issue by Inames** [torilmud/issues#239]
Just a heads up there Shev, I know you did something with it before, I thought it was fixed, but during our Jot invasion run today and testing afterward I can again confirm that powers quake is dropping targets who consent every time. Maybe something new broke it or maybe there was a copyover of some outdated file that un-did your fix. We would appreciate if you could take a look at it again!

**Comment by ghost** [comment]
there is a way around this inames, include target keyword in your eaq line, ie: eaq giant, or eaq beard, it will only hit those with that keyword in your room, whom are aggressive, or if non are, it will hit 1. of that keyword only

**Comment by shevarash** [comment]
This appears to be fixed in my testing. Please re-open if I am mistaken.
