### ISSUE TITLE
cant mem elemental water embody

### ISSUE THREAD

**Issue by Adriorn** [torilmud/issues#24]

**Comment by shevarash** [comment]
I'm having trouble re-creating the issue. Can you supply a log?

(If you indent four spaces GitHub will display it formatted nicely. You can also just attach a file.)

**Comment by Adriorn** [comment]
Yeah no clue either.  Now I can mem it just fine...

**Comment by shevarash** [comment]
Ok, closing this one. Please re-open if it happens again.
