### ISSUE TITLE
layhands 6 minutes vs 12 minutes

### ISSUE THREAD

**Issue by Hibbidy** [torilmud/issues#242]
Hey Shev, in the paladin post it says layhands is every 6 minutes since it heals less, but in-game its recharge is 12 minutes -

**Comment by shevarash** [comment]
Woops! We'll try it out at 6 minutes and see how that feels.

**Comment by Hibbidy** [comment]
Just a heads up, I saw the news says layhands is now 6 minutes, but I just tried it and its still 12:

 - Lay On Hands in 11 minutes 57 seconds 2 pulses
