### ISSUE TITLE
Names

### ISSUE THREAD

**Issue by Inames** [torilmud/issues#249]
Unacceptable names:

1) Silly or funny names. Examples: Gillywoper, Wooglewanper
                The only exceptions are the gnome and halfling races.
2) Compound words. Examples: Lordfear, Hawkfist
3) Words, mispelled or not. Examples: Wynde, Windy, Wynter
4) Name from books or television. Examples: Rand, Smaug
5) No names or words backwards. Examples: Regnarami, Diurd, Samoht
6) No famous names. Examples: Cher, Madonna, Billclinton
7) Names that do not fit the race you are playing. Examples:
        An elf named Garagh or a dwarf named Theleindifel
8) No words or names from other languages or cultures.
        This also includes oriental names.
9) No oriental names or oriental sounding names. We do not have
        a "Far East" on TorilMUD as yet (with no immediate plans to add
        one) so such names are not allowed.
10) No names from TSR, FR, or Tolkein spelled correctly or not.
        This falls under the names from books criteria, but it seems
        we have to indicate this as a separate item. Examples:
        Drizzt or Drizst, Crysania or Krisania, Frodo or Frodoh

Names that break these conventions and associated account:
(note that I took these names from the alt-lists compiled by Katumi of people who were online, this is likely not everyone or every name that needs to be considered, and some of them may have been changed or deleted already, since players have to manage their own alt lists through Katumi's scripts)

@ Diel - He has many characters who's names are poorly constructed and borderline or blatantly break the rules.
Diel - Deal? Dial? Either way falls under the mis-spelled words convention, the many variations of the name might be passable but probably deserve to be scrutinized
Badase - This is likely read Badass, or Bad-Ase(ace) either way it's bad
Boki - https://en.wikipedia.org/wiki/Boki_(Hawaiian_chief)
Godmasa - sounds like GodMasta(master) or a play on the ~sama honorific of Japanese, would would read God-sama
Haxed - Hax -> Hacks, Hacked? Haxed is common digital slang for being hacked or hacking
Gokilurself - This is obviously an issue.
Gokilafam - This should be obvious too, but Go kil a fam(ily?)
Various itterations of Pussi, Pissi, Sissi(sissy) and Gay/gai/fag slurs, Gai(might be read guy, instead of gay, still falls under the mis-spelled words convention. Gaidiel ->GuyDeal?)

-------------------------------------------------------------------------------------------------------------------

@ Enth
Lonekin - Lone Kin compound words
Cohibas - Cohiba is a cigar brand, Cohibas is the plural form
Tagtab, Tide, Cumun, Dem(slang/accented: them), Duno, Notpenises, Police, Yolo, Cumpapa, Lobabawao ([1 Rogue] Lobabawao (Moon Elf)), Loloh, Lules, Milaina(semi-popular real name, latin/hispanic origins), Penises, Rednik(Redneck?) ---- All of these are blatantly inappropriate, and I guarantee most of them didn't come from auto-gen, so someone on staff set up an auto-approve script and let it run un-scrutinized for quite a while.

-------------------------------------------------------------------------------------------------------------------

@ Nyyrazzilyss
Adud - A Dud, Compound words
Ajac - A jack? compound misspelled words
Bombad - Bomb bad? compound misspelled words
Caged - Self explanatory
Ihgod - I, god, hrmmm... *ponders*

-------------------------------------------------------------------------------------------------------------------

@ Banducci
Jafar - Disney character
Bete - Beat, Bet, Bait, any way you read it, it's a mis-spelled word.
Odnat - Odd gnat, compound misspelled word
Misarie - Misery?
Tangelas - Tangela(s) English version of a Pokemon's name/pluralized form?

-------------------------------------------------------------------------------------------------------------------

@ Areh
Elwyn - Lord of the Rings character, also the name of a town
Famed - An english word
Hapih - Happy?
Messes - Quite the messy name...

-------------------------------------------------------------------------------------------------------------------

@ Toraza
[50 Warrior] Kalal (Barbarian) - Seems to be thematically reaching for a Kal-el play there? (superman, in case you aren't quite THAT nerdy)

-------------------------------------------------------------------------------------------------------------------

@ Jasix
Felin - Felon? Feline?
Gnibbles - Nibbles, misspelling of an English word
Gungan - Jar-Jar's race from Star Wars
Bonerod - Compound words
Haked - Hacked?

-------------------------------------------------------------------------------------------------------------------

@ Hibbidy
Dojoy - Do, Joy, Compound words
Omnom - onomatopoeia for the sound of eating
Zeksey - Misspelling/played off word sounds like Sexy

-------------------------------------------------------------------------------------------------------------------

@ Tafi
Tafi - Taffy?
Duku - Count Dooku from star wars? Also, the name of a fruit.

-------------------------------------------------------------------------------------------------------------------

Okay I got bored, might add to this list later or as names come up that need addressing.

**Comment by Inames** [comment]
Now, I recognize that this is a fairly petty thing to do, but to anyone who wants to throw a fit, the name I came up with for my Elf Paladin, Aliyah, was thrown out because to Shar it was too similar to the name of an American singer named Aaliyah, who died in 2001, that I had never heard about before today. So fair is fair, and there needs to be some accountability for this stuff if it's actually/finally going to be enforced. So feel free to add other names that you feel break the conventions here so they can be dealt with accordingly.

**Comment by CountVooku** [comment]
You could pretty much do this with ANY name?

**Comment by ghost** [comment]
dude, are we totally forgetting Adriorc (half-orc)? that one is by far one of the worst names :P and i'm sure i have a few as well, such as my ogre....Dumbox,, oh yeah, and lets not forget Inames....compound word I names :P

**Comment by Ruagh** [comment]
Man, with a necromancer named Decay around, who would even mention those name rules? Theyre long dead. Which is sad, if you ask me, because at least silly names - autogen gives alot, but there are definitely manually set by imms ones too - could have been renamed. And while they arent enforced, may I be renamed into DragonMasta ASAP before somebody will squat this fine name???

**Comment by cmoncrief** [comment]
We've introduced a new name system to address these issues. Thank you for your feedback.
