### ISSUE TITLE
powers siphon doesn't work on some undead

### ISSUE THREAD

**Issue by Adriorn** [torilmud/issues#25]
but non powers version does

**Comment by shevarash** [comment]
Can you give me some example of undead that it doesn't work on?

**Comment by Adriorn** [comment]
There was a lich in Seers that it didn't work on.  I know Lilithelle knows of more.

**Comment by shevarash** [comment]
I found the lich: `the guardian lich` (#44018)

**Comment by shevarash** [comment]
This has been fixed at some point:

```
You cast the spell 'Siphon Undead'.
The guardian lich falters as his undead force is seized and drained!
```
