### ISSUE TITLE
Powers prompt: Increase to 12?

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#250]
Paladin has five 2h / five 1h powers, plus two 'special' powers (lay on hands / divine smite)

This isn't including anything that might show up when spells are done.

Would it be possible to increase the settable slots on the powers prompt from 10 to 12?

**Comment by i982** [comment]
if you include furious assault thats 13. might as well do 15 slots? not sure how this will look with spell changes. and is there a chance for a more compact prompt? would it cause problems removing the spaces between the power alias and the + sign to be removed? from |lh +|ds +| to |lh+|ds+| ?

**Comment by CountVooku** [comment]
I had FA on my prompt but took it off because of the long cooldown. Working on a timer bar for it instead. I'll share (mudlet) once I get it working well.

**Comment by shevarash** [comment]
Already increased this to 15.
