### ISSUE TITLE
Wrathful Smite not doing damage?

### ISSUE THREAD

**Issue by Toraza** [torilmud/issues#252]
< 735h/685H 120v/120V >
< T: Atinan TC: excellent E: seawitch EC: awful EP: std P: std > 
A kuo-toa seawitch staggers from your powerful bludgeon!
You enshroud a kuo-toa seawitch in a mist of blood with your mighty bludgeon!
A kuo-toa seawitch wounds you harshly with her massive slash.
OUCH!  That really did HURT!
A kuo-toa seawitch misses you with her slash.

< 619h/685H 120v/120V >
< T: Atinan TC: few scratches E: seawitch EC: awful EP: std P: std > ws
A halo of divine light emanates from you, filling you with holy wrath.
Your weapon explodes in a flash of searing holy light as you strike a kuo-toa seawitch!

< 618h/685H 120v/120V >
< T: Atinan TC: few scratches E: seawitch EC: awful EP: std P: std > 
You miss a kuo-toa seawitch with your bludgeon.
A kuo-toa seawitch misses you with her slash.
A kuo-toa seawitch misses you with her slash.

< 618h/685H 120v/120V >
< T: Atinan TC: few scratches E: seawitch EC: awful EP: std P: std > 
Your translucent golden shield fades away.
ss

< 618h/685H 120v/120V >
< T: Atinan TC: few scratches E: seawitch EC: awful EP: std P: std > A translucent golden shield forms in front of you as strike out at a kuo-toa seawitch.

< 618h/685H 120v/120V >
< T: Atinan TC: few scratches E: seawitch EC: awful EP: std P: std > 
A kuo-toa seawitch slumps to the ground.
You crushed a kuo-toa seawitch's skull, I'm afraid she's dead.
a kuo-toa seawitch is dead! R.I.P.

----------------------------------------------------------------------------

< 637h/685H 120v/120V >
< T: Atinan TC: few scratches E: grippli EC: awful EP: std P: std > 
A grippli tribe-mother's attack only grazes you as you dodge aside!
A grippli tribe-mother slightly wounds you with her strong hit.
A grippli tribe-mother badly wounds you with her powerful hit.
A grippli tribe-mother staggers from your mighty bludgeon!
You enshroud a grippli tribe-mother in a mist of blood with your mighty bludgeon!

< 594h/685H 120v/120V >
< T: Atinan TC: small wounds E: grippli EC: awful EP: std P: std > ws
A halo of divine light emanates from you, filling you with holy wrath.
Your weapon explodes in a flash of searing holy light as you strike a grippli tribe-mother!

< 594h/685H 120v/120V >
< T: Atinan TC: small wounds E: grippli EC: awful EP: std P: std > 
A grippli tribe-mother's attack only grazes you as you dodge aside!
A grippli tribe-mother barely wounds you with her average hit.
A grippli tribe-mother misses you with her hit.
A grippli tribe-mother is nearly slain by the force of your mighty bludgeon!
A grippli tribe-mother is mortally wounded, and will die soon, if not aided.
A grippli tribe-mother slumps to the ground.

< 582h/685H 120v/120V >
< E: grippli EC: awful EP: std P: std > 
A grippli tribe-mother slumps to the ground.
You crushed a grippli tribe-mother's skull, I'm afraid she's dead.
a grippli tribe-mother is dead! R.I.P.
A grippli tribe-mother slumps to the ground.

-----------------------------------------------------

Maybe not the best examples but I have seen it where a mob is 1 hit from death and wrathful smite didn't kill it.

**Comment by Toraza** [comment]
OK - it did smite a morted mob:

< 765h/715H 120v/120V >
< T: Atinan TC: excellent E: echinoloth EC: awful EP: std P: std > 
An echinoloth misses you with its bite.
An echinoloth misses you with its bite.
You miss an echinoloth with your bludgeon.
You enshroud an echinoloth in a mist of blood with your awesome bludgeon!
An echinoloth is nearly slain by the force of your mighty bludgeon!
An echinoloth is mortally wounded, and will die soon, if not aided.
A kuo-toa whip misses you with her hit.
A kuo-toa whip misses you with her hit.
A kuo-toa monitor misses you with his hit.
A kuo-toa monitor misses you with his hit.
A kuo-toa monitor misses you with his hit.
You nimbly avoid a kuo-toa monitor's attempt to knock you down and attack as he falls past!
Your massive bludgeon badly wounds a kuo-toa monitor.
Your massive bludgeon badly wounds a kuo-toa monitor.
A kuo-toa whip misses you with her hit.
A kuo-toa whip misses you with her hit.
A kuo-toa monitor misses you with his hit.
A kuo-toa monitor misses you with his hit.
A kuo-toa monitor misses you with his hit.
A kuo-toa monitor misses you with his hit.
A kuo-toa monitor misses you with his hit.
A kuo-toa monitor misses you with his hit.
A kuo-toa monitor misses you with his hit.
You partially deflect a kuo-toa monitor's lunge at you.
A kuo-toa monitor slightly wounds you with his strong hit.
A kuo-toa monitor misses you with his hit.
A kuo-toa monitor misses you with his hit.
A kuo-toa monitor misses you with his hit.
A kuo-toa monitor misses you with his hit.
A kuo-toa seawitch misses you with her slash.
A kuo-toa seawitch misses you with her slash.
A kuo-toa whip misses you with her hit.
A kuo-toa whip misses you with her hit.

< 739h/715H 120v/120V >
< E: echinoloth EC: awful EP: std P: std > ws
A halo of divine light emanates from you, filling you with holy wrath.
You strike an echinoloth down in a dazzling explosion of divine radiance!
an echinoloth is dead! R.I.P.
You receive 273,674 XP (1.09%) experience.

**Comment by shevarash** [comment]
Fixed this a few updates ago - it was an issue with all of the new 1H powers.
