### ISSUE TITLE
Rangers: Make cloak of resilience exclusive to blur

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#254]
Cloak of resilience on a ranger when combined with blur is way to powerful.

A ranger with both up can tank pretty much anything.

Perhaps change it to be exclusive, you can have one or the other but not both?

**Comment by CountVooku** [comment]
Veto

**Comment by shevarash** [comment]
We may adjust Cloak of Reslience, but making it conflict with blur is not the direction I'd like to take.
