### ISSUE TITLE
tiny gargantuan dragon in Oakvale

### ISSUE THREAD

**Issue by otebski** [torilmud/issues#258]
***A tiny faerie dragon flutters here.**

< 322h/516H 125v/128V P: std > 
l dragon
Shiny scales of deep green form an intricate pattern of armor
offering him vast protection from physical and magical attacks.
The tiny dragon beats his colorful translucent wings furiously
to keep him afloat.  Large eyes of amber peer about searching
for intruders.  Small sharp teeth sparkle as the dragon constantly
grins with laughter and excitement as he plays within the confines
of the forest.
**Newt is a gargantuan-sized level 51 Dragon.**

**Comment by torilmud-silvanus** [comment]
Fixed in https://github.com/torilmud/torilmud/pull/698 pending move to main

**Comment by gruumsh** [comment]
merged on july 31st
