### ISSUE TITLE
Earth plane "small" adjustments... come on...

### ISSUE THREAD

**Issue by i982** [torilmud/issues#260]
can you at least make the gems NOT wander into jermlaines room so we can do turn ins? jesus christ
A Ledge Within a Shaft of Gems
   This dark shaft within the earth is composed of black soil 
and stripes of rough crystalline rock. Wooden beams have been 
assembled into a ledge overlooking the shaft below. A rope and 
pulley system has been damaged beyond repair, leaving no safe way 
to descend into the mine shaft that extends into darkness below.
Exits: - Down          [85809] 
A large bucket and clockwork mechanism waits to carry you out of the mine.
A beautiful crystal is here.
A beautiful crystal is here.
A beautiful crystal is here.
A beautiful crystal is here.
An enslaved jermlaine is here.

**Comment by CountVooku** [comment]
I got a kick out of the 'small adjustments' also... nerfed to the point where it won't be used again.
