### ISSUE TITLE
Anti Paladin Spells?

### ISSUE THREAD

**Issue by i982** [torilmud/issues#261]
You have memorized the following spells:
( 9th circle)  1 - Dark Wrath
( 8th circle)  2 - Tazriks Frenzied Hound
**( 7th circle)  3 - minor paralysis**
( 6th circle)  3 - Blindness
( 5th circle)  4 - Spectral Hand
( 4th circle)  4 - Curse Item
**( 3rd circle)  5 - pain touch**
( 2nd circle)  4 - Armor
               1 - Command Undead
( 1st circle)  1 - Bless
               5 - Cause Light

And you are currently praying for the following spells:
   23 seconds:  ( 9th) Harm

You can pray for no more spells.

ive tried praying them differently. forgetting them. relogging. nothing changes them into the powers version.

**Comment by OghmaToril** [comment]
No longer an issue with Blackguard/Anti-paladin being re-written.
