### ISSUE TITLE
Non Powers Spells - Paladin

### ISSUE THREAD

**Issue by i982** [torilmud/issues#265]
not sure if this is intended or what. but you can still pray certain non powers spells if you use certain short hands to pray them. i.e. "pray det mag" will pray the non powers version. not a big deal but if its a bug i wanted to let you guys know.

( 1st circle)  1 - Bless
               1 - Cure Light
               1 - detect magic

And you are currently praying for the following spells:
    3 seconds:  ( 1st) Cure Light
   13 seconds:  ( 2nd) Armor
   32 seconds:  ( 7th) Dispel Magic
   57 seconds:  (10th) Holy Word
   73 seconds:  ( 5th) Remove Poison

You can pray for 2 1st, 4 2nd, 4 3rd, 4 4th, 2 7th, and 2 8th circle spell(s).

< 1171h/1171H 212v/212V P: sit > 
forget detect magic
You purge 'detect magic' spell from your thoughts.

< 1171h/1171H 212v/212V P: sit > 

You have finished praying for Cure Light.

< 1171h/1171H 212v/212V P: sit > 
pray det mag
You are praying for detect magic, which will take about 7 seconds.

< 1171h/1171H 212v/212V P: sit > 

You have finished praying for Armor.

< 1171h/1171H 212v/212V P: sit > 
forget det magi
You purge 'detect magic' spell from your thoughts.

< 1171h/1171H 212v/212V P: sit > 
pray detect magic
You are praying for Detect Magic, which will take about 7 seconds.

**Comment by shevarash** [comment]
This should be a non-issue now that their spell system has been swapped out. :)
