### ISSUE TITLE
Archery Mob Problems

### ISSUE THREAD

**Issue by shevarash** [torilmud/issues#270]
* Ranged shots from NPC archers are lagging players on hit
* Archer NPCs are firing on hidden players
* There are reports that NPC archers are doing too much damage

**Comment by otebski** [comment]
Damage from archery mobs is significantly higher than melee - 100ish hits from level 25 pixies in OV.

Removed: entry about arrows selling for plats. they are finite and this does not pose an issue

**Comment by shevarash** [comment]
I tested the damage out, and while it is relatively high, it is because Longbows themselves are powerful weapons with high damage dice. Archer mobs are doing the same damage that a mob of the same level with a 4d6 weapon would do.

Those pixies are level 36 by the way, and their damage averages around 50hp per ranged shot. Thanks for reporting all of these issues - the rest were bugs and are being resolved.

**Comment by shevarash** [comment]
This has been resolved.
