### ISSUE TITLE
Skill Caps please

### ISSUE THREAD

**Issue by i982** [torilmud/issues#271]
this is dumb. and i know you have been super busy with all the changes.

im getting old.. and for some reason i cannot tell the difference between maxed out skills and non-maxed.

can we please change the color of maxed to something a little more differential? light blue? yellow? anything to help differentiate between white and whiter?

I literally cannot tell the difference in shades anymore.

sorry for the silly request.

**Comment by i982** [comment]
never mind i suppose i just noticed if i highlight by dragging my mouse the colors are very distinct.

**Comment by shevarash** [comment]
I think bright cyan looks good here:

![image](https://user-images.githubusercontent.com/24870638/34919091-df0231b4-f923-11e7-925b-b8b940797d77.png)

**Comment by i982** [comment]
looks great!
