### ISSUE TITLE
Tia Crossbow and all crossbows in general

### ISSUE THREAD

**Issue by i982** [torilmud/issues#275]
would it be possible to move the flagged ammo to normal arrows? or have crossbows removed and reworked as bows? i mean this is a perfectly good item that is total garbage cause no bolts are worth using? the simplest adjustment would be to just allow them to fire normal arrows.

please consider:)

**Comment by shevarash** [comment]
Our goal here is to add more interesting crossbows and crossbow bolts. I realize that's frustrating to have to wait for, but we'll get there!
