### ISSUE TITLE
BUG: Dread Mist entry portal not working for undead

### ISSUE THREAD

**Issue by otebski** [torilmud/issues#278]
Lich/Necro pets may not "enter mist". Nothing happens

**Comment by shevarash** [comment]
I can't seem to recreate this. Maybe there wasn't any light in the room at the time?

**Comment by Inames** [comment]
That shouldn't be an issue with undead pets. Perhaps it's a level limitation on the portal object? What was the level of pet you were trying to bring in?

**Comment by otebski** [comment]
I cant figure a way to get past this problem.

Score information for Onir

Level: 50   Race: Human   Class: Lich        
Hit points: 776(758)  Moves: 120(120)
Experience Progress: 73 % 
Coins carried:   91 platinum   261 gold    77 silver    77 copper
Coins in bank: 1723 platinum     8 gold     2 silver     2 copper
Prestige: 5834   Acheron Kill Count: 0
Citizen of:   Viperstongue Outpost
Outcast from: Waterdeep, Griffon's Nest, Leuthilspar, Mithril Hall, Beluir,
Ashrumite, Calimport, Baldur's Gate, Scardale
Playing time: 15 days / 18 hours / 12 minutes
Title: 
Followers:
   the ghost of a human noble
   the spectre of a human noble
Status:  Standing.
Detecting:       Life Heat

Active Powers:
--------------
**Light**


< 776h/758H 120v/120V P: std > 
l room
The Edge of the Forest of Mir
   Sparsely placed gigantic redwood tree trunks stretch to great heights all
about here, marking the beginning of the black Forest of Mir. There is
almost no light here, as the ancient forest's trees create such a thick
netting of branches high above that almost all sunlight is blocked out.
Because of this, this forest has an ill reputation for harboring a host of
horrors, and few dare to explore it, as those that do generally do not
return at all.  The air smells tangy and musty, with the heady pine scent
overpowering.  The great black forest stretches out in all directions but
west, where lie the formidable Marching Mountains, the only practical entry
to Mir.
Exits: - North - East  - South - West 
**A mysterious mist parts revealing a path.**
A human adventurer tramples through the forest, looking for treasure.
**The spectre of a human noble stands here.
The ghost of a human noble stands here.**

< 775h/758H 120v/120V P: std > 

It's mild out today.

< 775h/758H 120v/120V P: std > 

An owlbear enters from the south.

< 773h/758H 120v/120V P: std > 

A human adventurer leaves east.

< 771h/758H 120v/120V P: std > 
**o followers en mist**

[ ORDER followers en mist ]
**Ok.**

< 771h/758H 120v/120V P: std > 
l
The Edge of the Forest of Mir
Exits: - North - East  - South - West  [Error: mud 'The Edge of the Forest of
 Mir' doesn't match mapper 'The Forest of Mir' at '18487'] 
A mysterious mist parts revealing a path.
An owlbear snuffles through the undergrowth, searching for food.
**The spectre of a human noble stands here.
The ghost of a human noble stands here.**

The spectre of a human noble is a medium-sized **level 50** Spirit.
The ghost of a human noble is a medium-sized **level 50** Spirit.

**Comment by marthammor** [comment]
Try again without mudlet and see if you continue to have issues please.

**Comment by Nyyrazzilyss** [comment]
I don't think it would be mudlet related in that the log shows both the command being sent as well as the mud response.

However, just in case (using cmud, a light in inventory)


< 613h/720H 258p/266P 130v/130V P: std > con ghost
The ghost of a human noble is a medium-sized level 50 spirit. The perfect match!
You cannot raise any undead from this being.

< 616h/720H 260p/266P 130v/130V P: std > o ghost enter mist
Ok.

< 618h/720H 261p/266P 130v/130V P: std > l
The Edge of the Forest of Mir
Exits: -N -E -S -W
A mysterious mist parts revealing a path.
The ghost of a human noble stands here.
A grig sprite flutters amongst the trees, grinning mischeviously.

**Comment by marthammor** [comment]
Okay, thanks Nyy. Just trying to eliminate possible causes.

**Comment by shevarash** [comment]
I updated the portal code awhile back - is this still happening?

**Comment by torilmud-silvanus** [comment]
This will be fixed in https://github.com/torilmud/torilmud/pull/617

**Comment by Nyyrazzilyss** [comment]
Just tested with a L40 ghast, still happening.

**Comment by torilmud-silvanus** [comment]
Yeah the above fix isn't live on the MUD yet. I'm not sure how much you can see of the link https://github.com/torilmud/torilmud/pull/617 but it needs to be merged before you will see the fix. Sorry for the miscommunication.
