### ISSUE TITLE
Dreadmist : dire raven blind

### ISSUE THREAD

**Issue by otebski** [torilmud/issues#279]
1. Dire ravens blind permanently
2. Blinded person cant leave Dreadmist (cant camp, cant find path out, cant enter hole)
3. Dire raven blind cannot be cured by powers/nonpowers heal, powers cure blind - cureable only by nonpowers cure blind.

**Comment by shevarash** [comment]
I fixed this - for now - by making the power version of cure blind able to remove the bit.
