### ISSUE TITLE
still can't mem powers doppleganger

### ISSUE THREAD

**Issue by Adriorn** [torilmud/issues#28]

**Comment by Adriorn** [comment]
memor dop
You are memorizing doppleganger, which will take about 6 seconds.

**Comment by cmoncrief** [comment]
Oops, I didn't actually move the fix in.  :man_facepalming:

**Comment by shevarash** [comment]
Oops, I didn't actually move the fix in. :man_facepalming:

**Comment by cmoncrief** [comment]
It should be in now?
