### ISSUE TITLE
Room names ending in space

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#280]
An Intersection in the Trail 
Exits: -N -S -W
A wooden sign stands along the road.
A hideously ugly merchant slowly trudges up the path.
< 783h/783H 389p/389P 123v/124V P: std > 
world
Syntax: world < stats, zones >
This server compiled at 11:29:45 Dec 27 2017.
You are currently in: The Ashstone Trail

This is the room that borders Ashstone/Greycloak/and Alterian Region - Mountains.

The name of the room is "An Intersection in the Trail ", it has a trailing space

"A Road Through the Forest "  <- 1 north of "A Junction of Three Paths", Ashstone Keep Road

"A Caravan Trail Across the Northern Tundra " 3s2es2e from Icecrag Entrance, The Northern Caravan Trail

Exits: -N -E -S -W [Error: trailing whitespace: (A Large Hallway Decorated with Exquisite Weaponry )]     [Clair]  (Scardale)

**Comment by marthammor** [comment]
Fixed.
Also fixed a lot of the extra trailing white spaces in Scardale beyond the one you mentioned.
Annnddd... I used grep to find all other instances with trailing white space in the world files, so.. shouldn't have any more of this issue.
And the mob files.
And the object files.
Awaiting move to main.
