### ISSUE TITLE
Scribing Missile Shield required 11 pages on Enchanter

### ISSUE THREAD

**Issue by Gyrx** [torilmud/issues#282]
Log:
< 799h/799H 433p/433P 137v/137V P: sit > 
scribe missile shield
You start to copy down the spell..

< 799h/799H 433p/433P 137v/137V P: sit > 

You have completed page 1 out of 11 of missile shield into your spellbook.

< 799h/799H 433p/433P 137v/137V P: sit > 
The earth shakes violently about you, and birds take to the air.

< 799h/799H 433p/433P 137v/137V P: sit > 

You have completed page 2 out of 11 of missile shield into your spellbook.

< 799h/799H 433p/433P 137v/137V P: sit > 

You have completed page 3 out of 11 of missile shield into your spellbook.

< 799h/799H 433p/433P 137v/137V P: sit > 

You have completed page 4 out of 11 of missile shield into your spellbook.

< 799h/799H 433p/433P 137v/137V P: sit > 

Autosaving...

< 799h/799H 433p/433P 137v/137V P: sit >

You're busy scribing a spell into your spellbook!

< 799h/799H 433p/433P 137v/137V P: sit > 

You have completed page 5 out of 11 of missile shield into your spellbook.

< 799h/799H 433p/433P 137v/137V P: sit > 

You have completed page 6 out of 11 of missile shield into your spellbook.

< 799h/799H 433p/433P 137v/137V P: sit > 

You have completed page 7 out of 11 of missile shield into your spellbook.

< 799h/799H 433p/433P 137v/137V P: sit > 

You have completed page 8 out of 11 of missile shield into your spellbook.

< 799h/799H 433p/433P 137v/137V P: sit > 

You have completed page 9 out of 11 of missile shield into your spellbook.

< 799h/799H 433p/433P 137v/137V P: sit > 

You have completed page 10 out of 11 of missile shield into your spellbook.

< 799h/799H 433p/433P 137v/137V P: sit > 

You finish scribing spell missile shield to a golden spellbook etched with platinum.
The spell uses 11 pages in a golden spellbook etched with platinum, leaving 282 more pages free.

---------------

< 799h/799H 433p/433P 137v/137V P: sit > 
h skill_ench
"SKILL_ENCHANTER"

The following is a list of all skills and spells available to the
Enchanter class:

SKILLS

...

SPELLS
...
3rd circle:     locate object, strength, dispel invisible, chromatic orb
                dexterity, blink, missile shield, ray of enfeeblement

-------

<held>               a golden spellbook etched with platinum (magic)
<held>               a fiery feather of a phoenix

**Comment by shevarash** [comment]
Were you in a guildhall when you did this, or were you copying the spell? The spell has been removed from all classes, so I'm not sure how you could hvae scribed it unless it was a copy...

**Comment by Gyrx** [comment]
I was copying from a legacy book of mine.

**Comment by shevarash** [comment]
We'll have to update this so that you can't copy it.
