### ISSUE TITLE
Spell focus improvement

### ISSUE THREAD

**Issue by otebski** [torilmud/issues#285]
Right now spell focus is mostly sough by damage dealers (invokers and liches) and healers as it has direct impact on core skills of the class.

For enchanters and illusionists SF is pretty much a side effect.
To balance SF among classes SF should impact buffs too.

E.g. each 2? 3? 4? SF should add additional mirror image or reduce degradation of displace.
for dragonscales it could increase the threshold of stopped damage or increase number of hits absorbed (or maybe add extra effects to hast too? eg. 2% chance of extra attack for a each sf ench?)

**Comment by otebski** [comment]
I completed some tests after posting. It seems that there is some impact of SF on displace (not indicated in powers info in anyway). I will test further. Maybe I was premature with my assumptions.

**Comment by shevarash** [comment]
SF should help everywhere that specialize helps, which is on most buffs. The effect of increased duration on some buffs is not as impressive as increased defensive power, but these spells have all been setup that way intentionally. I'm going to close this, but if you have more questions or issues please feel free to update the ticket.
