### ISSUE TITLE
Shadow bolt causes no aggro

### ISSUE THREAD

**Issue by otebski** [torilmud/issues#289]
Setup to replicate:

1. Send shade to tank a tracking mob (in that case it was a astral phoenix)
2. Walk in - bolt phoenix
3. Walk out

Expected result:
Phoenix tracking after killing shade

Actual result:
Phoenix is not tracking

**Comment by otebski** [comment]
A dark shade stands in mid-air here, fighting an ice troll.
An ice troll stands here, fighting a dark shade.

< 759h/759H 165v/166V P: std >

You start chanting... [Casting: bolt troll (Shadow Bolt)]

< 759h/759H 165v/166V P: std > 

Casting: Shadow Bolt 

< 759h/759H 165v/166V P: std > 

You complete your spell...[Completed spell: bolt troll (Shadow Bolt)]
You send a bolt of shadows towards an ice troll, impacting in a burst of
darkness!
You send a bolt of shadows towards an ice troll, impacting in a burst of
darkness!
You send a bolt of shadows towards an ice troll, impacting in a burst of
darkness!
You send a bolt of shadows towards an ice troll, impacting in a burst of
darkness!
You send a bolt of shadows towards an ice troll, impacting in a burst of
darkness!

< 759h/759H 166v/166V P: std > 
A Vast Plain of Farms at the Base of the Great Plateau
Exits: - North - South - West 
*A dark shade stands in mid-air here, fighting an ice troll.
An ice troll stands here, fighting a dark shade.

< 759h/759H 166v/166V P: std >

Inside a Huge Shack
   This huge shack, nearly twenty feet tall, is barely large
enough to accomodate the girth of a frost giant.  The walls are
made of wood lashed together with twine.  Animal skins are tacked
onto the wood to keep the wind out.  Farming implements clutter
the floor and a huge iron plow sits forlornly in one corner; none
of which give any clue as to how the giants manage to grow
anything in this climate.  A woven fur mat sits in one corner of
the shack and serves as a makeshift bed.  The door stands open
and leads south out to the plains.
Exits: - South

< 759h/759H 165v/166V P: std > 


Troll never tracked to me

**Comment by shevarash** [comment]
I tried to replicate this but I didn't have any success. Shadow bolt does indeed cause aggro, so it's possible that something was preventing the troll from tracking. Did you happen to have mislead up?

**Comment by otebski** [comment]
At phoenixes I didnt have mislead - 100% sure, I was trying to lure them, had to use mm scroll instead.
At jot - I dont think i did. Even if, I moved to adjacent room so it should track anyway.

**Comment by shevarash** [comment]
Hopefully this was an issue that was fixed with the big memory corruption cleanup in June. If you see it again, please re-open.
