### ISSUE TITLE
Powers vit values

### ISSUE THREAD

**Issue by shevarash** [torilmud/issues#29]
`Gava GCC: 'The one issue I have with those spells listed is powers vit, it is 162 hps for lili, but nonpowers is 191'`

**Comment by Zipalodok** [comment]
If it is anything like Vitality for Cleric. Then that is not a standard number for a non-power Vit, for it does not do the same number ever cast, can be lower or higher each cast. Once a player wears decent amount of SF-Heal, the Non-power does not compete at all. If that is the case, this is not a bug. Even non-power Fheal for cleric does more than powers fheal(no SF-Heal), but only sometimes.

**Comment by dnavarro** [comment]
Unable to reproduce. My testing is showing legacy vits at 220-260 and powers vit at 270 on an example level 50 cleric with no SF

To some degree the numbers are not going to match perfectly. If the discrepancy is shown to be significant we can revisit this
