### ISSUE TITLE
Spook stun ignores globe

### ISSUE THREAD

**Issue by otebski** [torilmud/issues#290]
Might not be fair for mobs:

You complete your spell...
**The globe around the siege master's body flares as it bears the brunt of your
assault!**
The siege master is **stunned!**

This happened for powers verison of the spell

**Comment by Inames** [comment]
I don't see an issue, globe is preventing the damage from the spell, not the side effects, no different than globed mobs dropping to quake, or being sunray blinded.

**Comment by shevarash** [comment]
This is intentional.
