### ISSUE TITLE
MIRROR IMAGE?!?!

### ISSUE THREAD

**Issue by ghost** [torilmud/issues#291]
so i know you used what the cast file was doing, but there is an error, i've never noticed before, and its the same with cast and power.

when someone, not the caster, sees the spell cast, the finishing message reads:

XXX is enveloped by a sphere of swirling shadows...

this is actually the visual of MISLEAD.  and the spell should say something about mirrors springing around the caster, which is what the caster sees, it's also what we see when someone proc's a volance.

don't know why i've never noticed this before, since as i mentioned, it does say the same thing when you watch someone cast it, rather than use the power.

enjoy.

Gerin

**Comment by shevarash** [comment]
Fixed, thanks!
