### ISSUE TITLE
adamantium shield from gn

### ISSUE THREAD

**Issue by ghost** [torilmud/issues#292]
item still has size modifier

**Comment by Ruagh** [comment]
Adding +size or some other way to bash +2 size notches would rock

**Comment by marthammor** [comment]
Fixed.
While I don't think the item warrants being able to bash +size, I did add some physical resists to make up for the removal of the weight.
Awaiting move to main.

**Comment by Ruagh** [comment]
Wrong. It was warranting being able to bash +size when it was +weight. Now you have just stripped it and calling it fixed - it is totally not right. There is a serious issue now about bashes btw, when the sizes were recently made discreet. Alot of items are broken, not only this shield, but the cloak of faeriekind, which is not making non-gnomes nobash anymore. And yes, "want a caster go gnome" is a serious issue in my own humble opinion.

**Comment by marthammor** [comment]
I asked my fellow staffers thier opinion on the shield. We'll adjust further if needed.

The bash issue is something else entirely. I'm of the personal opinion that players should not be able to become permanently !bash at all. Bash is a mechanic that needs to be worked around and dealt with by the player/group. At any rate, it's best another ticket was used for bash issues.
