### ISSUE TITLE
enter command

### ISSUE THREAD

**Issue by ghost** [torilmud/issues#297]
we need something in the code, that disregards containers, when using the enter command.  Several times, i've had problems entering a teleport named hole, because of my container, and i've also had issues with followers being left behind because of the same issue, enter hole, checks container first.

**Comment by otebski** [comment]
Not only containers. It check for equipment too. E.g. enter mist (dread mist) may be difficult if you are wearing anything with mist as keyword.

**Comment by shevarash** [comment]
This has been fixed.
