### ISSUE TITLE
chess event is broken

### ISSUE THREAD

**Issue by otebski** [torilmud/issues#300]
EDIT: Disregard, works fine. Leaving it, since Grummsh comment may help other poor sods.

The Quartz Square of a Giant Chessboard
   A rosy quartz courtyard square amongst a perfect playing 
field of positive verses negative forces. Opposites, black 
and white, onyx and quartz, holding ground and carving just 
a square worth of territory out for themselves at a time. 
Heavy footsteps echo from all around. There is no sky or 
horizon, just static black. It confuses the rods and the 
cones, and causes you to blink repeatedly. Directly to the 
north west, the gigantic shape of an onyx castle looms. Two 
squares north, and one west you notice four rooks, and two 
squares east from there a queen shudders. **You are now 
standing on square B3.**
Exits: None!
**A diagonal trail leads to square B3.**
A ring of smoke has developed around an endless chute.
Corpse of a dark knight is lying here.
**A beautiful elven statue smiles broadly.**

< 531h/526H 149v/149V P: std > 
ask statue hi
Princess Verenla smiles and inquires 'Do you care to move to square **A4** or E6?'

< 531h/526H 149v/149V P: std > 
ask statue a4
Princess Verenla warns 'A solitary castle guards this square.'

< 531h/526H 149v/149V P: std > 
**nod statue**
You nod at Princess Verenla.

< 531h/526H 149v/149V P: std > 

Princess Verenla says '**As you wish! I will march on the next square**!'

< 531h/526H 149v/149V P: std > 

Princess Verenla twirls about and meanders diagonaly tothe next square!
< 531h/526H 149v/149V P: std > 

**Princess Verenla fades into existence with a snap**!
Lilithelle GCC: 'freaking gerin'

l room
< 531h/526H 149v/149V P: std > 
The Quartz Square of a Giant Chessboard
   A rosy quartz courtyard square amongst a perfect playing 
field of positive verses negative forces. Opposites, black 
and white, onyx and quartz, holding ground and carving just 
a square worth of territory out for themselves at a time. 
Heavy footsteps echo from all around. There is no sky or 
horizon, just static black. It confuses the rods and the 
cones, and causes you to blink repeatedly. Directly to the 
north west, the gigantic shape of an onyx castle looms. Two 
squares north, and one west you notice four rooks, and two 
squares east from there a queen shudders. You are now 
standing on square **B3**.
Exits: None!
**A diagonal trail leads to square B3.**
A ring of smoke has developed around an endless chute.
Corpse of a dark knight is lying here.
A beautiful elven statue smiles broadly.

Seems like player pieces do not create new trails to next rooms.

**Comment by gruumsh** [comment]
Try say instead of ask.

**Comment by otebski** [comment]
i did... worked.. tree fiddy if you keep it hush hush
