### ISSUE TITLE
Reporting buggy messages, as instructed. (Paladin bug)

### ISSUE THREAD

**Issue by Inames** [torilmud/issues#304]
I'm assuming this is due to Shield of Warding spell which I had up during all instances of this occurring.

Klauth, Terror of the North launches into the air and streaks toward his foes!
Fupepe screams in terror as she is crushed beneath Klauth, Terror of the North!
Fupepe is knocked down on the ground!

**>>>>>>>>>>>>>Attack missed - report buggy msg.**

You are knocked down on the ground!
stand
Beikas shrieks in pain as Klauth, Terror of the North plunges a razor-sharp wing talon into his flesh!
Rew clambers to his feet.

Your mighty slash barely wounds Klauth, Terror of the North.
The globe around your body flares as it bears the brunt of Klauth, Terror of the North's assault!
Klauth, Terror of the North dodges your futile attack.
Your massive slash barely wounds Klauth, Terror of the North.
The globe around your body flares as it bears the brunt of Klauth, Terror of the North's assault!
Klauth, Terror of the North misses you with his claw.
Klauth, Terror of the North misses you with his claw.
Klauth, Terror of the North misses you with his claw.

**>>>>>>>>>>Breath missed - report buggy msg.**

< 778h/961H 205p/205P 128v/128V |vs +|ts +|brs 4|trs 5|wws +| >

Your massive slash severely wounds Klauth, Terror of the North.
The globe around your body flares as it bears the brunt of Klauth, Terror of the North's assault!
Your massive slash badly wounds Klauth, Terror of the North.
The globe around your body flares as it bears the brunt of Klauth, Terror of the North's assault!
Klauth, Terror of the North misses you with his claw.
You dodge Klauth, Terror of the North's vicious attack.
You parry Klauth, Terror of the North's lunge at you.

**>>>>>>>>>Attack missed - report buggy msg.**

Pidibeple shrieks in pain as Klauth, Terror of the North plunges a razor-sharp wing talon into his flesh!
Rrissun group-says '[[ BLUR OUT ]]'

< 868h/961H 205p/205P 128v/128V |vs +|ts +|brs 2|trs 3|wws +| >
< T: Isene TC: few scratches E: klauth EC: awful EP: std P: std >

**Comment by shevarash** [comment]
This is a result of the shields reducing the damage to zero. Those old spells/attacks aren't expecting to be able to "miss", so they show that message. We'll fix by suppressing those messages or altering them.

**Comment by shevarash** [comment]
I believe this has already been fixed and my testing seems to confirm that. If I'm mistaken, please re-open.
