### ISSUE TITLE
KEYWORD: a jar with a baby phase spider inside

### ISSUE THREAD

**Issue by i982** [torilmud/issues#310]
could a few more keywords be added to this please.

< 591h/545H 120v/120V |3|3|3|3|2| P: std > 
recite scroll jar
You recite a vellum scroll which turns to dust in your hands.
You feel informed:
Name 'a jar with a baby phase spider inside'
Keyword 'jar', Item type: SUMMON
Item can be worn on:  COMPONENT_BAG 
Item will give you following abilities:  NOBITS
Item is: FLOAT NOBURN NOLOCATE NOBITS
Weight: 0, Value: 1000
Can affect you as :
    Affects : ARMOR By -4
Magical auras become visible.

< 591h/545H 120v/120V |3|3|3|3|2| P: std >

**Comment by OghmaToril** [comment]
Resolved in February.
