### ISSUE TITLE
the mighty scepter of valhalla

### ISSUE THREAD

**Issue by zenevan** [torilmud/issues#312]
As you mutter 'defender of asgard' under your breath to the mighty scepter of valhalla you are surrounded by a soft green glow.  As you begin weaving your weapons in an intricate pattern of defense your her wounds begin to close before your eyes!

**Comment by zenevan** [comment]
defense your her wounds

**Comment by Inames** [comment]
So it needs a comma after defense, and a re-examination of pronoun filling variables in the text.

**Comment by OghmaToril** [comment]
This was resolved in February by Marthammor.
