### ISSUE TITLE
Hammer of Law Typo/wrong word?

### ISSUE THREAD

**Issue by Inames** [torilmud/issues#313]
exa hammer
This warhammer is about four feet long and has a huge head.  It is made
from adamantite and has a leather grip wound around the handle of the
hammer.  On either side of the hammer are etched a set of scales which
is often used to represent justice in manner cultures.  Tiny runes have
been carved into all other surfaces of the hammer such that there is
virtually no visible surface not covered by runes apart from the two
sides adorned by the scales.

In this sentence.
>On either side of the hammer are etched a set of scales which
is often used to represent justice in manner cultures.

>manner cultures = many cultures?

**Comment by OghmaToril** [comment]
This was fixed in February by Marthammor.
