### ISSUE TITLE
Double colon on ASSOC

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#314]
You ASSOC: 'Reminds me. ASSOC often has :: at the end of it'

< 819h/819H 912p/912P 119v/119V P: sit > 

Havorr polishes the bar while waiting for the next order.

< 819h/819H 912p/912P 119v/119V P: sit > 
acc Was that a mudlet or toril bug?
You ASSOC: 'Was that a mudlet or toril bug?'

< 819h/819H 912p/912P 119v/119V P: sit > 

Havorr polishes the bar while waiting for the next order.

< 819h/819H 912p/912P 119v/119V P: sit > 

Wigilil ASSOC:: 'think thats toril'

< 819h/819H 912p/912P 119v/119V P: sit >

**Comment by Inames** [comment]
It's definitely a Game-side issue, I noticed it then got used to it. Been that way forever. It's always 2 :: when you see other people chat, 1 : when you see your own message.
