### ISSUE TITLE
Noble Shield Applying damage before reduction

### ISSUE THREAD

**Issue by Inames** [torilmud/issues#317]
So here I present a segment of combat. As you will see, I start with 850 health before the round, and end with 539 health at the end of the round. I cast Noble Shield on Rargas. The only place in this text block where damage has a possibility of being transferred is where Rargas is attacking Izan who is fireshielded, but no burn message is displayed, because Rargas was globed. However I took damage from noble shield. So noble shield is applying 50% of the source damage despite the damage not occurring on the target. I believe this occurred at another point in the zone where I was taking damage from noble shield despite dragonscales diminishing that damage on the target.

< 850h/962H 206p/206P 130v/130V |vs 2|ts +|brs +|trs 4|wws 6| >
< T: Rargas TC: few wounds E: izan EC: awful EP: knl P: std > 
You complete your spell...
You throw up your hand, and a vortex of swirling energy surrounds Rargas.
A human bodyguard blocks Nebulza's attack with her shield!
Nebulza barely wounds a human bodyguard with her mighty pierce.
Nebulza barely wounds a human bodyguard with her mighty pierce.
Nebulza barely wounds a human bodyguard with her mighty pierce.
Nebulza barely wounds a human bodyguard with her mighty pierce.
Nitania slightly wounds Izan Frosteyes with her massive pierce.
Izan Frosteyes partially deflects Nitania's lunge at him.
Nitania barely wounds Izan Frosteyes with her massive pierce.
Nitania slightly wounds Izan Frosteyes with her massive pierce.
Izan Frosteyes deflects Nitania's blow, and strikes back at Nitania!
Izan Frosteyes misses Nitania with his slash.
RESCUE Nitania
Nitania slightly wounds Izan Frosteyes with her massive pierce.
Izan Frosteyes blocks Nitania's attack with his shield!
Izan Frosteyes partially deflects your lunge at him.

> Your awesome slash barely wounds Izan Frosteyes.
> The globe around your body flares as it bears the brunt of Izan Frosteyes's assault!
> You score a CRITICAL HIT!
> Your massive slash severely wounds Izan Frosteyes.
> The globe around your body flares as it bears the brunt of Izan Frosteyes's assault!
> Your massive slash badly wounds Izan Frosteyes.
> The globe around your body flares as it bears the brunt of Izan Frosteyes's assault!

Talomis badly wounds Izan Frosteyes with his massive bludgeon.
Talomis badly wounds Izan Frosteyes with his massive slash.
Talomis badly wounds Izan Frosteyes with his massive bludgeon.
Izan Frosteyes deflects Talomis's blow, and strikes back at Talomis!
Izan Frosteyes misses Talomis with his slash.
Talomis badly wounds Izan Frosteyes with his massive bludgeon.
Izan Frosteyes blocks Talomis's attack with his shield!
A human bodyguard partially blocks Raunpotriusheyan's attack with her shield!
Raunpotriusheyan barely wounds a human bodyguard with his mighty flame-enshrouded bludgeon.
Raunpotriusheyan barely wounds a human bodyguard with his massive flame-enshrouded slash.
Raunpotriusheyan slightly wounds a human bodyguard with his massive flame-enshrouded bludgeon.
Raunpotriusheyan barely wounds a human bodyguard with his massive flame-enshrouded slash.
Raunpotriusheyan barely wounds a human bodyguard with his massive flame-enshrouded bludgeon.
Milomobble misses a stone gargoyle with his slash.
Milomobble misses a stone gargoyle with his slash.
A stone gargoyle misses Kaizu with its bite.
A stone gargoyle misses Kaizu with its bite.
A human bodyguard blocks a gray slaad's attack with her shield!
A gray slaad misses a human bodyguard with its strike.
A human bodyguard partially deflects Vomicopol's lunge at her.
Vomicopol barely wounds a human bodyguard with his average bludgeon.
A human bodyguard parries Vomicopol's lunge at her.
A human bodyguard misses Kaizu with her slash.
A human bodyguard misses Kaizu with her slash.
a human bodyguard strikes out wildly about the area in a mighty burst of power!
A human bodyguard misses Vomicopol with her slash.
A human bodyguard misses Mafa with her slash.
A human bodyguard misses Jezah with her slash.
Jezah misses Izan Frosteyes with his bludgeon.
Jezah misses Izan Frosteyes with his bludgeon.
A human bodyguard parries Pidibeple's lunge at her.
Pidibeple barely wounds a human bodyguard with his strong flaming bludgeon.
Dizzag misses Izan Frosteyes with his pierce.
Dizzag slightly wounds Izan Frosteyes with his awesome pierce.
Dizzag is burned severely as he hits Izan Frosteyes!
Rekpezul barely wounds Izan Frosteyes with his mighty pierce.
Rekpezul slightly wounds Izan Frosteyes with his mighty pierce.
With a flick of the wrist Rekpezul sends his glaive deep into Izan Frosteyes!
Rekpezul slightly wounds Izan Frosteyes with his mighty pierce.

> Rargas badly wounds Izan Frosteyes with his massive bludgeon.
> Your noble shield absorbs some of Rargas's damage!
> Rargas severely wounds Izan Frosteyes with his massive bludgeon.
> Your noble shield absorbs some of Rargas's damage!
> Rargas severely wounds Izan Frosteyes with his massive bludgeon.
> Your noble shield absorbs some of Rargas's damage!

A stone gargoyle misses Kaizu with its bite.
A stone gargoyle misses Kaizu with its bite.
A stone gargoyle misses Kaizu with its bite.
a stone gargoyle tries to knock Kaizu over, but he nimbly sidesteps and attacks!
Kaizu brutally wounds a stone gargoyle with his massive bludgeon.
A stone gargoyle staggers from Kaizu's massive bludgeon!
Kaizu critically wounds a stone gargoyle with a massive bludgeon!
Kaizu enshrouds a stone gargoyle in a mist of blood with his massive bludgeon!
A stone gargoyle is nearly slain by the force of Kaizu's massive bludgeon!

> Your noble shield absorbs some of Rargas's damage!
> A human bodyguard misses Rargas with her slash.
> Your noble shield absorbs some of Rargas's damage!
> A human bodyguard misses Rargas with her slash.
> Your noble shield absorbs some of Rargas's damage!
> A human bodyguard misses Rargas with her slash.
> A human bodyguard clambers to her feet.
> Your noble shield absorbs some of Rargas's damage!
> A human bodyguard misses Rargas with her hit.
> Your noble shield absorbs some of Rargas's damage!
> A human bodyguard misses Rargas with her hit.

a human bodyguard strikes out wildly about the area in a mighty burst of power!
A human bodyguard misses Pidibeple with her hit.
A human bodyguard misses Mafa with her hit.
A human bodyguard misses Talomis with her hit.
A human bodyguard misses Raunpotriusheyan with her hit.

> Your noble shield absorbs some of Rargas's damage!
> Izan Frosteyes misses Rargas with his slash.
> Your noble shield absorbs some of Rargas's damage!
> Izan Frosteyes misses Rargas with his slash.
> Your noble shield absorbs some of Rargas's damage!
> Izan Frosteyes misses Rargas with his slash.
> Rargas's weapon explodes in a peal of roaring thunder as he strikes Izan Frosteyes!
> Your noble shield absorbs some of Rargas's damage!
> Izan Frosteyes is thrown to the ground by the shockwave!

Jezah starts casting an offensive spell called 'Lich Touch'

< 539h/962H 206p/206P 130v/130V |vs 1|ts +|brs +|trs 3|wws 5| >
< T: Rargas TC: few wounds E: izan EC: awful EP: rcl P: std >

**Comment by shevarash** [comment]
This is intentional. The damage gets split before it is applied to each character, and then each of you gets to further reduce that damage via spells/protections. If the target is scaled and you aren't, you're going to take more damage. I'm happy to discuss the intent more, but it is working correctly.
