### ISSUE TITLE
Bash removal ripple effects

### ISSUE THREAD

**Issue by i982** [torilmud/issues#318]
its fine.. you dont want bashing fine. but requiring 35 hitroll in order to land the powers knockdown is just ridiculous. i mean are we tanks or are we hitters? i have to give up 300hp to land bashes? in order to bash i need 2 sets of gear? one for fights that require bash one for everything else? its just to much. you want the rest of the skills to have hit miss glance chance fine but base actual knockdowns of bash off something else please.

i mean it used to be shield weight.. speaking of which can we get the shields weight removed since it no longer matters.. specially to the smaller races that have lower str pool?

**Comment by otebski** [comment]
I heard powers hit rate depends on STR. Maybe this was done to off-set the agi advantage?
Did you test it against dwarves/duergar? Do they hit it easier?

**Comment by i982** [comment]
33 hit you miss 34 you mis rarely 35 hit you never miss.

if it is str based this is something someone should have put in the powers info.. so people can at least try and prepare for it. either way i shouldnt have to sacrifice 300+hp to be able to bash.

**Comment by i982** [comment]
by all means i welcome you to look through the gear that has hp ac and hitroll on it and is usable by a tank. the list is small.. VERY small.

**Comment by i982** [comment]
better yet here:

a bracelet of woven silver * ac5 5hp 1hit * Armor (Wrist) * 1 lbs * 5000c * Zone: Silverymoon (Q) * Last ID: 12-24-09 
a carved white dragon claw * 4D4 15hp 3hit cold(5%) * MAGIC FLOAT * Weapon (Wield) * 4 lbs * 0c * Zone: Klauthen Vale (Q) * Last ID: 6-24-10 
a cloak of bat wings * ac8 5hp 1hit * Armor (About) * 4 lbs * 500c * Zone: Skullport (Q) * Last ID: 3-9-11 
a cloak of demon wings * ac14 15hp 2hit elect(5%) NoID * MAGIC NO-GOOD NO-NEUTRAL * Armor (About) * Zone: Blood Bayou * Last ID: 4-10-08 
a cloak of iron plates * ac18 10hp 3hit * Armor (About) * 8 lbs * 0c * Zone: Darktree (Q) * Last ID: 6-27-10 
a cloak of the bat * ac8 5hp 1hit INFRA LEVITATE * MAGIC * Armor (About) * 4 lbs * 10000c * Zone: Skullport (Q) * Last ID: 3-9-11 
a cyanite shield of entangled roses * ac18 12hp 2hit * Armor (Shield) * 2 lbs * 10000c * Zone: Darktree * Last ID: 4-5-10 
a darkwood bracer covered in glowing sigils * ac12 15hp 4hit * MAGIC NO-THIEF * Armor (Wrist) * 2 lbs * 945000c * Zone: Twisted Rune * Last ID: 7-12-09 
a fighters loop of sorcerous ability * ac0 60hp 5hit * NO-CLERIC NO-THIEF NO-MAGE NOBITS * Armor ( Finger ) * 1 lbs * 1000000c * Zone: Tiamat (R) * Last ID: 02-04-12 
a flowing pitch-black cloak covered in stars * ac15 20hp 2hit * Called Proc: 'starfall' Meteor Burst 1/week * MAGIC NOBURN * Armor (About) * 1 lbs * 0c * Zone: Finder's (Q) * Last ID: 6-14-07 
a glowing basinet of dread * ac10 8hp 3hit cold(5%) FARSEE * NOLOCATE NO-MAGE * Armor (Head) * 7 lbs * 0c * Zone: Muspelheim (I) * Last ID: 2-15-07 
a gnarled staff of Pahluruk's root * 4D5 25hp 2hit * Proc: Entangling Roots * MAGIC ANTI-EVIL ANTI-EVILRACE ANTI-GREYELF ANTI-DWARF ANTI-HALFLING ANTI-GNOME ANTI-LICH * Weapon (Wield) * 15 lbs * 0c * Zone: Griffon's Nest (Q) * Last ID: 1-22-06 
a growling gnoll faced bracer * ac11 11hp 3hit * NOBURN NO-MAGE * Armor (Wrist) * 2 lbs * 30000c * Zone: Darktree (Q) * Last ID: 4-5-10 
a helm of the brain golem patrol * ac8 10hp 2hit * MAGIC NOBURN NO-THIEF NO-MAGE * Armor (Head) * 16 lbs * 25000c * Zone: Brain Stem Tunnel * Last ID: 12-20-06 
a mask of the night * ac7 15hp 3hit INFRA * SECRET NO-MAGE ANTI-GREYELF ANTI-HALFELF ANTI-DWARF ANTI-HALFLING ANTI-GNOME ANTI-TROLL ANTI-OGRE ANTI-YUANTI * Armor (Face) * 5 lbs * 0c * Zone: Muspelheim * Last ID: 1-3-09 
a mask of undead flesh * ac5 5hp 1hit INFRA DET-MAGIC * Armor (Face) * 1 lbs * 2500c * Zone: Skullport (Q) * Last ID: 4-9-11 
a multi-colored eyepatch * ac2 10hp 1hit * Armor (Eyes) * 3 lbs * 25000c * Zone: Serene Forest (Q) * Last ID: 10-23-07 
a necklace of pit worm scales * ac4 12hp 3hit * GLOW MAGIC NOBURN NO-THIEF * Armor (Neck) * 4 lbs * 0c * Zone: Hulburg (Q) * Last ID: 5-20-06 
a pair of crystal lensed goggles * ac5 5hp 1hit SENSE-LIFE * NOBURN * Armor (Eyes) * 1 lbs * 10000c * Zone: Skullport (Q) * Last ID: 4-9-11 
a pair of lamellar boots * ac12 11hp 2hit * NO-CLERIC NO-THIEF NO-MAGE * Armor (Feet) * 7 lbs * 0c * Zone: Smoke Plane (Q) * Last ID: 1-22-06 
a pair of writhing ash gauntlets * ac6 7hp 2hit * Called Proc: 'Ashentoris Aid Me' Ashentoris' Aid 1/day * MAGIC ANTI-GOOD ANTI-NEUTRAL NOBURN TRANSIENT * Armor (Hands) * 1 lbs * 0c * Zone: Curse of Newhaven (Q) * Last ID: 10-29-06 
a red eyepatch * ac4 10hp 2hit * MAGIC ANTI-GOOD NO-MAGE * Armor (Eyes) * 0 lbs * 600c * Zone: Dragonspear Castle (R) * Last ID: 3-2-07 
a ruby studded black dragonscale * 10hp 2hit pois(5%) * MAGIC ANTI-GOOD ANTI-NEUTRAL SECRET NOLOCATE NO-CLERIC NO-MAGE * Worn (Earring) * 2 lbs * 45000c * Zone: Cloud Realms (R) * Last ID: 12-4-10 
a set of rugged work clothes * ac25 5hp 1hit * Armor (Whole-body) * 4 lbs * 200c * Zone: Silverymoon (Q) * Last ID: 5-17-10 
a shimmering dark black-red cloak * ac17 17hp 2hit * Armor (About) * 10 lbs * 45000c * Zone: Myth Drannor * Last ID: 2-26-07 
a shining steel backplate * ac21 7hp 1hit * NOBURN NO-THIEF NO-MAGE * Armor (About) * 4 lbs * 0c * Zone: Keep of Finn McCumhail (R) * Last ID: 4-7-07 
a shining steel barbute * ac15 7hp 1hit * SECRET NOBURN NO-THIEF NO-MAGE * Armor (Head) * 2 lbs * 0c * Zone: A'Quarthus Velg'Larn (R) * Last ID: 12-3-08 
a shining steel brichetter * ac15 7hp 1hit * SECRET NOBURN NO-THIEF NO-MAGE * Armor (Waist) * 2 lbs * 0c * Zone: A'Quarthus Velg'Larn (R) * Last ID: 12-1-09 
a shining steel pair of gauntlets * ac15 5hp 1hit * SECRET NOBURN NO-THIEF NO-MAGE * Armor (Hands) * 2 lbs * 0c * Zone: A'Quarthus Velg'Larn (R) * Last ID: 4-8-07 
a silver githyanki longsword * 2D8 20hp 2hit * MAGIC * Weapon (Wield) * 9 lbs * 50000c * Zone: Githyanki Fortress * Last ID: 12-30-09 
a silvery strand of spider webbing * ac1 3hp 1hit * Armor (Neck) * 1 lbs * 100c * Zone: Cursed Cemetary * Last ID: 3-8-06 
a smoldering set of molten arm plates * ac10 14hp 3hit fire(5%) acid(5%) * MAGIC NO-THIEF NO-MAGE * Armor (Arms) * 4 lbs * 200000c * Zone: Magma Plane (R) * Last ID: 3-30-09 
a spiked and studded cloak of strange leather * ac11 10hp 2hit * NOLOCATE NO-CLERIC * Armor (About) * 6 lbs * 32000c * Zone: Hulburg (R) * Last ID: 12-10-08 
a spiked bone helm * ac3 6hp 1hit * MAGIC ANTI-GOOD NO-THIEF NO-MAGE * Armor (Whole-head) * 0 lbs * 0c * Zone: Jungles of Ssrynss * Last ID: 6-13-06 
a suit of heavy etched rune plate * ac90 42hp 2hit cold(5%) * MAGIC ANTI-EVIL NO-THIEF NO-MAGE * Armor (Whole-body) * 30 lbs * 200000c * Zone: Pirate Isles * Last ID: 5-21-06 
a suit of mithril chainmail armor 4 * ac27 17hp 3hit * MAGIC NOBURN NO-MAGE * Armor (Body) * 10 lbs * 0c * Zone: Bryn Shander (Q) * Last ID: 1-4-09 
a suit of vermillion chainmail * ac17 17hp 2hit * MAGIC NOBURN NO-MAGE ANTI-THIEF * Armor (Body) * 1 lbs * 23924c * Zone: Greycloak Hills (Q) * Last ID: 7-25-06 
a supple pair of red dragonscale boots * ac10 9hp 2hit fire(5%) * MAGIC NOBURN NO-MAGE * Armor (Feet) * 10 lbs * 0c * Zone: Muspelheim (Q) * Last ID: 8-3-06 
a thick branta fur cloak * ac12 5hp 1hit cold(5%) * Armor (About) * 5 lbs * 500c * Zone: Silverymoon (Q) * Last ID: 3-24-10 
a thick shield of solid ice * ac9 9hp 1hit fire(5%) * NOSELL MAGIC NOBURN NOLOCATE NO-CLERIC NO-THIEF NO-MAGE * Armor (Shield) * 45 lbs * 1000c * Zone: Swamps of Meilech (R) * Last ID: 12-20-06 
a treant staff * 2D4 3% 2x * 10hp 2hit * MAGIC FLOAT * WEAPON: Quarterstaff (Simple) * 3 lbs * 1000c * Zone: Silverymoon * Last ID: 12-24-09 
a woven leather vest * ac14 22hp 1hit * MAGIC FLOAT * Armor (Body) * 2 lbs * 0c * Zone: Airship (R) * Last ID: 1-31-10 
an adamantite band set with a flawless ruby * 8hp 3hit * MAGIC NO-CLERIC NO-MAGE * Worn (Finger) * 1 lbs * 0c * Zone: Global (Q) * Last ID: 9-18-09 
an astral-forged force whip * 3D6 3% 2x * 25hp 5hit * Enchant: Sonic Burst 100% 100% 0 0 - Thundering 100% 100% -10 32 - Force 100% 100% -10 32 * MAGIC NOBITS * WEAPON: Whip (Exotic) * 2 lbs * 81930c * Zone: Skullport (I) * Last ID: 12-14-11 
an emerald teardrop earring * 8hp 2hit * NOBURN * Worn (Earring) * 1 lbs * 10000c * Zone: Swamps of Meilech (R) * Last ID: 2-16-07 
glyphs of power tattooed around one eye * ac5 7hp 2hit * MAGIC NOBURN NO-CLERIC NO-MAGE * Armor (Eyes) * 3 lbs * 0c * Zone: Muspelheim * Last ID: 1-12-10 
power assisted combat boots 1 * ac12 19hp 2hit * MAGIC NOBURN NOLOCATE NOSLEEP NO-THIEF NO-MAGE * Armor (Feet) * 8 lbs * 100c * Zone: Bronze Citadel * Last ID: 2-22-07 
some black and red warpaint * ac2 4hp 1hit * Armor (Eyes) * 2 lbs * 0c * Zone: Ashgorrock (Q) * Last ID: 9-15-07 
some red war paint * ac3 7hp 2hit * NO-CLERIC NO-MAGE * Armor (Eyes) * 3 lbs * 0c * Zone: Muspelheim * Last ID: 1-20-10 
some silver studded leather sleeves * ac7 5hp 2hit * NO-MAGE * Armor (Arms) * 4 lbs * 2500c * Zone: Skullport (Q) * Last ID: 3-9-11 
spiked iron armguards studded with skulls * ac10 12hp 3hit pois(5%) * MAGIC NO-CLERIC NO-THIEF NO-MAGE * Armor (Arms) * Zone: Golem Forge (R) * Last ID: 7-31-06 
the warty face of a giant troll * ac7 5hp 1hit * SECRET * Armor (Face) * 2 lbs * 1000c * Zone: Skullport * Last ID: 3-21-11 

most of these are shit items..

**Comment by i982** [comment]
to further prove my point....
[13 Blk] Gutodugam  (Duergar) [@Oteb]
Gutodugam's weapon unleashes a torrent of dark power as he strikes Elaith Waterstill, knocking him to the ground.

level 13 bashes level 56 mob NEVER missing at 28 hit under death fatigue

Your awesome slash barely wounds Elaith Waterstill.
The poison on your weapon wears off.
As your poison takes effect, Elaith Waterstill appears to go blind!
Your mighty slash barely wounds Elaith Waterstill.
Elaith Waterstill misses you with his hit.
Elaith Waterstill starts casting an offensive spell.

< 716h/716H 114v/114V |3|2|3|3|2| T: Caizu TC: excellent E: elaith EC: small wounds EP: std P: std > 

[Dominating Smite] DS
Elaith Waterstill retains his balance in the face of your punishing advance!

< 716h/716H 114v/114V |3|2|3|3|2| T: Caizu TC: excellent E: elaith EC: small wounds EP: std P: std > 

Your awesome slash barely wounds Elaith Waterstill.
Your massive slash barely wounds Elaith Waterstill.
at level 50 with with 36hit i still miss bashes.. on same mob...

only difference is i have 121 str horc he has 150 duergar..

Level 50 Half-Orc Blackguard  
---------------------------------------------------------------------------
STR: 121   AGI: 127   DEX:  98   CON: 106
INT:  54   WIS:  60   CHA:  47   POW:  45
---------------------------------------------------------------------------
Hit points   :   677/716      Move points   :   114/114  
Armor Class  :   -89          Agility bonus :   -25
To-hit bonus :   +36          Damage bonus  :   +55

this isnt right.

**Comment by shevarash** [comment]
The bash to-hit modifiers were updated awhile back to address these concerns.
