### ISSUE TITLE
Whats wrong with Timestop?! It expires too fast.

### ISSUE THREAD

**Issue by Ruagh** [torilmud/issues#319]
Its the bracers proc one:

Spells
time stop                 (  2:00)   Armor                     (  2:08)
< 779h/774H 527p/527P 224v/224V >
< >
You continue your praying.
< 779h/774H 527p/527P 224v/224V >
< >
You have finished praying for preserve.
< 779h/774H 527p/527P 224v/224V >
< >
Time speeds up suddenly!
< 779h/774H 527p/527P 224v/224V >

**Comment by shevarash** [comment]
Are you still experiencing this?
