### ISSUE TITLE
Sigil of pain/ Plundering smite

### ISSUE THREAD

**Issue by Fisig** [torilmud/issues#320]
Sigil of pain has no effect at level 33
Plundering smite fails to vamp when it is the killing blow

Also: No Yuan-ti blackguard?

**Comment by shevarash** [comment]
There's been some confusion about what Sigil of Pain does. From the helpfile:

>This sigil does
damage on the initial cast, and also causes the caster to gain bonus hit points from
any vampiric heals on the target.

So, at any level, you should be seeing the target take damage and any future vampiric healing you do versus that mob should give you slightly more health back.

That all seems to be working to me, so I'm going to close this assuming that it was a misunderstanding. If I'm wrong, please re-open and let me know what I missed. :)
