### ISSUE TITLE
Worthless non-MAXstat items?

### ISSUE THREAD

**Issue by Ruagh** [torilmud/issues#321]
Presently +stat items are obsolete and unused, cause everybody has what they need from rollers, people are using only +MAXstat items. But with the tons of usual +stat gear around, why not to think - maybe it may go above 100 at a somewhat reduced (maybe even exponential) rate? That allows merging of stat and maxstat items, and will put +stat items back to some use.

**Comment by OghmaToril** [comment]
+stat items still have use for lower level, lower gear level, and characters who want to hit that next sub 100 notch.
Changing them to add a +maxstat value even at a reduced rate would drastically cause the value of +stat.

This is something that is not currently on our roadmap of changes.
