### ISSUE TITLE
1h Torins burns Duergar BLKs

### ISSUE THREAD

**Issue by otebski** [torilmud/issues#322]
1h Torins burns Duergar BLKs. This should be probably fixed.

**Comment by marthammor** [comment]
Asking fellow staff on this one. While it is true anyone can wield these, the proc does specifically say Warrior, Paladin, Cleric classes and Shield Dwarf/Duergar Dwarf races.

**Comment by shevarash** [comment]
`"Classes Allowed: Warrior Paladin Cleric\n"`
