### ISSUE TITLE
Soul Touch does not heal when it kills victim

### ISSUE THREAD

**Issue by otebski** [torilmud/issues#323]
< **4h/399H** 105v/105V |3|0|0| T: Gutodugam TC: awful E: dwarf EC: few wounds EP:
std P: std > 
sot sergeant
**You are overcome with a dark euphoria as the last of a dwarf sergeant's life
force flows into you.**
a dwarf sergeant is dead! R.I.P.
You raise a level!
You receive 150,000 XP (11.18%) experience.
Your blood freezes as you hear the rattling death cry of a dwarf sergeant.
A dwarf foot soldier stops following a dwarf sergeant.
A dwarf foot soldier stops following a dwarf sergeant.

< **4h/413H** 105v/105V |3|0|1| T: Gutodugam TC: awful E: dwarf EC: few wounds EP:

**Comment by shevarash** [comment]
This will be fixed in an upcoming Necromancer class overhaul.
