### ISSUE TITLE
archery powers

### ISSUE THREAD

**Issue by ghost** [torilmud/issues#324]
hail of thorns, when cast in a room with corpses, say it hits x targets

arctic barrage will do damage to target, with ranged shot, even if the shot misses, which after 1 hit, all ranged shots miss, which makes it a pretty terrible skill, understand you don't want us sitting a room away and killing things, but should give the mob archer awareness and still allow for shots to hit, occasionally

need a 3rd power with archery, that hits wraith forms, only 2 hit now, and they are the longest recharge

knockdown shot needs to work on targets that are solid, and standing, has legs, is terrible, some race types don't have legs, but should still be bashable, elementals, yuan-ti.....ect.

rangers need a greater dodge, while arching, we lose parry and riposte, and get nothing to defend our selves with

no bow has hitroll, perhaps give a 20% to hit mod for archery

**Comment by shevarash** [comment]
Many of these issues have been addressed in today's update. Notably, archery has not been given any particular hitroll bonuses. This seems like an issue that can be resolved with gear.
