### ISSUE TITLE
Radiant charge recharge is too slow by 1 tic

### ISSUE THREAD

**Issue by Nightsinger** [torilmud/issues#325]
example:
A well toned commoner clambers to his feet.
< 212h/212H 120v/120V |bs 3| |3|3| T: Faelani TC: excellent E: toned EC: few wounds EP: std P: std > 
rc
That power hasn't recharged yet!
< 212h/212H 120v/120V |bs 2| |3|3| T: Faelani TC: excellent E: toned EC: few wounds EP: std P: std > 
rc
That power hasn't recharged yet!
< 212h/212H 120v/120V |bs 2| |3|3| T: Faelani TC: excellent E: toned EC: few wounds EP: std P: std > 
 - Radiant Charge in 1 pulse 
< 212h/212H 120v/120V |bs 2| |3|3| T: Faelani TC: excellent E: toned EC: few wounds EP: std P: std > 
Your attack only grazes a well toned commoner as he dodges aside!
Your average slash barely wounds a well toned commoner.
A well toned commoner misses you with his hit.
A well toned commoner sends you sprawling.

**Comment by marthammor** [comment]
I believe this goes along with ticket #335. Awaiting a reply to see if its intended to have a longer cooldown than the lag/duration it bashes your victim for.

**Comment by shevarash** [comment]
This was fixed.
