### ISSUE TITLE
a silver rapier is misflagged somehow

### ISSUE THREAD

**Issue by Lilithelle** [torilmud/issues#326]
Takrok is using a rapier rapier (object 49114) and his attacks are showing as hits, not slash or pierce.

A bum misses Takrok with his hit.
Takrok brutally wounds a bum with his average hit.

< 915h/913H 132v/132V > l Takrok
You see nothing special about him.
Takrok is a medium-sized level 4 Shield Dwarf.
He is in excellent condition.
He skin has barklike texture.

<worn on body>       a heavy woolen tunic
<worn about body>    a dark woolen cape
<worn about waist>   a thick leather girdle
<worn on arms>       a roughly hewn copper armlet
<worn on hands>      a pair of soft caribou gloves
<primary weapon>     a silver rapier
<worn on legs>       a leather scale kilt
<worn on feet>       a pair of soft leather boots

**Comment by marthammor** [comment]
This and #327 are duplicates.
Its fixed and awaiting a move to main.
