### ISSUE TITLE
BUG::Silver rapier has a wrong attack type???

### ISSUE THREAD

**Issue by Ruagh** [torilmud/issues#327]
primary weapon - a silver rapier

You recite a scroll dedicated to Savras which turns to dust in your hands.
You feel informed:
Name 'a silver rapier'
Keyword 'silver rapier', Item type: WEAPON
Item can be worn on:  WIELD
Item will give you following abilities:  NOBITS
Item is: ANTI-GOOD NOBITS
Weight: 4, Value: 15000
Type: Rapier Class: Martial
Damage:  2D9  Crit Range: 9%  Crit Bonus: 2x
Can affect you as :
    Affects : HITROLL By 3

Only piercing weapons can be used to backstab. - cannot backstab with it, although supposed to.

Your awesome hit barely wounds a graceful commoner. - attack type is not piercing nor even slashing!

**Comment by marthammor** [comment]
Fixed, waiting move to main.
