### ISSUE TITLE
Fire and air elemental not rescuing

### ISSUE THREAD

**Issue by ebouchard88** [torilmud/issues#330]
Since a week or so, fire and air elemental are not rescuing at all. They are not answering to the command. I tried with a water elemental and they do rescue normally. See below a sample fight I did. You can see a few order and air is not answering to it. I tried order air, order follower, it does the same.

< 1051h/1051H 76p/76P 131v/133V P: std > 
A Small Home
Exits: -N
A slender commoner moves about here.
A well toned commoner relaxes here.
An air elemental flies in from the north.

< 1051h/1051H 76p/76P 130v/133V P: std > 
l commoner
This half elven woman has a slender form, wearing a cotton dress she
wanders about looking for something.  Her ears are slightly pointed on
top, her face is narrow and graceful.  She has almond shaped blue
eyes and long blond hair.
A slender commoner is a medium-sized level 27 Half-Elf.
She is in excellent condition.

< 1051h/1051H 76p/76P 132v/133V P: std > 
kill commoner

[Stoneskin has expired on Hatan.]
Your average bludgeon barely wounds a slender commoner.

< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: few scratches EP: std P: std >

[No longer moving. Spellcasting has resumed]

A slender commoner misses you with her hit.
Your average bludgeon barely wounds a slender commoner.
You miss a slender commoner with your bludgeon.

< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: few scratches EP: std P: std >

Your flesh loses its stony texture.

< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: few scratches EP: std P: std >

The slender commoner deftly tries to trip you.

< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: few scratches EP: std P: std >
ss me

A slender commoner misses you with her hit.
A slender commoner dodges your futile attack.
You miss a slender commoner with your bludgeon.

< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: few scratches EP: std P: std >

< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: few scratches EP: std P: std >

You start chanting... [Casting: SS ME (Stoneskin)]

< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: few scratches EP: std P: std >

An air elemental says 'I must assist my friend!'
An air elemental barely wounds a slender commoner with its strong choke.

< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: few scratches EP: std P: std >
Casting: Stoneskin *

< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: few scratches EP: std P: std >

Casting: Stoneskin 

< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: few scratches EP: std P: std >

You complete your spell... [Completed spell: SS ME (Stoneskin)]
You feel your skin harden to stone.

< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: few scratches EP: std P: std >

An air elemental barely wounds a slender commoner with its strong choke.
A slender commoner dodges an air elemental's attack.
A slender commoner misses you with her hit.
A slender commoner, in a show of awesome skill, manages to trip up herself!
Your average bludgeon barely wounds a slender commoner.
Your average bludgeon barely wounds a slender commoner.

< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: few scratches EP: rcl P: std >
< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: few scratches EP: rcl P: std >

An air elemental barely wounds a slender commoner with its average choke.
An air elemental barely wounds a slender commoner with its strong choke.
A slender commoner misses you with her hit.
Your average bludgeon barely wounds a slender commoner.
Your average bludgeon barely wounds a slender commoner.

< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: small wounds EP: rcl P: std > 

Autosaving...
An air elemental barely wounds a slender commoner with its strong choke.
A slender commoner dodges an air elemental's attack.
A slender commoner misses you with her hit.
A slender commoner clambers to her feet.
You miss a slender commoner with your bludgeon.
Your average bludgeon barely wounds a slender commoner.

< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: small wounds EP: std P: std >

It is 10am, on the Day of the Deception
The 9th Day of the Month of Bestanth (the Renewal), Year 1012.
Time elapsed since boot-up: 1:53:37
Current time is: Sat Feb  3 13:28:48 2018

< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: small wounds EP: std P: std > 
order air rescue hatan
Ok.

< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: small wounds EP: std P: std > 

An air elemental's attack only grazes a slender commoner as she dodges aside!
An air elemental barely wounds a slender commoner with its average choke.
An air elemental misses a slender commoner with its choke.
A slender commoner misses you with her hit.
Your weak bludgeon barely wounds a slender commoner.
Your weak bludgeon barely wounds a slender commoner.

< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: small wounds EP: std P: std > 

An air elemental barely wounds a slender commoner with its average choke.
An air elemental barely wounds a slender commoner with its average choke.
A slender commoner misses you with her hit.
You miss a slender commoner with your bludgeon.
You miss a slender commoner with your bludgeon.

< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: small wounds EP: std P: std > 

An air elemental barely wounds a slender commoner with its strong choke.
An air elemental barely wounds a slender commoner with its average choke.
A slender commoner misses you with her hit.
You miss a slender commoner with your bludgeon.
Your average bludgeon barely wounds a slender commoner.

< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: small wounds EP: std P: std > 

An air elemental barely wounds a slender commoner with its average choke.
An air elemental's attack only grazes a slender commoner as she dodges aside!
An air elemental barely wounds a slender commoner with its average choke.
A slender commoner barely wounds you with her weak hit.
A slender commoner is burned severely as she hits you!
Your weak bludgeon barely wounds a slender commoner.
Your average bludgeon barely wounds a slender commoner.

< 1050h/1051H 76p/76P 133v/133V T: Hatan TC: few scratches E: slender EC: few wounds EP: std P: std
> 

An air elemental misses a slender commoner with its choke.
An air elemental barely wounds a slender commoner with its average choke.
A slender commoner misses you with her hit.
A slender commoner dodges your futile attack.
Your average bludgeon barely wounds a slender commoner.

< 1050h/1051H 76p/76P 133v/133V T: Hatan TC: few scratches E: slender EC: few wounds EP: std P: std
> 
petition so it seems water do rescue. I will post on the github site
You petition 'so it seems water do rescue. I will post on the github site'
If you do not receive a prompt response please email toril.help@gmail.com

< 1050h/1051H 76p/76P 133v/133V T: Hatan TC: few scratches E: slender EC: few wounds EP: std P: std
> 

An air elemental barely wounds a slender commoner with its strong choke.
An air elemental barely wounds a slender commoner with its average choke.
A slender commoner misses you with her hit.
A slender commoner, in a show of awesome skill, manages to trip up herself!
You miss a slender commoner with your bludgeon.
You miss a slender commoner with your bludgeon.

< 1050h/1051H 76p/76P 133v/133V T: Hatan TC: few scratches E: slender EC: few wounds EP: rcl P: std
> 

An air elemental barely wounds a slender commoner with its average choke.
An air elemental's attack only grazes a slender commoner as she dodges aside!
An air elemental barely wounds a slender commoner with its average choke.
A slender commoner misses you with her hit.
Your average bludgeon barely wounds a slender commoner.
Your average bludgeon barely wounds a slender commoner.

< 1050h/1051H 76p/76P 133v/133V T: Hatan TC: few scratches E: slender EC: few wounds EP: rcl P: std
> 
order air rescue hatan
Ok.

< 1050h/1051H 76p/76P 133v/133V T: Hatan TC: few scratches E: slender EC: few wounds EP: rcl P: std
> 
order air rescue hatan
Ok.

< 1050h/1051H 76p/76P 133v/133V T: Hatan TC: few scratches E: slender EC: few wounds EP: rcl P: std
> 
order air rescue hatan
Ok.

< 1050h/1051H 76p/76P 133v/133V T: Hatan TC: few scratches E: slender EC: few wounds EP: rcl P: std
> 

An air elemental slightly wounds a slender commoner with its strong choke.
An air elemental slightly wounds a slender commoner with its strong choke.
A slender commoner misses you with her hit.
A slender commoner clambers to her feet.
Your average bludgeon barely wounds a slender commoner.
Your average bludgeon barely wounds a slender commoner.

< 1050h/1051H 76p/76P 133v/133V T: Hatan TC: few scratches E: slender EC: few wounds EP: std P: std
> 

Ihgod GCC: 'Mostly going to take a month or two of zoning blackguard with different weapons to see
how it manages'

< 1050h/1051H 76p/76P 133v/133V T: Hatan TC: few scratches E: slender EC: few wounds EP: std P: std
> 

An air elemental's attack only grazes a slender commoner as she dodges aside!
An air elemental barely wounds a slender commoner with its weak choke.
An air elemental slightly wounds a slender commoner with its strong choke.
A slender commoner misses you with her hit.
Your average bludgeon barely wounds a slender commoner.
Your average bludgeon barely wounds a slender commoner.

< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: few wounds EP: std P: std > 

An air elemental barely wounds a slender commoner with its average choke.
An air elemental slightly wounds a slender commoner with its average choke.
A slender commoner misses you with her hit.
You miss a slender commoner with your bludgeon.
Your average bludgeon barely wounds a slender commoner.

< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: few wounds EP: std P: std > 
ee
You are already affected by Elemental Fire Embodiment!

< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: few wounds EP: std P: std > 
< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: few wounds EP: std P: std > 
eb
You start chanting... [Casting: EB (Earthblood)]

< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: few wounds EP: std P: std > 

An air elemental's attack only grazes a slender commoner as she dodges aside!
An air elemental barely wounds a slender commoner with its average choke.
An air elemental barely wounds a slender commoner with its average choke.
A slender commoner misses you with her hit.

< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: nasty wounds EP: std P: std > 

Casting: Earthblood *

< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: nasty wounds EP: std P: std > 
The well toned commoner rubs his hands in discomfort.

< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: nasty wounds EP: std P: std > 

You complete your spell... [Completed spell: EB (Earthblood)]
A slender commoner convulses in agony as you transmute her blood into dirt!
A slender commoner ceases to move as her body is overcome with elemental earth!

< 1051h/1051H 76p/76P 133v/133V T: Hatan TC: excellent E: slender EC: awful EP: std P: std > 
eb
< 1051h/1051H 76p/76P 133v/133V E: slender EC: awful EP: std P: std >

A slender commoner staggers from your weak bludgeon!
A slender commoner is nearly slain by the force of your average bludgeon!
A slender commoner is mortally wounded, and will die soon, if not aided.
A slender commoner slumps to the ground.
You start chanting... [Casting: EB (Earthblood)]

< 1051h/1051H 76p/76P 133v/133V E: slender EC: awful EP: rcl P: std > 

An air elemental says 'I must assist my friend!'
An air elemental hits a slender commoner in the throat, she chokes, gasps, and dies.
a slender commoner is dead! R.I.P.
Your blood freezes as you hear the rattling death cry of a slender commoner.
You abort your spell before it's done!

< 1051h/1051H 76p/76P 133v/133V P: std >

**Comment by shevarash** [comment]
I think this has been fixed with the general cleanup of misc issues in June. If you're still experiencing please re-open it.
