### ISSUE TITLE
buggy message: report buggy msg

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#331]
Might be duplicate, however: 

An ancient white dragon breathes a cone of frost!
Breath missed - report buggy msg.

A rapid pulse of blue-white frost tunnels out of the mouth of the
white dragon consort directly at Kaisi! The instant bitter-cold
contact with her flesh leaves her wincing in pain. As her body
temperature plummets, her skin visibly hardens and cracks. The ice
grows thicker and Kaisi is left unable to move, numb, and near
to death.

The white dragon consort breathes a cone of frost!
Breath missed - report buggy msg.
An ancient white dragon breathes a cone of frost!
Breath missed - report buggy msg.
Your attack glances harmlessly off of an ancient white dragon's scales!

**Comment by Nyyrazzilyss** [comment]
Probably a duplicate of 304 (This was with blackguard though)

**Comment by shevarash** [comment]
Yep, same underlying issue. This will be resolved with #304.
