### ISSUE TITLE
Necro points not working as it should

### ISSUE THREAD

**Issue by ebouchard88** [torilmud/issues#333]
I am level 2 necro, I raise my first skeleton. I check attributes, I see 1/2 points used. All good. I try to raise my second skeleton, it tells me I am too weak to raise another one, I check my attribute and I now see 2/2. However I still only have 1 skeleton.

Looks like a bug

**Comment by marthammor** [comment]
I'm not able to replicate this with a level 2 necromancer. Any more information on this that might help us track this down?

**Comment by ebouchard88** [comment]
It seems the problem only happened with skeletons at low level. Now that I am level 20ish, zombie, ghoul shadows all worked as expected. It just happened with skeleton at low level. While it might be not considered a show stopper, it does make a bad impression on the new beginners. I do not have other information to bring. As I said, I am now level higher and not experiencing the issue. As for more information, I know that It did happen from level 1 to 6 or so. Anytime I was trying to raise a skeleton during those level, I was not able to get the full potential army as the bug always kicked in and I was only able to get about half of the number of skeleton I could have according to the help (ie 1 skeleton = 1 points, so at level 4 I could get at least 4) but that was not the case.


________________________________
De : Marthammor <notifications@github.com>
Envoyé : 8 février 2018 21:27
À : torilmud/issues
Cc : ebouchard88; Author
Objet : Re: [torilmud/issues] Necro points not working as it should (#333)


I'm not able to replicate this with a level 2 necromancer. Any more information on this that might help us track this down?
