### ISSUE TITLE
Radiant Charge / Dominating Strike

### ISSUE THREAD

**Issue by Zipalodok** [torilmud/issues#335]
The power info on these state it as 8seconds wait just like Bash. But when you use either it has a 12second wait instead. Which results in not being able to use these powers to bash when mob stands. Results in "Power not recharged" yet, when it in fact should be, if the timer was indeed 8seconds.

 Even with a 2.5 second delay on my end, I still sometimes end up not being able to Bash via RC/DS when mob stands.

I assume this is same for Radiant Charge. My testing done with Dominating Smite.

**Comment by marthammor** [comment]
So, this is a little confusing at first when reading the info on powers.
The lag you are seeing is how long the victim of your attack is lagged.
The recharge is what you should be looking at, which for these two powers is 12 seconds.
Bash only has a 4 second recharge, but lags you 8 seconds on success or 4 seconds if you miss.

I'm checking into this to see if its intended to be a 12 second recharge that only keeps the target down for 8 seconds.

**Comment by Zipalodok** [comment]
Yes you're correct, I did read that wrong. I still think it should always be ready after mob stands. Sometimes recharge says 1-2seconds or 1-2 pulses, after mob has stood up. Which means the 12seconds should be over by then. It basically creates un-needed spam using these skills.

**Comment by Inames** [comment]
Sweeping Strike(dual), Radiant Charge(1h/sh), and Dominating Smite(1h/sh) are all 8 seconds down, 12 seconds recharge.

Thunderous Smite(2h), and Shattering Smite (2h) are both 12 seconds down, 12 seconds recharge.

It appears to me that shev probably intended this? I'd certainly check with him. That being said, it isn't really problematic. it still functions in the same fashion as bash, I'd suggest considering changing recharge times on melee powers to be 2s less, so it's more likely you can utilize the power during the interval when you expect them to be standing without having to spam it to catch it right on that 12s timer. But 2s less won't allow you to utilize the skill more often in combat than intended. 9s recharge timer would keep the same frequency restriction and provide even more opportunity to trigger the ability.

**Comment by Zipalodok** [comment]
I think it has to do with the pulses. From my own understanding, I assume the game syncs with client to mud off the pulses? For the skill is normally up by time mob stands, but has remaining pulse time or says none, when you type recharge.

Basically I'm saying some the times don't sync, yet how they're programmed on paper it would "seem" as they're in sync. I don't know the direct cause of it, my guess is delay from syncing with client to server itself. Like mud-server says 12seconds for mob to stand, then on my end it gets delayed and my 12second recharge timer becomes smidge longer. Not sure! certainly something not syncing though. A 1.5-2sec shorter recharge would stop it indeed.

**Comment by otebski** [comment]
Even with 2h skills, in some cases mob can stand up and use instant cast skill before bash can be reapplied. This is rare but pretty evident if you fight e.g. drakes. Every once in a while my SS lags by a pulse and drakes stands up and breathes same round

**Comment by shevarash** [comment]
This was corrected by extending the lag to be 12 seconds on the 1h bash skills. These updates went in with the Warrior updates on 3/29.
