### ISSUE TITLE
Spirit Naga in Ashtone Vrock Gauntlet

### ISSUE THREAD

**Issue by onut** [torilmud/issues#336]
This creature looks much like a snake, its body stretches to almost
twenty feet in length.  Formidable physically it is also to be feared
for its magic.  The body has bands of red and black scales running down
its length.  The head looks like that of a beautiful woman, but with no
hair, simply a scaly covering like that of a reptile.  She looks at you
with beguiling eyes.
A spirit naga is a large-sized level 55 Naga.
She is in excellent condition.

< 710h/550H 120v/121V |3|3|1|3|0| P: std > 

A spirit naga starts casting a spell.

< 708h/550H 121v/121V |3|3|1|3|0| P: std > 
md naga
Strands of darkness shroud your form as you land a wicked strike upon a spirit naga.
You shiver from unnatural cold.
YIKES!  Another hit like that, and you've had it!!
A spirit naga cowers in fear!

< 185h/550H 121v/121V |3|3|1|3|0| T: Zedzeg TC: nasty wounds E: naga EC: small wounds EP: std P: std
> 

[No longer moving. Spellcasting has resumed]

[SPELL: Shadow Healing] SH
You start chanting... [Casting: SH (Shadow Healing)]

< 185h/550H 121v/121V |3|3|1|3|0| T: Zedzeg TC: nasty wounds E: naga EC: small wounds EP: std P: std
> 

A spirit naga stops chanting abruptly!
You complete your spell... [ SH (Shadow Healing) ]
You are embraced by a corona of swirling shadows as your wounds begin to heal.

Not sure if this was intended to be this way but I'm pretty sure that Coldshield is supposed to show on look and in status. Neither place was it displayed. Unfortunatly this is all of the log that was still on scroll back or I would of posted the status also.

**Comment by shevarash** [comment]
I couldn't recreate this. This bug may have been fixed as a result of the big code cleanup done in June. If you see this again, please re-open. Thanks!
