### ISSUE TITLE
Broken timers on non-Tia proccing items

### ISSUE THREAD

**Issue by Ruagh** [torilmud/issues#337]
Whats wrong with timers on:
-Vortex cloak
-Tattered grey cloak?

**Comment by marthammor** [comment]
What's broken with them? Are they wrong? Do they not recharge?

**Comment by Ruagh** [comment]
Recharge timers are very weird... they dont work as it shows on ID. Generally, Vortex and tattered cloaks are like almost never working, guess its a reset on logoff/removal and a very long wear timer afterwards.

**Comment by Inames** [comment]
Vortex as far as I'm aware must be worn at all times to maintain it's charge, if you remove it, it loses charge immediately, if you log off, but are still wearing it, it should maintain the charge. And it does have a considerable recharge timer. There are a lot of recharging procs like this in the game.

**Comment by shevarash** [comment]
Inames is correct. This is working as designed. In a nut shell, if you want the daily mirror image, you have to wear the cloak for a day to charge it up.
