### ISSUE TITLE
Teleportable distro room

### ISSUE THREAD

**Issue by Lilithelle** [torilmud/issues#338]
It let me teleport into a distro room in Ashstone Keep Road.

Mob Distro Room
Room size: Large (L:30 ft  W:30 ft  H:50 ft)
Exits: None!

< 830h/830H 110v/110V > world
Syntax: world < stats, zones >
This server compiled at 12:04:23 Feb 11 2018.
You are currently in: Ashstone Keep Road

**Comment by Dugmaren** [comment]
Mob Distro Room [83:18500]
 - Field - [NOBITS]

**Comment by Dartan82** [comment]
Noob area maker!
