### ISSUE TITLE
Upgrade shaman pet

### ISSUE THREAD

**Issue by Zipalodok** [torilmud/issues#34]
Summon totem for Shaman, does not have a Power counterpart. Be nice if you used the CHP Slaad code for the spirits as well. The Slaad auto rescues, Spirits do not till Phurt(what im told, never seen it happen) and Slaads have 4-5x the HP. Spirit as is, is lacking.

**Comment by Adriorn** [comment]
Yeah, currently the spirit animal has no use at level 50, for the most part.

**Comment by CountVooku** [comment]
I agree. Making them higher than lvl 40 would be a start. I thought being able to summon different types of totem spirits (ie - tanking type (bear), DPS type (tiger, wolf), and a casting type. Would add some flexibility and make playing one a bit more... fun.

Increasing the level would probably be pretty easy. The other stuff not so much.

**Comment by Dhelindel** [comment]
I would love to see spirits have an area debuff like howl on dire wolves.  And possible add buffs to shaman for having spirits summoned. i.e add increase to spell focus spirit for having spirit out.

**Comment by shevarash** [comment]
Thanks for the feedback! This will be considered in an upcoming Shaman class overhaul.
