### ISSUE TITLE
Duplicates in 'powers list'

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#344]
Not all spells, but many display duplicates

Spells:
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=--=-=--=-=-=-=-=-=-=-=-=-=--=-=-=-
Ancestral Fury                      [afu   ]   Study           10th circle
Ancestral Shield                    [ash   ]   Study           10th circle
Ancestral Shield                    [ash   ]   Study           10th circle
Control Weather                     [cnw   ]   Study           9th circle
Group Heal                          [gh    ]   Study           9th circle
Group Heal                          [gh    ]   Study           9th circle
Plane Shift                         [psh   ]   Study           9th circle
Plane Shift                         [psh   ]   Study           9th circle
Spirit Walk                         [swalk ]   Study           9th circle
Spirit Walk                         [swalk ]   Study           9th circle

**Comment by shevarash** [comment]
I can't replicate this - closing, assuming it was fixed awhile back. If you're still seeing it, please re-open and note they character that you're seeing it with.
