### ISSUE TITLE
Black Knight Aggressive toggle

### ISSUE THREAD

**Issue by Zipalodok** [torilmud/issues#345]
Cannot turn off Black Knight Aggressive toggle, once you turn it on you cannot turn it off. Says this when I use "aggr off" command "What?  Let somebody else get the first blow?  Not a chance!".

Please fix, I dont wish to auto engage.

**Comment by Inames** [comment]
Blackguard*

**Comment by otebski** [comment]
Please fix. I wanted to verify zip's report and now I am stuck in aggro with no way to turn it off.

**Comment by shevarash** [comment]
This is fixed.
