### ISSUE TITLE
Aura of Death max vamp

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#347]
Powers info shows:

Self Effect      : --> Vampiric heal 5 hit points, up to 133% of max  

Looking at a log, while I do vamp quickly to max, I don't seem to be going much above it. Definitely not 133%.

< 959h/909H 131v/131V |ps 1|drs 37|ds 2|rs 3|dm 3| |3|1|1|1|0| T: Ihgod TC: excellent E: shalyssa EC: few wounds EP: rcl P: std > 

Shalyssa Lurialar misses you with her hit.
You miss Shalyssa Lurialar with your bludgeon. (x2)
The dark mists surge as life force is siphoned into you.
Your massive bludgeon barely wounds Shalyssa Lurialar.

< 964h/909H 131v/131V |ps 1|drs 37|ds 2|rs 3|dm 3| |3|1|1|1|0| T: Ihgod TC: excellent E: shalyssa EC: few wounds EP: rcl P: std > 

[Ihgod : the mystical circlet of the coiled serpent]
The dark mists surge as life force is siphoned into you.
Your massive bludgeon barely wounds Shalyssa Lurialar.
The dark mists surge as life force is siphoned into you.
Your massive bludgeon barely wounds Shalyssa Lurialar.
The dark mists surge as life force is siphoned into you.
Your massive bludgeon barely wounds Shalyssa Lurialar.
The dark mists surge as life force is siphoned into you.
Your massive bludgeon barely wounds Shalyssa Lurialar.
The dark mists surge as life force is siphoned into you.
Your massive bludgeon barely wounds Shalyssa Lurialar.
The dark mists surge as life force is siphoned into you.
Your massive bludgeon barely wounds Shalyssa Lurialar.
The dark mists surge as life force is siphoned into you.
Your massive bludgeon barely wounds Shalyssa Lurialar.

< 964h/909H 131v/131V |ps +|drs 36|ds 1|rs 2|dm 2| |3|1|1|1|0| T: Ihgod TC: excellent E: shalyssa EC: few wounds EP: rcl P: std > 

Shalyssa Lurialar misses you with her hit.
Shalyssa Lurialar clambers to her feet.
You miss Shalyssa Lurialar with your bludgeon.
The dark mists surge as life force is siphoned into you.
Your awesome bludgeon barely wounds Shalyssa Lurialar.
The dark mists surge as life force is siphoned into you.
Your awesome bludgeon barely wounds Shalyssa Lurialar.

< 964h/909H 131v/131V |ps +|drs 36|ds 1|rs 2|dm 2| |3|1|1|1|0| T: Ihgod TC: excellent E: shalyssa EC: few wounds EP: std P: std > 

[MELEE: Plundering Smite] PS
Your strike leaves a vile blight on Shalyssa Lurialar, and some of her life flows into you.

< 964h/909H 131v/131V |ps 3|drs 35|ds +|rs 1|dm 1| |3|1|1|1|0| T: Ihgod TC: excellent E: shalyssa EC: few wounds EP: std P: std > 

You dodge Shalyssa Lurialar's vicious attack.
Shalyssa Lurialar starts casting an offensive spell.
The dark mists surge as life force is siphoned into you.
Your powerful bludgeon barely wounds Shalyssa Lurialar.
The dark mists surge as life force is siphoned into you.
Your massive bludgeon barely wounds Shalyssa Lurialar.
The dark mists surge as life force is siphoned into you.
Your massive bludgeon barely wounds Shalyssa Lurialar.

< 964h/909H 131v/131V |ps 3|drs 35|ds +|rs 1|dm 1| |3|1|1|1|0| T: Ihgod TC: excellent E: shalyssa EC: few wounds EP: std P: std >

**Comment by ghost** [comment]
yeah, it's a major issue with this spell on blackguards, basically, if you really wanted to utilize it, you'd need to attack several 30 and under mobs that aren't likely to touch you, to vamp up your hp, then go take on something bigger, becuase as soon as you start taking damage, the minor vamping isn't gonna really beef you up like paladin's vit spell

**Comment by shevarash** [comment]
I believe this was fixed with #562. If not please re-open!
