### ISSUE TITLE
Shroud of Shadow - not so 100% protection

### ISSUE THREAD

**Issue by otebski** [torilmud/issues#348]
Coldshield damage does not get stopped by Shroud of Shadow.
100% prot from cold should prevent any coldshield damage.

LOG:

sos
You start chanting... 

< 732h/722H 105v/105V |vs +|ss +|sph +|uf +|md +| |3|2|3|2|1| P: std > 

You complete your spell... 
### A misty cloud of gloom swirls about you, **shielding you from harm.**

< 732h/722H 105v/105V |vs +|ss +|sph +|uf +|md +| |3|2|3|1|1| P: std > 

ss sultan
< 732h/722H 105v/105V |vs +|ss +|sph +|uf +|md +| ## |3|2|3|1|1| P: std >

Intersection in the Grand Hallway
Exits: - North - East  - South - West 

< 732h/722H 105v/105V |vs +|ss +|sph +|uf +|md +| |3|2|3|1|1| P: std >

Throne Room of the Sultan
   This massive room some one thousand feet square contains the throne
of the mighty Sultan of all the efreeti.  Shadam Quilen, rules here from
his massive glowing throne of solid brass.  There is a huge statue of
Kossuth here, bending down to set the crown of might upon Shadam's
head.  Massive supporting columns of brass and fire hold the huge vaulted
ceiling up high above.  Balconies overlook the grand floor from on high
and the ever present royal guard of the Sultan are here in force.  Huge
murals depicting Shadam and his family attending affairs of state as well
as battles personally lead by the sultan himself are hung on the walls here.
The floor is of polished brass, and this entire room glows with a radiance
that causes pain to any who stand within that are not of this plane.
A vast table set with foods of all sorts is also within.  The heat in this
room
is far greater then anywhere else in the palace, anything not protected from
magic fire would burst into flame and melt or dissolve in an instant.
Exits: - North# - South
The elite palace guard is here guarding the sultan. (x2)
The Sultan of all the efreeti Shadam Quilen is here resting on his throne.

< 732h/722H 104v/105V |vs +|ss +|sph +|uf +|md +| |3|2|3|1|1| P: std >

Your weapon unleashes a torrent of dark power as you strike The Sultan, 
knocking him to the ground.
The spell cast by The Sultan is partially absorbed!
### You shiver from unnatural cold.
YIKES!  Another hit like that, and you've had it!!

< 349h/722H 104v/105V |vs +|ss 3|sph +|uf +|md +| |3|2|3|1|1| T: Gutodugam TC:
nasty wounds E: sultan EC: few scratches EP: rcl P: std > 
< 349h/722H 104v/105V |vs +|ss 3|sph +|uf +|md +| |3|2|3|1|1| T: Gutodugam TC:
nasty wounds E: sultan EC: few scratches EP: rcl P: std > 
You parry an elite palace guard's lunge at you.

< 349h/722H 105v/105V |vs +|ss 3|sph +|uf +|md +| |3|2|3|1|1| T: Gutodugam TC:
nasty wounds E: sultan EC: few scratches EP: rcl P: std > 
You dodge a bash from an elite palace guard, who loses his balance and falls.

< 349h/722H 105v/105V |vs +|ss 3|sph +|uf +|md +| |3|2|3|1|1| T: Gutodugam TC:
nasty wounds E: sultan EC: few scratches EP: rcl P: sit > 
disarm

An elite palace guard misses you with his beat.
An elite palace guard's attack only grazes you as you dodge aside!
An elite palace guard misses you with his beat. (x2)
You partially deflect an elite palace guard's lunge at you.
An elite palace guard misses you with his beat.
You dodge an elite palace guard's vicious attack.
An elite palace guard misses you with his beat.
Your Unholy Avenger glows jet black and plunges itself into
The Sultan's body, calling on the Power of Darkness.
The Sultan seems to be blinded!
You score a CRITICAL HIT!
The dark mists surge as life force is siphoned into you.
Your massive slash barely wounds The Sultan.
The spell cast by The Sultan is partially absorbed!
### You shiver from unnatural cold.
OUCH!  That really did HURT!
The dark mists surge as life force is siphoned into you.
Your massive slash barely wounds The Sultan.
The spell cast by The Sultan is partially absorbed!
### You shiver from unnatural cold.
The Sultan misses you with his flaming slash. (x2)
The Sultan's a burning star-metal falchion explodes in a burst of searing
flames!
The Sultan misses you with his flaming slash.

< 126h/722H 105v/105V |vs +|ss 3|sph +|uf +|md +| |3|2|3|1|1| T: Gutodugam TC:
pretty hurt E: sultan EC: few scratches EP: rcl P: sit > 

The dark mists swirling around you melt back into the shadows.

< 126h/722H 105v/105V |vs +|ss 3|sph +|uf +|md +| |3|2|3|1|1| T: Gutodugam TC:
pretty hurt E: sultan EC: few scratches EP: rcl P: sit > 

A momentary brilliant glow originating from your circlet begins
a rapid change in your appearance. Countless serpents begin to uncoil,
slithering and sliding their way down and around your arms, neck,
and torso, granting you a reptilian quickstrike ability! Your eyes gleam
a vivid yellow as the brief enchantment begins to fade. Quickly as
they descended, the serpents twist and twine their way back to the magic
within their circlet.
Your weak slash barely wounds The Sultan.
The spell cast by The Sultan is partially absorbed!
Your weak slash barely wounds The Sultan.
The spell cast by The Sultan is partially absorbed!
The Sultan parries your futile lunge at him.

< 126h/722H 105v/105V |vs +|ss 2|sph +|uf +|md +| |3|2|3|1|1| T: Gutodugam TC:
pretty hurt E: sultan EC: few scratches EP: rcl P: sit > 
An elite palace guard misses you with his beat. (x2)
An elite palace guard's attack only grazes you as you dodge aside!
An elite palace guard misses you with his beat.
You parry an elite palace guard's lunge at you.
flee
An elite palace guard misses you with his beat.
You parry an elite palace guard's lunge at you.
Your Unholy Avenger glows jet black and plunges itself into
The Sultan's body, calling on the Power of Darkness.
You score a CRITICAL HIT!
Your massive slash barely wounds The Sultan.
The spell cast by The Sultan is partially absorbed!
### BRR! As you hit The Sultan, deadly cold fills your bones..
With a final blow, you feel yourself falling to the ground.
Your soul leaves your body in the cold sleep of death...
Your body returns to its normal size.

You are dead!

Your soul is transported to The Fugue Plane as your crumbling body
succumbs

to the cold sleep of death. Here in Kelemvor's realm all dead souls await
either judgement or escape from this timeless prison.

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

The Top of the Crystal Spire on the Fugue Plane

**Comment by Inames** [comment]
help shroud of shadow
"SHROUD OF SHADOW"
Spell.

Area of effect: Self
Aggressive:     No
Cumulative:     No
Class/Circle:   Blackguard 4th
Type of spell:  Divine

A murky shield composed of enchanted shadows wraps around the caster. This shield will
negate all damage directed against the caster. **_Note that some special effects may bypass
the shield._**

**Comment by otebski** [comment]
Power i shroud of shadow shows that all prots are set at 100%. 100% prot cold should negate all coldshield damage. 

Coldshield can hardly be considered special effect. Against 5 mage-casters using unleashed fury would mean instant death.  Hardly an expected result for using 5 minute cooldown that lasts 12 seconds.

I was under impression that the quoted note was a gateway to allow stuff like 10th eye, remorhaz swallow and some instant death procs to go through.
