### ISSUE TITLE
power target agg doesn't work

### ISSUE THREAD

**Issue by Inames** [torilmud/issues#349]
Every time I attempt to use agg on an ability, whether I type '(power alias) agg' while in combat, or '(power alias) (target) agg' in or out of combat, it always returns the message: No target for your power could be found!

**Comment by otebski** [comment]
It is a bit clunky.
Out of combat "(alias) (target) agg" always works for me. Dunno why it does not for you.

In combat "(aliast) (target) agg" works only if (target)=(my current target) else i get no target message

(alias) agg never works in combat, despite current target being only valid target.

**Comment by shevarash** [comment]
This should work now, with the addition of the auto targetting via "all" and "agg". See the news for usage details.
