### ISSUE TITLE
Knockdown Powers

### ISSUE THREAD

**Issue by Inames** [torilmud/issues#350]
Can we consider changing the knockdown to be size restricted rather than the power itself? I don't see a reason to not allow the damage component to go through on non-bashable creatures.

EDIT: I noticed that this is already the case for the 2h knockdown powers, but not for the 1h/sh or dw knockdowns.

**Comment by ghost** [comment]
sweeping strike either on ranger!

**Comment by shevarash** [comment]
This has been done.
