### ISSUE TITLE
holy avenger proc

### ISSUE THREAD

**Issue by zenevan** [torilmud/issues#355]
so im playing with my avenger in scardale, level 1 2h skill 20
I thought this only proc at 75 skill, well it does proc before that.
until you practice 2h skill at the guild master

A Blood Stained Chamber
  The peaceful and tranquility of the temple has been completely 
defiled and left nothing but a constant feeling of un-easiness 
and anger throughout the temple. The air is stagnant and pungent 
with the odor of dried blood. At the far end of the hall is a 
slightly raised podium upon which an altar stands flanked by 
two candelabra and a large stone altar. Behind the altar hang 
the tattered remains of a large red tapestry covering most of 
the south wall. It is covered by a giant depiction of a furious 
Bane and a peaceful Helm. The mutilated remains of a priest and 
several acolytes liter the floor, and their remains lie smeared 
on the walls.  A partially blocked doorway leads west into a 
smoke filled hallway.
Exits: - West          [46122] 
Corpse of Tocc is lying here.
A chain with a wooden symbol lies here on the ground.
A robe lies here in a pile.
A severed head lies here, covered in maggots.
A half-orc berserker filled with blood lust, wildly stomps around the room.(Red Aura)
A filthy orc stalks about the here, grumbling to himself.(Red Aura)
A grimy orc stands here picking his nose.(Red Aura)

< 231h/248H 109v/110V |2| P: std > 
You lift a holy avenger enshrouded in light high in righteous fury, and you
are bathed in a divine radiance that quickly fills the area.  A powerful wave
pulses out from the hilt of the blade, pearl flashing quickly as a holy wrath
assaults your enemies.
a half-orc berserker is dead! R.I.P.
You receive 1,500 XP (7.89%) experience.
Your blood freezes as you hear the rattling death cry of a half-orc berserker.
a filthy orc is dead! R.I.P.
You receive 1,000 XP (5.26%) experience.
Your blood freezes as you hear the rattling death cry of a filthy orc.
a grimy orc is dead! R.I.P.
You receive 625 XP (3.29%) experience.
Your blood freezes as you hear the rattling death cry of a grimy orc.

< 231h/248H 110v/110V |2| P: std > 
You get a small pile of coins from corpse of a grimy orc.
There were: 9 silver coins, 27 copper coins.

< 235h/248H 110v/110V |2| P: std >

**Comment by OghmaToril** [comment]
Interesting.  Can you share your character name and/or race?

**Comment by zenevan** [comment]
I have investigated further, its based on weapon skill being 75% of max for that level.
Once you level up past level 1, the skill requirement goes down and the proc is removed.
Albeit I can train 2h at the dummy to max for level and get it proccing again, Sorry i just didn't understand.

That was my gnome paladin Nidzipple or something like that =D
