### ISSUE TITLE
psi stops meditating on enter

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#359]
You start meditating...

< 818h/818H 913p/913P 120v/120V P: sit > 
"" <--- this is a null string (enter key) being sent to mud

You stop meditating.

**Comment by OghmaToril** [comment]
I'm having a hard time replicating this.  Can you make sure all scripts are off to see if that fixes it?

**Comment by Nyyrazzilyss** [comment]
Using telnet:

< 593h/289H 833p/833P 120v/120V P: sit > med

You start meditating...

< 590h/289H 833p/833P 120v/120V P: sit >        <-- pressed the enter key
You stop meditating.

**Comment by OghmaToril** [comment]
Ok, looks like something introduced recently as I was able to confirm it on mainmud.

**Comment by shevarash** [comment]
This is fixed with #496.
