### ISSUE TITLE
cm epic quests

### ISSUE THREAD

**Issue by ghost** [torilmud/issues#362]
just a little feedback, would probably fall under enhancement

healing touch from dragonhunter weapons (bow and axe, not really mace), and saber of darkness, i understand the frequency and amount to be very well aligned and i not only agree with it, but think it is about perfect, not over the top, and not too terrible, but there is a minor issue.....the -2 hp proc for opposite align attacks, dragonhunter eats you for attacking good align, and saber for attacking evil align..........dragonhunter isn't terrible, few good align mobs, but on saber, this is a major let down, 95% of the mobs in game are evil............can we have the -2 changed to +1 instead?  5 3 1, instead of 5 3 -2, on the align attacks for healing touch?

a frost medallion......requires you to do one of the epic quests to get this item......is there a reason it's flag'd TREASURE and thus has no ac?  when another of the rewards is also neck item, knife charm...and it's got ac and 1/3.....frost medallion seems like an error....

a book of necromancy.........maxcon on a spellbook? seems like someone typed in the wrong bit vector here

while i'm on the subject of cm epics, there are a couple things i would also like to request: mostly with blood dome, and pops

zaggut make widow bloodstone, the remove/load after dropping it, needs to be put into a shorter pop zone, cm's 15 min doesnt' seem like long, until you have a group sitting, waiting, for 15+ minutes while a solo person kills, searches, and then waits for pop

black cube, triangular runestone, glass cube....these items are set to cm's pop timer, but can be a burdon due to the cm pop time, would also like to see these moved to another shorter pop zon file, 1 min too short, but 5 min might work better, and be less of a time sink

the 2 drop 8 and drop 9 bloodstones parts of blood dome, are obviously in a shorter pop area, and work rather nicely, same with the red glass cube drop timer

just a couple thoughts!

**Comment by ghost** [comment]
make pink and blue life crystals rentable also, plz, forgot about that.

**Comment by jokkmeister** [comment]
Does Dragonhunter axe even do anything on it's proc? I can't see anything happening at all. Doesn't heal, doesn't hit more or do more damage. Seems broken and I blame powers for it.
