### ISSUE TITLE
taunts

### ISSUE THREAD

**Issue by ghost** [torilmud/issues#365]
flip the taunts on blk and pal, area should be the higher level with longer recharge, single target should be the lower level, and lower recharge timer

**Comment by shevarash** [comment]
They are set up the way they are intentionally. Think of it like this:

Making a big scene and getting a group to pay attention to you is _easy_. Singling out one foe and getting them to come to you, now that takes skill and gravitas. Let's review in picture form, for fun:

**Area taunts:**

![image](https://user-images.githubusercontent.com/24870638/38628033-00523d46-3d76-11e8-862e-c7990f97f247.png)

**Single target taunts:**

![image](https://user-images.githubusercontent.com/24870638/38627792-6b1c5342-3d75-11e8-95bd-17dd9d950957.png)
