### ISSUE TITLE
Enhancement to phantom heal (Placebo effect)

### ISSUE THREAD

**Issue by otebski** [torilmud/issues#367]
Right now phantom heals adds 300 hp and removes 300 hp after the lapse of 2 minute period.

Proposition no 1:
Make sf illus and spec illus effect the duration.

Proposition no 2:
Make sf illus and spec illus effect the hp added, but not hp removed. This way with maxed spec illusionist would get 100hp heal ever 2 minutes  if he is under 50% hp. 150 heal at near max sf illus available (~30sf illus is reasonable max).

Proposition no 3: 
Both of the above. Will make spell more use-able and limit the healing over time.

**Comment by shevarash** [comment]
Good ideas - the spell as is is not terribly useful.

**Comment by shevarash** [comment]
This will be addressed in an upcoming class overhaul.
