### ISSUE TITLE
Enhance: Add board(s)

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#368]
You GCC: 'Moonway & Ghostwalk could use a board'

You GCC: 'Probably with the same board also in Scardale'

**Comment by shevarash** [comment]
Pardon the dumb question, but what boards specifically?

**Comment by Nyyrazzilyss** [comment]
I'm assuming it's the main board, the one that's at the great fountain in Waterdeep?

**Comment by shevarash** [comment]
...what for? I've been considering just removing all boards.

**Comment by Nyyrazzilyss** [comment]
Removing the boards would also be an option. This would probably be more related to if they were left ingame, moving them to more occupied locations.
