### ISSUE TITLE
Powers Chromatic Orb doesnt work.

### ISSUE THREAD

**Issue by i982** [torilmud/issues#369]
leveling my enchanter and noticed the powers version does nothing. non powers version seems to be working as intended.

**NON-POWERS VERSION**
c 'chromatic orb' commoner
You start chanting... [Casting: C 'CHROMATIC ORB' COMMONER (Chromatic orb)]

< 561h/570H 201v/201V P: std > 

You complete your spell... [ C 'CHROMATIC ORB' COMMONER (Chromatic orb) ]
You hurl a small orb of wildly shifting colors at a tall commoner!

c 'chromatic orb' commoner
You start chanting... [Casting: C 'CHROMATIC ORB' COMMONER (Chromatic orb)]

< 570h/570H 199v/201V P: std > 

You complete your spell... [ C 'CHROMATIC ORB' COMMONER (Chromatic orb) ]
You hurl a small orb of wildly shifting colors at an attractive commoner!
An attractive commoner is bathed in an explosion of crimson light!

**POWERS VERSION:**
[SPELL: Chromatic orb] CO
You start chanting... [Casting: CO (Chromatic orb)]

< 570h/570H 201v/201V T: Fizibible TC: excellent E: heavyset EC: few wounds EP: std P: std > 

A heavyset commoner misses you with her hit.

< 570h/570H 201v/201V T: Fizibible TC: excellent E: heavyset EC: few wounds EP: std P: std > 

Casting: Chromatic Orb **

< 570h/570H 201v/201V T: Fizibible TC: excellent E: heavyset EC: few wounds EP: std P: std > 

Casting: Chromatic Orb *

< 570h/570H 201v/201V T: Fizibible TC: excellent E: heavyset EC: few wounds EP: std P: std > 

You complete your spell... [ CO (Chromatic orb) ]

< 570h/570H 201v/201V T: Fizibible TC: excellent E: heavyset EC: few wounds EP: std P: std > 
You miss a heavyset commoner with your hit.
A heavyset commoner misses you with her hit.

< 570h/570H 201v/201V T: Fizibible TC: excellent E: heavyset EC: few wounds EP: std P: std > 
< 570h/570H 201v/201V T: Fizibible TC: excellent E: heavyset EC: few wounds EP: std P: std > 
[ powerAliases:castDamage() - co ]

[SPELL: Chromatic orb] CO
You start chanting... [Casting: CO (Chromatic orb)]

< 570h/570H 201v/201V T: Fizibible TC: excellent E: heavyset EC: few wounds EP: std P: std > 

A heavyset commoner slightly wounds you with her average hit.
OUCH!  That really did HURT!

< 552h/570H 201v/201V T: Fizibible TC: few scratches E: heavyset EC: few wounds EP: std P: std > 

You complete your spell... [ CO (Chromatic orb) ]

**Comment by ghost** [comment]
i've not seen where it does nothing, only that you don't get the cast message, chromatic orb has always had a chance to not fire any orbs, or at least that's what i've seen with condensed on

**Comment by shevarash** [comment]
Definitely bugged. Thanks.

**Comment by shevarash** [comment]
The issue was that the cast message was not shown. It is possible to get no effects from a chromatic orb, though that becomes less likely as you level up. The cast message will now be shown so tha tit's clear that the spell is working.
