### ISSUE TITLE
powers sunray

### ISSUE THREAD

**Issue by Adriorn** [torilmud/issues#37]
Isn't giving a message for when mobs are blinded.

**Comment by shevarash** [comment]
It seems like it is in my testing. Am I missing something?

![image](https://user-images.githubusercontent.com/24870638/27199184-b995e664-51da-11e7-9184-1b33ed465897.png)

**Comment by ghost** [comment]
i do believe he means with condensed toggled on, you see the cast, no effects, most power spells have this issue though, where you dont see it in condensed, hailstorm's slowness, dessicates stoneskin shatter/damage, are another 2 with same issue

**Comment by Adriorn** [comment]
With condensed on you don't get those messages like you do on non powers version with condensed on.
