### ISSUE TITLE
Enhance: Find zones by level range

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#372]
Kopek 'is there any way to list just low level areas with "credits"?'
Dugmaren 'nope, be nice though... #grep'
Kopek 'yeah, I'm making my own list, I want to see the low zones while I'm still low'
Dugmaren 'The suggested level is very much just a suggestion, I think with lower levels it matches up with average mob level. And the older zones are more balanced for weaker gear as well.'
You 'You should be able to solo complete most of the zones showing around your level as a paladin'
Kopek 'cool, I'm aiming at anything starting under 20'
You '< 20 for sure'

Or perhaps, have two copies of credits, one sorted by level?

**Comment by shevarash** [comment]
Storing level information and making it sortable and filterable is a good idea.
