### ISSUE TITLE
0 xp from kill when mobs slump to the ground

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#375]
This is with a level 2 blackguard

< 54h/54H 104v/105V |vs +|sot 38|bc +|drs +| |1| T: Gakomagik TC: excellent E: merchant EC: few wounds EP: std P: std > 

[MELEE: Dread Smite] DRS
An opulent merchant is stunned!
An opulent merchant slumps to the ground.
Your dread strike pulverizes an opulent merchant in a blast of frigid shadows!
an opulent merchant is dead! R.I.P.
An opulent merchant slumps to the ground.
You receive 0 XP (0.00%) experience.
Your blood freezes as you hear the rattling death cry of an opulent merchant.

[MELEE: Vengeance Strike] VS
Your weapon begins to pulse with a sinister glow as your soul fills with vengeance.
An opulent merchant slumps to the ground.
An opulent merchant is consumed by the purifying flames as you lash out in retribution!
an opulent merchant is dead! R.I.P.
An opulent merchant slumps to the ground.
You receive 0 XP (0.00%) experience.
Your blood freezes as you hear the rattling death cry of an opulent merchant.

It's not however ever time, only some of the time. Example: 

[MELEE: Dread Smite] DRS
Your dread strike pulverizes a dapper noble in a blast of frigid shadows!
a dapper noble is dead! R.I.P.
You receive 2,812 XP (25.13%) experience.
Your blood freezes as you hear the rattling death cry of a dapper noble.

**Comment by otebski** [comment]
Its not the skills that are a problem. I am getting  0 xp from pure melee kills too:
< 89h/156H 120v/120V T: Ralev TC: few wounds E: man EC: awful EP: std P: std > 

You miss a local man with your pierce.
A local man is stunned!
A local man slumps to the ground.
You pierce a local man's heart, you heartbreaker you.
a local man is dead! R.I.P.
A local man slumps to the ground.
You receive 0 XP (0.00%) experience.
Your blood freezes as you hear the rattling death cry of a local man.

**Comment by otebski** [comment]
I think the problem is that trophy works before level 20. at low levels its easy to get trophy so high that you get 0 exp.
Previously trophy did not kick in till around 20 partially, and till mid 30s for its full effect. Now it applies at level 1

**Comment by Nyyrazzilyss** [comment]
It shouldn't be trophy though - While I hadn't included it in my log I was getting 20-25% xp from that same mob subsequent to getting 0%, and was only killing 2 mobs at that time (the merchants + nobles at the inn).

Something noticable in all the log snippets with 0xp - The 'is dead' message is immediately followed with (mobname) slumps to the ground, and then 0 xp. When receiving xp, the mob never slumps.

**Comment by otebski** [comment]
For me it only happened at level 2-5 and only when trophy for the mob was above 100%. It did not happen for the next 30 levels so far.
I think if it was due to reasons other than extreme trophy it would happen throughout the whole leveling process.

**Comment by shevarash** [comment]
You should never get 0% exp from a kill. I'll investigate.
