### ISSUE TITLE
Unbreakable modification is backward from expected

### ISSUE THREAD

**Issue by torkur** [torilmud/issues#378]
Hey,

  Looks like Unbreakable is backward.  It's reducing our physical resists by 15 (bad), but I'd expect it to increase our resistances instead.

Thanks!

Name             : Unbreakable              
Alias            : ub                       
Type             : Melee                    
Source           : Martial                  
Target           : Self
Recharge         : 3 minutes 
Restrictions     : Standing
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Self Effect      : Modify physical resistance by -15 for 1 minute

**Comment by i982** [comment]
Here you go. a log.

          Character attributes for Xou

Level: 50   Race: Troll   Class: Warrior     
Age: 11 yrs / 7 mths  Size: Medium
STR: 106  AGI: 116  DEX: 111  CON: 106
POW:  45  INT:  54  WIS:  69  CHA:  46
Armor Class: -61  (100 to -100)  Agility Bonus: -25
Magic Resistance: 0 percent
Hitroll: 29   Damroll: 66
Alignment: Chaotic Evil
Saving Throws: PAR[-3]  ROD[0]  PET[-5]  BRE[0]  SPE[0]
   Wimpy: not set
Load carried: Paltry
Damage Resistance:
Unarmd:    0% Slash :    0% Bludgn:    0% Pierce:    0% Range :    0% 
Spells:    0% Fire  :  -80% Cold  :   35% Elect :   15% Acid  :   30% 
Sonic :    0% Poison:   15% Pos   :    0% Neg   :    0% Psi   :    5% 
Mental:    0% Good  :    0% Evil  :    0% Law   :    0% Chaos :    0% 
Force :    0% 

< 804h/817H 131v/131V P: std > 

unbreakable

< 804h/817H 131v/131V P: std >

You adjust your defensive stance and steel yourself for incoming attacks.

< 804h/817H 131v/131V P: std > 
att

          Character attributes for Xou

Level: 50   Race: Troll   Class: Warrior     
Age: 11 yrs / 7 mths  Size: Medium
STR: 106  AGI: 116  DEX: 111  CON: 106
POW:  45  INT:  54  WIS:  69  CHA:  46
Armor Class: -61  (100 to -100)  Agility Bonus: -25
Magic Resistance: 0 percent
Hitroll: 29   Damroll: 66
Alignment: Chaotic Evil
Saving Throws: PAR[-3]  ROD[0]  PET[-5]  BRE[0]  SPE[0]
   Wimpy: not set
Load carried: Paltry
Damage Resistance:
Unarmd:  -15% Slash :  -15% Bludgn:  -15% Pierce:  -15% Range :    0% 
Spells:    0% Fire  :  -80% Cold  :   35% Elect :   15% Acid  :   30% 
Sonic :    0% Poison:   15% Pos   :    0% Neg   :    0% Psi   :    5% 
Mental:    0% Good  :    0% Evil  :    0% Law   :    0% Chaos :    0% 
Force :    0% 

< 804h/817H 131v/131V P: std >

**Comment by shevarash** [comment]
Oops - will fix.

**Comment by shevarash** [comment]
Fixed!
