### ISSUE TITLE
Warrior (spells) sharing timer with powers

### ISSUE THREAD

**Issue by i982** [torilmud/issues#380]
no idea if this is as intended but for pld/blk their spells go off regardless. this delay is literally life or death when it comes to things like iron will or unstoppable...

You slam your shield into Dragor Keenblade with tremendous force, knocking him to the ground!

< 817h/817H 131v/131V T: Xou TC: excellent E: dragor EC: few scratches EP: rcl P: std > 
< 817h/817H 131v/131V T: Xou TC: excellent E: dragor EC: few scratches EP: rcl P: std > 
DSD
You're not ready to perform another action!

< 817h/817H 131v/131V T: Xou TC: excellent E: dragor EC: few scratches EP: rcl P: std > 

[MELEE: Defensive Strike] DS
You're not ready to perform another action!

DSD
< 817h/817H 131v/131V T: Xou TC: excellent E: dragor EC: few scratches EP: rcl P: std > 
You're not ready to perform another action!

< 817h/817H 131v/131V T: Xou TC: excellent E: dragor EC: few scratches EP: rcl P: std > 

[MELEE: Relentless Assault] RA
You're not ready to perform another action!

DSD
< 817h/817H 131v/131V T: Xou TC: excellent E: dragor EC: few scratches EP: rcl P: std > 
You're not ready to perform another action!

< 817h/817H 131v/131V T: Xou TC: excellent E: dragor EC: few scratches EP: rcl P: std > 

[MELEE: Brutal Strike] BS

< 832h/817H 131v/131V T: Xou TC: excellent E: dragor EC: few scratches EP: rcl P: std >

You lunge forward and crack Dragor Keenblade a brutal blow upside the head with your weapon.

DSD
< 832h/817H 131v/131V T: Xou TC: excellent E: dragor EC: few scratches EP: rcl P: std > 
You're not ready to perform another action!

< 832h/817H 131v/131V T: Xou TC: excellent E: dragor EC: few scratches EP: rcl P: std > 

[MELEE: Comeback Strike] CS
You're not ready to perform another action!

DSD
< 832h/817H 131v/131V T: Xou TC: excellent E: dragor EC: few scratches EP: rcl P: std > 
You're not ready to perform another action!

< 832h/817H 131v/131V T: Xou TC: excellent E: dragor EC: few scratches EP: rcl P: std > 
DSD
You're not ready to perform another action!

< 832h/817H 131v/131V T: Xou TC: excellent E: dragor EC: few scratches EP: rcl P: std > 
DSD
Dragor Keenblade slightly wounds you with his powerful hit.
Dragor Keenblade severely wounds you with his massive hit.
You channel your indomitable will into an impenetrable active defense.

**Comment by shevarash** [comment]
This is definitely a bug. I'll get it fixed shortly.

**Comment by shevarash** [comment]
Fixed!
