### ISSUE TITLE
Warrior (spells) Cooldowns

### ISSUE THREAD

**Issue by i982** [torilmud/issues#381]
if they had charges like the other classes it would be one thing...

but honestly these 5-7 minute cooldowns are just atrocious.. 

iron will a.k.a. shield of warding for paladin has 3 charges and still only has a 6 minute cooldown:\

and it is literally the best defense that pal/blk have period. making  warriors considerably weaker than their counterparts.

the other warrior(spells) are the same way. the reward is just not good compared to the cooldown involved. especially with the delay behind them. i mean there is no clutch move.. no decisions. if you are in that moment where "omg i have to do this" and you cant cause youre gated behind an imaginary cooldown.

Name             : Unstoppable              
Alias            : ut                       
Type             : Melee                    
Source           : Martial                  
Target           : Self
Recharge         : 5 minutes 
Restrictions     : Standing
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Self Effect      : Heal for 250 hit points  

5 minutes for this? i mean its a decent heal.. but when its all you have as a 2hand warrior you are literally screwed hehe. 2 minutes tops should be the cooldown here.

id suggest considerably lowers these cooldowns are adding multiple stacks to them as the other classes have.

**Comment by shevarash** [comment]
The mechanical difference here is intended to make Warriors play a little differently than the other tanks. It's all about timing the cooldowns and deciding when to use them. That said, the timing might very well be off. I'm going to leave this open and will keep monitoring as we get additional play time with the new Warriors under our belts.

**Comment by shevarash** [comment]
These were adjusted back in 2020.
