### ISSUE TITLE
Defensive Strike / Diamond Shield Defense

### ISSUE THREAD

**Issue by i982** [torilmud/issues#382]
i understand that one might be for 2handing. BUT identical effect. 12 second cooldown vs 5 minute cooldown. grants i know the diamond shield defense has a 1 minute duration. but defensive strike has a 100% uptime:p no idea what id change here but id completely rewrite diamond shield to something better. maybe a % when struck to deal % 75 or something less damage? varying of course on how long the cooldown remains..

Name             : Defensive Strike         
Alias            : ds                       
Type             : Melee                    
Source           : Martial                  
Attack Type      : Armor                    
Target           : Offense
**Recharge         : 12 seconds** 
Implements       : Weapon, Shield, One handed
Restrictions     : Standing, Can See
To-Hit Mods      : Level Diff +1, Str 25%, Hit Roll 200%
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Target Effect    : Strike with all weapons for 100% (Weapon, Shield, One handed) 
**Self Effect      : Add target hitroll trigger effect for 12 seconds  
Self Effect      : --> Modify target hitroll by -25 for 12 seconds**  
Miss Effect      : Strike with all weapons for 100% (Weapon, Shield, One handed)

Name             : Diamond Shield Defense   
Alias            : dsd                      
Type             : Melee                    
Source           : Martial                  
Target           : Self
**Recharge         : 5 minutes** 
Restrictions     : Standing
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
**Self Effect      : Add target hitroll trigger effect for 1 minute  
Self Effect      : Modify target hitroll by -25 for 1 minute**

**Comment by shevarash** [comment]
Thanks for the feedback. These powers stack on the user for a blur-like effect when used together. The idea is that you can get a mini-blur when two handing, and a full blur when shielding, but not with 100% uptime.
