### ISSUE TITLE
Trolls weakness to fire..

### ISSUE THREAD

**Issue by i982** [torilmud/issues#384]
this is going to draw ire i am sure...

but at this point i think the 100% weakness to fire is overdone. Especially since dualwield is out.
50% would be bearable but honestly this race is on the verge of being sidelined as a warrior because of this weakness. their main benefit is strong hp pool/agi. well the hp mean nothing anymore since your ability to heal yourself is gone especially in 2hand situations. the troll regen in current game is laughable since the class upgrades.

and no matter how much hp you stack its all for nothing if you die everytime a fire spell is casted.

as i said i know some wont agree but im just basing this off of the other classes/race combos. 

even in forgotten realms listing ice trolls would be melted by fire like swamp trolls are but swamp trolls only recieved a small penalty from fire.

i mean an idea would be to remove the 100% weakness and just add an extra set % of damage additional they take from fire based spells.

**Comment by shevarash** [comment]
You make a good point - 2x damage might be a bit much at this point. I think it's worth giving the Warriors changes a little more time to play out before changing this though. I'll leave it open and revisit in the future.
