### ISSUE TITLE
racial warrior specializations

### ISSUE THREAD

**Issue by settlestone** [torilmud/issues#387]
with the new warrior changes an idea came to me.  each warrior race could be subclassed by the race they pick into different subclass specializations.  IE.  Shield Dwarf Battlerager-Barbarian Berserker-Moon Elf Swashbuckler-Drow elf Brigand-Ogre Destroyer-Troll Mauler-Halfling Giantslayer-Human Sellsword-Duergar Clansman.. something thematic towards the ethos of what those races evoke.  

I really think this could add so much depth and fun into how we choose and play warrior.  and it would be a great way to make all of the races have viability.. play towards their strengths.

**Comment by shevarash** [comment]
These are very interesting ideas. I like the idea of giving classes a way to specialize. I'm closing the ticket, but will keep this idea in mind. Thanks!
