### ISSUE TITLE
Warrior update easy fixes

### ISSUE THREAD

**Issue by vitaladsr** [torilmud/issues#388]
I noted that all the powers 2h and shield the to_hit mods are str based and all use +25 str mod. Perhaps it would be better to change the shield to_hit mod to agil since half the warriors are agil based (tank) and the other half are str (damage) based.

I would also really like to see a strength modifier play a more important role in damage output especially of the 2h powers giving the edge to the stronger races (for damage). Keep in mind the stronger races usually don't have the agil build for sustained tanking damage. That would help balance a little and give the changes much more mileage.

And on a side note, always dreamed of having some way to dual 2h weapons .. I didn't see any powers that are even dual wield based .. so perhaps that's enough of a sacrifice right there.

**Comment by shevarash** [comment]
Thanks for the feedback. Right now, the strength bonus rather than agility is intended as a way to help balance out Agility's dominance for the tank classes. It's worth pointing out that the +Str mod on those powers are relatively small - your hitroll is much more important.
