### ISSUE TITLE
vortex cloak charging still borked

### ISSUE THREAD

**Issue by vitaladsr** [torilmud/issues#389]
This cloak never seems to charge, not sure whats up with it.

**Comment by OghmaToril** [comment]
The issue here is that the proc recharge duration doesn't match what it states in identify.  Querying the staff to get ideas where the recharge should be.

**Comment by shevarash** [comment]
The current recharge is 1x/week, though identify states 1x/day. We're (sort of) splitting the difference and making it 1x/2 days.
