### ISSUE TITLE
thorn gauntlets

### ISSUE THREAD

**Issue by vitaladsr** [torilmud/issues#391]
This item seems to never proc

**Comment by Zipalodok** [comment]
Its a called proc to not allow a mob to flee, sorta useless. But thats why it wont work for you.
Use an Identify scroll on the gauntlets to see the info better.

Called Effects : (invoked by 'say'ing them)
                 'ensnare'   Entangle 3x/Day

You "say ensnare" to call the proc

**Comment by vitaladsr** [comment]
Ah ok .. thanks I was testing them for hours expecting something to happen. Damn ... I really wish this was more useful because they are extremely hard to obtain .. one of the (lesser) epic quests .. still a huge challenge you have to do trune atleast 4-5 times (and win the bid) hoping all the phylacteries load and turn in your holy avenger???
