### ISSUE TITLE
Enhance: Add value to platinum - Discuss?

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#392]
Mobs load with money. Do they need to also repop with money?

I could see modifying it a bit for lower level, however, perhaps mobs less then level 40 repop with platinum (not much anyways, they're low level) so could be farmed, but higher level mobs have cash only initial load only?

**Comment by shevarash** [comment]
I do think mobs should continue to load with money, but I also agree that the value of money and the conomy in general need some adjusting. Closing, but the fundamental issue is valid.
