### ISSUE TITLE
blk: shattering smite not recognizing size restrict

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#393]
[MELEE: Shattering Smite] SS

< 1313h/1579H 134v/134V |drs 54|ss +|sph 6|uf +| |3|0|3|2|0| T: Ihgod TC: small wounds E: hamatula EC: few wounds EP: std P: std >

Your weapon unleashes a torrent of dark power as you strike a hamatula sentinel, knocking him to the ground.

Your weapon unleashes a torrent of dark power as you strike an elder green dragon, knocking him to the ground.

**Comment by i982** [comment]
just curious did you look to see if it actually knocked them down cause i dont think it does. i think the message is wrong but i dont think it actually knocks them down. i noticed this same thing on dragons.

**Comment by shevarash** [comment]
I believe this is a messaging issue. Only the knockdown is size restricted now, though the damage can always hit. The problem is that the message still says that they are knocked down. Will fix.
