### ISSUE TITLE
XP and botting solution.. or at least a start

### ISSUE THREAD

**Issue by i982** [torilmud/issues#394]
pretty simple.

anyone 4 levels below the highest level person in the group gets no xp OR an increasing xp penalty the bigger the level gap.

personally i opt for NO XP to eliminate power leveling altogether IF that is the desire for everyone.

also implement a % exp bonus for each person in party. 5% or something per additional member. so a party of 4 would recieve 20% xp bonus but could only be within 4 levels of the leader to recieve it.

remove all xp tokens except for in the areas where groups xp as a random group drop to split at end like groups used to do with plats.

now this will make ppl group together and xp in other areas of the game... BUT it isnt going to stop ppl from relying on triggers to do everything for them.

if you want to stop botting its going to be tough on anyone but the guy driving the group. but it would be and idea to make xp areas not have stationary pops like sm and such. so that the party path is ever changing kind of like a maze that changes every pop. but it still only makes the driver stay at the wheel. unless you added an element like kenjin tower where players go certain directions to end up in the same room. but even then it could be scripted to where a driver could control it. but its some ideas as a start.

**Comment by shevarash** [comment]
Thanks for the feedback. I'll keep this open under enhancement for now.
