### ISSUE TITLE
Powers coding definition

### ISSUE THREAD

**Issue by vitaladsr** [torilmud/issues#395]
I am specifically looking for the right "type" as per the following article. Ie. Damage, Healing, Teleportation ... I am looking for Vampiric .. but the link below was not provided.

﻿﻿https://github.com/torilmud/docs/wiki/Powers

I am looking to add my own vampiric "type" power to a mob I am creating. Thanks!!!

**Comment by gruumsh** [comment]
Adding custom power types isn't in the cards for the foreseeable future. If you want to make a vamp power there are other ways to go about it, like a damage effect coupled with a healing effect.
