### ISSUE TITLE
Psionicist problems even in Rainbow Curtain

### ISSUE THREAD

**Issue by i982** [torilmud/issues#400]
**heres the problem... i have used every available skill to defend myself. and nearly all my skills are maxxed. yep in various places throughout this area i am completely one shot before the remote possibility of fleeing. then on top of that i have to suiside repeatedly waiting for my innate since there is no timers for our powers. it takes if perfectly executed about an hour to run through this... for a chance at a possible reward or NOTHING. granted there is a chance if you drop and carry the items to the end 30% of xp tokens but you no longer lose xp.. and then you get the staff. the crystal staff is the only thing really making this class worth playing otherwise in zones every mem time is a death mem but longer to get psps back. My suggestion is to make this worth while since it takes around 2 hours if done with reasonable speed. it can take up to 6 if rng is against you. half your skills dont even work as intended as some of these mobs are golems that ignore detonate. others can be synaptic static'd but continue to cast. and then the last real "mob" is literally spamming luck timing hoping that once it attacks you you can ultrablast or deathfield and flee in hopes that it doesnt kill you before flee. this isnt a test of anything cept connection speed. and finally there is the rng of death. dying over and over and over because why? latency kept to one second from fleeing? there is no skill here just hit and hope. this isnt a class test this is an rng bodytoss. pelase make it worth while in some manner. and lastly.. the staff at the end of this which is norent should be a tia level item either quested from the staff that is no rent and a tia item or just a drop from tia. granted minor adjustments to it could be made such as a 40% of max baseline on psp gain but the hp proc is rather low. shrug id really like to see where this class is going cause as it stands its nearly impossible to be useful, at least more-so than one half geared ranger.
**

You scan down...
A Thick Layer of Accumulated Scum
Exits: -U
The fabric of reality flails about with gooey reaching tendrils here.
The fabric of reality flails about with gooey reaching tendrils here.
The fabric of reality flails about with gooey reaching tendrils here.
The fabric of reality flails about with gooey reaching tendrils here.
The fabric of reality flails about with gooey reaching tendrils here.
A glimmer of winking light dances about here.
A glimmer of winking light dances about here.
A titan of elemental phlogiston encompasses the area here.

Status of Mixamilon
---------------------------------------------------------------------------

Effects
---------------------------------------------------------------------------
body control              catfall                   meditate                  
ultravision               

Conditions
---------------------------------------------------------------------------
expansion                 (  0:00)   flesh armor               (  4:00)   
adrenalize                (  6:00)   adrenalize                (  6:00)   
adrenalize                (  6:00)   catfall                   ( 22:00)   
body control              ( 66:00) 

A Thick Layer of Accumulated Scum
   A grimy layer of mushy lichen has accumulated in the depths of the 
goo. Thick gooey muck is all around the area, forming an impenetrable 
layer of jelly at the bottom of these depths. Grumbling incoherently, 
this massive gelatinous puddle seems to make up the bottom of the area 
of emerald jelly. The sludge here is thick and impenetrable, a dark build 
< 146h/146H 589p/679P 92v/93V P: std >

The air in the immediate area darkens abruptly as a result of your projection!

< 146h/146H 561p/679P 92v/93V P: std > 

A tendril of ooze twists around you.
The Primordial badly wounds you with its average beat.

< 136h/146H 561p/679P 92v/93V T: Mixamilon TC: few scratches E: primordial EC: excellent EP: std P: std > 
A tendril of ooze twists around you.

< 136h/146H 561p/679P 92v/93V T: Mixamilon TC: few scratches E: primordial EC: excellent EP: std P: std > 

A warbling groan echoes from somewhere nearby.

< 137h/146H 561p/679P 93v/93V T: Mixamilon TC: few scratches E: primordial EC: excellent EP: std P: std > 

A tendril of ooze twists around you.

< 137h/146H 562p/679P 93v/93V T: Mixamilon TC: few scratches E: primordial EC: excellent EP: std P: std > 

A massive maw forms in the center of the titan's form.

< 137h/146H 562p/679P 93v/93V T: Mixamilon TC: few scratches E: primordial EC: excellent EP: std P: std > 

The Primordial badly wounds you with its average beat.
A writhing mass of ooze slightly wounds you with its weak slash.
There appears to be poison on your opponent's weapon!
A writhing mass of ooze severely wounds you with its average slash.
There appears to be poison on your opponent's weapon!
A writhing mass of ooze badly wounds you with its average slash.
There appears to be poison on your opponent's weapon!
A writhing mass of ooze badly wounds you with its average slash.
There appears to be poison on your opponent's weapon!
A writhing mass of ooze severely wounds you with its average slash.
There appears to be poison on your opponent's weapon!
A writhing mass of ooze badly wounds you with its average slash.
There appears to be poison on your opponent's weapon!
A writhing mass of ooze severely wounds you with its average slash.
There appears to be poison on your opponent's weapon!
A writhing mass of ooze severely wounds you with its average slash.
There appears to be poison on your opponent's weapon!
A writhing mass of ooze wounds you harshly with its average slash.
There appears to be poison on your opponent's weapon!

< 51h/146H 562p/679P 93v/93V T: Mixamilon TC: nasty wounds E: primordial EC: excellent EP: std P: std > 

A blinking light pulses a momentary warning.

< 51h/146H 562p/679P 93v/93V T: Mixamilon TC: nasty wounds E: primordial EC: excellent EP: std P: std > 

The Primordial swings forth its hammer-shaped tail toward you...
The Primordial misses its targeted item on you.
The Primordial wounds you harshly with its average beat.
A writhing mass of ooze wounds you harshly with its average slash.
There appears to be poison on your opponent's weapon!
A writhing mass of ooze brutally wounds you with its average slash.
There appears to be poison on your opponent's weapon!
You stagger from a writhing mass of ooze's average slash!
There appears to be poison on your opponent's weapon!
A writhing mass of ooze brutally wounds you with its weak slash.
There appears to be poison on your opponent's weapon!
You wish that your wounds would stop BLEEDING so much!

A writhing mass of ooze brutally wounds you with its weak slash.
There appears to be poison on your opponent's weapon!
You wish that your wounds would stop BLEEDING so much!

A writhing mass of ooze critically wounds you with a average slash!
There appears to be poison on your opponent's weapon!
YIKES!  Another hit like that, and you've had it!!
You wish that your wounds would stop BLEEDING so much!

A writhing mass of ooze nearly slays you with the force of its average slash!
There appears to be poison on your opponent's weapon!
You are mortally wounded, and will die soon, if not aided.

< -7h/146H 563p/679P 93v/93V P: std > 
You are dead!

Your soul is transported to The Fugue Plane as your crumbling body succumbs43682

[Clearing memorized spells]

[Spellqueue cleared.]
to the cold sleep of death. Here in Kelemvor's realm all dead souls await
either judgement or escape from this timeless prison.

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

The Top of the Crystal Spire on the Fugue Plane
   This large, circular chamber looks out high over the featureless grey
landscape of the Fugue Plane, where dead souls come to await judgement. The
walls are made of clear, transparent crystal and appear featureless and
smooth to the touch. A polished obsidian bench runs the length of the room's
curved walls. Tiny crystal globes ensconced high along the walls emit a soft
white light, which reveals little in this featureless waiting room. Down
below, other disembodied souls can be seen traversing the bleak landscape.
This chamber appears to be reserved for those souls that are favored by a
member of the pantheon. There do not appear to be any exits from this

From here you may either re-enter the game by typing enter portal, or wait
to be resurrected by another player. Type help death for more information.

You can't do that on the Fugue Plane.

< 24h/96H 169p/679P 23v/93V P: std >

**Comment by i982** [comment]
**and then there is this... when a skill does "work" you get knocked out for 10 minutes........ what the heck? my catfall is 92 i think. i cant check because im knocked out.. but still it took literally weeks to get it that high practicing it 24 hours a day... and this is the skill reward?**

The Fluffy Floor of the Pit of Distorted Reality
   The purple energies of this indigo space seem to be causing 
intense gravitational fluctuation. Spatial distortions teasingly 
stretch and pull on your body. In the groundless space below, the 
sporadic forces that resemble gravity draw you downward into the 
lavender depths with unrelenting force. The lower you descend the 
stronger the gravitational propulsion becomes. Rushing upward are 
powerful astral winds. Maniacal laughter echoes about the area.
A wispy layer of fluffy floor seems unable to stop your descent.
Exits: - Up            [78924] 
The mists of imagination writhe with unconceived possibilities.
Although your catfall ability absorbs the brunt of the impact.
You still land with stunning force!
You collapse in a heap on the ground.
The world starts spinning, and your ears are ringing!
[Spellqueue cleared.]

< 14h/146H 591p/679P 87v/93V P: knl >

Being knocked unconscious strictly limits what you can do.
Try typing 'commands'.

< 14h/146H 591p/679P 87v/93V P: knl >

Being knocked unconscious strictly limits what you can do.
Try typing 'commands'.

< 14h/146H 591p/679P 87v/93V P: knl >

Being knocked unconscious strictly limits what you can do.
Try typing 'commands'.

< 14h/146H 591p/679P 88v/93V P: knl >

**Comment by i982** [comment]
**another example of how rng it is in here with this class. literally half the mobs are dead and still just random death**

A Thick Layer of Accumulated Scum
   A grimy layer of mushy lichen has accumulated in the depths of the 
goo. Thick gooey muck is all around the area, forming an impenetrable 
layer of jelly at the bottom of these depths. Grumbling incoherently, 
this massive gelatinous puddle seems to make up the bottom of the area 
of emerald jelly. The sludge here is thick and impenetrable, a dark build 
< 146h/146H 582p/679P 92v/93V P: std >

The air in the immediate area darkens abruptly as a result of your projection!
A writhing mass of ooze slumps to the ground.
a writhing mass of ooze is dead! R.I.P.
A writhing mass of ooze slumps to the ground.
You receive 244,235 XP (0.56%) experience.
Your blood freezes as you hear the rattling death cry of a writhing mass of ooze.
A writhing mass of ooze slumps to the ground.
a writhing mass of ooze is dead! R.I.P.
A writhing mass of ooze slumps to the ground.
You receive 242,393 XP (0.55%) experience.
Your blood freezes as you hear the rattling death cry of a writhing mass of ooze.
The sphere around you slowly dissipates.

< 146h/146H 555p/679P 92v/93V P: std > 

A giant primordial fist rises out of the muck to slap at you.

< 146h/146H 555p/679P 93v/93V P: std > 

The Primordial badly wounds you with its average beat.
The Primordial badly wounds you with its average beat.
A writhing mass of ooze severely wounds you with its average slash.
There appears to be poison on your opponent's weapon!
A writhing mass of ooze badly wounds you with its average slash.
There appears to be poison on your opponent's weapon!
A writhing mass of ooze badly wounds you with its average slash.
There appears to be poison on your opponent's weapon!
A writhing mass of ooze badly wounds you with its average slash.
There appears to be poison on your opponent's weapon!

< 92h/146H 555p/679P 93v/93V T: Mixamilon TC: few wounds E: primordial EC: few wounds EP: std P: std > 

A tendril of ooze twists around you.

< 93h/146H 556p/679P 93v/93V T: Mixamilon TC: few wounds E: primordial EC: few wounds EP: std P: std > 

The Primordial severely wounds you with its average beat.
The Primordial badly wounds you with its average beat.
A writhing mass of ooze wounds you harshly with its average slash.
There appears to be poison on your opponent's weapon!
A writhing mass of ooze wounds you harshly with its average slash.
There appears to be poison on your opponent's weapon!
A writhing mass of ooze severely wounds you with its average slash.
There appears to be poison on your opponent's weapon!
A writhing mass of ooze wounds you harshly with its average slash.
There appears to be poison on your opponent's weapon!

< 39h/146H 557p/679P 93v/93V T: Mixamilon TC: pretty hurt E: primordial EC: few wounds EP: std P: std > 
PANIC!  You couldn't escape!
[Spellqueue cleared.]

< 39h/146H 557p/679P 93v/93V T: Mixamilon TC: pretty hurt E: primordial EC: few wounds EP: std P: std >

< 39h/146H 557p/679P 93v/93V T: Mixamilon TC: pretty hurt E: primordial EC: few wounds EP: std P: std >

A Thick Layer of Accumulated Scum
Exits: - Up            [43682] 
[3] Corpse of a writhing mass of ooze is lying here.
A writhing mass of ooze stands here, fighting YOU!
A writhing mass of ooze stands here, fighting YOU!
The Primordial stands here, fighting YOU!

< 39h/146H 557p/679P 93v/93V T: Mixamilon TC: pretty hurt E: primordial EC: few wounds EP: std P: std >

PANIC!  You couldn't escape!

< 39h/146H 557p/679P 93v/93V T: Mixamilon TC: pretty hurt E: primordial EC: few wounds EP: std P: std > 

The Primordial brutally wounds you with its average beat.
A writhing mass of ooze enshrouds you in a mist of blood with its average slash!
There appears to be poison on your opponent's weapon!
YIKES!  Another hit like that, and you've had it!!
A writhing mass of ooze enshrouds you in a mist of blood with its average slash!
There appears to be poison on your opponent's weapon!
YIKES!  Another hit like that, and you've had it!!
You wish that your wounds would stop BLEEDING so much!

A writhing mass of ooze nearly slays you with the force of its average slash!
There appears to be poison on your opponent's weapon!
You are incapacitated and will slowly die, if not aided.

< -3h/146H 558p/679P 93v/93V P: std > 

There appears to be poison on your opponent's weapon!

You are dead!

Your soul is transported to The Fugue Plane as your crumbling body succumbs43682

[Clearing memorized spells]

[Spellqueue cleared.]
to the cold sleep of death. Here in Kelemvor's realm all dead souls await
either judgement or escape from this timeless prison.

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

The Top of the Crystal Spire on the Fugue Plane
   This large, circular chamber looks out high over the featureless grey
landscape of the Fugue Plane, where dead souls come to await judgement. The
walls are made of clear, transparent crystal and appear featureless and
smooth to the touch. A polished obsidian bench runs the length of the room's
curved walls. Tiny crystal globes ensconced high along the walls emit a soft
white light, which reveals little in this featureless waiting room. Down
below, other disembodied souls can be seen traversing the bleak landscape.
This chamber appears to be reserved for those souls that are favored by a
member of the pantheon. There do not appear to be any exits from this
chamber.
Exits: None!           [93848] 
A wispy smoke colored portal hovers just above the center of the room.


From here you may either re-enter the game by typing enter portal, or wait
to be resurrected by another player. Type help death for more information.

**Comment by i982** [comment]
**complete rng as to whether i live or die. fully spelled again.**

A Golden Vortex of Amber Waves
   The amber waves of this churning vortex of golden light wash 
the area in brilliant illumination. Shining with alternating hues of 
aurulent colors, the hypnotic winking of these intense sparkles is 
mesmerizing. Surrounded by whirling geometric patterns of infinite 
variety, this bizarre and entrancing place of kaleidoscopic lights 
< 146h/146H 494p/679P 92v/93V P: std >

The air ripples as you thrust a wave of pure telekinetic force at a grell guardian.
The sphere around you slowly dissipates.

< 146h/146H 459p/679P 92v/93V P: std > 

a grell guardian makes a swift move, stinging you with its tail.
A grell guardian enshrouds you in a mist of blood with its massive bite!
OUCH!  That really did HURT!
A grell guardian wounds you harshly with its average bite.

< 63h/146H 460p/679P 93v/93V T: Mixamilon TC: nasty wounds E: grell EC: few wounds EP: std P: std > 
equal self
flee
A grell guardian severely wounds you with its average bite.
a grell guardian makes a swift move, stinging you with its tail.
A grell guardian smashes your throat, gasping and choking, you descend into darkness.
With a final blow, you feel yourself falling to the ground.
Your soul leaves your body in the cold sleep of death...
The burning in your veins eases.

You are dead!

Your soul is transported to The Fugue Plane as your crumbling body succumbs43681

[Clearing memorized spells]

[Spellqueue cleared.]
to the cold sleep of death. Here in Kelemvor's realm all dead souls await
either judgement or escape from this timeless prison.

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

The Top of the Crystal Spire on the Fugue Plane
   This large, circular chamber looks out high over the featureless grey
landscape of the Fugue Plane, where dead souls come to await judgement. The
walls are made of clear, transparent crystal and appear featureless and
smooth to the touch. A polished obsidian bench runs the length of the room's
curved walls. Tiny crystal globes ensconced high along the walls emit a soft
white light, which reveals little in this featureless waiting room. Down
below, other disembodied souls can be seen traversing the bleak landscape.
This chamber appears to be reserved for those souls that are favored by a
member of the pantheon. There do not appear to be any exits from this

From here you may either re-enter the game by typing enter portal, or wait
to be resurrected by another player. Type help death for more information.

**Comment by i982** [comment]
**this isnt challenge its annoyance... complete rng at its worst.. synaptic static completely worthless?**

A Golden Vortex of Amber Waves
   The amber waves of this churning vortex of golden light wash 
the area in brilliant illumination. Shining with alternating hues of 
aurulent colors, the hypnotic winking of these intense sparkles is 
mesmerizing. Surrounded by whirling geometric patterns of infinite 
variety, this bizarre and entrancing place of kaleidoscopic lights 
doesn't seem to resemble any traditional plane of existence.
Exits: - East  - South  [43681] 
A celestial lammasu stands guard stoically.
A rainbow warrior of living light is here.

< 146h/146H 443p/679P 92v/93V P: std >

Your spell fails to take hold on the Golden Protector.
You rip the memory of your assault from your foe's mind!
Your projection successfully scrambles the Golden Protector thoughts and memories.

< 146h/146H 364p/679P 92v/93V P: std > 
A rainbow warrior of living light barely wounds you with his weak pummel.

< 145h/146H 364p/679P 92v/93V T: Mixamilon TC: few scratches E: rainbow EC: excellent EP: std P: std > 

Your flesh loses its stony texture.
A rainbow warrior of living light barely wounds you with his weak pummel.
**The Golden Protector breathes a cone of fire!
You are scorched by the intense flames!
YIKES!  Another hit like that, and you've had it!!**

< 31h/146H 364p/679P 93v/93V T: Mixamilon TC: pretty hurt E: rainbow EC: excellent EP: std P: std > 

A rainbow warrior of living light nearly slays you with the force of his mighty pummel!
You are mortally wounded, and will die soon, if not aided.

< -9h/146H 366p/679P 93v/93V P: std > 
You are in pretty bad shape, unable to do anything!

< -9h/146H 366p/679P 93v/93V P: std >

You are in pretty bad shape, unable to do anything!

< -9h/146H 366p/679P 93v/93V P: std >

You are in pretty bad shape, unable to do anything!

< -9h/146H 366p/679P 93v/93V P: std > 
The Golden Protector shakes its noble leonine mane.

< -9h/146H 366p/679P 93v/93V P: std > 
st;flee
You are in pretty bad shape, unable to do anything!

< -9h/146H 368p/679P 93v/93V P: std >

You are in pretty bad shape, unable to do anything!

< -9h/146H 368p/679P 93v/93V P: std > 


You are dead!

Your soul is transported to The Fugue Plane as your crumbling body succumbs43681

[Clearing memorized spells]

[Spellqueue cleared.]
to the cold sleep of death. Here in Kelemvor's realm all dead souls await
either judgement or escape from this timeless prison.

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

The Top of the Crystal Spire on the Fugue Plane
   This large, circular chamber looks out high over the featureless grey
landscape of the Fugue Plane, where dead souls come to await judgement. The
walls are made of clear, transparent crystal and appear featureless and
smooth to the touch. A polished obsidian bench runs the length of the room's
curved walls. Tiny crystal globes ensconced high along the walls emit a soft
white light, which reveals little in this featureless waiting room. Down
below, other disembodied souls can be seen traversing the bleak landscape.
This chamber appears to be reserved for those souls that are favored by a
member of the pantheon. There do not appear to be any exits from this

From here you may either re-enter the game by typing enter portal, or wait
to be resurrected by another player. Type help death for more information.

**Comment by Nyyrazzilyss** [comment]
There's lots of ways to do the rainbow curtain. When I was doing it every boot, I had reached a 90%+ success rate. A psi has ways around everything you posted.

**Comment by i982** [comment]
i can do it with a 100% success rate. it doesnt change that there are mechanics that ignore specific abilities psi's have to counter them. as the log show.

**Comment by Nyyrazzilyss** [comment]
You proved 100% success isn't possible in your log with bad luck causing multiple failed flees. When i'm saying 90%+ I mean if I were to do it 10 times, i'll succeed 9 of them without dying.

A fully quested and practiced psi can easily get around everything (except the multiple failed flees) that you posted through correct use of the existing skills/abilities.

**Comment by i982** [comment]
yeah ok. well when you prove to me you can do it in 25 minutes like you claimed in gcc ill believe you. but you more or less proved my point. it not skill its rng luck. "your log with bad luck causing multiple failed flees." one of those deaths was a failed flee btw. the rest were psi-skill lag deaths.

combatmind                (above average) (60)
mindblast                 (good)          (72)
aurasight                 (above average) (61)
danger sense              (master)        (99)

Psychokinetics:

project force             (master)        (99)
detonate                  (master)        (99)
telekineticthrust         (master)        (99)

Psychometabolics:

adrenalize                (master)        (93)
flesh armor               (master)        (98)
body control              (very good)     (83)
catfall                   (very good)     (90)
reduction                 (master)        (99)
expansion                 (master)        (99)
deathfield                (master)        (99)
sustain                   (master)        (99)
equalibrium               (master)        (99)

Psychoportation:

planar rift               (unlearned)     (0)
shift                     (good)          (74)
wormhole                  (very good)     (87)

Telepathy:

tower of iron will        (master)        (99)
dominate                  (master)        (99)
mass domination           (master)        (99)
synaptic static           (master)        (99)

Metapsionics:

stasis field              (master)        (99)
battle trance             (unlearned)     (0)
ultrablast                (unlearned)     (0)
canibalize                (master)        (99)
globe of darkness         (unlearned)     (0)
charge                    (master)        (99)

only thing im missing from the skillset that matters in there is ultrablast. and its not going to stop me from being killed in one cast-lag cycle.

**Comment by torkur** [comment]
You didn't read my guide and you're doing the Primordial section wrong.  There is a "trick" to every section as Nyyr said and you don't die after you figure that out. It's not the class being deficient.

**Comment by torilmud-silvanus** [comment]
Thank you for the feedback. You are right that there are chances that you will die due to no error of your own. However, this zone has been balanced and constructed as carefully as I could manage, and it already became "easier" as there are less costs to dying now that you don't lose xp. So for now, I don't have plans to make changes to this zone's balance.
