### ISSUE TITLE
Vamp shield proc reducing HP total on Blackguards

### ISSUE THREAD

**Issue by Fisig** [torilmud/issues#402]
You feel informed:
Name 'a fine mithril shield embedded with spikes'
Keyword 'shield mithril spikes embedded spiked', Item type: ARMOR
Item can be worn on:  SHIELD 
Item will give you following abilities:  NOBITS
Item is: NOSELL MAGIC NOBURN NOLOCATE NO-THIEF NO-MAGE NOBITS
Weight: 35, Value: 100000
AC-apply is 18
Powers: Spikethrust
Can affect you as :
    Affects : HITROLL by 2
    Affects : DAMROLL by 2
Special Effects : Lifedrain
Special Powers  : Spikethrust
    Alias : spike

****************************

< 1131h/864H 106v/106V |3|2|1|3|0| T: Halmetalok TC: excellent E: elaith EC: few scratches EP: rcl P: std > 

The dark mists surge as life force is siphoned into you.
Your massive slash barely wounds Elaith Waterstill.
The dark mists surge as life force is siphoned into you.
Your massive slash barely wounds Elaith Waterstill.
You miss Elaith Waterstill with your slash.
Your shield glows brightly as it steals some lifeforce
from Elaith Waterstill and transfers it back to you.
You block Elaith Waterstill's attack with your shield!

< 914h/864H 106v/106V |3|2|1|3|0| T: Halmetalok TC: excellent E: elaith EC: small wounds EP: rcl P: std > 

*********************************************************************************************************

< 1097h/864H 106v/106V |3|2|1|3|0| T: Halmetalok TC: excellent E: elaith EC: pretty hurt EP: rcl P: std > 
Your massive slash badly wounds Elaith Waterstill.
Your massive slash badly wounds Elaith Waterstill.
Your awesome slash slightly wounds Elaith Waterstill.
Your shield glows brightly as it steals some lifeforce
from Elaith Waterstill and transfers it back to you.
You block Elaith Waterstill's attack with your shield!

< 914h/864H 106v/106V |3|2|1|3|0| T: Halmetalok TC: excellent E: elaith EC: awful EP: rcl P: std > 

********************************************************************************************************

< 1020h/864H 106v/106V |3|3|1|3|1| T: Halmetalok TC: excellent E: seipora EC: awful EP: rcl P: std > 

The dark mists surge as life force is siphoned into you.
Seipora Rein staggers from your awesome slash!
Seipora Rein dodges your futile attack.
The dark mists surge as life force is siphoned into you.
You critically wound Seipora Rein with a awesome slash!
Your shield glows brightly as it steals some lifeforce
from Seipora Rein and transfers it back to you.
You block Seipora Rein's attack with your shield!

< 914h/864H 106v/106V |3|3|1|3|1| T: Halmetalok TC: excellent E: seipora EC: awful EP: rcl P: std > 

********************************************************************************************************

< 921h/864H 101v/106V |3|3|1|3|1| T: Halmetalok TC: excellent E: ersenas EC: small wounds EP: rcl P: std > 

The dark mists surge as life force is siphoned into you.
Your awesome slash barely wounds Ersenas.
You feel a powerful fury rise up in your chest, causing your
vision to go red.  You lift a warped broadsword and slam it
down on Ersenas in all your rage.  Unsatisfied,
you slam it down again, and then yet again, howling in berserker
fury.
Your attack only grazes Ersenas as he dodges aside!
You score a CRITICAL HIT!
The dark mists surge as life force is siphoned into you.
Your strong slash barely wounds Ersenas.
The dark mists surge as life force is siphoned into you.
Your awesome slash barely wounds Ersenas.
Your attack only grazes Ersenas as he dodges aside!
The dark mists surge as life force is siphoned into you.
Your strong slash barely wounds Ersenas.
The dark mists surge as life force is siphoned into you.
Your massive slash barely wounds Ersenas.
The dark mists surge as life force is siphoned into you.
Your massive slash barely wounds Ersenas.
The dark mists surge as life force is siphoned into you.
Your massive slash barely wounds Ersenas.
Your shield glows brightly as it steals some lifeforce
from Ersenas and transfers it back to you.
You block Ersenas's attack with your shield!
Ersenas misses you with his hit.

< 914h/864H 104v/106V |3|3|1|3|1| T: Halmetalok TC: excellent E: ersenas EC: few wounds EP: rcl P: std >

**Comment by shevarash** [comment]
The vamp had a small limit over max that it could go, so it was resetting hitpoints down to that ceiling if they were higher from any other powers. It's been changed so that this proc can vamp to max, but not over. This way it won't ever reduce your hitpoints, but can still heal you if you're below max.
