### ISSUE TITLE
a mithril two-handed dwarven battle hammer

### ISSUE THREAD

**Issue by Fisig** [torilmud/issues#403]
You feel informed:
Name 'a mithril two-handed dwarven battle hammer'
Keyword 'hammer mithril handed dwarven', Item type: WEAPON
Item can be worn on:  WIELD 
Item will give you following abilities:  NOBITS
Item is: MAGIC NODROP ANTI-GOOD ANTI-NEUTRAL TWOHANDS NO-THIEF NO-MAGE ANTI-HUMAN ANTI-GREYELF ANTI-HALFELF ANTI-HALFLING
ANTI-GNOME ANTI-BARBARIAN ANTI-DROWELF ANTI-TROLL ANTI-OGRE ANTI-ILLITHID ANTI-YUANTI ANTI-LICH 
Weight: 18, Value: 500000
Type: Throwing Hammer Class: Martial
Damage:  6D4  Crit Range: 3%  Crit Bonus: 2x
Can affect you as :
    Affects : HITROLL by 3
    Affects : DAMROLL by 2
Special Effects : Chain Lightning

Duergar warrior/blackguard cant use it. (Type: Throwing Hammer ?)

**Comment by OghmaToril** [comment]
Thanks for bringing this up.  Changing it to be Type: Warhammer

**Comment by torilmud-silvanus** [comment]
Please clarify the issue regarding duergar warrior/blackguard @Fisig as far as I can tell they can wield it fine?

**Comment by Fisig** [comment]
i
You are carrying:
an intricate divination scroll
a mithril two-handed dwarven battle hammer

< 863h/670H 103v/106V |3|3|3|3|2| P: std > 
wi hammer
You can't wield that.

< 854h/670H 106v/106V |3|3|3|3|2| P: std > 
rec scroll hammer
You recite an intricate divination scroll which turns to dust in your hands.
You feel informed:
Name 'a mithril two-handed dwarven battle hammer'
Keyword 'hammer mithril handed dwarven', Item type: WEAPON
Item can be worn on:  WIELD 
Item will give you following abilities:  NOBITS
Item is: MAGIC NODROP ANTI-GOOD ANTI-NEUTRAL TWOHANDS NO-THIEF NO-MAGE ANTI-HUMAN ANTI-GREYELF ANTI-HALFELF ANTI-HALFLING
ANTI-GNOME ANTI-BARBARIAN ANTI-DROWELF ANTI-TROLL ANTI-OGRE ANTI-ILLITHID ANTI-YUANTI ANTI-LICH 
Weight: 18, Value: 500000
Type: Throwing Hammer Class: Martial
Damage:  6D4  Crit Range: 3%  Crit Bonus: 2x
Can affect you as :
    Affects : HITROLL by 3
    Affects : DAMROLL by 2
Special Effects : Chain Lightning


< 846h/670H 106v/106V |3|3|3|3|2| P: std > 

Geyreree ASSOC:: 'hole ix'

< 842h/670H 106v/106V |3|3|3|3|2| P: std > 
att

          Character attributes for Halmetalok

Level: 50   Race: Duergar   Class: Blackguard  
Age: 83 yrs / 8 mths  Size: Medium
STR: 100  AGI: 100  DEX:  90  CON: 100
POW:  52  INT:  59  WIS:  60  CHA:  51
Armor Class: 70  (100 to -100)  Agility Bonus: -15
Magic Resistance: 0 percent
Hitroll: 5   Damroll: 7
Alignment: Lawful Evil
Saving Throws: PAR[0]  ROD[0]  PET[0]  BRE[0]  SPE[0]
   Wimpy: not set

** Type: Throwing Hammer Class: Martial

**Comment by gruumsh** [comment]
This was addressed by https://github.com/torilmud/torilmud/pull/567 changes are live
