### ISSUE TITLE
"Breath missed - report buggy msg."

### ISSUE THREAD

**Issue by Gyrx** [torilmud/issues#406]
Approx 2:53PM PST

< 1238h/1238H 89v/120V |3|3|3|2|0| T: Gyrxtok TC: excellent E: tiamat EC: pretty hurt EP: std P: std
> 
OUCH!  That really did HURT!
Tiamat misses you with her claw. (x2)
Tiamat breathes a cloud of toxic gas!
Breath missed - report buggy msg.

< 1151h/1238H 89v/120V |3|3|3|2|0| T: Gyrxtok TC: few scratches E: tiamat EC: pretty hurt EP: std P:
std > 

Your wounds begin

**Comment by Gyrx** [comment]
More..



Tiamat thrusts all five heads into the air and screams in draconic fury!

< 1338h/1338H 120v/120V |3|3|3|1|1| T: Gyrxtok TC: excellent E: tiamat EC: few scratches EP: std P:
std > 

OUCH!  That really did HURT!
Tiamat misses you with her claw. (x3)
Tiamat breathes a cone of frost!
Breath missed - report buggy msg.
Tiamat breathes a massive bolt of lightning!
Breath missed - report buggy msg.
Your attack is partially absorbed by Tiamat's scales!

< 1267h/1338H 120v/120V |3|3|3|1|1| T: Gyrxtok TC: few scratches E: tiamat EC: few scratches EP: std
P: std >

**Comment by Gyrx** [comment]
north.

< 1238h/1238H 109v/120V |3|3|3|0|2| T: Gyrxtok TC: excellent E: tiamat EC: few wounds EP: std P: std
> 
OUCH!  That really did HURT!
Tiamat misses you with her claw. (x3)
Attack missed - report buggy msg.
You are slammed down on the ground!

< 1153h/1238H 110v/120V |

**Comment by shevarash** [comment]
These attacks all had placeholder messages for attacks that did zero damage. I gave them all messages.
