### ISSUE TITLE
Deathknell blind proc lasts 25 seconds now, down from old length

### ISSUE THREAD

**Issue by torkur** [torilmud/issues#407]
Just noticed this tonight on my level 42 Drow Blackguard.  I petitioned in case it was an intentional change and it doesn't sound like it.  Oghma said he hasn't seen proc changes to it for a long while. I know the old blind proc on deathknell was same duration as cleric blind, so not sure if this was meant to change with all the powers stuff or was broken accidentally.

**Comment by GeneralGormal** [comment]
Deathknell needs a nerf though.

**Comment by shevarash** [comment]
We haven't updated this proc in some time. What do you remember the old duration as being?

**Comment by torkur** [comment]
It used to be just like the normal casted blind spell....think it was 1 minute. If it hasn't been changed maybe something else affected it....like low spellcast skill lowering duration or lack of spellfocus worn or something?
