### ISSUE TITLE
Powers Targeting (agg/all)

### ISSUE THREAD

**Issue by GeneralGormal** [torilmud/issues#408]
'powername all' only attacks everything in the room if you're already fighting.

An Elegant Home
Exits: -S
A lithe commoner wanders about gracefully.
A graceful commoner stands here proudly.

< 898h/898H 107v/107V |vs +|ts +|brs +|trs +|wws +|lh +|dc +| |3|3|3|3|2| >
< P: std > wws all
No target for your power could be found!

< 898h/898H 107v/107V |vs +|ts +|brs +|trs +|wws +|lh +|dc +| |3|3|3|3|2| >
< P: std > wws room
No target for your power could be found!

< 898h/898H 107v/107V |vs +|ts +|brs +|trs +|wws +|lh +|dc +| |3|3|3|3|2| >
< P: std > kill commoner
Your massive slash barely wounds a lithe commoner.

< 898h/898H 107v/107V |vs +|ts +|brs +|trs +|wws +|lh +|dc +| |3|3|3|3|2| >
< T: Rargas TC: excellent E: lithe EC: few scratches EP: std P: std > 
You parry a lithe commoner's lunge at you.
A lithe commoner misses you with her hit.
A lithe commoner dodges your futile attack.
Your massive slash barely wounds a lithe commoner.

< 898h/898H 107v/107V |vs +|ts +|brs +|trs +|wws +|lh +|dc +| |3|3|3|3|2| >
< T: Rargas TC: excellent E: lithe EC: few scratches EP: std P: std > wws all
Brilliant holy light explodes around you as you swing your weapon in a full circle!
A lithe commoner is struck by your dazzling full-circle smite!
A graceful commoner is struck by your dazzling full-circle smite!
You parry a graceful commoner's lunge at you.

**Comment by shevarash** [comment]
I believe this was fixed awhile ago. Please re-open if not.
