### ISSUE TITLE
powers fumble and stumble add dex/agi to the mob not subtract

### ISSUE THREAD

**Issue by Lilithelle** [torilmud/issues#409]
Line 33 from fumble.json
          "name": "Dex Target",
          "value": 30,
          "target": "Modifier"
Line 33 from stumble.json
          "name": "Agi Target",
          "value": 30,
          "target": "Modifier"
Where as the ray of enfeeblement json shows a negative modifier, tested it on test mud, fumble does raise mob dex.

**Comment by OghmaToril** [comment]
Good eye!  This will be fixed on future code move.
