### ISSUE TITLE
reported: group barkskin rolls over ac

### ISSUE THREAD

**Issue by gruumsh** [torilmud/issues#41]
> Bustit GCC: 'rolling ac over'
> Hilol GCC: 'group cast barkskin rolled me over,  however single target did not '
> Kiper GCC: 'the specific numbers for me: I had -64 ac and used an armor scroll to be at -84 ac.  Druid barkskin put me at +100ac.  I dispelled, used an armor scroll, and cast barkskin on myself and i had -100ac :)'
> Kiper GCC: '*druid group barkskin'

the only thing i can see different from power d barkskin and power d group barkskin is this line:
on barkskin
Status           : armor by 1 for 25 minutes   
on group barkskin
> Status           : armor by 0 for 25 minutes

**Comment by shevarash** [comment]
This has been fixed.
