### ISSUE TITLE
Permanent blind proc in Dread Mist

### ISSUE THREAD

**Issue by Lilithelle** [torilmud/issues#411]
In a blur of feathers, a raven swoops down pecking at your face!
Raising your hands up clumsily, you are too slow to defend yourself.
Perching on your face, it pecks relentlessly, feasting savagely on you.
Jabbing its beak repeatedly, a raven gouges out your eyes in a spray of blood!
You have been blinded!

Status of Gurru
---------------------------------------------------------------------------

Effects
---------------------------------------------------------------------------
blind                     detect evil               detect good               
detect invisible          farsee                    fly                       
haste                     infravision               no summon                 
sense life                slow poison               

Spells
---------------------------------------------------------------------------
fly                       ( 64:00)   

< 860h/860H 141v/141V > hd
You shake off your adverse conditions in a burst of willpower.

< 860h/860H 141v/141V > l
You can't see a thing, you're blinded!

< 860h/860H 141v/141V > camp
On the list of the most dangerous places to set up camp, this place ranks somewhere
between a red dragon's lair and inside a gelatinous cube. Find somewhere else to camp!

No duration, wasn't cured by heroic defiance, can't camp out to get rid of it, can only leave the zone by "enter mist" which you can't do while blind.

**Comment by GeneralGormal** [comment]
There are 4-5 different NPC-blind-powers in Dreadmist (only the dire raven one is permanent) that can only be cleared by--specifically--the powers version of cure blind.  The NPC powers need to apply a standard blind/pwb so they can be cured with other spells.

**Comment by torilmud-silvanus** [comment]
1. The raven blind is intended to be a "mundane" effect, and thus not be able to be removed by _dispel magic_. Otherwise "curing" approaches should all work. 

(I know this "mundane blind" is harsh/annoying, and I'm open to discussing it, but for the purpose of this ticket I think there are some actual bugs here that need addressing and I want to make the distinction and separate discussion of changing that aspect from the actual bugs)

2. All other blind powers in this zone should function as any other blindness spell. So any inconsistencies there are bugs.

**Comment by torilmud-silvanus** [comment]
To staff working on this issue: See https://github.com/torilmud/torilmud/issues/558 and particularly the "Further testing" section to see details on the issues with certain blind sources vs certain blind removal approaches

**Comment by GeneralGormal** [comment]
Mundane stuff is fine, but currently only one 'curing' approach works for all blind procs, including raven. New melee blind clearing skills don't work, heal/fheal don't work, etc.

**Comment by torilmud-silvanus** [comment]
Yeah below were my findings during testing:
- While testing the nuances of this I have found the following: Certain blindness powers can _only be cured by Cure Blindness_. 
  - Actual: Nyth Flare/PWB's perm blind is not healed by Heal, Full Heal, nor Group Heal. Only Cure Blindness seems to be healing all blindness effects

**Comment by Lilithelle** [comment]
Every other blind effect in game has a duration, what I object to is there is no way to remove it as a warrior. Heroic defiance didn't work, can't camp in the zone, can't leave the zone because that takes "enter"ing something. So all you can do is ask someone to come fix you, basically every other effect either ends or you can so something about it (except some charms, those can be annoying). 
Lilithelle

**Comment by GeneralGormal** [comment]
As far as I'm aware, only the dire raven's blind is permanent. The nyth and other blind procs (I forget exactly which mobs have them, but there are at least 4 different blind procs in the zone) should have a duration. If they new powers and healing spells would clear them all, it'd be amazing, though I could get behind leaving the dire raven PWB more difficult to remove.

**Comment by Lilithelle** [comment]
sure, but give it a duration, I'm a troll, I have regeneration, but it never goes away. 
Lilithelle
