### ISSUE TITLE
VIP bug

### ISSUE THREAD

**Issue by vitaladsr** [torilmud/issues#414]
Seems to be hurting me whenever the person I am guard'ing's weapon procs. It also seems super out of whack .. I am taking more than 25% of the damage .. or there is something very not right about this skill.

This was a 2 man group I was in: (You can see how my hp dropped 100 when Geyreree uses a power on the Sultan) (Then you can see how, after only 1 round I am down to 100 hp .. then dead) .. only fighting 3 mobs.

Geyreree flies in from the south.

< 507h/806H 159v/139V >
< P: std > 
Geyreree snaps into visibility.
Geyreree's weapon unleashes a torrent of dark power as she strikes The Sultan, knocking him to the ground.
You move to protect Geyreree and absorb some of her damage.

< 407h/806H 159v/139V >
< P: std > 
You move to protect Geyreree and absorb some of her damage.
An elite palace guard misses Geyreree with his beat.

< 408h/806H 159v/139V >
< T: Mugo TC: few wounds E: elite EC: excellent EP: std P: std > 

You move to protect Geyreree and absorb some of her damage.
Geyreree looks really sick, and shivers uncomfortably.
An elite palace guard blocks your futile attempt with his shield!
An elite palace guard blocks your futile attempt with his shield!
An elite palace guard dodges your futile attack.
You parry an elite palace guard's lunge at you.
You partially deflect an elite palace guard's lunge at you.
Upon being struck, a mirror image of Mugo shatters into a million particles of light!
You partially deflect an elite palace guard's lunge at you.
Upon being struck, a mirror image of Mugo shatters into a million particles of light!
You move to protect Geyreree and absorb some of her damage.
An elite palace guard misses Geyreree with his beat.
You move to protect Geyreree and absorb some of her damage.
An elite palace guard misses Geyreree with his beat.
You move to protect Geyreree and absorb some of her damage.
An elite palace guard misses Geyreree with his beat.
Geyreree barely wounds The Sultan with her massive slash.
You move to protect Geyreree and absorb some of her damage.
Geyreree barely wounds The Sultan with her massive slash.
You move to protect Geyreree and absorb some of her damage.
Geyreree barely wounds The Sultan with her massive slash.
You move to protect Geyreree and absorb some of her damage.
The Sultan's a burning star-metal falchion explodes in a burst of searing flames!
You move to protect Geyreree and absorb some of her damage.
You move to protect Geyreree and absorb some of her damage.
Geyreree parries The Sultan's lunge at her.
You move to protect Geyreree and absorb some of her damage.
The Sultan misses Geyreree with his flaming slash.
You move to protect Geyreree and absorb some of her damage.
Geyreree parries The Sultan's lunge at her.

< 190h/806H 159v/139V >

**Comment by cmoncrief** [comment]
The issue here was that the damage was being transferred before the fireshield damage was being reduced. I've fixed it by moving the damage transfer to _after_ all of the globe, resist, etc checks so that the warrior using VIP will take 25% of the damage that the target actually takes, not the theoretical damage that they _could_ have taken.

**Comment by shevarash** [comment]
The issue here was that the damage was being transferred before the fireshield damage was being reduced. I've fixed it by moving the damage transfer to after all of the globe, resist, etc checks so that the warrior using VIP will take 25% of the damage that the target actually takes, not the theoretical damage that they could have taken.

**Comment by vitaladsr** [comment]
Thanks man!! Merry Xmas .. Next up Ogre Dires?!
