### ISSUE TITLE
Additional mileage, Remort

### ISSUE THREAD

**Issue by vitaladsr** [torilmud/issues#415]
There are some race/class combos left out, common in AD&D campaigns that would make sense. Why not have a level 50 remort (for classes) .. would be nifty to quest a hybrid warrior/ranger for dwarf/halfling at lvl 50 ... i would imagine it would be easy to create dual classes War-Ranger for example, or a Sorc-Rogue. Though balancing always the biggest concern.

**Comment by CountVooku** [comment]
I never say never. That being said. This will never happen.
