### ISSUE TITLE
Scardale Equipment Load Limits

### ISSUE THREAD

**Issue by GeneralGormal** [torilmud/issues#417]
It's a real shame for newbies that the entire Scardale loot table is usually sitting on the Silverymoon vendor because experienced players run through it and take it outside.  I think it's a bit ridiculous that the newbie zone eq is maxload 1.

**Comment by torilmud-silvanus** [comment]
Suggestion accepted, maxloads will be increased / effectively removed. May include some rareload chances to vary the loads some, but acquiring these items will no longer be boot dependent. This will be particularly nice for the Scardale quests which often appear to be undoable unless you know to do runs on reboot.

**Comment by GeneralGormal** [comment]
I think some of the knights/rangers are not guaranteed to load.

**Comment by torilmud-silvanus** [comment]
I'm sorry can you clarify what the above statement meant @GeneralGormal ?

**Comment by GeneralGormal** [comment]
Just pointing out that I think there is already some rarity built into the zone, though I could be wrong.
