### ISSUE TITLE
Torin  Ancient Mithril warhammer

### ISSUE THREAD

**Issue by odinson1975** [torilmud/issues#418]
It keeps burning me even thought I am a dwarven ranger, we changed it after dwarfs could be paladins, can we do this for dwarven rangers?

Thanks Rhazien

**Comment by torilmud-silvanus** [comment]
Thanks for bringing it up for review, but I'm afraid we will be keeping this item as is for now. The current intent is that it is usable by Tanks and Healers only, and not usable by Hitters.
