### ISSUE TITLE
a runed ironwood sheaf arrow

### ISSUE THREAD

**Issue by GeneralGormal** [torilmud/issues#419]
These got overlooked with the recent arrow changes.  To get them you need a Muspelheim rare to open the lair and then fight 3x red dragons together and a then single, perma-shielded ancient red in a silent room.

**Comment by ghost** [comment]
i'm with jake on this, it's of the weaker dice/bonus arrow class, but it is def not farmable, should get some kind of enchantment

**Comment by gruumsh** [comment]
Ok, open to suggestions. I think last time jake and i discussed this we talked about flaming burst.

**Comment by shevarash** [comment]
This is a duplicate of a newer issue. We'll track it with that one and close this.
