### ISSUE TITLE
Powers links not displaying in docs

### ISSUE THREAD

**Issue by vitaladsr** [torilmud/issues#420]
Most of the links in this document don't work: https://github.com/torilmud/docs/wiki/Powers

Under "Power Settings"

restricts: Restrictions that determine how the power can be used. This is an array that takes as many values as needed. [Add link to full list]

targets: Determines the valid targets for this power. This tells the game whether this power is targeted at characters, objects, rooms, etc, as well as where they have to be in relation to the user. [Link to full list]
implement: An array that specifies what weapons, shields, etc need to be present in order to use this power. For instance, the bash power requires a shield implement. [Link to full list]
hitMods: Modifiers to the hit chances for this power. This is an array of modifier objects, which have a name and a value. [Link to full list]
raceAllow: A race pattern array specifying races that can use this power. [Link to race patterns section]
raceRestrictTarget: A race pattern array specifying races that can not be targeted with this power. [Link to race patterns section]

Under "Effects"

condition: The condition type to be used by this effect. [Link to conditions]

damageType: The damage type for this effect. [Link to damage types]

position: A character position to be set for this effect. This is a number, and the values can be found at [Link to positions]

statusFlags: Affected flags to be used by this effect. This is an array of multiple values. [Link to affected flags]
location: The object apply location to be used by this effect. [Link to applys]

roomFlags: Room flags to be used by this effect. [Link to room flags]

effectOptions: Various options for effects. Some are universal, others are used only by specific effects. [Link to effect options]

triggers: Trigger types for advanced powers. [Link to trigger types]

raceRestrict: A race pattern array specifying races that can not use this effect. [Link to race patterns section]

raceAllow: A race pattern array specifying races that can use this effect. [Link to race patterns section]

raceRestrictTarget: A race pattern array specifying races that can not be targeted with this effect. [Link to race patterns section]

raceAllowTarget: A race pattern array specifying races that can be targeted with this effect. [Link to race patterns section]

effectMods: An array of effect modifier objects that consist of a name, value and target. These are used to modify saving throws, modifiers, and durations. [link to effect mod section]

saveData: A saving throw object that consists of a saveType, saveChance and saveMod. [Link to saving throws section]

timerData: A timer object that consists of timerDuration, timerCycles, and timerOptions. [Link to timers section]

messages: Messages object that controls how this effect is communicated. [Link to messages section]

**Comment by shevarash** [comment]
The docs are under construction. The [Link to trigger types] is where I've noted that we need to add the link _once those pages exist_. :)
