### ISSUE TITLE
Cannot look chapter7 using newbie book.

### ISSUE THREAD

**Issue by Lilithelle** [torilmud/issues#421]
You are carrying:
a book titled, 'Newbie Help' (illuminating)

l book
This book was created to try and help new players learn a little bit about the mud
and to take any confusion away from being a new player.

You can also type 'help' or 'help <command>' where <command> is replaced
with that ever you want help text for.

--- Index ---
Chapter 1: Movement
Chapter 2: Communication
Chapter 3: Information
Chapter 4: Objects
Chapter 5: Combat
Chapter 6: Utility
Chapter 7: Monetary
Chapter 8: Common help subjects

To read a chapter type 'read chapter1' or whatever the chapter number was. You
can also type 'read movement' etc, to read chapter 1 and so on.

l chapter7
You do not see that here.

Looks at least like chapter7 is on the keyword list, so not sure what the issue is, but this is an excerpt of the extra description keyword list:
EXCHANGE BANKS BALANCE DEPOSIT WITHDRAW
E
chapter7 monetary money

What is the lone E?

**Comment by torilmud-silvanus** [comment]
Will be fixed by https://github.com/torilmud/torilmud/pull/577
