### ISSUE TITLE
Halfelf...

### ISSUE THREAD

**Issue by CountVooku** [torilmud/issues#422]
I've seen like 1 person play halfelf in the nearly 2 years I've been back. How about some halfelf love? 105 agi is bleh. Halforc is 115. Shouldn't halfelf is at least the same?

**Comment by shevarash** [comment]
Half elfs, and many other races, are due for some adjustments. I don't have plans for doing that at the moment as classes are the top priority, but we will revisit this in the future. Thanks for bringing it up.
