### ISSUE TITLE
Power Version of Abi Dalzims Horrid Wilting Does not do extra damage to plants.

### ISSUE THREAD

**Issue by Casorus** [torilmud/issues#424]
< 639h/639H 120v/120V P: std > 
abi fern
< 639h/639H 120v/120V P: std >

You start chanting... [Casting: ABI FERN (Abi Dalzims Horrid Wilting)]

< 639h/639H 120v/120V P: std > 

An overgrown fern misses the spectre of a guardian of the ebony knights with its smash.
An overgrown fern misses the spectre of a guardian of the ebony knights with its smash.
An overgrown fern dodges the spectre of a guardian of the ebony knights's attack.
The spectre of a guardian of the ebony knights barely wounds an overgrown fern with its powerful 
drain.

< 639h/639H 120v/120V P: std > 

Casting: Abi Dalzims Horrid Wilting *****

< 639h/639H 120v/120V P: std > 

Casting: Abi Dalzims Horrid Wilting ***

< 639h/639H 120v/120V P: std > 

An overgrown fern misses the spectre of a guardian of the ebony knights with its smash.
An overgrown fern misses the spectre of a guardian of the ebony knights with its smash.
The spectre of a guardian of the ebony knights barely wounds an overgrown fern with its powerful 
drain.
The spectre of a guardian of the ebony knights barely wounds an overgrown fern with its mighty drain.
The spectre of a guardian of the ebony knights misses an overgrown fern with its drain.

< 639h/639H 120v/120V P: std > 
Casting: Abi Dalzims Horrid Wilting **

< 639h/639H 120v/120V P: std > 

Casting: Abi Dalzims Horrid Wilting *

< 639h/639H 120v/120V P: std > 

You complete your spell... [ ABI FERN (Abi Dalzims Horrid Wilting) ]
Your fog sucks the moisture out of an overgrown fern!

< 639h/639H 120v/120V P: std > 
c 'abi' fern

Autosaving...
The spectre of a guardian of the ebony knights dodges an overgrown fern's attack.
An overgrown fern barely wounds the spectre of a guardian of the ebony knights with its average 
smash.
The spectre of a guardian of the ebony knights misses an overgrown fern with its drain.
The spectre of a guardian of the ebony knights barely wounds an overgrown fern with its mighty drain.
The spectre of a guardian of the ebony knights barely wounds an overgrown fern with its awesome 
drain.

< 639h/639H 120v/120V P: std >

< 639h/639H 120v/120V P: std >

You start chanting... [Casting: C 'ABI' FERN (Abi)]

< 639h/639H 120v/120V P: std > 

Casting: Abi Dalzims Horrid Wilting **

< 639h/639H 120v/120V P: std > 

Casting: Abi Dalzims Horrid Wilting *

< 639h/639H 120v/120V P: std > 

You complete your spell... [ C 'ABI' FERN (Abi) ]
**Your wilting causes an overgrown fern to HOWL in pain and anger.**
Your fog sucks the moisture out of an overgrown fern!
An overgrown fern barely wounds the spectre of a guardian of the ebony knights with its average 
smash.
An overgrown fern misses the spectre of a guardian of the ebony knights with its smash.
The spectre of a guardian of the ebony knights barely wounds an overgrown fern with its strong drain.

< 639h/639H 120v/120V P: std >

**Comment by shevarash** [comment]
Rather than just have a hardcoded race damage modifier, it may be wiser to use damage/resist types.

**Comment by shevarash** [comment]
This will be address in an upcoming Necromancer class overhaul.
