### ISSUE TITLE
a mithril headed dwarven waraxe graven with runes 

### ISSUE THREAD

**Issue by GeneralGormal** [torilmud/issues#426]
This quite rare axe from Choking Palace has become almost worthless with the new powers system.  It procs breach for everyone, which is awesome, but the multi-hit Fury component only works if your adjusted strength is above some threshold (anything stronger than human gets it for sure).  The problem is that in order to prevent it from proccing off of itself, the axe is designed to not proc when the user is stunned, and it stuns you after a Fury proc.  This now prevents you from using a power and spell during the next combat round, which is usually a net damage and survivability loss. The hit/dam and weapon enchantments are awesome, but the damage proc actually reduces it's output significantly and endangers your group since you can't rescue, heal, or anything.

Can we please remove the stun and code it to simply not proc off itself in some other way? It's one of the rarest weapons in the game (way harder to get than Valhalla) and now I don't believe it's worth using on any class.

Name 'a mithril headed dwarven waraxe graven with runes'
Keyword 'axe waraxe runes', Item type: WEAPON
Item can be worn on:  WIELD 
Item will give you following abilities:  NOBITS
Item is: MAGIC FLOAT NOBURN NO-CLERIC NO-THIEF NO-MAGE NOBITS
Weight: 10, Value: 1000000
Type: Dwarven Waraxe Class: Exotic
Damage:  4D3  Crit Range: 3%  Crit Bonus: 3x
Enchantments:
    Type: Keen             Damage: 100% Frequency: 100% Modifier: 0   Duration: 0  
    Type: Ghost Touch      Damage: 100% Frequency: 100% Modifier: 0   Duration: 0  

Can affect you as :
    Affects : HITROLL by 5
    Affects : DAMROLL by 8
Special Effects : Fury
                  Breach

**Comment by CountVooku** [comment]
I've been back for 2 years and haven't seen the note load yet. I think it did once when I wasn't on.

**Comment by jokkmeister** [comment]
Yeah please fix the procs so it is useful again.

**Comment by Dartan82** [comment]
Please fix :(

**Comment by CountVooku** [comment]
After doing a bunch of testing, it does need some love. Not being able to perform a powers move the following round due to the stun is an overall damage reduction when compared to the damage the powers could have done.

**Comment by gruumsh** [comment]
Fixed & merged, see patch notes: http://www.torilmud.com/news/patch-notes-9-27-2019/
