### ISSUE TITLE
enhance: Waterdeep elites repop order

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#428]
It would be nice if the elite guards/dockmasters in Waterdeep could be changed to repop to their assigned rooms.

Currently, if you kill half of them and repop hits, the dead ones all repop to the same room. All of them have to be dead prior to pop to repop to the correct rooms.

**Comment by GeneralGormal** [comment]
There has always been a proper order to kill elites in order to make them pop correctly.  People could bot less and play more and figure these things out, but since this request is to facilitate more botting...

**Comment by Nyyrazzilyss** [comment]
Proper order sure, but it's still dependent on poptime. You have to either constantly check for repop, or know when repop is. If you follow the order and miss pop, the next mob you kill will take them out of order.

The intent is to encourage more people to return to Waterdeep. When's the last time anyone has killed the elites?

**Comment by shevarash** [comment]
This is a fundamental issue with the way Toril loads mobs. I don't think that drawing people to Waterdeep is the right catalyst to address it though. Closing, but feel free to make a counter argument.

**Comment by Nyyrazzilyss** [comment]
I understand that it is due to how the load process works. I think what I was hoping for though wasn't a change in the load process, but working with it to get around it :)

I'm guessing the problem would be related to all elite guards having identical vnum identifiers. Perhaps copying the entry with a different vnum so each load room has a 'unique' elite that loads there? Granted this would probably interfere with trophy (not that anyone is trophied on elites anymore)
