### ISSUE TITLE
Dimension Door has a relocate failure

### ISSUE THREAD

**Issue by Adriorn** [torilmud/issues#43]
the dimension door power unlike the old version does have a chance to put you in the wrong place, I don't know if that's intended or not.

**Comment by dnavarro** [comment]
I am assuming that Powers are supposed to be basically identical, so I am considering this a bug, unless Shev informs me otherwise

**Comment by shevarash** [comment]
Definitely a bug.

**Comment by cmoncrief** [comment]
This has been fixed.
