### ISSUE TITLE
searching rooms, corpses, containers

### ISSUE THREAD

**Issue by vitaladsr** [torilmud/issues#432]
From my due diligence in discussing searching w other players that have a variety of races the consensus is that searching seemed to get even slower somehow that it was in the past (takes more searches in general, even with grey/drow/snake).

I really enjoy figuring things out and searching for hidden things but sometimes it is such a buzzkill to have to keep trying over and over, especially when your searching every room in a zone, every corpses for a key. Perhaps its time to revise that aspect a little. Thoughts?

**Comment by GeneralGormal** [comment]
Some kind of take 20 option would own.

**Comment by shevarash** [comment]
I agree - searching is due for some modernization.

**Comment by Inames** [comment]
Make it an int/skill based check and make it work really well at high skill. like bandage! anyone can try it, but you gotta work at it to be good at it! Make it operate similarly to how it does now, but at higher skill it should succeed (find the items, or determine there is nothing there) in the first 1 or 2 attempts. whereas at lower skill, it should be as ineffective/random as it is now. So anyone can use the skill, more intelligent characters will be more successful at the skill in the early stages, but anyone can spend the time and train themselves to be successful investigators.

**Comment by shevarash** [comment]
This was done!
