### ISSUE TITLE
Charisma for Bards

### ISSUE THREAD

**Issue by laiyna** [torilmud/issues#433]
Charisma is main stat for bards, but is barely doing anything, except making a good vendor trash alt.

Give charisma a small bonus:
- regen psp for bards maybe?
- nodges you make in charisma is the amount of combat rounds your song lingers in a room after death?
- amount of bonus psp for bards?
- AC bonus for bards (who wants to hit that beauty) ?
- bigger (noticible) bonus on songs?

Now a bard highest stat and all maxCha items dont do much... And I gladly want to make an character with different equipment choices, then going wizzie style....

**Comment by shevarash** [comment]
You're correct, charisma does not do very much for bards. We are planning on overhauling the Bard classes, but I don't have any kind of timeline for that. Great ideas though - I'll note those for when we redo the class.
