### ISSUE TITLE
dire raiders

### ISSUE THREAD

**Issue by vitaladsr** [torilmud/issues#437]
some ideas here! You could drop the word "dire" and create a class called raider .. kinda an evil ranger pretty much.
An alternate to rewriting the mounted combat system would be to summon a pet (non mount) .. maybe something that has some kind of synergetic power and or some powers that require that pet to be in the room and alive.
Also .. dire wolf is the favorite pet of Grolantor the Ogre God .. just a hint there!

**Comment by shevarash** [comment]
Great ideas - thanks!
