### ISSUE TITLE
Starting Equipment - Ranger

### ISSUE THREAD

**Issue by belkyrnn** [torilmud/issues#440]
Created a new character as a ranger and logged game with 2x longsword wielded (dual wield) plus wearing a shield at the same time.

**Comment by Nyyrazzilyss** [comment]
You are using:
<worn on head>       a smooth wooden helmet
<worn on body>       a soft cloth tunic
<held as shield>     a small bark shield
<worn on hands>      a pair of mottled brown gloves
<primary weapon>     a slender longsword
<secondary weapon>   a slender longsword
<worn on legs>       a pair of soft cloth pants
<worn on feet>       a pair of soft leather boots

**Comment by shevarash** [comment]
This should be fixed by removing the shield from the newbie set as Rangers don't need it at all.

**Comment by shevarash** [comment]
Removed shields from all ranger newbie loads.
