### ISSUE TITLE
There are no active areas gods

### ISSUE THREAD

**Issue by vitaladsr** [torilmud/issues#441]
There are at least two reputable (not first time) creators who have had finished content (one fully approved zone) in the cue for well over 3 months. There is no response from Silvanus, Gruumsh and very very little from Dugmaren who all have much more important things to do of course. They should at least retire (or let you know they are not going to be able to help anytime soon) so you can figure out somebody who has time that can help you immediately. New content is so important to any online game and it's sad to have so many willing and capable that are unable to help because there are no staff members.

**Comment by shevarash** [comment]
You're right - new content is really important. I'm aware that we've had some issues getting new content into the game, and I'm actively working on solving the problems and making that content live.

To your point about specific areas staff members, all I can say is that we're all unpaid volunteers and the time that we _wish_ we could spend on Toril doesn't often match up to the time that our real lives and jobs allow us. 

Thanks for bringing this up. I'm happy to be transparent about the process. I'm going to close the issue, but please feel free to keep discussing it here.
