### ISSUE TITLE
Arch-Magi Staff Does not Absorb spells

### ISSUE THREAD

**Issue by Casorus** [torilmud/issues#444]
Sometimes works, absorbed earthquake once, but both prismatic spray and incendiary cloud went right past it.

**Comment by Casorus** [comment]
< 675h/675H 120v/120V P: std > 
ass spectre
You assist the spectre of a lieutenant of the Knights in Silver heroically.
You miss a soldier of the Knights in Silver with your hit.

< 675h/675H 120v/120V T: spectre TC: excellent E: soldier EC: few scratches EP: std P: std > 

A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.

< 675h/675H 120v/120V T: spectre TC: excellent E: soldier EC: few scratches EP: std P: std > 

A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver barely wounds the spectre of a lieutenant of the Knights in Silver with his average slash.
You miss a soldier of the Knights in Silver with your hit.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
The spectre of a human hunter misses a soldier of the Knights in Silver with its drain.
A soldier of the Knights in Silver barely wounds the spectre of a human hunter with his average slash.
A soldier of the Knights in Silver barely wounds the spectre of a human hunter with his average slash.
A soldier of the Knights in Silver blocks the spectre of a lieutenant of the Knights in Silver's attack with his shield!
A soldier of the Knights in Silver blocks the spectre of a lieutenant of the Knights in Silver's attack with his shield!
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver barely wounds the spectre of a lieutenant of the Knights in Silver with his average slash.
A soldier of the Knights in Silver barely wounds the spectre of a lieutenant of the Knights in Silver with his average slash.

< 675h/675H 120v/120V T: spectre TC: excellent E: soldier EC: few scratches EP: std P: std > 
< 675h/675H 120v/120V T: spectre TC: excellent E: soldier EC: few scratches EP: std P: std > 
say Protect me
Your staff sparks painfully in your hand.

< 675h/675H 120v/120V T: spectre TC: excellent E: soldier EC: few scratches EP: std P: std > 
say Protect me
Your staff sparks painfully in your hand.

< 675h/675H 120v/120V T: spectre TC: excellent E: soldier EC: few scratches EP: std P: std > 
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver attemps to shieldpunch you, but you dodge it in time!
You miss a soldier of the Knights in Silver with your hit.
A soldier of the Knights in Silver barely wounds the spectre of a lieutenant of the Knights in Silver with his average slash.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver attemps to shieldpunch you, but you dodge it in time!
The spectre of a human hunter misses a soldier of the Knights in Silver with its drain.
The spectre of a human hunter dodges a soldier of the Knights in Silver's attack.
The spectre of a lieutenant of the Knights in Silver misses a soldier of the Knights in Silver with its drain.
A soldier of the Knights in Silver's attack only grazes the spectre of a lieutenant of the Knights in Silver as it dodges aside!
A soldier of the Knights in Silver barely wounds the spectre of a lieutenant of the Knights in Silver with his weak slash.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.

say Protect me
< 675h/675H 120v/120V T: spectre TC: excellent E: soldier EC: few scratches EP: std P: std > 
Your staff sparks painfully in your hand.

say Protect me
< 675h/675H 120v/120V T: spectre TC: excellent E: soldier EC: few scratches EP: std P: std > 
say Protect me
Your staff sparks painfully in your hand.
say Protect me

< 675h/675H 120v/120V T: spectre TC: excellent E: soldier EC: few scratches EP: std P: std >

A mage in the Spellguard flies in from the south.
Your staff sparks painfully in your hand.

< 675h/675H 120v/120V T: spectre TC: excellent E: soldier EC: few scratches EP: std P: std >

A mage in the Spellguard misses the spectre of a lieutenant of the Knights in Silver with her hit.
Your staff sparks painfully in your hand.

< 675h/675H 120v/120V T: spectre TC: excellent E: soldier EC: few scratches EP: std P: std > 

A mage in the Spellguard misses the spectre of a lieutenant of the Knights in Silver with her hit.
The spectre of a lieutenant of the Knights in Silver dodges a mage in the Spellguard's attack.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver barely wounds the spectre of a lieutenant of the Knights in Silver with his average slash.
You miss a soldier of the Knights in Silver with your hit.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver barely wounds the spectre of a lieutenant of the Knights in Silver with his average slash.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver barely wounds the spectre of a human hunter with his average slash.
A soldier of the Knights in Silver's attack only grazes the spectre of a human hunter as it dodges aside!
A soldier of the Knights in Silver barely wounds the spectre of a human hunter with his weak slash.
The spectre of a lieutenant of the Knights in Silver misses a soldier of the Knights in Silver with its drain.
A soldier of the Knights in Silver partially blocks the spectre of a lieutenant of the Knights in Silver's attack with his shield!
The spectre of a lieutenant of the Knights in Silver barely wounds a soldier of the Knights in Silver with its average drain.
The spectre of a lieutenant of the Knights in Silver dodges a soldier of the Knights in Silver's attack.
A soldier of the Knights in Silver barely wounds the spectre of a lieutenant of the Knights in Silver with his average slash.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.

< 675h/675H 120v/120V T: spectre TC: excellent E: soldier EC: few scratches EP: std P: std > 
Your staff sparks painfully in your hand.

< 675h/675H 120v/120V T: spectre TC: excellent E: soldier EC: few scratches EP: std P: std > 

A mage in the Spellguard misses the spectre of a lieutenant of the Knights in Silver with her hit.
A mage in the Spellguard's attack only grazes the spectre of a lieutenant of the Knights in Silver as it dodges aside!
A mage in the Spellguard barely wounds the spectre of a lieutenant of the Knights in Silver with her weak hit.
A mage in the Spellguard starts casting an offensive spell called 'prismatic spray'.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver attemps to shieldpunch you, but you dodge it in time!
You miss a soldier of the Knights in Silver with your hit.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver barely wounds the spectre of a lieutenant of the Knights in Silver with his average slash.
A soldier of the Knights in Silver's attack only grazes the spectre of a lieutenant of the Knights in Silver as it dodges aside!
A soldier of the Knights in Silver barely wounds the spectre of a lieutenant of the Knights in Silver with his weak slash.
A soldier of the Knights in Silver attemps to shieldpunch you, but you dodge it in time!
The spectre of a human hunter barely wounds a soldier of the Knights in Silver with its powerful drain.
A soldier of the Knights in Silver barely wounds the spectre of a human hunter with his average slash.
A soldier of the Knights in Silver partially blocks the spectre of a lieutenant of the Knights in Silver's attack with his shield!
The spectre of a lieutenant of the Knights in Silver barely wounds a soldier of the Knights in Silver with its average drain.
The spectre of a lieutenant of the Knights in Silver tears into a soldier of the Knights in Silver, leaving him quivering in fear!
A soldier of the Knights in Silver blocks the spectre of a lieutenant of the Knights in Silver's attack with his shield!
A soldier of the Knights in Silver barely wounds the spectre of a lieutenant of the Knights in Silver with his average slash.
A soldier of the Knights in Silver slightly wounds the spectre of a lieutenant of the Knights in Silver with his average slash.
A soldier of the Knights in Silver barely wounds the spectre of a lieutenant of the Knights in Silver with his average slash.

rot
< 675h/675H 120v/120V T: spectre TC: few scratches E: soldier EC: few scratches EP: std P: std > 
You don't have that spell memorized. [Casting: ROT (Rot)]

< 675h/675H 120v/120V T: spectre TC: few scratches E: soldier EC: few scratches EP: std P: std > 
lt
You start chanting... [Casting: LT (Lich Touch)]

< 675h/675H 120v/120V T: spectre TC: few scratches E: soldier EC: few scratches EP: std P: std > 

The mage of the Spellguard fights with an excited vigor.

< 675h/675H 120v/120V T: spectre TC: few scratches E: soldier EC: few scratches EP: std P: std > 

A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver misses the spectre of a human hunter with his slash.
A soldier of the Knights in Silver barely wounds the spectre of a human hunter with his average slash.
The spectre of a lieutenant of the Knights in Silver misses a soldier of the Knights in Silver with its drain.
The spectre of a lieutenant of the Knights in Silver misses a soldier of the Knights in Silver with its drain.
A soldier of the Knights in Silver barely wounds the spectre of a lieutenant of the Knights in Silver with his weak slash.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.

< 675h/675H 120v/120V T: spectre TC: few scratches E: soldier EC: few scratches EP: std P: std > 

Casting: Lich Touch *

< 675h/675H 120v/120V T: spectre TC: few scratches E: soldier EC: few scratches EP: std P: std > 

Casting: Lich Touch 

< 675h/675H 120v/120V T: spectre TC: few scratches E: soldier EC: few scratches EP: std P: std > 

You complete your spell... [ LT (Lich Touch) ]
Your lich touch connects with a soldier of the Knights in Silver making him scream in agony!

< 675h/675H 120v/120V T: spectre TC: few scratches E: soldier EC: small wounds EP: std P: std > 

A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
The spectre of a lieutenant of the Knights in Silver dodges a soldier of the Knights in Silver's attack.
You miss a soldier of the Knights in Silver with your hit.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver dodges the spectre of a human hunter's attack.
The spectre of a human hunter barely wounds a soldier of the Knights in Silver with its powerful drain.
A soldier of the Knights in Silver misses the spectre of a human hunter with his slash.
The spectre of a lieutenant of the Knights in Silver misses a soldier of the Knights in Silver with its drain.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.

< 675h/675H 120v/120V T: spectre TC: few scratches E: soldier EC: small wounds EP: std P: std > 
< 675h/675H 120v/120V T: spectre TC: few scratches E: soldier EC: small wounds EP: std P: std > 

A mage in the Spellguard completes her spell...
A mage in the Spellguard utters the words, 'prismatic spray'.
A mage in the Spellguard sends a rainbow of prismatic spray from her hands!
A mage in the Spellguard sends a indigo shaft of light streaking towards the spectre of a lieutenant of the Knights in Silver!
A mage in the Spellguard sends a violet shaft of light streaking towards the spectre of a human hunter!
A mage in the Spellguard tries to dispel the spectre of a human hunter's magic!
And fails miserably...
A mage in the Spellguard sends a yellow shaft of light streaking towards the spectre of a human hunter!
A mage in the Spellguard sends a violet shaft of light streaking towards YOU!
A mage in the Spellguard tries to dispel your magic!
A mage in the Spellguard sends a blue shaft of light streaking towards YOU!
Your body becomes like stone as the paralyzation takes effect.
[Spellqueue cleared.]

< 675h/675H 120v/120V P: std > 

A mage in the Spellguard's attack only grazes the spectre of a lieutenant of the Knights in Silver as it dodges aside!
A mage in the Spellguard barely wounds the spectre of a lieutenant of the Knights in Silver with her weak hit.
A mage in the Spellguard barely wounds the spectre of a lieutenant of the Knights in Silver with her weak hit.
A soldier of the Knights in Silver barely wounds the spectre of a lieutenant of the Knights in Silver with his average slash.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver barely wounds the spectre of a lieutenant of the Knights in Silver with his average slash.
A soldier of the Knights in Silver's attack only grazes the spectre of a lieutenant of the Knights in Silver as it dodges aside!
A soldier of the Knights in Silver barely wounds the spectre of a lieutenant of the Knights in Silver with his weak slash.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
The spectre of a human hunter barely wounds a soldier of the Knights in Silver with its powerful drain.
A soldier of the Knights in Silver misses the spectre of a human hunter with his slash.
A soldier of the Knights in Silver barely wounds the spectre of a human hunter with his strong slash.
A soldier of the Knights in Silver attemps to shieldpunch you, but you dodge it in time!
The spectre of a lieutenant of the Knights in Silver barely wounds a soldier of the Knights in Silver with its strong drain.
A soldier of the Knights in Silver barely wounds the spectre of a lieutenant of the Knights in Silver with his average slash.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.

< 675h/675H 120v/120V P: std > 

A mage in the Spellguard misses the spectre of a lieutenant of the Knights in Silver with her hit.
A mage in the Spellguard misses the spectre of a lieutenant of the Knights in Silver with her hit.
A soldier of the Knights in Silver's attack only grazes the spectre of a lieutenant of the Knights in Silver as it dodges aside!
A soldier of the Knights in Silver barely wounds the spectre of a lieutenant of the Knights in Silver with his weak slash.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver barely wounds the spectre of a lieutenant of the Knights in Silver with his average slash.
A soldier of the Knights in Silver barely wounds the spectre of a lieutenant of the Knights in Silver with his average slash.
A soldier of the Knights in Silver misses the spectre of a human hunter with his slash.
The spectre of a lieutenant of the Knights in Silver's attack only grazes a soldier of the Knights in Silver as he dodges aside!
The spectre of a lieutenant of the Knights in Silver barely wounds a soldier of the Knights in Silver with its average drain.
The spectre of a lieutenant of the Knights in Silver barely wounds a soldier of the Knights in Silver with its mighty drain.
A soldier of the Knights in Silver's attack only grazes the spectre of a lieutenant of the Knights in Silver as it dodges aside!
A soldier of the Knights in Silver barely wounds the spectre of a lieutenant of the Knights in Silver with his weak slash.

< 675h/675H 120v/120V P: std > 
status

The spectre of a lieutenant of the Knights in Silver dodges a mage in the Spellguard's attack.
The spectre of a lieutenant of the Knights in Silver dodges a mage in the Spellguard's attack.
A mage in the Spellguard starts casting an offensive spell.
Your average hit barely wounds a mage in the Spellguard.
The spell cast by a mage in the Spellguard is partially absorbed!
You are burned as you hit a mage in the Spellguard!
A soldier of the Knights in Silver barely wounds the spectre of a lieutenant of the Knights in Silver with his average slash.
A soldier of the Knights in Silver barely wounds the spectre of a lieutenant of the Knights in Silver with his average slash.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
The spectre of a lieutenant of the Knights in Silver dodges a soldier of the Knights in Silver's attack.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.
The spectre of a human hunter barely wounds a soldier of the Knights in Silver with its powerful drain.
A soldier of the Knights in Silver barely wounds the spectre of a human hunter with his average slash.
A soldier of the Knights in Silver barely wounds the spectre of a human hunter with his average slash.
The spectre of a lieutenant of the Knights in Silver barely wounds a soldier of the Knights in Silver with its powerful drain.
The spectre of a lieutenant of the Knights in Silver dodges a soldier of the Knights in Silver's attack.
A soldier of the Knights in Silver misses the spectre of a lieutenant of the Knights in Silver with his slash.

< 670h/675H 120v/120V P: std >

You can't!  You're paralyzed to the bone.

< 670h/675H 120v/120V P: std > 

A wagon rumbles along nearby, wooden wheels clattering on the stones.

sc
< 672h/675H 120v/120V P: std > 

          Score information for Casorus

Level: 48   Race: Human   Class: Lich        
Hit points: 672(675)  Moves: 120(120)
Experience Progress: 34 % 
Coins carried:  199 platinum   196 gold   746 silver    33 copper
Coins in bank: 21424 platinum  3502 gold  5193 silver  1022 copper
Prestige: 5786   Acheron Kill Count: 0
Name status: Approved
Citizen of:   Viperstongue Outpost
Outcast from: Waterdeep, Griffon's Nest, Leuthilspar, Mithril Hall, Beluir, Ashrumite, Calimport, Baldur's Gate, Scardale
Playing time: 9 days / 7 hours / 23 minutes
Title: 
Followers:
   the spectre of a human hunter
   the spectre of a lieutenant of the Knights in Silver
Status:  Standing.
Detecting:       Invisible Heat
Enchantments:    Nondetection No Charm No Sleep No Summon
Afflicted with:  Total Paralysis

Active Spells:
--------------
major paralysis
nondetection


< 672h/675H 120v/120V P: std >

**Comment by Nyyrazzilyss** [comment]
Your staff sparks painfully in your hand.

Did perhaps you just use it in the past dozen or so minutes, and it hasn't charged yet to capture another spell?

You lift an ancient staff of the arch-magi high above your head, calling
out powerfully.  The runes flare, writhing tendrils of magical energy flowing
down the length of it and down around your body.  The captured magic within pours
out at your command, and lashes out at a small lizard.
Your God's wrath causes a small lizard to scream in pain, and its immediate death.
a small lizard is dead! R.I.P.
You receive 1 XP (0.00%) experience.
[onNetworkOutput: LOOK]
Your blood freezes as you hear the rattling death cry of a small lizard.

< 847h/847H 913p/913P 124v/124V P: std > 
protect
[onNetworkOutput: SAY Protect me]
Your staff sparks painfully in your hand.

< 847h/847H 913p/913P 124v/124V P: std > 


It only holds one spell, then that spell needs to be released. After release, it needs to charge up again before you can set it to absorb another spell.

**Comment by Casorus** [comment]
It was not holding a spell at the time, the staff sparking painfully in your hand means that it's ready to accept a spell, it hasn't been used in quite a long time.  For SOME spells it works, for others it does not.

**Comment by shevarash** [comment]
I can't say whether it's buggy or not off hand, but I'll review it to refresh myself with how it's supposed to work and get back to you.

**Comment by ghost** [comment]
sparks painfully in your hand is NOT telling you it's ready, it's telling you you need to wait for it to recharge...

sa Protect me

You whisper quietly to an ancient staff of the arch-magi, hefting it in
your hand.  Power pulses throughout its length, as the runes flare in response
to your orders.

that, is what it says when it's ready and will intercept the next aoe fired

**Comment by shevarash** [comment]
Alurissi's comment above is correct. I've update the message to be more clear that the staff is not yet ready to accept a new spell.
