### ISSUE TITLE
No Connection?

### ISSUE THREAD

**Issue by i982** [torilmud/issues#448]
tried using blowtorch: no connection
disable firewall: no connection
change ip: no connection
restart modem: no connection
tried different device with different network: no connection

servers down? or has something changed?

DisconnectEvent was just called
    
[ ALERT ] - Socket got disconnected.
            Reason: Unknown error
[ INFO ]  - Connection time: 00:04:03.856
                
[ INFO ]  - Looking up the IP address of server:torilmud.org:9999 ...
[ INFO ]  - The IP address of torilmud.org has been found. It is: 104.236.2.214
[ INFO ]  - Trying to connect to 104.236.2.214: 9999 ...
[ INFO ]  - A connection has been established successfully.
                
                
DisconnectEvent was just called
    
[ ALERT ] - Socket got disconnected.
            Reason: Unknown error
[ INFO ]  - Connection time: 00:06:46.810
                
[ INFO ]  - Looking up the IP address of server:torilmud.org:9999 ...
[ INFO ]  - The IP address of torilmud.org has been found. It is: 104.236.2.214
[ INFO ]  - Trying to connect to 104.236.2.214: 9999 ...
[ INFO ]  - A connection has been established successfully.
                
                
DisconnectEvent was just called
    
[ ALERT ] - Socket got disconnected.
            Reason: Unknown error
[ INFO ]  - Connection time: 00:00:02.896
                
[ INFO ]  - Looking up the IP address of server:torilmud.org:9999 ...
[ INFO ]  - The IP address of torilmud.org has been found. It is: 104.236.2.214
[ INFO ]  - Trying to connect to 104.236.2.214: 9999 ...
[ INFO ]  - A connection has been established successfully.
                
                
DisconnectEvent was just called
    
[ ALERT ] - Socket got disconnected.
            Reason: Unknown error
[ INFO ]  - Connection time: 00:00:02.712
                
[ INFO ]  - Looking up the IP address of server:torilmud.org:9999 ...
[ INFO ]  - The IP address of torilmud.org has been found. It is: 104.236.2.214
[ INFO ]  - Trying to connect to 104.236.2.214: 9999 ...
[ INFO ]  - A connection has been established successfully.

**Comment by vitaladsr** [comment]
Ditto .. it seems hanging on login

**Comment by shevarash** [comment]
We had some minor server related issues yesterday that are nopw all fixed. Thanks for the heads up.
