### ISSUE TITLE
Use of powers outside combat prevent fleeing from combat.

### ISSUE THREAD

**Issue by Lilithelle** [torilmud/issues#450]
ut
You grit your teeth and ignore some of your wounds as your adrenaline surges.

< 643h/860H 140v/142V |bs +|cs +|ds +|iw +|ra +|sod +| > w
Inside a Caravansary
Exits: -N -E -W
A metal lever is here on the wagon.
A circus wagon rests here.
A metal lever is here on the wagon.
A circus wagon rests here.
A metal lever is here on the wagon.
A circus wagon rests here.
A metal lever is here on the wagon.
A circus wagon rests here.
A metal lever is here on the wagon.
A circus wagon rests here.
A metal lever is here on the wagon.
A circus wagon rests here.
A metal lever is here on the wagon.
A circus wagon rests here.
A fox-like woman stands here looking around keenly.
A four legged shark-like creature stands here.
A rock-like creature stands here on its three legs.
A gnome stands here helping the doctor.
A doppelganger of Doctor Trundles stands here.
Doctor Trundles stands here looking after his wagons.
A traveling cleric stands here waiting for the show to begin.

< 649h/860H 141v/142V |bs +|cs +|ds +|iw +|ra +|sod +| > 
A doppelganger of Doctor Trundles recognizes you, and charges to attack you!
A doppelganger of Doctor Trundles severely wounds you with his massive strike.

< 573h/860H 141v/142V |bs +|cs +|ds +|iw +|ra +|sod +| T: Gurru TC: few wounds E: doppel EC: excellent > 
Tanaroo Quinson misses you with his hit.
A xorn misses you with its smash.
Someone severely wounds you with its mighty drain.
A traveling cleric misses you with her hit.

< 524h/860H 141v/142V |bs +|cs +|ds +|iw +|ra +|sod +| T: Gurru TC: few wounds E: doppel EC: excellent > 
OUCH!  That really did HURT!
A bulette misses you with its bite.
Doctor Trundles misses you with his hit.

< 435h/860H 141v/142V |bs +|cs +|ds +|iw +|ra +|sod +| T: Gurru TC: few wounds E: doppel EC: excellent > 
Doctor Trundles's attack glances off your shield, but finds its mark!
Doctor Trundles badly wounds you with his powerful hit.
You block Doctor Trundles's attack with your shield!
A bulette wounds you harshly with its awesome bite.
A bulette brutally wounds you with its massive bite.
A bulette misses you with its bite.
You stagger from a foxwoman's massive claw!
A foxwoman misses you with her claw.
You partially deflect a traveling cleric's lunge at you.
A traveling cleric wounds you harshly with her powerful hit.
You're too busy trying to gain the initiative to flee!
You stagger from someone's awesome drain!
You're too busy trying to gain the initiative to flee!
Someone misses you with its drain.
You're too busy trying to gain the initiative to flee!
Someone misses you with its drain.
You're too busy trying to gain the initiative to flee!
A xorn's attack only grazes you as you dodge aside!
You stagger from a xorn's powerful smash!
You're too busy trying to gain the initiative to flee!
A xorn misses you with its smash.
You're too busy trying to gain the initiative to flee!
A xorn nearly slays you with the force of its massive smash!
YIKES!  Another hit like that, and you've had it!!
You wish that your wounds would stop BLEEDING so much!

**Comment by shevarash** [comment]
That doesn't look right. Had you used a weapon power before the logs start? Do you about how long ago it had been?

**Comment by Lilithelle** [comment]
I think it was not recently, but I can try again.
