### ISSUE TITLE
Broken areas (per Annam)

### ISSUE THREAD

**Issue by vitaladsr** [torilmud/issues#451]
This is my fix (to do list) .. Unfortunately nobody (at the moment) seems to be available to allow me to fix these issues. Some of which are very problematic requiring IM intervention, players petitioning, others just minor. Feel free to add anything below:

Looking forward to fixing this stuff asap.

WHARK:

(Icicle bow)

1. General is not reloading for whark quest (after you turn in handshake+note from General) makes no sense because all the items are !rent and must be quested in the same boot.

2. Max load on icicle bowstring should be more than 1 (failing to load icicle bowstring when fight is popped further failing to finish the loading chain and the dragon accompanying the rider doesn't appear)

horn of sekolah (should do something)
(dragon horn from forest dragons too)
(keprum / ogre spy branch of whark)

charcharactaculmeron (dragon) not following or can be lured away from demon (heart container)

note from ogre spy to haren should pop the green dragon fight

FAANG & DT

- bozurg cave fix spider loading
- bozurg cave popping (if drow spy dies outside of the room (ie. 1d bc he flees) chimney it won’t re-pop anymore)
- change ogre-rogue to grumpy ogre (when they wake up they are aggro)

(X) elven fisherwoman sex is male (should be female)

DT chessboard .. square D7 not working

“An drow elf explores the cavern, wearing a traveling cloak.” (is race duergar) (fix grammar)

a wonderful cloak of autumn leaves (should be about body)

CPV:

o 49199 transient (skeleton key is transient)

FAANG INVASION

fix keywords on mobs
price of bone/fen arrows is ridiculously high .. allowing players to make thousands of plat by selling them

FOGWATHA RAMPAGE

fogwatha + mobs are aggro (not allowing players to easily assist him to attack Darktree)
mob keywords are bad
some theme adjustments needed (some mob names a little silly)

TROLL KING:

does dog room have to be silent?

fix open door (up) so that its !flee

PROCS:

Berserker Gauntlets .. proc drops so quickly that when you fail a switch or kill 1 out of 10 mobs (that you are still fighting) it drops ... it is only supposed to drop when you are out of combat

Demonsword seems to have problems bashing demons with new power system .. might want to check this out

**Comment by marthammor** [comment]
If you have fixes for things, or want to fix things, I'll see what I can do to help. I don't have a lot of time to go through a whole zone, and only have an hour or so late nights to try to load files and such.

**Comment by vitaladsr** [comment]
That would be cool .. I can fix all this stuff on my own, just need somebody to load the fixed ver so i can check it and then move to main once its in good shape! Best regards .. Annam

**Comment by shevarash** [comment]
I'm also available to move files around. If you send files in and copy all of us (I'm shevarash@gmail.com) we'll get your fixes loaded.

**Comment by Nyyrazzilyss** [comment]
Re; Troll King (does dog room have to be silent?)

I'm assuming you're talking solitary confinement - I have no issue with it being silent/or potentially not, however: Shouldn't this room be !tele? I can teleport into that room fairly quickly as an illithid, and then wormhole in a group to kill the mobs. This makes it relatively easy to reach the latter part of the area without having to clear the start.

**Comment by vitaladsr** [comment]
Shevy & Marthy thanks ... will do!! That will help greatly.

Nyyrazz .. yes this is true as well, I have to think pretty hard about that one .. If it stayed as is maybe you still need to force a group to clear the lower dungeon (that is my biggest concern) .. because they still need to clear the 2nd grid to get to Sahjuni's loot .. im going to focus on quickest solutions first then go from there. Thanks!

**Comment by shevarash** [comment]
(Still waiting on some files in my email...)

**Comment by vitaladsr** [comment]
I will be modifying baldurs.qst, swamp_two.zon, swamp_three.wld (Circa 2012).. for starters .. and  daynight2.zon ... however I am worried because there is a partial faang invasion fix in there that never got moved .. im not sure how to handle that. Should I focus on that first? Send .. load .. and then modify to fix whark (baldurs, daynight2) .. and finally a third time for (troll king .. swamp_two/three)? I understand we need to keep the updates separate for proper revision tracking etc.

I didn't want to bother you during the week and had a long day today already :) Thanks for being on top of me ... that's encouraging!!! Let me know how we should proceed from here. If you want you can forward me all the latest vers of baldurs, swamp_two, swamp_three, daynight2 and I can figure it out myself!

vitalmusic@yahoo.com is good

Annam

**Comment by vitaladsr** [comment]
Btw .. marthy reached out re: my baphomet revision that has been virtually finished waiting for like 4 months ... that should move quickly now too! You will love what i did there.

**Comment by shevarash** [comment]
I think most of this has gone in.
