### ISSUE TITLE
Enhance: Minimap marker

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#453]
While the minimap is a set size, the first few lines of it are also quite often just blank lines. There's no easy way to pull it out of the text stream at time of arrival: You have to work backwards from arrival of the Exits: lines to find the minimap and extract it from the stream.

It would be great if a unique marker could be used prior to sending the minimap such that you can easily trigger off that and know the following 13 lines are going to be the minimap.

Either something visible, or even invisible (example: replace the blank link prior to the minimap with \t\t\t\n)

**Comment by shevarash** [comment]
This is in now.
