### ISSUE TITLE
Character Creation issues and typos

### ISSUE THREAD

**Issue by Serity** [torilmud/issues#455]
Just registered, noticed some jank during character creation I thought you might like to update.

-----

Typos/things that need to be updated in character creation

Race selection:
* **"D" ('moon elf help') does not work**
* **"E" ('shield dwarf help') does not work**

* "F" ('duergar dwarf help') says 'as one of six evil races' - there's 7
** also, help suggests odd [See also: ... invisibility, "Spell, strength] - <"Spell>, instead of "underdark sneak" (although that helpfile doesn't exist)
* "I" ('ogre help') 6 evil races
* "J" ('swamp troll help') no mention of evil race warning
* "P" ('illithid help') 6 evil races
* "Q" ('yuan-ti help') 6 evil races, also cuts off at 'are a *very* advanced player and are used to the TorilMUD style of'
* "R" ('orc help') 6 evil races, no 'Warning:' red color

* "G" ('halfling help') - innate: hamstring, but help suggests 'See also: steal' (the lore paragraph suggests kleptomania too)
* "S" ('half-orc help') - does not suggest 'See also: furious' (or 'assault', since 'furious assault' does not work)

* If you are new to Sojourn (instead of TorilMUD, yes I know it was Sojourn before)
** note at bottom of race selection
** 3x in the '2' good/evil explanation info blurb ('2' at race selection')
* the '2' good/evil explanation and "If you are new" at bottom of race select suggests playing as Mountain Dwarf instead of ..whichever dwarf that is, I assume shield

------

Class information selection (from Race selection):
* List says anti-paladin instead of blackguard. As a result..
** **"e" ('anti-paladin help') does not work**
* In the list, half-orc is mentioned nowhere (Shaman, Dire Raider.. basically anything)
* "v" ('illusionist help') says "For an up-to-date listing of the available **invoker** skills.."

-----
Newbie help room
* Mentions 'wear all' even though you wear everything by default now
* Tells you to go west to anti-paladin guild instead of blackguard
* I started with three newbie help books for some reason (two on-hand, one in bag) (as a Halfling Rogue)

-----
Newbie help book
* chapter 6 mentions disarmtrap and detecttrap which don't exist

**Comment by Nyyrazzilyss** [comment]
I'll see what I can do about the the problem with race/class selection: That would likely be from conflict with the mud and my script. I have n/e/s/w/u/d all aliased from movement, so when they're sent to the mud they get capitalized. Pretty sure the character selection distinguishes between lower and upper case.

Shev: If you wanted to, another way to fix that part would be if you wanted to change the letters used there to not include [neswudNESWUD] ?

**Comment by Serity** [comment]
"Does not work" in the sense that it says there's no existing help file. Sorry for the ambiguity, I had just scribbled it down in notepad as I was going through it. "S" for half-orc help does work, so it shouldn't be directions screwing with it.

Not sure what your script is; I was using my own personal client. It'd be pretty funny if there just happened to be a totally separate unrelated issue stemming from this.

**Comment by Nyyrazzilyss** [comment]
woops thanks ignore what I said :) I know my script had a problem with that in the past, just retested though and apparently i'd already fixed it. The missing help files though is definitely an issue.

**Comment by Dartan82** [comment]
https://www.reddit.com/r/MUD/comments/9av1cg/come_back_to_torilmud/

Here is this bug being made public :)

**Comment by shevarash** [comment]
Thank you so much for documenting all of this. A lot of changes have been made lately and some of the help files are out of sync with the character creator. I'll get this all sorted out.

**Comment by shevarash** [comment]
All of the issues noted above have been fixed. Thanks again for pointing these out.
