### ISSUE TITLE
Vampiric Curse powers info confusing

### ISSUE THREAD

**Issue by Dartan82** [torilmud/issues#460]
The Conflicts: Fireshield, Coldshield prevents you from casting the spell on a target with fireshield/coldshield but if you somehow land the spell it tries to remove those powers.... is this intended?

Name             : Vampiric Curse           
Alias            : vc                       
Type             : Spell                    
Source           : Arcane                   
Attack Type      : Auto                     
Prepare          : Study                    
Target           : Offense, Character in room
Activation Time  : 4 seconds 
Related Skill    : spellcast necromancy
Conflicts        : Fireshield, Coldshield
Restrictions     : Autofire, Garrote, Standing, Can Speak
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Target Effect    : Add melee damaged trigger effect for 3 minutes 55 seconds 3 pulses  
                   Save versus spell to avoid  
Target Effect    : --> Remove fireshield                              
Target Effect    : --> Remove power Fireshield                        
Target Effect    : --> Remove power Coldshield                        
Target Effect    : --> Remove power Unholy Aura                       
Target Effect    : --> Heal for 34% of reflected hit points

**Comment by Inames** [comment]
I think it removes the shield effect and prevents them from being re-cast while it's active? otherwise it serves no real purpose.

**Comment by shevarash** [comment]
The power removals were unnecessary. That first "remove fireshield" is still needed though, to make sure that any other spells that happen to grant fireshield are also purged.

**Comment by Dartan82** [comment]
what about remove coldshield?  So vampiric curse is supposed to remove fire/cold shield and add vampiric curse too?
