### ISSUE TITLE
Iron warrior invincibility doesn't stop coldshield damage

### ISSUE THREAD

**Issue by Lilithelle** [torilmud/issues#462]
You feel a wave of vigor flooding through you as you stand fast against your foes.

                Character attributes for Gurru
.
.
.
Unarmd:  100% Slash :  100% Bludgn:  100% Pierce:  100% Range :  100% 
Spells:  100% Fire  :   35% Cold  :  130% Elect :  115% Acid  :  120% 
Sonic :  100% Poison:  115% Pos   :  100% Neg   :  100% Psi   :  100% 
Mental:  100% Good  :  100% Evil  :  100% Law   :  100% Chaos :  100% 
Force :  100% 

You become a whirling cyclone of terror as you spin your weapon about and charge your enemies.
You press the attack against a githyanki greater necromancer, striking repeatedly in a frenzy of blood!
A githyanki greater necromancer snaps into visibility.
You shiver from unnatural cold.
OUCH!  That really did HURT!

**Comment by Dartan82** [comment]
Same with paladin's Shield of Warding

**Comment by ghost** [comment]
sos on blk also, don't think those skills/spells were ever meant to replace globe, i'm fine with them as is

**Comment by Dartan82** [comment]
It's more like resists don't do anything to fire or cold shield.  Would be very nice if resists worked against fire/coldshield but would mean alot of people would try to wear a ton of fire/cold resist

**Comment by Lilithelle** [comment]
They do grant 100% pff/pfc, that means no pff/pfc reduces cold/fireshield damage, is that right? 
Lilithelle

**Comment by Inames** [comment]
but it's already been tested that 100% fire resist reduces fireshield damage completely... it's a thing... but cold resist doesn't work on coldshield? something else is broken there, it's gotta be with the cold damage type being calculated in combat. It's not a question of whether those tank class abilities were intended to replace globe, it's the fact that they mechanically have the same effect, and it's simply not working for cold damage. which means there's something broken in the application of cold damage from coldshield regardless of those defensive abilities and it needs to be addressed.

**Comment by shevarash** [comment]
There was a bug specifically with coldshield. Its damage was unclassified, so it was not affected by any resists.
