### ISSUE TITLE
Muspelheim Room issue - no break line between room description and exits

### ISSUE THREAD

**Issue by Gyrx** [torilmud/issues#465]
There is no break line between the room description and the room exits.  Please see bold below.

======================
Log:

< 668h/569H 228v/228V |3|3|3|3|2| P: std >
n

A Charred Valley in Muspelheim
You can still see the heavy branches of Yggdrasil high
up to the east from here. The valley of Muspelheim
is very dark, black glassy obsidian covers most of the
ground around here, ancient lava flows attest to the
brutality of this area. Volcanoes surround the area on
all sides, belching smoke and spitting lava, you can
see movement in the valley, although from this distance
you can't make out exactly what it could be. High above you
creatures circle in the air, flying higher then the tops of
**the mountains.Exits: - North - East - South - West**
An enormous bird circles about.

< 666h/569H 227v/228V |3|3|3|3|2| P: std >

**Comment by ghost** [comment]
there's one of those in blipp temple too, i think it's all down the vertical shaft

**Comment by gruumsh** [comment]
> there's one of those in blipp temple too, i think it's all down the vertical shaft

If you want to get that one fixed sooner rather than later, find it and post the log of the room in a new issue like Gyrx did for this one.
