### ISSUE TITLE
Broken newbie code

### ISSUE THREAD

**Issue by ghost** [torilmud/issues#467]
created a level 1 char........i'm in scardale, newbie eq.........and i find:

A tiny puppy is a small-sized level 1 Canine.

a tiny puppy is dead! R.I.P.
You receive 100 XP (4.39%) experience.

      Exp   %           Name
         71.9           a tiny puppy

so, i find another

a tiny puppy is dead! R.I.P.
You receive 25 XP (1.06%) experience.

I have just killed 2 level 1 mobs, with a new character, for an even more skewed xp problem, i could have tackled something higher in level, works the same............

Some how, trophy has been engaged on < 20 pc's, making it nearly impossible, for new chars to xp out of scardale, and thus, will not help to promote the game, when you have basic starter eq, can only kill little mobs, and after you kill one, you will stop gaining xp on them due to trophy.

I've tested with other new chars, and higher level mobs, if you kill a level 5 mob, you gain 25%, and a 98% trophy......kill it again, and you gain around .06% xp

fix me!

**Comment by ghost** [comment]
okay, here i am, same level 1 char, only ever killed those 2 puppys, i find something bigger to slay.....

A shiny feathered black bird is a tiny-sized level 11 Bird.

a shiny feathered black bird is dead! R.I.P.
You receive 3,680 XP (25.39%) experience.

      Exp   %           Name
         235.7          a shiny feathered black bird
          8.0           a tiny puppy

as you can see, that's pretty insane for only my 3rd kill.......so i decided to kill another one, that gave me a nice xp boost at level 1!

a shiny feathered black bird is dead! R.I.P.
You receive 0 XP (0.00%) experience.

so, i've spent time, firing around 50 sacred flames and fleeing and bandaging myself, to kill my 4th mob, since character creation.......for 0 xp

interestingly, my trophy dropped from it.............

      Exp   %           Name
         152.6          a shiny feathered black bird
          5.2           a tiny puppy

so if i kill about 50 more, i might start gaining xp on them again!

enjoy my late night posting, plz fix this issue of trophy on new characters

**Comment by Inames** [comment]
Trophy drop was due to damage exp, so the exp you had gained from killing that bird was on a % scale less of your total exp. Trophy isn't even supposed to function until you hit lvl 20, idk how or when they broke that again...
