### ISSUE TITLE
broken exits

### ISSUE THREAD

**Issue by ghost** [torilmud/issues#468]
there's one in pit of souls, sw, of ladder, either n or e exit, or coming from one of those dirs, is broken, and shows badly on map because of it

there's one in scardale, psi guild, 1s1w of entry off the street, if you move e, you are 2s of entry,

**Comment by Nyyrazzilyss** [comment]
Beluir, wnwn of the rogue guildmaster. The exit south leads to the room sw

**Comment by torilmud-silvanus** [comment]
Fixed in https://github.com/torilmud/torilmud/pull/697 pending move to main

**Comment by gruumsh** [comment]
This was merged on july 31st
