### ISSUE TITLE
gate spell

### ISSUE THREAD

**Issue by Alurissi** [torilmud/issues#47]
not all planes are acceptable as a target, such as astral......maybe others

**Comment by dnavarro** [comment]
I just casted gate astral

I am unable to reproduce this issue. Please provide more info

**Comment by Alurissi** [comment]
< 472h/697H 129v/130V >
< P: std > gate astral
That plane is not accessible.


i'm not using cast, this is a powers issue, i believe it's not the only teleport spell that doesn't accept all the planes as targets, rift, pshift, for example, but i'll let it go at gate at this point in time

**Comment by Inames** [comment]
I just went through and tested all the planes with gate/rift/pshift, everything works except for powers gate astral, and powers pshift astral.

**Comment by cmoncrief** [comment]
This has been fixed.
