### ISSUE TITLE
furious assault

### ISSUE THREAD

**Issue by ghost** [torilmud/issues#471]
need to update this power to reflect other powers, str needs to go to 25, from the 20, and needs to add in the hitroll mod

**Comment by ghost** [comment]
might consider adding a miss message, on a failed attempt, that misses, in condensed, all i see is a disappearing blank line.........as in, no line between status/hp/powers, and the next line is also those things, usually there's a blank line between the two, seeing no blank line is the only indication that it missed and did not even land a normal hit.....

**Comment by Nyyrazzilyss** [comment]
I have something similar mentioned in https://github.com/torilmud/issues/issues/361
