### ISSUE TITLE
auto stat character generation

### ISSUE THREAD

**Issue by ghost** [torilmud/issues#474]
so i recently rolled up 2 different race/classes, and chose the prerolled stats, both of which, gave me a 0 in charisma.........this is somewhat of an important stat, power i can do w/o which also rolls up as 0 on some classes........but why 0? no charisma at all? this has to be a bug, the 2 race/class combos i rolled, were half-elf druid, and yuan-ti ele......

**Comment by Inames** [comment]
This is Noted in #430 as a bug already. Shev is aware.

**Comment by shevarash** [comment]
Closing as this is a duplicate of #430.
