### ISSUE TITLE
some runed kodragon leggings stats

### ISSUE THREAD

**Issue by Dartan82** [torilmud/issues#476]
kodragon leggings are currently ac 10 10 hp 3 maxagi mage/thief only

In comparison to this quest which is:
some cloudy chain leggings with iron knee plates * (cloudy chain leggings iron knee some) * QUEST-ITEM * ARMOR (LEGS) * 5 lbs * 300000 c * ac11 24hp 3max_agil * NO-WARRIOR NO-THIEF NO-MAGE

https://www.tapatalk.com/groups/triteriumbbs/some-cloudy-chain-leggings-with-iron-knee-plates-t1724.html

the Ashstone upgrade is much harder and time consuming.  Please upgrade the stats.  Some physical resists would be nice!

**Comment by jokkmeister** [comment]
Ahstone is harder?
1. it can be done every single boot
2. it can be solo'd
3. There are too many really good quest items for a "safe" zone already in ashstone. Great items should be hard to get and come from aggro zones and really shouldn't be soloable.

**Comment by Dartan82** [comment]
Read the link.  4 areas that are easy with 2 people or less.

**Comment by jokkmeister** [comment]
Yes but Ashstone is easy on your own and the load is not rare. Cloudy leggings can only be done so often. Kodragon every boot on your own if needed.

**Comment by Dartan82** [comment]
Yes so 4 easy fights in easy areas that are rare vs. 11 easy fights in easy areas.

All these zones are "safe".  In fact most zones are already safe these days ever since rogues were put into game.

**Comment by jokkmeister** [comment]
I think it boils down to Kodragon can be solo'd every boot, Cloudy can not.

**Comment by Dartan82** [comment]
You can get 1 kodragon a boot if you spend the time.  Over 3-4 boots you can get a cloudy on top of a heap of other gear.

**Comment by Dartan82** [comment]
https://github.com/torilmud/issues/issues/596
