### ISSUE TITLE
Help menu corruption

### ISSUE THREAD

**Issue by vadi2** [torilmud/issues#477]
Using ASCII encoding:

![image](https://user-images.githubusercontent.com/110988/47473453-eb178c00-d812-11e8-813a-51b0416a7a62.png)

Using UTF-8 encoding:

![image](https://user-images.githubusercontent.com/110988/47473464-f7034e00-d812-11e8-9dda-d7bf4f59685d.png)

In both cases � appears and there is color corruption after `Toril`.

**Comment by shevarash** [comment]
Fixed the color corruption and bad characters and also rewrote part of this, as well as the INFO screen.
