### ISSUE TITLE
corrupted char

### ISSUE THREAD

**Issue by Alurissi** [torilmud/issues#48]
so it's been what? 3 4 years now, and it still says that my invoker, Hobotikle, is corrupted and will not log in, nor is his storage accessable, i do not remember the exact time this happened, but i do know how it happened........Lili was lagging the mud, doing 2000 or so buccaneers? in skullport, getting gladiuses to turn back in for 1 plat, and i was attempting to end the 5 min mud lag with invoker, it did involve recreating my spell list, to where i had 30 or so force missiles, and then dying, had worked before in crashing the mud, failed this time, and corrupted char instead.   Not a real big issue, but it would be neat to beable to use that guy again, as he was my only invoker! and super cool

**Comment by shevarash** [comment]
This is a support issue. 

I've forwarded this on to the support email at toril.help@gmail.com . That's the best place to send support issues like that, as all of the staff have access to it and it goes right to our phones in some cases. I'm closing this ticket, but we'll work this through email.
