### ISSUE TITLE
consents for dragging

### ISSUE THREAD

**Issue by ghost** [torilmud/issues#485]
shevarash, can you add to gcmd type commands, that gives group leader the ability to drag corpses w/o needing them to consent you?

group leaders could use this little perk for many things, crs, dragging mortally wounded people, giving heavy items to afk winner at split.

if you can't trust your group leader, you shouldn't be in their group!

**Comment by Dartan82** [comment]
Or another group role called lieutenant or something that the group leader can assign that gives group consent.  Not all leaders are draggers.

**Comment by shevarash** [comment]
The dragging/consent situation is definitely due for an overhaul.

**Comment by Dartan82** [comment]
Shevarash can you bump this to higher priority please?  Saves the Bahamut group alot of time and frustration.
