### ISSUE TITLE
dragonhunter bow

### ISSUE THREAD

**Issue by ghost** [torilmud/issues#489]
you'll find a similar post, already up here, from april, with new archery code, this has become one of the worst bows in game, hp and svbr instead of hit/dam, which archery now checks off bow stats, something needs to be done to spice this bow up a little bit to compensate for the lack of hit/dam

**Comment by jokkmeister** [comment]
It was supposed to be a vamping bow if I remember correctly. To actually get it to vamp would be nice, then it doesn't need hit/dam.
