### ISSUE TITLE
Baphomet not linked on main

### ISSUE THREAD

**Issue by vitaladsr** [torilmud/issues#491]
There should be a room in the death bog (swamp_one.wld) containing r26032 that needs a north exit to 12662

The Death Bog [120:26032]
   The vegetation grows thick and dangerous in this section of the swamp.
Carrion vines snake along the loose soil awaiting new prey.  The relatively
stable soil of the bog gives way to more of the expansive swamp.  The still
waters that surround the bog are thriving with large alligators and other
aggresive carnivores in the murky water.
Exits: - North [58:12662] - East  [120:26033] - South [120:26029] - West  [120:26031]
A large vicious fish with four squat legs wanders around here.[26010]

**Comment by marthammor** [comment]
Yeah..
Someone may have forgotten to uncomment it...

**Comment by shevarash** [comment]
details, details
