### ISSUE TITLE
great weapon defense

### ISSUE THREAD

**Issue by ghost** [torilmud/issues#492]
this is a paladin/blk/warrior power..........there is a slight niche in warrior class, they get dual wield skill

can we get dual wield added to this power, instead of just two-handed weapon?

rangers do not get great weapon defense, so would not affect them, however, i personally enjoy dual wielding with my warriors, and aside from the refusal to give warriors dual wield powers, this 1 change, would be a nice up for those who choose to dual on warrior

**Comment by shevarash** [comment]
Not at this time, though there is opportunity in the future for more dual wielding usage by Warriors.
