### ISSUE TITLE
Misc new class issues

### ISSUE THREAD

**Issue by ghost** [torilmud/issues#493]
not sure anyone even looks at github anymore, but figured i'd post a few things that don't seem to have ever been fixed from their initial rollout

pc's lose kick, mobs retain the skill, but still, we receive no defensive check vs them kicking us

ranger: 2h weapon skills, no powers to go with it

paladin/blk: spellcast healing and protection......but every spell is flag'd generic

all ranger paladin and blk spells are flag'd atwill, even though all 3 classes have quick chant skill

warrior: dual wield skill, no powers to go with it

ranged weapon defense: not sure this is even working

ranger: tree stride......still saying this is a waste, no one ever uses it, ever, and should be replaced with a cure blind, as ranger is the only fighter that can't cure it's own blindness

pal/blk: ds/ps.........5 min recharge is a little lame, given that it's 700% on success, and during recharge, you can fire off 8x 500% damage blows, either the skill needs to have status effects added, or duration shortened

archery: maxes at 95, and i've seen no difference in high dex vs low dex for successrate, having ammo riposted is also rather odd!

**Comment by shevarash** [comment]
There are some valid issues in here. Most of them are things that are just in progress, like the skills and spell types. 

Ranged Weapon Defense appears to be working fine. Do you have a reason to think it isn't? 

Point taken on Divine Smite. 

Archery should probably max at 99. I'm not sure what you mean about Dex - powers or regular hits? The riposting is a bug.
