### ISSUE TITLE
Mobs that cast spells per .qst broken

### ISSUE THREAD

**Issue by vitaladsr** [torilmud/issues#494]
Mobs that you can give money, or an item to (.qst) in return to get a spell cast upon you are broken.

**Comment by gruumsh** [comment]
Can you give us an example of some specific mobs? I just tested some and they appeared to be working correctly.

**Comment by vitaladsr** [comment]
The demonic counselor in the tooth and maw guildhall for example. And a few in SM. I can get you more examples if needed. Maybe Shevy phases out legacy spell casting for powers?


Sent from Yahoo Mail for iPhone


On Sunday, December 2, 2018, 6:34 PM, gruumsh <notifications@github.com> wrote:


Can you give us an example of some specific mobs? I just tested some and they appeared to be working correctly.

**Comment by gruumsh** [comment]
There is indeed a problem with that mob (m100417)

**Comment by vitaladsr** [comment]
100421                                Dardrith
100417                                a demonic councilor

Reportedly all guildhall mobs that spell you up
and some in various zones

Anything that is result/reward of a quest entry i believe
