### ISSUE TITLE
Finder quest cloak no longer procs

### ISSUE THREAD

**Issue by Dartan82** [torilmud/issues#497]
<worn about body>    a flowing pitch-black cloak covered in stars
<worn as quiver>     a sturdy doeskin quiver
<worn about waist>   a thick girdle of silver dragonhide with adamantine bolsters
<worn on arms>       a set of flayed demonleather sleeves
<worn around wrist>  an adamantine hoop whirling with tendrils
<worn on finger>     a fighter's loop of sorcerous ability
<worn on finger>     a fighter's loop of sorcerous ability
<primary weapon>     the mighty scepter of valhalla (glowing)
<secondary weapon>   a shimmering crystal scimitar
<worn on legs>       a set of greaves made of jagged ice
<worn on feet>       the mystical boots of the traveler (glowing)
< 695h/695H 220v/220V |ts +|ss +|ap +|ev +|bs +| |3|3|3|3|2| P: std > 
Thelen enters from above.
< 695h/695H 220v/220V |ts +|ss +|ap +|ev +|bs +| |3|3|3|3|2| P: std > g divination hole
reci divination stars
save
Time: Monday December 3, 2018 8:53:31 pm
sc
You get an intricate divination scroll from a portable hole.
< 695h/695H 220v/220V |ts +|ss +|ap +|ev +|bs +| |3|3|3|3|2| P: std > You recite an intricate divination scroll which turns to dust in your hands.
You feel informed:
Name 'a flowing pitch-black cloak covered in stars'
Keyword 'night cloak stars', Item type: ARMOR
Item can be worn on:  ABOUT 
Item will give you following abilities:  NOBITS
Item is: MAGIC NOBURN NOBITS
Weight: 1, Value: 0
AC-apply is 15
Can affect you as :
    Affects : HITROLL by 2
    Affects : HITPOINTS by 20
Called Effects :  (invoked by 'say'ing them)
                  'starfall'   Meteor Burst 1 / week

**Comment by gruumsh** [comment]
Tested, it is working. 
However it requires the user to be engaged to proc, and will not throw a message if they are not. 
This might lead to confusion and could warrant either allowing it to proc without targets or an out of combat message.
