### ISSUE TITLE
a bracelet of flowing shadows

### ISSUE THREAD

**Issue by ghost** [torilmud/issues#498]
this object is really rather weak for the quest.  you are required to do quite a bit of work, including rares, and quests, and large zones to get this, it needs a little bit of lovin

currently it's ac 6 1/3, going by how difficult the quest actually is, i believe it should be adjusted to perhaps, ac 10 1/3, or ac 6 2/3

I do believe there's only 4 in game, because of the quest, needs some serious review

**Comment by Lilithelle** [comment]
He's right, I was a real jerk with this one.
earring of ethereal shadows (semi-rare kenjin)
a dark shadowy ring (soloable citadel, but a bit of work)
talisman of shadows (quest: list - a small amount of solo work, circlet of negative energy from MS, skeleton finger hanging from a silver chain, skeleton finger hanging on gold chain, 2 strings of black diamond, shadow dagger, cloak of shadows from nizari, shadow club from attic, shadow blade from conquered village, shadow staff)
belt of shadows (easy quest but with a rare that takes several boots)
lightweight cloak of shadows from BC (evil version)
a swirling robe of shadows (muspel quest just as hard as devilskin robe for khanjari)
sleeves of flowing shadows (quest, 2 items from Mhereg Ssar in Scorn, solo/small group)
a basic hood of wispy shadow (10 remnants from shadow daemons on astral)

**Comment by ghost** [comment]
shadowy ring is actually from cursed cemetary, which is a 15-35 level only zone, and the ring is rare inside, on a lvl 40 wraith form
