### ISSUE TITLE
Hulburg's remove object quests require review

### ISSUE THREAD

**Issue by gruumsh** [torilmud/issues#499]
The zone will not repop while occupied, review is needed to determine what should be placed in a 1 minute pop zone, or in the long delay zone.

_Originally posted by @Alurissi in https://github.com/torilmud/issues/issues/53#issuecomment-284797610_

**Comment by ghost** [comment]
really the only one i can think of that this effects, is eyeball earring quest loading final turnin mob, and maybe, the loading of slime whip chest in cp
