### ISSUE TITLE
phantasmal tendrils

### ISSUE THREAD

**Issue by Alurissi** [torilmud/issues#50]
well established, the spell is only hitting a single target, however, the message we see, is hitting xxx targets, where as it's how ever many mobs are in the room, also, due to the fact this isn't an area spell, it should be dragable, and power version isn't

**Comment by dnavarro** [comment]
The message issue sounds like a defect

The dragging thing I think is just a change with the new version. Is this intended @cmoncrief ?

**Comment by shevarash** [comment]
The change to be undraggable is intentional, much like rot and doom.

I'll look into the rest though.
