### ISSUE TITLE
Bad account name on who

### ISSUE THREAD

**Issue by Lilithelle** [torilmud/issues#500]
[ 1 Rogue       ] Olmonil  (Moon Elf) (@green dragon scale dragonscale wristguard)
He's a new player, and his account name is actually @Sheer, but I, and he, gets the above when typing who Olmonil.

**Comment by Lilithelle** [comment]
[ 1 Ranger      ] Nehna  (Half-Elf) (@)
(actually account name: @Sonorous)

**Comment by shevarash** [comment]
This should be fixed. His character appears back to normal as well.
