### ISSUE TITLE
warrior cooldowns

### ISSUE THREAD

**Issue by settlestone** [torilmud/issues#504]
the cooldowns on iron warrior, diamond shield defense and unbreakable are way too long compared to what paladin gets.  Please lower it to something manageable like say two minutes for iron warrior, diamond shield and unbreakable.

**Comment by vitaladsr** [comment]
I don't think it would hurt to move storm of destruction down to 5 mins (from 7) .. I don't mind the others **as** much .. (cooldown wise) ... because there are 3 possible defensive options .. although iron warrior duration could be nudged a little perhaps (if the cooldown remains the same)

**Comment by shevarash** [comment]
Thank you for the feedback, we'll consider it.
