### ISSUE TITLE
Crown of the death dragon

### ISSUE THREAD

**Issue by settlestone** [torilmud/issues#505]
The power doesnt recharge.  Also the cooldown is way too long for the power.  Please either increase the aura to 1 minute with a 9 min CD or make the CD something manageable like 2 mins .  But ya . First things first.. the power needs to be able to recharge... which currently it cannot.

**Comment by jokkmeister** [comment]
I have to concur, I have a hard time seeing this being used at all. Easier to get serpents from Tiamat than this one. So proc should be at least as good for tanks as serpents is for hitters.

**Comment by settlestone** [comment]
So it does work sometimes.. but the power doesnt show on the recharge list.
