### ISSUE TITLE
dispel magic

### ISSUE THREAD

**Issue by Alurissi** [torilmud/issues#51]
dism (char), even with consent:

You can not cast offensive spells on other players!

**Comment by Adriorn** [comment]
I second this.  Only the non-powers version works on players.

**Comment by cmoncrief** [comment]
This has been fixed.

**Comment by shevarash** [comment]
The last fix messed up offensive and self targeting. Re-opening to resolve that.

**Comment by shevarash** [comment]
Re-fixed.
