### ISSUE TITLE
Toon "Jooku" on my acount cannot reply to anyone...

### ISSUE THREAD

**Issue by CountVooku** [torilmud/issues#510]
After a tell I get "But you are not currently replying to anyone!" when I reply.

Reply with no argument gives me "You are not currently replying to anyone.".

**Comment by shevarash** [comment]
This is really weird. Is it still happening to you? I'm wondering if the recent crash and memory corruption issues that were resolved have cleared it up.

**Comment by CountVooku** [comment]
Yep. Jooku still can’t reply to anyone. All other toons in account are fine.

“But you are not currently replying to anyone!”

**Comment by shevarash** [comment]
(If you're still having this issue please let us know.)
