### ISSUE TITLE
Spectral Hand

### ISSUE THREAD

**Issue by Fisig** [torilmud/issues#511]
Name             : Spectral Hand            
Alias            : sh                       
Type             : Spell                    
Source           : Arcane                   
Attack Type      : Auto                     
Prepare          : Study                    
Target           : Offense, Character in room
Activation Time  : 2 seconds 
Restrictions     : Autofire, Garrote, Standing, Can Speak
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Target Effect    : Deal 8d22 negative damage                          
                   Save versus spell for 50%

Its not spellcast necromancy?

**Comment by shevarash** [comment]
Good catch!
