### ISSUE TITLE
Magic Missile Imbalance

### ISSUE THREAD

**Issue by Fisig** [torilmud/issues#512]
Invoker - magic missile: spellcast invocation
Enchanter - magic missile: spellcast invocation
Necromancer - magic missile: spellcast invocation
Illusionist - shadow bolt: spellcast illusion
Shaman - totem darts: spellcast spirit

Only some specialists get a magic missile type spell that is related the the specialty.

**Comment by Inames** [comment]
Magic missile is an invocation spell, sure there are similar spells that draw on other particular specialties, but enchanters and necromancers have other spells that fall into their purview and align with their specialties, magic missiles is just a sort of minor damaging tool for them that is standard practice for aspiring mages, and specialization in those spells wont modify the damage significantly enough to warrant changing things or tip the power balance in their favor.

Though I grant that there is some room for flavor in adding a minor missile spell to the other specialties. Something like a "Bone Bolts" for necromancer that does necrotic damage with a minor infection-like DoT, and "Color Spikes" for enchanter with minor 1-2 round duration special effects would be dope.

**Comment by Fisig** [comment]
Inames,
"Magic missile is an invocation spell, sure there are similar spells that draw on other particular specialties, but enchanters and necromancers have other spells that fall into their purview and align with their specialties,"

Pointless. All casters do. You seem to have missed or ignored the point. 
Why is it 3/5 (+cleric-heal/cause) get a spell that is aligned with their specialty as the main leveling offense? Enchanters/Necros must opt for less effective spells to level with, should they choose to use a spell from their specialty, until they reach mid level (+). That is bias.

If any specialist gets "special" treatment (shaman/illusionist- esp.), then all should.

Something like,
Necrotic bolts, Shimmering missiles, or some such. They dont need special effects, just from the right school of magic. So a leveling Enchanter/Necro are using spells from the their specialty, as the others do.

And yes, this is all meaningless to someone who is already 50th, or power leveling. Oddly enough though, that isnt everyone.

**Comment by shevarash** [comment]
This is a fair point, and will be addressed in the future caster class upgrades.
