### ISSUE TITLE
Illusionist Issues

### ISSUE THREAD

**Issue by druzix** [torilmud/issues#514]
- Doppleganger mobs are misspelled (Doppelgangers)
- Dopplegangers need die-off timers or something. Moves don't regen, so they just lag behind and linger forever, making zoning with this spell nigh-useless. If dopplegangers had a duration based on skill then it could at least be zoned with nicely.
- Tranquility does nothing. Useless. Even at max spellcast_illu, specialize_ill and SF_ILLU at +12% it does nothing effective.

**Comment by shevarash** [comment]
We have another ticket to track the Doppelganger spelling - suffice it to say tha tit is more complex than it seems, and it bugs me too! :/

See #522 for the Tranq ticket as well.
