### ISSUE TITLE
Poison effect/spell

### ISSUE THREAD

**Issue by vitaladsr** [torilmud/issues#515]
I noticed that MR seems to protect against poison .. but in addition I would like to make a general comment / idea that poison (given the updated amount of MR/hp on both mobs, pc's) could be MUCH stronger/more damaging. I ate a prism cast by a lvl40 mob and was poisoned and it did 4-8 hp damage per round.

Maybe an easy way to make things more dangerous. I do like some of the poison traps that do 100-200 hp per round. That is exciting.

**Comment by shevarash** [comment]
We have a much stronger version of poison called venom. Future powers may incorporate this rather than old-school weak poison.
