### ISSUE TITLE
the hollowed claw of a balor demon called proc power does nothing.

### ISSUE THREAD

**Issue by i982** [torilmud/issues#516]
this item doesnt work. has never worked. won't recharge. lili says opposite on test mud. it needs no charge time and works.

someone said you have to be logged out with them for the timer to count. tried logging out while wearing for 3 days. tried leaving them on char not worm logged out for days. tried leaving in storage for days. nadda.

Combat Powers:
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=--=-=--=-=-=-=-=-=-=-=-=-=--=-=-=-
**Wings of the Balor                  [fly   ]                   Equipment 
Wings of the Balor                  [fly   ]                   Equipment** 
Circle                              [cr    ]    Piercing       Level 15  
Backstab                            [bs    ]    Piercing       Level 1   
Trip                                [tr    ]                   Level 25  
Hamstring                           [hms   ]                   Level 1   

< 556h/556H 165v/165V P: std > 
**fly
That power hasn't recharged yet!**

< 556h/556H 165v/165V P: std >

A small lizard enters from the east.
**You do not have any powers recharging.**

< 556h/556H 165v/165V P: std > 
eq
You are using:
<worn as a badge>    phoenix insignia of the Lords of Imphras
<worn on head>       the mystical circlet of the coiled serpent (magic)
<worn on eyes>       a silvered scale of deepest blue hue (magic)
<worn in ear>        a tiny mithril stud set with a ruby
<worn in ear>        a tiny mithril stud set with a ruby
<worn on face>       a cringing mask of the trickster
<worn around neck>   the black steel amulet of the crescent moon (magic)
<worn around neck>   the black steel amulet of the crescent moon (magic)
<worn on body>       a suit of ancient banded steel armor
<worn about body>    an entirely encasing cloak of darkness
<worn as quiver>     a hard leather bandolier with mithril studs
<worn about waist>   a luminous cincture of nightfallen stars (magic)
<worn on arms>       a set of flayed demonleather sleeves (magic)
<worn around wrist>  a storm bracelet (magic)
<worn around wrist>  a storm bracelet (magic)
<worn on hands>      a pair of gauntlets wreathed in electricity (magic) (glowing)
**<worn on finger>     the hollowed claw of a balor demon (magic)
<worn on finger>     the hollowed claw of a balor demon (magic)**
<primary weapon>     a glittering dagger of the Nurturing Matriarch (poisoned) (magic)
<secondary weapon>   a red dragon fanged dagger (poisoned) (magic)
<worn on legs>       some silver scaled leggings of attack
<worn on feet>       a pair of taut red leather boots with adamantine buckles (magic)

< 556h/556H 165v/165V P: std > 
status

Status of Mival
---------------------------------------------------------------------------

Effects
---------------------------------------------------------------------------
detect magic              haste                     infravision               
no summon                 protection from evil      sense life                
sneak                     

Spells
---------------------------------------------------------------------------
detect magic              ( 27:00)

**Comment by Dartan82** [comment]
Also occurs with 
a silver ring with mirrored finish

**Comment by shevarash** [comment]
These are both fixed as of last week.
