### ISSUE TITLE
Vampiric Curse

### ISSUE THREAD

**Issue by Fisig** [torilmud/issues#518]
"VAMPIRIC CURSE"
Spell.

Area of effect: <victim>
Aggressive:     Yes
Cumulative:     N/A
Duration:       Instantaneous
Class/Circle:   Necromancer 9th
Type of spell:  Necromancy

Casting this spell causes a vampiric aura to form around the target.
The aura sends back healing energy for the damage done to the
Unfortunate victim.

Does not affect those already utilizing an aura spell such as Fireshield
and the like.  This spell can only be cast by living necromancers.
If cast by the undead, it will have no effect.
+
Name             : Vampiric Curse           
Alias            : vc                       
Type             : Spell                    
Source           : Arcane                   
Attack Type      : Auto                     
Prepare          : Study                    
Target           : Offense, Character in room
Activation Time  : 4 seconds 
Related Skill    : spellcast necromancy
Conflicts        : Fireshield, Coldshield
Restrictions     : Autofire, Garrote, Standing, Can Speak
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Target Effect    : Add melee damaged trigger effect for 4 minutes 24 seconds 2 pulses  
                   Save versus spell to avoid  
Target Effect    : --> Remove fireshield                              
Target Effect    : --> Heal for 34% of reflected hit points           

Cant cast it on someone who has coldshield on.
If its wai the files need to be fixed.

**Comment by shevarash** [comment]
I think this is actually working as intended. Here's what the info display is saying:

1) You can't cast it on someone who has Fireshield or Coldshield up.
2) If you manage to cast it on someone with the fireshield effect up (which is granted by some other spells), it will be removed. 

Essentially, #2 is a safeguard to make sure no fireshield effect can be stacked with Vamp Curse. For reference, the coldshield spell actually sues the fireshield effect bit under the hood. I realize this is confusing, but it appears to be working correctly. Please feel free to re-open if I'm missing something.
