### ISSUE TITLE
rogue shadow skill

### ISSUE THREAD

**Issue by billimek** [torilmud/issues#519]
* I spent about 4 hours shadowing a patrolling mob and shadow skill (58) didn't increase once.
* I spent about ~2~ ~3~ 4 hours shadowing a PC (Magpie) who was walking around Silverymoon murdering innocent mobs and shadow skill didn't increase once.  It was quite traumatic to witness all of the murder!
![image](https://user-images.githubusercontent.com/6393612/51881934-0979b000-234b-11e9-8d19-ca1c93de815e.png)

Is it actually possible to increase the shadow skill?

**Comment by Dartan82** [comment]
You can't even practice shadow on a new character :/

**Comment by settlestone** [comment]
don't think shadow works..

**Comment by shevarash** [comment]
Shadow has been broken for awhile, and we need to either remove it or fix it.

(Sorry about the murder trauma?)
