### ISSUE TITLE
Stats and rerolling

### ISSUE THREAD

**Issue by Dartan82** [torilmud/issues#521]
Can we get a way to increase our primary stats?  Maybe use exp or prestige or plat to increase them.  I don't see why spending weeks to roll 3-4 100's on a character should be the answer to getting perfect stats versus using another currency like plat.

**Comment by Inames** [comment]
Agreed, development of character stats should be a thing that happens during the leveling process and thereafter, your physical and mental capabilities are not determined from birth.

**Comment by shevarash** [comment]
I agree that this area needs work. I'm closing this ticket because it's not really actionable, but please feel free to continue discussing it here, on the subreddit, or on Discord.
