### ISSUE TITLE
Protect undead/ Protection from undead/ Preserve

### ISSUE THREAD

**Issue by Fisig** [torilmud/issues#523]
Protect undead/ protection from undead/ preserve /embalm do not seem to be affected by spell focus necromancy, in either duration nor in effects granted.
Also...

powers info prs

Name             : Preserve                 
Alias            : prs                      
Type             : Spell                    
Source           : Arcane                   
Prepare          : Study                    
Target           : Corpse in room
Activation Time  : 5 seconds 
Restrictions     : Autofire, Garrote, Standing, Can Speak
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Object Effect    : Preserve corpse for 255 minutes (51 minutes for NPC corpses) 

Isnt spellcast necromancy?

**Comment by shevarash** [comment]
This is intended. These spells are level based.
