### ISSUE TITLE
baphomet broken

### ISSUE THREAD

**Issue by ghost** [torilmud/issues#529]
I know for sure, we cleared 3rd floor in under 20min, 3x now, and every time it's registered as failure

**Comment by ghost** [comment]
while we're at it, something needs to be done about the 2 groups of skeletal minotaurs on 3rd floor, using power ice tomb, which has no save other than being above 1000 hp, they always clump together in same room, because nearly every exit is a stupid teleport, all to same area, they aren't combat lurable, and fuggin stupid as crap that 1 mob can wipe a group, and you put 18 in 1 fight.  either make them sentinel, or take away power ice tomb for a different spell.  no reason in hell, success of this should depend upon a rare load room silence staff from another zone, this is, truely pathetic, and i blame the creator as much as shevarash for power ice tomb having 0 saving throw!

**Comment by shevarash** [comment]
I believe this is fixed now, per Discord conversation.
