### ISSUE TITLE
Whole Entire Gear Set Poofed.....

### ISSUE THREAD

**Issue by i982** [torilmud/issues#533]
**heres the log.. killed mob. moved to next room and gear was gone.

[Reached train station: (48958) half-elven merchant]

A half-elven merchant is in an excellent condition. (Medium)

< 876h/876H 106v/110V |0|1|2|0|1| P: std > 

[Attacking: Half-elven]

[MELEE: Sweeping Strike] SS HALF-ELVEN
You sweep attack a half-elven merchant with unbound fury, knocking him off balance!
Tendrils of acidic greenfire leap from your weapon!
Tendrils of acidic greenfire leap from your weapon!
A half-elven merchant crashes to the ground!

< 876h/876H 107v/110V |0|1|2|0|1| T: Tukin TC: excellent E: merchant EC: small wounds EP: rcl P: std > 

[No longer moving. Spellcasting has resumed]

[MELEE: Bladestorm] BS
A Stately House
[MELEE: Bladestorm] BS
< 876h/876H 108v/110V |0|1|2|0|1| T: Tukin TC: excellent E: merchant EC: small wounds EP: rcl P: std >

You're not ready to perform another action!

< 876h/876H 108v/110V |0|1|2|0|1| T: Tukin TC: excellent E: merchant EC: small wounds EP: rcl P: std > 

Your massive greenfire slash barely wounds a half-elven merchant.
Your massive greenfire slash badly wounds a half-elven merchant.
A half-elven merchant dodges your futile attack.
You miss a half-elven merchant with your greenfire slash.
A half-elven merchant misses you with his hit.

< 876h/876H 110v/110V |1|1|2|0|1| T: Tukin TC: excellent E: merchant EC: small wounds EP: rcl P: std > 

[MELEE: Eviscerate] EV

[Greenfire has expired on Tukin.]
The virulent green flames coating your weapons are extinguished.
You swing your weapons in lethal arcs, dousing the area with a half-elven merchant's blood.
A half-elven merchant is weakened!

< 876h/876H 110v/110V |1|1|2|0|1| T: Tukin TC: excellent E: merchant EC: few wounds EP: rcl P: std > 
[SPELL: Hunters Mark] HM
You start chanting... [Casting: HM (Hunters Mark)]

< 876h/876H 110v/110V |1|1|2|0|1| T: Tukin TC: excellent E: merchant EC: few wounds EP: rcl P: std > 

You complete your spell... [ HM (Hunters Mark) ]
a half-elven merchant is marked with a faint blue glow.

< 876h/876H 110v/110V |0|1|2|0|1| T: Tukin TC: excellent E: merchant EC: few wounds EP: rcl P: std > 
You score a CRITICAL HIT!
Your massive slash severely wounds a half-elven merchant.
Your massive slash severely wounds a half-elven merchant.
Your massive slash severely wounds a half-elven merchant.
Your massive slash severely wounds a half-elven merchant.
Your massive slash severely wounds a half-elven merchant.
A half-elven merchant misses you with his hit.
A half-elven merchant barely wounds you with his average hit.
A Stately House
A half-elven merchant barely wounds you with his average hit.
< 868h/876H 110v/110V |0|1|2|0|1| T: Tukin TC: few scratches E: merchant EC: nasty wounds EP: rcl P: std > 
[SPELL: Blades of Fire] BOF
Mhordregoth GCC: 'ok.. Longhollow.. I have the heads of the knight, the necromancer, and the priest, but am missing something?'

< 868h/876H 110v/110V |0|1|2|0|1| T: Tukin TC: few scratches E: merchant EC: nasty wounds EP: rcl P: std >

You start chanting... [Casting: BOF (Blades of Fire)]

< 868h/876H 110v/110V |0|1|2|0|1| T: Tukin TC: few scratches E: merchant EC: nasty wounds EP: rcl P: std > 

You complete your spell... [ BOF (Blades of Fire) ]
[Half-Elven Merchant has nasty wounds!]
Your weapons burst into searing white-hot flames.

< 868h/876H 110v/110V |0|1|1|0|1| T: Tukin TC: few scratches E: merchant EC: nasty wounds EP: rcl P: std > 

[MELEE: Bladestorm] BS

[Cloak of Resilience has expired on Tukin.]
A Stately House
[Cloak of Resilience has expired on Tukin.]
< 868h/876H 110v/110V |0|1|1|0|1| T: Tukin TC: few scratches E: merchant EC: nasty wounds EP: rcl P: std >

Your shadowy cloak of resilience dissolves.

You spin and leap through the fray, unleashing a torrent of steel on your enemies!
You rain a series of deadly blows on a half-elven merchant!

< 868h/876H 110v/110V |0|1|1|0|1| T: Tukin TC: few scratches E: merchant EC: awful EP: rcl P: std > 

A half-elven merchant is nearly slain by the force of your massive flame-enshrouded slash!
Your final slash sends a half-elven merchant's head bouncing along the ground.
a half-elven merchant is dead! R.I.P.
You receive 0 XP (0.00%) experience.
Your blood freezes as you hear the rattling death cry of a half-elven merchant.

[Calling function: NextTrainStop()]

< 873h/876H 110v/110V |0|1|1|0|1| P: std >

You get a small pile of coins from corpse of a half-elven merchant.
put all.coin portable;put all portable
There were: 4 platinum coins, 27 gold coins, 1 copper coin.

< 873h/686H 110v/110V |0|1|1|0|1| P: std >

A Stately House

< 873h/686H 110v/110V |0|1|1|0|1| P: std >

Ok.
You put some coins into a portable hole.

< 873h/686H 110v/110V |0|1|1|0|1| P: std >

You can't do that. Perhaps that item is cursed?
You don't have anything to put in it.

< 873h/686H 110v/110V |0|1|1|0|1| P: std > 

[Moving to: Human Hunter (48954)  <.s2en>]
Pardon?

< 873h/686H 110v/110V |0|1|1|0|1| P: std > 
@fwalk 48954
[Path: .s2en]
s

[Currently moving. Spellcasting is temporarily paused.]

e
e
n

               

   .-. .-. .-. .-. .-. .-. .-.   
  | + |----   ---- ----   | + |  
  |   |   +.-.+   |*-* *-*|   +  
  |--- ----   ----|--- ---|---   
  |   |   +.-.|. .|   |   |   +  
+-| + |-+--   | + | + | + | + |  
   .!. .!. .!. .@. .!. .!. . .   
----------- + -------------------
      |           |              
----------- + -------------------
   ,-, ,-, ,-, ,-, ,-, ,-, ,-,   
---------------------------------
                                 
               
Along Southern Wallrun
Exits: -N -E -W

< 873h/686H 109v/110V |0|1|1|0|1| P: std >

   .-. .-. .-. .-. .-. .-. .-.   
+ | + |   ---- ----   |----   ---
  |   +.-.+   |*-* *-*|   +.-.+  
-- ----   ----|--- ---|----   ---
  |   +.-.|   |.!.|   |   +.-.|  
+ |-+--   | + | + | + | + |   | +
   .!. .!. . . .@. .!. . . . .   
------- + -----------------------
  |           |                  
------- + -----------------------
   ,-, ,-, ,-, ,-, ,-, ,-, ,-,   
---------------------------------
                                 
               
At Southern Wallrun
Exits: -N -E -W
A barbarian shaman looks about warily.
A ruby-throated humming bird hovers here feeding.

< 873h/686H 108v/110V |0|1|1|0|1| P: std >

   .-. .-. .-. .-. .-. .-. .-.   
+ |   | + |----   |----   ----| +
  +.-.|   |*-* *-*|   +.-.+   |  
---    ---|--- ---|----   ---- --
  +.-.|   |   |.!.|   +.-.|   |  
+--   | + | + | + | + |   | + | +
   .!. . . .!. .@. . . . . .!.   
--- + ---------------------------
          |                      
--- + ---------------------------
   ,-, ,-, ,-, ,-, ,-, ,-, ,-,   
---------------------------------
                                 
               
Along Southern Wallrun
Exits: -N -E -W
A grey squirrel sniffs the air cautiously.

< 873h/686H 107v/110V |0|1|1|0|1| P: std >

  +.-.|*-*|^-^|.-.|.-.+.-.|.-.|  
+--   |   |   | + |-+--   | + | +
   .-. .-. .-. .-. .-. .-. .-.   
+ |   | + |----   |----   ----| +
  +.-.|.-.|*-* *-*|.-.+.-.+.-.|  
---    ---|--- ---|----   ---- --
  +.-.|.-.|.-.|.@.|.-.+.-.|.-.|  
+--   | + | + | + | + |   | + | +
   .-. .-. .-. .!. .-. .-. .-.   
--- + ---------------------------
   .-. .-.|                      
--- + ---------------------------
   ,-, ,-, ,-, ,-, ,-, ,-, ,-,   
               
A Hunting Lodge
Exits: -S
A fine layer of dust lies here.
A cobweb hangs from the ceiling here.
A human hunter is here preparing for a hunt.

< 873h/686H 106v/110V |0|1|1|0|1| P: std > 

[Reached train station: (48954) human hunter]

A human hunter is in an excellent condition. (Medium)

< 873h/686H 107v/110V |0|1|1|0|1| P: std > 

[Attacking: Human]

[MELEE: Sweeping Strike] SS HUMAN
You have to be dual wielding to do that.

< 871h/686H 108v/110V |0|2|1|0|1| P: std > 

[Attacking: Human]

[Attacking: Human]

[MELEE: Sweeping Strike] SS HUMAN

[Blades of Fire has expired on Tukin.]
You have to be dual wielding to do that.

< 867h/686H 110v/110V |0|2|1|0|1| P: std >

**Comment by i982** [comment]
problem solved can be closed

**Comment by torilmud-silvanus** [comment]
@i982 what was the solution?

**Comment by i982** [comment]
@torilmud-silvanus Shev was able to restore me.

**Comment by torilmud-silvanus** [comment]
Cool sounds good
