### ISSUE TITLE
"x.scroll" as a keyword keeps bringing up the wrong item

### ISSUE THREAD

**Issue by Dartan82** [torilmud/issues#534]
The Quartermaster's Hold
Exits: -N
A tall, sharp-eyed and grey haired man stands here at ease.
< 685h/537H 118v/121V |dc +|lh +|tn +| |3|3|3|3|2| P: std > list
You can buy:
 1) A rune inscribed scale of a leviathan for 11 platinum, and 4 gold coins. 
 2) A pitch black scroll of identification for 1 platinum, and 8 gold coins. 
 3) A vat of rancid goat milk for 11 platinum, 2 gold, and 5 silver coins. 
 4) The severed head of a medusa for 45 platinum, 3 gold, 2 silver, and 4 copper coins. (*)
 5) An annoyance of netlings scroll for 10 platinum, 3 gold, and 5 silver coins. 
 6) A flickering globe of witchfire for 6 platinum coins. 
 7) A scroll of necrotic glamor for 9 platinum coins. 
 8) A miniature replica of the Captain's Cutlass for 1 platinum, and 2 gold coins. 
 9) A silver treasure chest of the Valkurian Blades for 12984 platinum, 2 gold, 8 silver, and 5 copper coins. 
10) A scroll of Valkurian protection for 1 platinum, and 8 gold coins. 
11) A ruby colored scroll of remove curse for 9 platinum coins. 
12) An enchanted scroll of dispel invisible for 27 platinum coins. 
13) A potion of enhanced vigilance for 12 platinum coins. 
14) A twisted, glowing wand of a sea witch for 183 platinum, 6 gold, 7 silver, and 2 copper coins. (*)
15) Lightning in a jar for 66 platinum, and 6 gold coins. 
16) A crystal vial containing a glowing green maelstrom for 90 platinum coins. 
17) The sharpened spine of a sea urchin for 1 silver, and 8 copper coins. 
18) An ensorcelled scroll of the Mistwalker for 11 platinum, 7 gold, 3 silver, and 6 copper coins. 
19) A misty red vial of manta ray poison for 9 platinum coins. 
20) A crystal vial of jet black kraken's ink for 13 platinum, and 5 gold coins. 

 buy 100 ab.scroll hole
Raith Diagrasonne says 'That'll be 1140 platinum coins for that item.'
You receive a rune inscribed scale of a leviathan(s) from Raith Diagrasonne.

You feel informed:
Name 'a rune inscribed scale of a leviathan'
Keyword 'wb scroll water leviathan scale rune waterbreath scroll', Item type: SCROLL
Item can be worn on:  NOBITS
Item will give you following abilities:  NOBITS
Item is: MAGIC NOBITS
Weight: 0, Value: 9500
Level 26 spells of:
water breathing

g remove.scroll hole
You get a rune inscribed scale of a leviathan from a portable hole.

**Comment by shevarash** [comment]
That's odd - seems like a bug for sure.
