### ISSUE TITLE
memory leak with profile name

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#537]
< 784h/784H 914p/914P 129v/129V P: sit (AFK) > 
who nizara
[onNetworkOutput: WHO nizara]
 Listing of Specific Character
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
[ 1 Druid       ] Nizara  (Moon Elf) (AFK) (@d. Removq)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

who nizara
[onNetworkOutput: WHO nizara]
 Listing of Specific Character
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
[ 1 Druid       ] Nizara  (Moon Elf) (AFK) (@0)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

< 784h/784H 914p/914P 129v/129V P: sit > 

[DisconnectEvent was just called]

**Comment by shevarash** [comment]
I believe this was related to the crash bug that was just fixed. Please re-open if it happens again.
