### ISSUE TITLE
PFU Grants -58 AC

### ISSUE THREAD

**Issue by Casorus** [torilmud/issues#545]
< 734h/734H 120v/120V P: std > 
att

          Character attributes for Casorus

Level: 50   Race: Human   Class: Lich        
Age: 34 yrs / 12 mths  Size: Medium
STR:  80  AGI: 107  DEX:  70  CON: 100
POW:  80  INT: 127  WIS:  75  CHA:  10
Armor Class: -49  (100 to -100)  Agility Bonus: -19
Magic Resistance: 4 percent
Hitroll: 3   Damroll: 4   Undead Points: 50/60
Spell Focus: [Necromancy: +17%] 
Alignment: Lawful Evil
Saving Throws: PAR[0]  ROD[0]  PET[-3]  BRE[-12]  SPE[-7]
   Wimpy: 200
Load carried: Light
Damage Resistance:
Unarmd:    0% Slash :    0% Bludgn:    0% Pierce:    0% Range :    0% 
Spells:    0% Fire  :    5% Cold  :   15% Elect :    0% Acid  :    5% 
Sonic :    0% Poison:    0% Pos   :    5% Neg   :   15% Psi   :    0% 
Mental:    0% Good  :    0% Evil  :    5% Law   :    0% Chaos :    0% 
Force :    0% 

< 734h/734H 120v/120V P: std > 
powers info protection from undead

Name             : Protection From Undead   
Alias            : pfu                      
Type             : Spell                    
Source           : Arcane                   
Prepare          : Study                    
Target           : Character in room
Activation Time  : 6 seconds 
Related Skill    : spellcast necromancy
Restrictions     : Autofire, Garrote, Standing, Can Speak
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Target Effect    : Add protection from undead for 6 minutes 2 seconds 2 pulses  
Target Effect    : Modify armor by -58 for 6 minutes 2 seconds 2 pulses  

< 734h/734H 120v/120V P: std > 

Autosaving...

< 734h/734H 120v/120V P: std > 
pfu me

[SPELL: Protection From Undead] PFU me
You start chanting... [Casting: PFU ME (Protection From Undead)]

< 734h/734H 120v/120V P: std > 

Casting: Protection From Undead ***

< 734h/734H 120v/120V P: std > 

Casting: Protection From Undead **

< 734h/734H 120v/120V P: std > 

Casting: Protection From Undead *

< 734h/734H 120v/120V P: std > 

You complete your spell... [ PFU ME (Protection From Undead) ]
You feel somewhat safer from things that go bump in the night.

< 734h/734H 120v/120V P: std > 
< 734h/734H 120v/120V P: std > 
att

          Character attributes for Casorus

Level: 50   Race: Human   Class: Lich        
Age: 34 yrs / 12 mths  Size: Medium
STR:  80  AGI: 107  DEX:  70  CON: 100
POW:  80  INT: 127  WIS:  75  CHA:  10
Armor Class: -100  (100 to -100)  Agility Bonus: -19
Magic Resistance: 4 percent
Hitroll: 3   Damroll: 4   Undead Points: 50/60
Spell Focus: [Necromancy: +17%] 
Alignment: Lawful Evil
Saving Throws: PAR[0]  ROD[0]  PET[-3]  BRE[-12]  SPE[-7]
   Wimpy: 200
Load carried: Light
Damage Resistance:
Unarmd:    0% Slash :    0% Bludgn:    0% Pierce:    0% Range :    0% 
Spells:    0% Fire  :    5% Cold  :   15% Elect :    0% Acid  :    5% 
Sonic :    0% Poison:    0% Pos   :    5% Neg   :   15% Psi   :    0% 
Mental:    0% Good  :    0% Evil  :    5% Law   :    0% Chaos :    0% 
Force :    0% 

< 734h/734H 120v/120V P: std > 
status

Status of Casorus
---------------------------------------------------------------------------

Effects
---------------------------------------------------------------------------
aware                     infravision               protection from undead    
sense life                

Spells
---------------------------------------------------------------------------
Protection From Undead    (  5:44)   

< 734h/734H 120v/120V P: std > 

Now I'm all for lich buffs but.....is this intentional?

**Comment by shevarash** [comment]
This is definitely a bug - thanks!

**Comment by gruumsh** [comment]
Fixed & merged, see patch notes: http://www.torilmud.com/news/patch-notes-9-27-2019/
