### ISSUE TITLE
Enhance: Practice at level 1

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#546]
It's very common for new 1st level players to be asking why they can't practice / how do they 'learn' something.

Currently, players start at level 1 fully 'practiced' as far as what the guildmaster might teach. Could this be adjusted that the player could practice each known skill at first level? (even if it doesn't actually have an effect).

If nothing else, it would give an early sense of accomplishment.

**Comment by shevarash** [comment]
I don't think this is the right approach, bu tI agree that the current setup is not ideal. I think this will roll up under a general new player overhaul.

**Comment by shevarash** [comment]
I forgot to say - closing for now, but there are plans to address this area of the game.
