### ISSUE TITLE
cluster of glittering cerulean scales

### ISSUE THREAD

**Issue by derwulv** [torilmud/issues#548]
The item:
a cluster of glittering cerulean scales

says it can be worn on earring or tail but it tells me:
You have no tail on which to wear a cluster of glittering cerulean scales!

And I have an empty ear slot when I try to wear the scales

Here is the ID of the item as of (18 Apr 2019)

You feel informed:
Name 'a cluster of glittering cerulean scales'
Keyword 'cluster scales glittering cerulean wb', Item type: TREASURE
Item can be worn on:  EARRING TAIL 
Item will give you following abilities:  WATERBREATH 
Item is: MAGIC FLOAT NOBURN NOLOCATE NOBITS
Weight: 0, Value: 0

**Comment by marthammor** [comment]
Try 'wear scales ear' and see if that works. 

⁣Sent from BlueMail ​

**Comment by derwulv** [comment]
That took care of it.

Thanks...
