### ISSUE TITLE
Help Files - Missile Shield should be removed from help_enchanter

### ISSUE THREAD

**Issue by Gyrx** [torilmud/issues#549]
This is leading to confusion for new players.

Example:
Tusse 'hole me'
Beniwozil '3rd level enchanter spell 'missile shield' listed 
in help skill_enc, but not powers..  anyone know what 
happened to it?'
You 'missile shield was removed from the game when rangers 
powers update happened.  should be removed from the help file 
/'
You ':/'
Beniwozil 'hmm  rangers messing with us enchanters! grr :}  
thanks :}'

**Comment by OghmaToril** [comment]
Will be fixed in next typo-fix release.
