### ISSUE TITLE
Suggestion: make bodycontrol like realms

### ISSUE THREAD

**Issue by Adriorn** [torilmud/issues#55]
So that psis have a self-only realms.

**Comment by dnavarro** [comment]
I support this

Possible Idea: Potentially giving bodycontrol arguments could allow for different uses of the skill. 

Example:
<bodycontrol waterbreath> gives waterbreathing
<bodycontrol elements> gives resist elements

They can have differing psp costs this way, in the case that we want one to be more expensive. Also this approach could lead to some interesting interactions with other Resists.... 
<bodycontrol physical> perhaps?

**Comment by shevarash** [comment]
Thanks for the feedback. This will be considered in an upcoming Psionicist class overhaul.
