### ISSUE TITLE
Half-orc agi is better than Half-elf agi

### ISSUE THREAD

**Issue by Dartan82** [torilmud/issues#551]
Can we relook at half-elf stats?  Half-orcs were just so good vs. half-elf and their other half (not human) should be way better than orc.

**Comment by CountVooku** [comment]
I hub'd this a year ago. Human 100 + Orc 100 = HOrc 115... Human 100 + Elf 130 = HElf 105? *boggle*

If HElf agi was 120 they'd be worth playing imo.

**Comment by shevarash** [comment]
This is a fair criticism, and we do have plans to address and update racial stats. I'm going to close this issue, but we are working on addressing this in future updates.
