### ISSUE TITLE
Item proc based on old skill - no longer works

### ISSUE THREAD

**Issue by Lamnicaes** [torilmud/issues#555]
Item: a fine mithril shield embedded with spikes

The 'spike' called proc on this shield tries to do a shiledpunch, but never lands on any mob worth using it on. Needs to be changed to a power(like plundering smite, or comeback strike), or just a skill of it's own.

eg, I'm level 50 Blk.
You miss a lithe commoner with your clumsy shieldpunch!

**Comment by beshaba-toril** [comment]
Fixed and merged to main.
