### ISSUE TITLE
script bug: motd change

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#556]
The recent change to the motd on login is causing me a slight issue, I was triggering on part of it as a way to recognize that you'd just logged in to the mud without reconnecting. The final couple lines of it used to be: 

Find us on the web:

Web Client : http://www.torilmud.com/login
News       : http://news.torilmud.com/
Support    : http://toril.lighthouseapp.com/
Forums     : http://www.torilmud.org/phpBB3/

I've been using ^Find us on the web[:]$ as a trigger pattern. Would it be possible to restore those that few lines?

**Comment by shevarash** [comment]
This was done.
