### ISSUE TITLE
TYPO - Help file - skill_cleric

### ISSUE THREAD

**Issue by Kukako** [torilmud/issues#558]
Hey just noticed that the help file for **skill_cleric** contains the following and seems to be bit missleading.

```
See also:  CLERIC, WEAPONS, CIRCLE, SPELLCAST, SPECIALIZE, MAGIC,
SKILLS
```
Probably should be

```
See also:  CLERIC, WEAPONS, "SPELL CIRCLE", SPELLCAST, SPECIALIZE, MAGIC,
SKILLS
```

**Comment by OghmaToril** [comment]
Will be resolved in next typo-fix release.
