### ISSUE TITLE
bracers of elemental fury

### ISSUE THREAD

**Issue by Alurissi** [torilmud/issues#56]
original bracers are elementalist only, upgraded is missing 2 anti flags, illusionist and bard........and while we're at it, since they take elemental tempest.......why not add 5% electric to them!?!? not like there's a big change in stats to begin with, just 1 mr for 3sf_ele!

**Comment by dnavarro** [comment]
- [ ] agreed that the anti flag hole needs plugging

the pfl request is not too crazy, though the sf transfer really is solid on its own imo, i still wouldnt mind the definitive ele bracer receiving some love. the question just becomes whether to enhance it during this quest, or make this just one step in the upgrade process

alternatively swapping a prot for pfl would be do-able, but i would expect that to feel like a dg
