### ISSUE TITLE
Breach targets self by default

### ISSUE THREAD

**Issue by shevarash** [torilmud/issues#560]
Attribution:

Lilithelle OOC: 'do you know if you type brc (breach) while fighting a mob, you breach yourself?'

**Comment by ghost** [comment]
as it's been pointed out, since inception, EVERY power targets self first, aoe powers target from top of room list down, and if you include a keyword, and mobs aren't aggro to YOU, it'll only hit the mobs with that keyword, never mind the other mobs killing your tank
