### ISSUE TITLE
a crimson-edged obsidian blade proc extra messed up message

### ISSUE THREAD

**Issue by mrizzalazzrazzi** [torilmud/issues#561]
Please check the proc message on a crimson-edged obsidian blade. There  are  some sort of  extra incomplete proc  message shown when  the weapon procs. Example  below;

Your crimson-edged obsidian blade pulses crimson in a torrent of unholy might!
An inky black miasma writhes forth from your blade coating an especially large cave
spider in Stygian darkness!
as you can think of nothing
but destroying your foes.
Nothing seems to happen.
You attack an especially large cave spider, landing three hits.

**Comment by mrizzalazzrazzi** [comment]
today i got another more weird proc  message...


Your crimson-edged obsidian blade pulses crimson in a torrent of unholy might!
An inky black miasma writhes forth from your blade coating a stone golem in Stygian
darkness!
lare as you can think of nothing
but destroying your foes.
 throat. he lets the sound build,
and build, till he releases it in a devastating torrent. The air itself seems to shudder
and shake with sonic energy. Expanding outward in a cone, the force of the airy blast
violently assaults anything it encounters. Pieces of metal and flesh are carried away
by the devastating wind.

A stone golem seems to be blinded!



dont  know where those  proc message comes...strange

**Comment by gruumsh** [comment]
This bug has since been fixed.
