### ISSUE TITLE
Blackguard: Plundering Smite not vamping over max

### ISSUE THREAD

**Issue by projectx43** [torilmud/issues#562]
Name             : Plundering Smite         
Alias            : ps                       
Type             : Melee                    
Source           : Martial                  
Attack Type      : Armor                    
Target           : Offense
Recharge         : 12 seconds 
Implements       : Weapon, Shield, One handed
Restrictions     : Standing, Can See
To-Hit Mods      : Level Diff +1, Str 25%, Hit Roll 200%
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Target Effect    : Strike with all weapons for 300% (Weapon, Shield, One handed) Mod: +200% 
Self Effect      : Vampiric heal 50 hit points, up to 120% of max     
Miss Effect      : Strike with all weapons for 100% (Weapon, Shield, One handed)

<primary weapon>     a rune graven adamantine longsword (glowing)

< 663h/663H 120v/120V |ds +|ps +|dm +|rs +|fs +|drs +|rav +|bc +| P: std >

< 663h/663H 120v/120V |ds +|ps +|dm +|rs +|fs +|drs +|rav +|bc +| P: std > ds aratha
You advance upon Aratha Sul with a series of devastating blows that send her crashing to the ground.
< 663h/663H 120v/120V |ds 3|ps +|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: few scratches EP: rcl P: std > 
Aratha Sul stops chanting abruptly!
< 663h/663H 120v/120V |ds 3|ps +|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: few scratches EP: rcl P: std > 
A momentary brilliant glow originating from your circlet begins
a rapid change in your appearance. Countless serpents begin to uncoil,
slithering and sliding their way down and around your arms, neck,
and torso, granting you a reptilian quickstrike ability! Your eyes gleam
a vivid yellow as the brief enchantment begins to fade. Quickly as
they descended, the serpents twist and twine their way back to the magic
within their circlet.
You score a CRITICAL HIT!
Your massive slash barely wounds Aratha Sul.
Your massive slash barely wounds Aratha Sul.
Your massive slash barely wounds Aratha Sul.
Your massive slash barely wounds Aratha Sul.
Your massive slash barely wounds Aratha Sul.
Your massive slash barely wounds Aratha Sul.
Your massive slash barely wounds Aratha Sul.
< 663h/663H 120v/120V |ds 3|ps +|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: few scratches EP: rcl P: std > 
You score a CRITICAL HIT!
You attack Aratha Sul, landing three hits.
< 663h/663H 120v/120V |ds 3|ps +|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: small wounds EP: rcl P: std > 
< 663h/663H 120v/120V |ds 3|ps +|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: small wounds EP: rcl P: std > ps
**Your strike leaves a vile blight on Aratha Sul, and some of her life flows into you.
< 663h/663H 120v/120V |ds 2|ps 3|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: small wounds EP: rcl P: std >** 
You score a CRITICAL HIT!
You have learned something new about 1h slashing!
You attack Aratha Sul, landing three hits.
< 663h/663H 120v/120V |ds 2|ps 3|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: small wounds EP: rcl P: std > 
You attack Aratha Sul, landing three hits.
< 663h/663H 120v/120V |ds 1|ps 2|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: small wounds EP: rcl P: std > 
Aratha says, 'Lets see who luck favors.'
You attack Aratha Sul, landing three hits.
Aratha Sul clambers to her feet.
ds
< 663h/663H 120v/120V |ds +|ps 1|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: small wounds EP: std P: std > You advance upon Aratha Sul with a series of devastating blows that send her crashing to the ground.
< 663h/663H 120v/120V |ds 3|ps 1|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: small wounds EP: rcl P: std > 
You attack Aratha Sul, landing three hits.
< 663h/663H 120v/120V |ds 2|ps +|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: few wounds EP: rcl P: std > ps
**Your strike leaves a vile blight on Aratha Sul, and some of her life flows into you.
< 663h/663H 120v/120V |ds 1|ps 3|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: few wounds EP: rcl P: std >** 
You attack Aratha Sul, landing three hits.
< 663h/663H 120v/120V |ds 1|ps 3|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: few wounds EP: rcl P: std > 
You attack Aratha Sul, landing three hits.
< 663h/663H 120v/120V |ds 1|ps 2|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: few wounds EP: rcl P: std >  
You attack Aratha Sul, landing two hits.
Aratha Sul clambers to her feet.
ds
< 663h/663H 120v/120V |ds +|ps 1|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: few wounds EP: std P: std > You advance upon Aratha Sul with a series of devastating blows that send her crashing to the ground.
< 663h/663H 120v/120V |ds 3|ps 1|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: few wounds EP: rcl P: std > 
A momentary brilliant glow originating from your circlet begins
a rapid change in your appearance. Countless serpents begin to uncoil,
slithering and sliding their way down and around your arms, neck,
and torso, granting you a reptilian quickstrike ability! Your eyes gleam
a vivid yellow as the brief enchantment begins to fade. Quickly as
they descended, the serpents twist and twine their way back to the magic
within their circlet.
Your massive slash barely wounds Aratha Sul.
You miss Aratha Sul with your slash.
Your massive slash barely wounds Aratha Sul.
< 663h/663H 120v/120V |ds 2|ps +|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: few wounds EP: rcl P: std > 
You attack Aratha Sul, landing three hits.
< 663h/663H 120v/120V |ds 2|ps +|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: few wounds EP: rcl P: std > ps
**Your strike leaves a vile blight on Aratha Sul, and some of her life flows into you.
< 663h/663H 120v/120V |ds 1|ps 3|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: few wounds EP: rcl P: std >**  
You attack Aratha Sul, landing two hits.
< 663h/663H 120v/120V |ds 1|ps 3|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: few wounds EP: rcl P: std > 
A momentary brilliant glow originating from your circlet begins
a rapid change in your appearance. Countless serpents begin to uncoil,
slithering and sliding their way down and around your arms, neck,
and torso, granting you a reptilian quickstrike ability! Your eyes gleam
a vivid yellow as the brief enchantment begins to fade. Quickly as
they descended, the serpents twist and twine their way back to the magic
within their circlet.
Your massive slash barely wounds Aratha Sul.
Your massive slash barely wounds Aratha Sul.
You score a CRITICAL HIT!
Your massive slash slightly wounds Aratha Sul.
Your massive slash barely wounds Aratha Sul.
You score a CRITICAL HIT!
Your massive slash slightly wounds Aratha Sul.
Your massive slash barely wounds Aratha Sul.
You score a CRITICAL HIT!
Your massive slash badly wounds Aratha Sul.
You attack Aratha Sul, landing three hits.
< 663h/663H 120v/120V |ds 1|ps 2|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: nasty wounds EP: rcl P: std > 
You score a CRITICAL HIT!
You attack Aratha Sul, landing two hits.
Aratha Sul clambers to her feet.
ds
< 663h/663H 120v/120V |ds +|ps 1|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: nasty wounds EP: std P: std > You advance upon Aratha Sul with a series of devastating blows that send her crashing to the ground.
< 663h/663H 120v/120V |ds 3|ps 1|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: nasty wounds EP: rcl P: std > 
You attack Aratha Sul, landing three hits.
< 663h/663H 120v/120V |ds 2|ps +|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: nasty wounds EP: rcl P: std > ps
**Your strike leaves a vile blight on Aratha Sul, and some of her life flows into you.
< 663h/663H 120v/120V |ds 1|ps 3|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: pretty hurt EP: rcl P: std >** 
Your longsword glows dark and bites into Aratha Sul's neck.
Aratha Sul seems to be blinded!
You score a CRITICAL HIT!
You attack Aratha Sul, landing three hits.
< 663h/663H 120v/120V |ds 1|ps 3|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: pretty hurt EP: rcl P: std > 
You score a CRITICAL HIT!
You attack Aratha Sul, landing three hits.
< 663h/663H 120v/120V |ds 1|ps 2|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: pretty hurt EP: rcl P: std > 
You score a CRITICAL HIT!
You attack Aratha Sul, landing three hits.
Aratha Sul clambers to her feet.
ds
< 663h/663H 120v/120V |ds +|ps 1|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: pretty hurt EP: std P: std > You advance upon Aratha Sul with a series of devastating blows that send her crashing to the ground.
< 663h/663H 120v/120V |ds 3|ps 1|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: pretty hurt EP: rcl P: std > 
A momentary brilliant glow originating from your circlet begins
a rapid change in your appearance. Countless serpents begin to uncoil,
slithering and sliding their way down and around your arms, neck,
and torso, granting you a reptilian quickstrike ability! Your eyes gleam
a vivid yellow as the brief enchantment begins to fade. Quickly as
they descended, the serpents twist and twine their way back to the magic
within their circlet.
You score a CRITICAL HIT!
Your massive slash severely wounds Aratha Sul.
Your massive slash slightly wounds Aratha Sul.
Your massive slash slightly wounds Aratha Sul.
< 663h/663H 120v/120V |ds 3|ps 1|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: pretty hurt EP: rcl P: std > 
Aratha says, 'Lets see who luck favors.'
< 663h/663H 120v/120V |ds 2|ps +|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: pretty hurt EP: rcl P: std > ps
You're not ready to perform another action!
< 663h/663H 120v/120V |ds 2|ps +|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: pretty hurt EP: rcl P: std > 
You score a CRITICAL HIT!
You attack Aratha Sul, landing three hits.
< 663h/663H 120v/120V |ds 2|ps +|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: awful EP: rcl P: std > ps
**Your strike leaves a vile blight on Aratha Sul, and some of her life flows into you.
< 663h/663H 120v/120V |ds 1|ps 3|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: awful EP: rcl P: std >** 
You attack Aratha Sul, landing three hits.
< 663h/663H 120v/120V |ds 1|ps 3|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: awful EP: rcl P: std > 
Aratha says, 'Lets see who luck favors.'
< 663h/663H 120v/120V |ds 1|ps 2|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: awful EP: rcl P: std > 
You score a CRITICAL HIT!
You attack Aratha Sul, landing three hits.
< 663h/663H 120v/120V |ds 1|ps 2|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: awful EP: rcl P: std > 
You attack Aratha Sul, landing two hits.
Aratha Sul clambers to her feet.
ds
< 663h/663H 120v/120V |ds +|ps 1|dm +|rs +|fs +|drs +|rav +|bc +| T: Azheh TC: excellent E: aratha EC: awful EP: std P: std > Aratha Sul slumps to the ground.
You advance mercilessly upon Aratha Sul, raining down blow after blow until she lays defeated before you.
Aratha Sul is dead! R.I.P.
Aratha Sul slumps to the ground.
You receive 256,047 XP (0.68%) experience.
get coins corpse
put all.coin cube
Your blood freezes as you hear the rattling death cry of Aratha Sul.

**Comment by Nyyrazzilyss** [comment]
Might be related to https://github.com/torilmud/issues/issues/347

**Comment by shevarash** [comment]
This was fixed.
