### ISSUE TITLE
Narrow Rooms

### ISSUE THREAD

**Issue by vitaladsr** [torilmud/issues#565]
Narrow rooms are an interesting thing here. Often either a pain in the butt or a way for PC's to twink mobs .. which is cool its strategic. I am wondering about how the size of mobs can add another dimension to this aspect of the game. It would make sense that tiny mobs like insects, fairys etc. wouldn't be affected as much as larger mobs ... mabye this aspect of the game can be revised to take that into consideration.

**Comment by Nyyrazzilyss** [comment]
That could be interesting - A swarm of bees attacking in a single file room?

**Comment by shevarash** [comment]
This is a good idea. Closing the ticket since it's not actionable, but I'll label it so we can find it.
