### ISSUE TITLE
Cleric - Divine Power - Powers Alias - Divine Purification - Conflict

### ISSUE THREAD

**Issue by Kukako** [torilmud/issues#566]
Having problems with **Divine Power** on my **Duergar Cleric**. I have the spell learned and the power alias `dp` for it casts **Divine Purification**.

Also doesn't seem to work with the normal `cast 'divine power'`.

In the prayed spells list it is also lower case like its still not converted to the new powers?

**Works after re-logging, must be old spell týpe to power conversion problem.**

**Comment by shevarash** [comment]
Closing since you noted that it's working now. If I misunderstood please re-open.
