### ISSUE TITLE
Physical resists do not mitigate dragon talon

### ISSUE THREAD

**Issue by Dartan82** [torilmud/issues#567]
Dragon talon can do anywhere from 600-1100 hp and are not mitigated by any physical resists.  Shevarash mentioned this was not intended on discord

**Comment by torilmud-silvanus** [comment]
Probably need to check the dragon procs and make sure their damage is being assigned type

**Comment by shevarash** [comment]
I'm assuming that you mean this attack:

```You shriek in pain as Scorxariam plunges a razor-sharp wing talon into your flesh!```

If so, I checked this and it is currently doing piercing damage and is correctly reduced by piercing resistance in my testing. If I'm not understanding the issue can you please elaborate or post a log? Thanks!

**Comment by Dartan82** [comment]
Hmm maybe it is the claw attack then?  One of the attacks ignores it for sure.

**Comment by shevarash** [comment]
I think I see what you're referring to now. The dragon attacks themselves are all properly damage typed, but the wing spike attack has a critical hit component that bypasses resists. There is a saving throw though. You may want to invest in higher constitution to avoid this proc. Closing as this is actually intended.
