### ISSUE TITLE
Remove Earring

### ISSUE THREAD

**Issue by Inames** [torilmud/issues#569]
Remove earring doesn't work for 2nd earring slot because of the new remove by slotname code, please change it to remove ear/2.ear so we can use earring as a keyword on our earrings.

**Comment by shevarash** [comment]
I don't understand the issue. Can you please provide a log?

Here's mine:

```
You are using:
<worn in ear>        [ 5720] a tiny golden earring (magic)
<worn in ear>        [96077] a tiny earring woven of fireweed (magic)

> rem 2.earring

< > You stop using a tiny earring woven of fireweed.
```

**Comment by Gyrx** [comment]
Log:

< 415h/415H 171v/171V P: std > 
wear earring
[onNetworkOutput: wear earring]
You wear an emerald earring on your right ear.

< 415h/415H 171v/171V P: std > 
eq
[onNetworkOutput: EQ]
You are using:
<worn as a badge>    a tattoo of three bolts of lightning over a cutlass (glowing)
<worn on head>       a winged shining steel great helm
<worn on eyes>       a silvered scale of deepest blue hue
<worn in ear>        an emerald earring (x2)
<worn on face>       a cringing mask of the trickster
<worn around neck>   the black steel amulet of the crescent moon (x2)
<worn on body>       some jagged armor of serpent teeth
<worn about body>    the flaming feathers of a phoenix
<worn as quiver>     a hard leather sword scabbard
<worn about waist>   a luminous cincture of nightfallen stars
<worn on arms>       matte black drow chainmail sleeves
<worn around wrist>  a golden wrist band
<worn around wrist>  a bracelet of flowing shadows
<worn on hands>      a pair of gauntlets wreathed in electricity (glowing)
<worn on finger>     a flaming ring of the efreeti (x2)
<primary weapon>     a blunt training knife
<held>               a squirming metallic string
<worn on legs>       some gem studded leggings of Flandal
<worn on feet>       a pair of taut red leather boots with adamantine buckles
< 415h/415H 171v/171V P: std > 
rem earring
[onNetworkOutput: rem earring]
You stop using an emerald earring.
rem earring
[onNetworkOutput: rem earring]

< 415h/415H 171v/171V P: std >

Remove what?

< 415h/415H 171v/171V P: std >
