### ISSUE TITLE
a blackened dirk can't be used to backstab

### ISSUE THREAD

**Issue by ebuchmann** [torilmud/issues#571]
primary weapon - a blacked dirk

Name 'a blackened dirk'
Keyword 'blackened dirk shadow', Item type: WEAPON
Item can be worn on:  WIELD 
Item will give you following abilities:  NOBITS
Item is: NOBITSNOBITS
Weight: 1, Value: 600
Type: Flail Class: Martial
Damage:  1D6  Crit Range: 3%  Crit Bonus: 2x

Seems odd that this is a flail that pierces. Can't actually backstab with it, when it seems like this should be a dagger since the attack verb is pierce and all.

**Comment by torilmud-silvanus** [comment]
This should not be a flail. This should be changed to dagger.

**Comment by OghmaToril** [comment]
This should go in with my next update.
