### ISSUE TITLE
Bahamut djinn's whirlwinds have no cooldown

### ISSUE THREAD

**Issue by Dartan82** [torilmud/issues#574]
Log confirms only 1 djinn in, 2 whirlwinds within a couple of seconds.
          
In a Lookout Atop the Tower
Exits: -N -E -S -W -D
Corpse of Sarberos is lying here.
Corpse of Zenasha is lying here.
Blood is smeared all over the area.
Edcat  (Drow Elf) stands in mid-air here, fighting an ancient brass dragon.
Sunay  (RP) (Barbarian) hulks in mid-air here, fighting Ileuthra.
Gedd  (Barbarian) stands here, fighting Ileuthra.
Kohut  (Barbarian) stands in mid-air here, fighting Ileuthra.
Satac  (Barbarian) is lying here, fighting Ileuthra.
Ogof  (Barbarian) is lying in mid-air here, fighting Ileuthra.
Erreth  (Half-Elf) stands here, fighting Ileuthra.
A djinn stands in mid-air here, fighting YOU!
An ancient brass dragon stands in mid-air here, fighting Edcat.
An ancient brass dragon stands in mid-air here, fighting YOU!
Ileuthra stands in mid-air here, fighting Sunay.
< 471h/1203H 220v/220V |ts 2|ss +|ap 2|ev 5|bs 7| |1|2|3|0|1| T: Sunay TC: few scratches E: ileuthra EC: awful EP: std P: rcl > Ileuthra closes the gap in his defenses.
You clamber to your feet.
Ogof clambers to his feet.
Edcat switches targets..
< 471h/1203H 220v/220V |ts 2|ss +|ap 2|ev 5|bs 7| |1|2|3|0|1| T: Sunay TC: few scratches E: ileuthra EC: awful EP: std P: std > You sweep attack Ileuthra with unbound fury, knocking him off balance!
Satac clambers to his feet.
< 471h/1203H 220v/220V |ts 1|ss 3|ap 1|ev 4|bs 6| |1|2|3|0|1| T: Sunay TC: few scratches E: ileuthra EC: awful EP: std P: std > That power hasn't recharged yet!
Ogof attempts to flee.
Ogof flies south.
< 471h/1203H 220v/220V |ts 1|ss 3|ap 1|ev 4|bs 6| |1|2|3|0|1| T: Sunay TC: few scratches E: ileuthra EC: awful EP: std P: std > That power hasn't recharged yet!
< 471h/1203H 220v/220V |ts 1|ss 3|ap 1|ev 4|bs 6| |1|2|3|0|1| T: Sunay TC: few scratches E: ileuthra EC: awful EP: std P: std > 
A momentary brilliant glow originating from Kohut's circlet begins
a rapid change in his appearance. Countless serpents begin to uncoil,
slithering and sliding their way down and around Kohut's arms, neck,
and torso, granting him a reptilian quickstrike ability! As his eyes gleam
a vivid yellow the brief enchantment begins to fade. Quickly as
they descended, the serpents twist and twine their way back to the magic
within their circlet.
Kohut barely wounds Ileuthra with his mighty bludgeon.
Kohut slightly wounds Ileuthra with his massive bludgeon.
Kohut slightly wounds Ileuthra with his massive bludgeon.
Kohut slightly wounds Ileuthra with his massive bludgeon.
Kohut misses Ileuthra with his bludgeon.
< 471h/1203H 220v/220V |ts 1|ss 3|ap 1|ev 4|bs 6| |1|2|3|0|1| T: Sunay TC: few scratches E: ileuthra EC: awful EP: std P: std > 
Ogof flies in from the south.
< 471h/1203H 220v/220V |ts 1|ss 3|ap 1|ev 4|bs 6| |1|2|3|0|1| T: Sunay TC: few scratches E: ileuthra EC: awful EP: std P: std > 
Ogof flies north.
< 471h/1203H 220v/220V |ts 1|ss 3|ap 1|ev 4|bs 6| |1|2|3|0|1| T: Sunay TC: few scratches E: ileuthra EC: awful EP: std P: std > 
ts
Ileuthra utters the words, 'summon djinni'.

Ileuthra trembles and appears vulnerable!
< 471h/1203H 220v/220V |ts 1|ss 3|ap 1|ev 4|bs 6| |1|2|3|0|1| T: Sunay TC: few scratches E: ileuthra EC: awful EP: std P: std > That power hasn't recharged yet!
< 471h/1203H 220v/220V |ts 1|ss 3|ap 1|ev 4|bs 6| |1|2|3|0|1| T: Sunay TC: few scratches E: ileuthra EC: awful EP: std P: std > ts
That power hasn't recharged yet!
Gurkz enters from the north.
< 471h/1203H 220v/220V |ts 1|ss 3|ap 1|ev 4|bs 6| |1|2|3|0|1| T: Sunay TC: few scratches E: ileuthra EC: awful EP: std P: std > 
Gurkz brutally wounds Ileuthra with his massive slash.
< 471h/1203H 220v/220V |ts 1|ss 3|ap 1|ev 4|bs 6| |1|2|3|0|1| T: Sunay TC: few scratches E: ileuthra EC: awful EP: std P: std > 
ts
Gurkz attacks Ileuthra, landing three hits.
Edcat is slammed down on the ground!
Ileuthra attacks Sunay, landing a single hit.
Ileuthra launches into the air and streaks toward his foes!
Sunay is knocked down on his knees!
Gedd is knocked down on his knees!
Kohut is knocked down on his knees!
Rolanis screams in terror as she is crushed beneath Ileuthra!
You are knocked down on the ground!
st
Gedd quickly falls silent as Ileuthra impales him on a razor-sharp wing talon!
Gedd is dead! R.I.P.
Your blood freezes as you hear the rattling death cry of Gedd.
Gedd has died!
Sunay attacks Ileuthra, landing two hits.
An ancient brass dragon badly wounds you with his powerful claw.
An ancient brass dragon misses you with his claw.
An ancient brass dragon misses you with his claw.
An ancient brass dragon misses you with his claw.
An ancient brass dragon breathes a cone of fire!
Edcat is dead! R.I.P.
Your blood freezes as you hear the rattling death cry of Edcat.
Edcat has died!
OUCH!  That really did HURT!
A djinn misses you with her shocking slash.
A djinn misses you with her shocking slash.
A djinn misses you with her shocking slash.
A djinn misses you with her shocking slash.
A djinn misses you with her shocking slash.
Kohut attacks Ileuthra, landing two hits.
Satac attacks Ileuthra, landing three hits.
You cave in Ileuthra's chest, he dies rather quickly.
Ileuthra is dead! R.I.P.
You receive 56,522 XP at Time: Friday July 5, 2019 6:44:26 pm (0.19%) experience.
Your blood freezes as you hear the rattling death cry of Ileuthra.
Something pulsates briefly, calling out to something...
Within moments, the soul of Ileuthra surrounds the orb.
Suddenly a mild concussive shockwave and a blinding flash of light bathes the room...

Soon, the radiance subsides, slowly pulsating as it recedes into an orb of dragonkind
An ancient brass dragon stops following Ileuthra.
An ancient brass dragon stops following Ileuthra.
< 305h/1203H 220v/220V |ts 1|ss 3|ap 1|ev 4|bs 6| |1|2|3|0|1| P: rcl > 
ts
Zenasha group-says 'ill just sit back...'
< 305h/1203H 220v/220V |ts 1|ss 3|ap 1|ev 4|bs 6| |1|2|3|0|1| P: rcl > 
a djinn's whirlwind whips at Rolanis's body and pounds her with flying debris.
OUCH!  That really did HURT!
Lilabipple group-says 'regroup'
Gedd group-says 'Vitality Out --------- Larim'
< 155h/1203H 220v/220V |ts +|ss 2|ap +|ev 3|bs 5| |1|2|3|0|1| T: Rolanis TC: awful E: djinn EC: few scratches EP: std P: rcl > 
n
Lilabipple group-says 'regroup'
< 155h/1203H 220v/220V |ts +|ss 2|ap +|ev 3|bs 5| |1|2|3|0|1| T: Rolanis TC: awful E: djinn EC: few scratches EP: std P: rcl > a djinn's whirlwind pounds you to death.
a djinn's whirlwind pounds Rolanis to death.
With a final blow, you feel yourself falling to the ground.

**Comment by Tiamafas** [comment]
Ileuthra utters the words, 'summon djinni'.

Does this mean he might have summoned another so there was actually 2 in the room?

**Comment by Dartan82** [comment]
Not at all...

**Comment by gruumsh** [comment]
It looks like it could be two different djinns. One already in room, doing 5 hits of slashing damage. ~then the other one doing bludgeon/unarmed type damage. Nevermind, that's from the power.~ 

Still, both whirlwinds might have come from the same djinn, so it's something to keep an eye out for.

**Comment by Dartan82** [comment]
Both whirlwinds did come from the djinn.  Ileuthra's summon djinn just means there may be a djinn coming soon from .nw of the fight.  This looks similar to how leonals would spam roars

**Comment by gruumsh** [comment]
Fixed & merged, see patch notes: http://www.torilmud.com/news/patch-notes-9-27-2019/
