### ISSUE TITLE
Gear poofed on moving again...

### ISSUE THREAD

**Issue by i982** [torilmud/issues#576]
< 585h/621H 122v/122V |0|1|0|0|1| T: Valahir TC: few scratches E: lieutenant EC: awful EP: std P: std > 
< 585h/621H 122v/122V |0|1|0|0|1| T: Valahir TC: few scratches E: lieutenant EC: awful EP: std P: std > 

Your massive vampiric slash brutally wounds a lieutenant of the Knights in Silver.
Your massive vampiric slash brutally wounds a lieutenant of the Knights in Silver.
You critically wound a lieutenant of the Knights in Silver with a massive vampiric slash!
You critically wound a lieutenant of the Knights in Silver with a massive vampiric slash!
A lieutenant of the Knights in Silver is nearly slain by the force of your massive vampiric slash!
A lieutenant of the Knights in Silver dodges your futile attack.
A lieutenant of the Knights in Silver misses you with her hit.
A lieutenant of the Knights in Silver misses you with her hit.

< 612h/621H 122v/122V |0|1|0|0|1| T: Valahir TC: few scratches E: lieutenant EC: awful EP: std P: std > 

[MELEE: Sweeping Strike] SS
A lieutenant of the Knights in Silver closes the gap in her defenses.

< 612h/621H 122v/122V |0|1|0|0|1| T: Valahir TC: few scratches E: lieutenant EC: awful EP: std P: std >

A lieutenant of the Knights in Silver is stunned!
A lieutenant of the Knights in Silver slumps to the ground.
You sweep a lieutenant of the Knights in Silver to the ground and finish her with a pair of killing blows.
a lieutenant of the Knights in Silver is dead! R.I.P.
A lieutenant of the Knights in Silver slumps to the ground.
You receive 0 XP (0.00%) experience.
Your blood freezes as you hear the rattling death cry of a lieutenant of the Knights in Silver.

[Calling function: NextTrainStop()]

< 612h/621H 122v/122V |0|1|0|0|1| P: std > 
You get a small pile of coins from corpse of a lieutenant of the Knights in Silver.
put all.coin portable;put all portable
There were: 5 platinum coins, 20 gold coins, 6 silver coins, 1 copper coin.

< 612h/431H 122v/122V |0|1|0|0|1| P: std >

< 612h/431H 122v/122V |0|1|0|0|1| P: std >

Ok.
You put some coins into a portable hole.

< 612h/431H 122v/122V |0|1|0|0|1| P: std >

You can't do that. Perhaps that item is cursed?
You can't do that. Perhaps that item is cursed?
You can't do that. Perhaps that item is cursed?
You don't have anything to put in it.

< 612h/431H 122v/122V |0|1|0|0|1| P: std > 

Cthylla GCC: 'elk and moose as well'

< 611h/431H 122v/122V |0|1|0|0|2| P: std > 

[Moving to: Human Noble (49063)  <.wne>]
Pardon?

< 609h/431H 122v/122V |0|1|0|0|2| P: std > 
@fwalk 49063
[Path: .wne]
w

[Currently moving. Spellcasting is temporarily paused.]

n
e

Mulgate Avenue
   A wide cobbled stone street Mulgate runs from the banks of the River
Rauvin in the north to the southern Wallrun.  A wide street it has many
large homes.  Near the Lady's College and Mielikki's Glade wizards and
druids can often been found walking the sidewalks.  The trees lining
the street are mostly small and ornamental allowing the sun to shine
through in the day and the moon to light the night.  A large
intersection can be seen to the south.
Exits: - North - East  - South - West                  [49059] 
A half-elven guide wanders town looking for an employer.
A majestic eagle perches here.
A spotted housecat is here looking for mice.

< 606h/431H 121v/122V |0|1|0|0|2| P: std >

At the End of Mulgate Avenue
   On the north bank the streets tend to run at odd angles and are
narrow.  Here on the south bank the streets run straight and are wide
enough for two carriages to pass each other.  Flat stone sidewalks
elevated above the street run on both sides.  The houses here are large
and are no doubt home to the well-to-do.  The streets are paved in
cobbled stone and aren't as rutted as those in the north but still
thousands of wheels have left their mark.
Exits: - North - East  - South - West                  [49062] 
A gnome tinker journeys here.
An austere commoner struts about.

< 606h/431H 120v/122V |0|1|0|0|2| P: std >

A Noble's Home
   The Rauvin River lies just to the north of the homes here, near
where it changes its course from west to east to north to south.  The
soil here is sandy where the river has deposited its silt.  The front
of this home is lined with white marble columns giving the structure an
air of timelessness.  The marble gleams from regular cleanings.  Two
large oak doors lead inside.  A large foyer greets guests with a forest
of columns holding up the high stone ceiling.  Twin stone stairs with
marble banisters frame the room leading to the residential quarters
upstairs.  A number of wooden doors in the foyer lead to the kitchen
and other rooms used by the household staff.
Exits: - West          [49063] 
An ornate gilded metal cage hangs here.
A human noble stands here haughtily.

< 606h/431H 119v/122V |0|1|0|0|2| P: std > 

[Reached train station: (49063) human noble]

A human noble is in an excellent condition. (Medium)

< 605h/431H 119v/122V |0|1|0|0|2| P: std > 

[Attacking: Human]

[MELEE: Sweeping Strike] SS HUMAN
You have to be dual wielding to do that.

< 603h/431H 121v/122V |0|1|0|0|2| P: std > 

[Attacking: Human]

[Attacking: Human]

[MELEE: Sweeping Strike] SS HUMAN
You have to be dual wielding to do that.

< 600h/431H 122v/122V |0|1|0|0|2| P: std > 

[Attacking: Human]

[Attacking: Human]

[MELEE: Sweeping Strike] SS HUMAN
You have to be dual wielding to do that.

< 597h/431H 122v/122V |0|1|0|0|2| P: std >

**Comment by i982** [comment]
sunday july 7th 8:53pm central time (event occurrence)

**Comment by OghmaToril** [comment]
This was resolved via restore
