### ISSUE TITLE
Randar's quest falchion and mithril axe

### ISSUE THREAD

**Issue by Dartan82** [torilmud/issues#578]
Recommend falchion getting shocking/shocking burst (see description)
Recommend mithril getting frost/frost burst (see description)

**Comment by torilmud-silvanus** [comment]
Is there a reason these rewards' values should be increased? Or is this request just because thematically the weapon strings imply enchanted?

Would an upgrade quest be appropriate as opposed to changing the current item?

**Comment by Dartan82** [comment]
I found a mudmail from Marthammor 15 years ago on Dartan with proc request information which reminded me of this. I probably lost interest in Toril as I was playing WoW beta heavily that year.  

The weapon string implies enchant but the description and the overall quest implied enchants as well.  The Randar quest is a story about Randar wanting a strong weapon and you and his mage help make him one from the starting base of Myrke's gleaming falchion.  After you kill Randar you get an option to give the weapon to the dwarf and his ancestors drop an axe in the room.  I believe there was intent to get a proc one day but I don't recall being hopefully on getting a coder's time to add damage procs.  

Rapier with rubies and the coral rapier from Corvinar are both fairly easy items to get and are both a regular and burst enchant so I don't think the upgrade quest is needed to meet the issue's recommendation.

I'm not opposed to doing an upgrade quest in general as well but feel the current items are within its original scope.  Back when this quest was made the only damage weapons were fireblossom, basket hilt, and icy dagger from GN area.  Pretty weak.

**Comment by vitaladsr** [comment]
Would be nice to see these weapons stronger w procs

**Comment by torilmud-silvanus** [comment]
This will be handled in https://github.com/torilmud/torilmud/pull/688 pending move

**Comment by gruumsh** [comment]
This was merged on july 31st
