### ISSUE TITLE
auction wont go over 999,999

### ISSUE THREAD

**Issue by vitaladsr** [torilmud/issues#579]
Level: 50   Race: Duergar   Class: Blackguard  
Hit points: 756(750)  Moves: 114(114)
Experience Progress: 3577 % 
Coins carried:    0 platinum     0 gold     0 silver     0 copper
Coins in bank: 2020447 platinum     7 gold     6 silver     5 copper
Prestige: 8463   Acheron Kill Count: 0
Name status: Approved
Citizen of:   Gloomhaven
Outcast from: Griffon's Nest
Playing time: 40 days / 2 hours / 11 minutes
Title: 
Status:  Standing.
Detecting:       Good Life Heat
Enchantments:    Farsee Fly Ultravision Waterbreath No Summon

Active Spells:
--------------
armor
fly

< 756h/750H 114v/114V >
< P: std > aucbid 60 2000000
You are about to bid 999999 platinum on item 60 a flaming ring of the efreeti.  Please confirm you want to do so. (Y/N): [No]

y
An auctioneer says 'You must bid at least 1009999 to outbid the current bidder.'

**Comment by Nyyrazzilyss** [comment]
Related to https://github.com/torilmud/issues/issues/167
