### ISSUE TITLE
Chrysalis Statue Issue

### ISSUE THREAD

**Issue by derwulv** [torilmud/issues#580]
Within Chrysalis there is a room called "Room Of Elven Worshiping"

There is an elfgate and 4 statues.  You can look at and enter the elfgate, you also can look at and touch 3 of the statues but the 4th one (Hanali Celanil) you can't touch or even look at.  It acts like the statue isn't even there.  Additionally if you use 1.statue and 2.statue you will get Rillifane as 1 and Corellon as 2

![image](https://user-images.githubusercontent.com/48165259/62123764-a1bf0600-b296-11e9-8d91-e6f38f598df3.png)

**Comment by torilmud-silvanus** [comment]
This will be resolved by https://github.com/torilmud/torilmud/pull/696 when it is moved to main
