### ISSUE TITLE
Hexblade: Spectral Fade

### ISSUE THREAD

**Issue by derwulv** [torilmud/issues#581]
While having "Spectral Fade" up i will periodically get the message "You stop trying to hide." when doing some actions.

As hexblades don't have the hide skill and even if we did I never triggered it.

I have attached a screenshot showing the message when doing an action

![image](https://user-images.githubusercontent.com/48165259/62229485-bf22cb80-b38d-11e9-9753-68ea8c6decd0.png)

**Comment by derwulv** [comment]
I see from "status" that Spectral Fade adds
- camoflauge
- hide
- invisibility
So this is probably the reason for the "You stop trying to hide." Message

It doesn't show every time I do a specific action like pick something up but most of the time it does

**Comment by shevarash** [comment]
This was fixed.
