### ISSUE TITLE
MCCP errors in tintin++ on some hexblade soulcutter hits

### ISSUE THREAD

**Issue by immixazer** [torilmud/issues#582]
Not sure if this happens with ansi enabled, I have term set to generic.  This doesn't happen on most soulcutter hits, just occasionally:

> #IAC BAD TELOPT 127
> #IAC BAD TELOPT 127
> #IAC BAD TELOPT 127
> #IAC BAD TELOPT 127
> #IAC BAD TELOPT 127
> #IAC BAD TELOPT 127
> #IAC BAD TELOPT 127
> #IAC BAD TELOPT 127
> #IAC BAD TELOPT 127
> #IAC BAD TELOPT 127
> #IAC BAD TELOPT 127
> #IAC BAD TELOPT 127
> #IAC BAD TELOPT 127
> #IAC BAD TELOPT 127
> Your weapon unleashes a cascade of ▒(u▒e▒(u▒l▒(u▒d▒(u▒r▒(u▒i▒(u▒t▒(u▒c▒(u▒h ▒(u▒e▒(u▒n▒(u▒e▒(u▒r▒(u▒g▒(u▒y as it strikes a Faang citizen.

**Comment by shevarash** [comment]
1) Is this still happening?
2) What client are you using?

**Comment by immixazer** [comment]
I can't reproduce it anymore.  I'm using tintin++ 2.00.5.

**Comment by immixazer** [comment]
Spoke too soon.  Happened just a few mins ago:

Lilabipple starts casting an offensive spell.
< 1102h/1121H 106v/106V (2) T: Anaria TC: excellent E: skeletal EC: few scratches EP: std P: std > 
The spectre of a human warrior says 'I must assist my friend!'
The spectre of a human warrior misses a skeletal warrior with its drain.
A shadowy wisp misses Nilan with its drain.
Tenebexee group-says '[[ SCALE OUT ]]'
Tenebexee radiates a powerful sense of crushing dread as she confronts Runelord Shyressa.
Runelord Shyressa turns her attention to Tenebexee.
The vampire elite guard turns his attention to Tenebexee.
A shadowy wisp turns its attention to Tenebexee.
The vampire elite guard turns his attention to Tenebexee.
A skeletal warrior turns its attention to Tenebexee.
#IAC BAD TELOPT 127
#IAC BAD TELOPT 127
#IAC BAD TELOPT 127
#IAC BAD TELOPT 127
#IAC BAD TELOPT 127
#IAC BAD TELOPT 127
#IAC BAD TELOPT 127
#IAC BAD TELOPT 127
#IAC BAD TELOPT 127
#IAC BAD TELOPT 127
#IAC BAD TELOPT 127
#IAC BAD TELOPT 127
#IAC BAD TELOPT 127
Dizzag starts casting an offensive spell called 'Rot'
Dark �=�c�=�r�=�i�=�m�=�s�=�o�=�n �=�f�=�l�=�a�=�m�=�e�=�s leap off of Dematuzak's weapon as he strikes a skeletal warrior, searing its flesh.
#IAC BAD TELOPT 127
#IAC BAD TELOPT 127
#IAC BAD TELOPT 127
#IAC BAD TELOPT 127
#IAC BAD TELOPT 127
#IAC BAD TELOPT 127
#IAC BAD TELOPT 127
#IAC BAD TELOPT 127
#IAC BAD TELOPT 127
#IAC BAD TELOPT 127
a skeletal warrior is knocked off its feet by the �=�f�=�i�=�e�=�r�=�y �=�b�=�l�=�a�=�s�=�t.
Pidibeple starts casting an offensive spell called 'Inferno'
The spectre of a human warrior attacks a skeletal warrior, landing a single hit.
You send a small amount of caustic goo flying from your dread gythka,

**Comment by shevarash** [comment]
I believe this has been fixed with some related terminal fixes, but if it happens again please re-open.
