### ISSUE TITLE
Typo - Weapon - a razor sharp volgue with a runed haft

### ISSUE THREAD

**Issue by Kukako** [torilmud/issues#583]
It seems that this item has a slight typo.

`a razor sharp volgue with a runed haft`

```
This polearm is nearly ten feet in length and has a heavy blade
on the end that closely resembles an elongated cleaver.  The very
tip forms a sharp angle with the blade and tapers quickly to a
point.  The haft is made from a sturdy oaken branch carved into
a straight length with iron rings every two feet for reinforcement.
```

I think this is actually supposed to be **voulge**.

`a razor sharp voulge with a runed haft`

Also the description does not mention anything about runes which feels somewhat strange to me.

**Comment by OghmaToril** [comment]
Will be resolved in next typo-fix release.
