### ISSUE TITLE
No Expired Message for Vipermind or Scaleskin

### ISSUE THREAD

**Issue by derwulv** [torilmud/issues#589]
Both of these Yuan Ti buffs show a message when activated but neither is showing a message when they expire.  I tested on a dumb terminal (no triggers or anything) and I received no message for either buff when they expired.

**Comment by ghost** [comment]
fairly certain you are mistaken, because i have seen them both, many times.,,,,,,,,,,,,your flesh loses it's scaly toughness.......or something.............you feel less like a viper..........or something
