### ISSUE TITLE
doppleganger

### ISSUE THREAD

**Issue by Alurissi** [torilmud/issues#59]
**Silvanus edit:**
- [ ] Consider allowing doppelgangers to regen moves
- [ ] Consider whether doppelgangers should poof when caster dies
- [ ] Consider whether doppelgangers should poof when subject dies

**Below is the original post:**
119/0    move    403/403   hit - A doppelganger of Rumollew

just sayin, something that can't regain moves, might be an issue......

also............

~~A doppelganger of Rumollew slightly wounds a dapper noble with his average strike.~~

~~Name             : Doppleganger~~             
~~Alias            : dopple~~

~~which is it? dopple or doppel?~~

so yeah, can dopple mobs, and pets also, and they don't poof when you rent/die

**Comment by Inames** [comment]
Doppelgangers have never been able to regain moves. Though I agree that's rather annoying and a change might be worth considering. Also, the word is correctly spelled as Doppelganger, the spell name and alias should be fixed to reflect that.

**Comment by dnavarro** [comment]
If you would, please create a separate ticket for the typo issues. The moves issue can be discussed as a possible Enhancement, but the typos are Defects

**Comment by dnavarro** [comment]
okay i created the new ticket. The typos will be tracked in #79 I will edit the body of this ticket for the remaining issue
