### ISSUE TITLE
enhance: help cast

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#591]
help cast really needs to be updated to mention powers / usage of powers.

It's quite common for new players to ask 'How do I cast a spell?' or 'What are the holy symbols?'

**Comment by beshaba-toril** [comment]
Added a few lines that lead to HELP POWERS as a temporary fix. Coordinating with others about potentially replacing CAST with POWERS all together.

**Comment by beshaba-toril** [comment]
Fix merged to main. Closing ticket.
