### ISSUE TITLE
Add a feature to have spells synchronize better

### ISSUE THREAD

**Issue by Dartan82** [torilmud/issues#601]
In another game i play, 10 of us need to get spelled up.  In order to stay synchronized there is a flag players can turn on and off called savespell.  With this flag on, spells don't tick if our hp/mana/mv are 100% and are in a heal room.

One idea would be to have a spell casted upon the room or just make time stop do this to where buffs don't tick down until the group moves.

**Comment by Alurissi** [comment]
i'd rather see a questable remort to enchanter class, which gains the ability to cast area buffs, at a great cost of course, and the duration on them, should be chaotic and erratic, to force individual attention mid fight, something like dragonscale, prob not area type, but blur, could be...

**Comment by Dartan82** [comment]
Nobody gives a shit.
