### ISSUE TITLE
Please make this Baphomet zone progression mob !kill

### ISSUE THREAD

**Issue by Dartan82** [torilmud/issues#602]
A Rope Bound Platform
Exits: -S -D
Corpse of a minotaur from Nightwood is lying here.
Corpse of a Suzail minotaur is lying here.
Corpse of a minotaur from Nightwood is lying here.
Corpse of a Suzail minotaur is lying here.
[3] Corpse of a minotaur from Nightwood is lying here.
Corpse of a Suzail minotaur is lying here.
Corpse of an obsidian statue is lying here.
Corpse of a minotaur from Nightwood is lying here.
[2] Corpse of a Suzail minotaur is lying here.
A mysterious golden lever tempts you.
A gigantic crate swings here from a bundle of rope.
Shimmering, a ghostly minotaur begins to fade into thin air.

The ghostly minotaur.  People keep accidentally keep killing him and ruining the zone.

**Comment by Dartan82** [comment]
Was this fixed?

**Comment by gruumsh** [comment]
This was fixed.
