### ISSUE TITLE
Stand while already standing breaks hide

### ISSUE THREAD

**Issue by Dartan82** [torilmud/issues#603]
< 683h/683H 221v/221V |ts +|ss +|ap +|ev +|bs +| |3|3|3|3|2| P: std > st
You stop trying to hide.
You are already standing.

Why does this break hide.  I'm already standing!

**Comment by shevarash** [comment]
I initially thought this was a bug, but, it's a little more complicated.

The command checks for hide are not context sensitive across the board. In other words, the game has a whitelist of commands that you are able to use while hidden. If you use a command that is not on that list, you will stop hiding. It would be nice if the game would also consider whether those commands would have any impact, but that would require a pretty big rewrite of the command system.

I'm going to close this, but I acknowledge that this is hardly ideal behavior.
