### ISSUE TITLE
Entangle buff?

### ISSUE THREAD

**Issue by Dartan82** [torilmud/issues#606]
Name             : Entangle [eng]
Type             : Spell                    
Attack Type      : Auto                     
Prepare          : Study                    
Target           : Offense, Character in room
Activation Time  : 4 seconds 
Related Skill    : spellcast nature
Restrictions     : Autofire, Immaterial, Garrote, Standing, Can Speak
Race Restrict (T): Type Dragon

Effects:
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Target Effect    : Add entangle for 3 minutes 32 seconds 1 pulse      
                   Save versus paralysis to avoid  

How about reducing AC or adding to hit against target on an entangled mob?  I mean they can't move... why should they get dodges...

**Comment by shevarash** [comment]
This will be addressed in an upcoming Druid class overhaul.
