### ISSUE TITLE
lockpicks marked 0% chance to break, broke first use

### ISSUE THREAD

**Issue by Lamnicaes** [torilmud/issues#607]
Name 'golden lockpicks'
Keyword 'golden lockpicks pick', Item type: PICK
Item can be worn on:  HOLD 
Item will give you following abilities:  NOBITS
Item is: MAGIC NOBITS
Weight: 1, Value: 10000
This lockpick has a 50% bonus chance to successfully pick a lock.
This lockpick has a 0% chance to break upon use.

Practicing lock pick on the crate in the SM warehouse. 91 lock pick skill. The above lock pick broke on first try.

pick crate
*Snick* unlocked.
Damn!  But you broke your golden lockpicks!

**Comment by gruumsh** [comment]
From the looks of the code, the identify text is reversed and 0 will always break.
