### ISSUE TITLE
circlet sandals loop staffs

### ISSUE THREAD

**Issue by ghost** [torilmud/issues#611]
all the single proc remems need fixed.  plz, one line break missing from at person echo, it seems, as the message never changes.....

The mysterious feeling of grass between toes, tickles your imagination.
You have finished praying for armor.
You have finished praying for Armor.

The sapphire set in your circlet flashes briefly, and you feel knowledge flow through
you.
You have finished praying for armor.
You have finished praying for Group Heal.

that's tk sandals and shaman circlet, all the others do the same thing, showing  "You have finished praying for armor"  100% of the time, in same place, never changing, and then it lists the actual spell it memed.

I might forget something in this list, but pretty sure the proc is the same error, so it's pulling from same place, and it is missing a line break or a tilde

Both seelie staffs, upgraded
tk sandals and tail loop
shaman circlet

yup

**Comment by shevarash** [comment]
This is fixed for all of the above items and will be in the next patch notes.
