### ISSUE TITLE
Quit and Camp commands should be the same

### ISSUE THREAD

**Issue by gonoph** [torilmud/issues#613]
There are very few reasons to have both commands this day and age.

Today, we had a new player accidentally drop all their equipment by using quit.

Granted, they should have read the screen more carefully, but..

A lot of MUDS use QUIT as the method to disconnect and store your character safely. It is confusing to have both commands and discouraging for visiting players to lose their stuff due to this misunderstanding.

It’s 2019, let’s alias it, please, and bring a better player experience for new players.

**Comment by marthammor** [comment]
A recent update took care of this. Closing.

**Comment by gonoph** [comment]
Thank you! Works great!
