### ISSUE TITLE
Enhance: Plat sink

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#614]
Legopple 'it was also a complaint about the influx of money 
due to botting'
Fyydo 'yeah thats a problem'
You 'I'd think there'd be better way around that'
You 'Put a tax at the banks of 25%/month for all account 
balances > 100k'
Fyydo 'nothing that a pwipe cant fix'
You 'Add a 50% auctioneer's fee for sales >250k'
You 'Of course you'll end up seeing people making 1000 plat 
storage chars'

**Comment by Nyyrazzilyss** [comment]
Give a maximum bank balance of 2k/lvl

**Comment by Nyyrazzilyss** [comment]
Sorry, not interest - Service charge

**Comment by ghost** [comment]
you could just do something like a repair timer, say 8 hours, with incremental increases in repair cost for each repair within that time frame

**Comment by Nyyrazzilyss** [comment]
Repair costs could definitely use a increase. Ideally, related to bank balance. There would always be people complaining saying they can't afford it if it was just straight level related.

**Comment by shevarash** [comment]
We certainly need some improvements to the in-game economy. We have some ideas, and I'll add these to the list.
