### ISSUE TITLE
a badge of the Order of Zillsxxixln

### ISSUE THREAD

**Issue by Adriorn** [torilmud/issues#62]
Should be flagged as a badge.

**Comment by torilmud-silvanus** [comment]
Sounds okay to me

- [x] Confirm that it is statless
- [x] Add badge worn slot

**Comment by dnavarro** [comment]
Approved for work

**Comment by gruumsh** [comment]
Fixed & merged, see patch notes: http://www.torilmud.com/news/patch-notes-9-27-2019/
