### ISSUE TITLE
auction vs bank account

### ISSUE THREAD

**Issue by ghost** [torilmud/issues#621]
102)     137510 a heavy silver amulet with a hammer and anvil cr             10           1        No Bid Yet  7 m    OPEN Lilithelle

aucbid 102 10

You are about to bid 10 platinum on item 102 a heavy silver amulet with a hammer and anvil crest.  
Please confirm you want to do so. (Y/N): [No]

y

An auctioneer says 'You do not have the funds for that bid.'

Coins carried:    0 platinum     0 gold     0 silver     0 copper
Coins in bank: 3000000 platinum    13 gold    14 silver    13 copper

**Comment by Ruagh** [comment]
Happens when one has too much plats. Duckpond is an easy solution!
