### ISSUE TITLE
Newbie adaptation

### ISSUE THREAD

**Issue by Ruagh** [torilmud/issues#627]
Please:

1.Make the Newbie Help Guide wearable as quiver (or badge?)

2.Make the backpack sold in SoI guild illuminating by default (its a phoenix after all) and maybe quiver-wearable too.

Many thanks in advance from the hopeless newbs.

**Comment by shevarash** [comment]
I don't know why a book would be wearable.

If you would like an update to a guildhall, please contact the guild leader.
