### ISSUE TITLE
Condensed mode

### ISSUE THREAD

**Issue by Ruagh** [torilmud/issues#628]
Fix it for gods sake?
Lots of procs are ignoring it - Tia circlet, Spammy Leggings, now the newly added skills/spells for the new classes and even the old ones like Prismatic Spray are a headache. Although its a great idea, it isnt working as intended.

**Comment by magic8balljuice** [comment]
might be because of nyy script? pretty sure it disables condensed. i'm probably wrong

**Comment by ghost** [comment]
fug nyyr's XP script, not everyone uses that stupid crap, and we still have condensed not condensing

**Comment by Ruagh** [comment]
Im not a NYYbot, its a code issue. Lots of new code bypasses condensed, as well as certain old ones like Serpents circlet

**Comment by shevarash** [comment]
It is definitely due for a revamp. Thank you for pointing it out.
