### ISSUE TITLE
Possible to get stuck in chessboard

### ISSUE THREAD

**Issue by feyder213** [torilmud/issues#630]
It appears that the paths in chessboard (or at least the one immediately after "play chess") are level restricted. You are able to get "get piece" and "play chess" but once in that first room you can get stuck if you are not high enough. The room where you "play chess" has an exit that is teleable. 

Making the chess piece level restricted would keep inquisitive newbies from playing with it since it only has I think 2 uses, while restricting the chessboard inside would allow it to be consumed on accident but prevent someone too low from getting stuck inside.

**Comment by shevarash** [comment]
I believe this has been fixed!
