### ISSUE TITLE
no message position change on rogue?

### ISSUE THREAD

**Issue by ghost** [torilmud/issues#633]
< 224h/610H 172v/172V >
< T: Tebyhaj TC: nasty wounds E: relonor EC: nasty wounds EP: std P: std > tr
You attack Relonor, landing four hits.
You do a fancy maneuver, tripping Relonor.

< 224h/610H 172v/172V >
< T: Tebyhaj TC: nasty wounds E: relonor EC: pretty hurt EP: rcl P: rcl > 
Relonor stops chanting abruptly!

**Comment by marthammor** [comment]
I think this is related to whatever is happening in torilmud/issues#626

**Comment by ghost** [comment]
according to dartan, 626 is a % physicals thing, rogue had 0 % physicals, well, 2% unarmed, that's it, thinking maybe condensed has stop'd showing mob takes you down with them.......
