### ISSUE TITLE
disable all forms of void/camp in um2

### ISSUE THREAD

**Issue by ghost** [torilmud/issues#635]
tired of getting stuck in vortex, because 2 people are camping inside, taking the cloak, and not being able to exit because of it

**Comment by marthammor** [comment]
I just checked on this. The rooms that are part of the cloak challenge aren't campable. Void also acts like camp and moves people out of no camp rooms. If there is a way to bypass this that you know of, please let me know.

**Comment by ghost** [comment]
you need key from cowled thief to get past locked door, to get inside the area where vortex entrance is, key acquired from thief, is no rent, so when i kill it, get key, and then go inside, only to findout cloak is gone, i'm guessing they are camping just past the locked door
