### ISSUE TITLE
faerie fog

### ISSUE THREAD

**Issue by Alurissi** [torilmud/issues#64]
power faerie fog is set at aggressive, needs to lose this flag

**Comment by dnavarro** [comment]
Defined "needs" please @Alurissi  Is this expected because the legacy version was not agg? Or is this an enhancement request?

**Comment by Inames** [comment]
I agree that it should not be aggressive due to the success rate and because the legacy version was also not aggro. Also if faerie fog is always gonna be agro, there's never a reason to use it because you'd be better off just nuking to unhide/uninvis a mob.

**Comment by Alurissi** [comment]
inames has once again, hit the nail on the head here, powers fog being aggro to entire room, makes it completely useless

**Comment by dnavarro** [comment]
Yup, agreed

**Comment by dnavarro** [comment]
- [ ] Note: It looks like message wildcards are reversed $N should be used for target

**Comment by shevarash** [comment]
The issue here is that there's no concept in powers of a spell that hits only offensive targets but does not actually raise aggro. We'll need to add something like that for this spell.

**Comment by ghost** [comment]
i can think of another example, sort of, guess it's not really a power, that i'm aware of, but mace from zaor has an area proc, that does not aggro anything, come to think of it, finn's keep flaming longsword, also has an area proc, that does not cause aggro, but does do damage....these probably aren't powers, but the framework could be similar, not sure!
