### ISSUE TITLE
Weapon diversification

### ISSUE THREAD

**Issue by vitaladsr** [torilmud/issues#649]
There are alot of fun weapons in the game but most people have the best possible weapon in game and that is all they will use outside of RP. So I came up with a few ways to create a need to have backups and use different types of weapons.

1. Some weapon types are more (or less) effective vs certain mobs (ie. attacking a dragon w a sword vs a club .. the club prob would be almost useless. But attacking a skeleton with a club vs a sword would be another story.)

2. What the weapon is made of counts. (Silver sword vs the werewolf kinda thing) the material of construction matters.

3. Weapons break randomly, especially vs armor or mobs that may be a mismatch. (The dagger bends when you try to stab a rock golem) .. if weapons are breaking out in zones, that will create a need to pull another club out of the bag. Maybe this time a 9 iron.

**Comment by ghost** [comment]
i'm with you on point 3, other 2 would require extensive work, but weapons wearing out i could totally see being an easy enough update, and while you're at it, resurrection effect on damage ammount, is utterly terrible, 50 res before broken? who dies 50x in a zone? this needs adjusted badly

**Comment by Tiamafas** [comment]
1. This can already be handled by area makers with physical resistances.

**Comment by vitaladsr** [comment]
Yeah I would be alot happier w gear breaking much more easily .. not just damaged but going completely useless. Or if damage actually reduced stats that would be so nice. Having backup gear isnt fun unless you get to use it once in awhile .. and some of the marathon zones could really require some brainstorming to get right .. maybe you don't start out with your good shit bc you will need it in the end right?

**Comment by Ruagh** [comment]
Yup yup... ill see what youll be saying just discovering you lost a prot due to eq damage right before this damn dragonbreath...

**Comment by shevarash** [comment]
Good ideas. We'll keep them in mind as we design new gear.
