### ISSUE TITLE
Achery code is totally broken - no arrows needed.

### ISSUE THREAD

**Issue by Ruagh** [torilmud/issues#651]
I can fire a bow without any arrows at all!

All I need is to wear an EMPTY quiver, cuz code checks that - or ammo belt, although xbow doesnt work with powers skillset. 

Tried Magma and Imix bow, Tia xbow. All are firing with no arrows on me - in the quiver or even in a bag, stored it just to be sure.

Also havent noticed less attacks with xbow, but hard to test thoroughly on a phone.

Also i dont think that breaking the arrow dice code was a good idea. Yes, much easier to code, but illogical. Also, theres no big difference now between generic newbie arrows and hard to quest elite ones, which looks silly to me.

**Comment by Ruagh** [comment]
Btw maybe certain hi-end magic bows not needing arrows would be an interesting feature. Although if their "immaterial ones" would be comparable or better than the quest ones, nobody will quest for arrows, which was a nice feature. So maybe an option - fire an arrow if available, fire (somewhat weaker?) magik if runned outta.

**Comment by ghost** [comment]
so you really should go back and look at the introduction of ranger powers, or even the ingame help with archery, no arrows is intended, it's not broken, and you can switch to using real ammo in various ways, by enchantment type, by  name....help function in game is useful

**Comment by Ruagh** [comment]
Yup, HELP AMMO vaguely explains. But as an oldtimer - I couldnt even think that you MAY NOT NEED arrows at all today. It makes alot of "realistic details" of archery obsolete.

And with the bows being all with the same 4d6 dice... Whats the difference now between a newbie bow and a top-gun bow? A mere 10%?

**Comment by OghmaToril** [comment]
This is working as intended.  Arrows are no longer required, however they may convey bonuses to those that use actual ammunition.
