### ISSUE TITLE
restore my character

### ISSUE THREAD

**Issue by gukker** [torilmud/issues#652]
I had a character and want to play with my friend again. I didnt know it would be deleted on source base.

**Comment by marthammor** [comment]
Hello.
We haven't deleted any characters in many years. I seen on the backlog of our support channel that you were looking for a drider. We don't have a drider player race. Were you perhaps talking about a drow?

**Comment by gukker** [comment]
I have a password issue I thought it was deleted.. the character is
gukksilkiska and on account gukk I think, but I dont have the password

**Comment by marthammor** [comment]
I've looked it up and the character and account are still there. I am not able to retrieve your password though, but I'll poke at someone who might be able to.
