### ISSUE TITLE
Bank account wiped clean

### ISSUE THREAD

**Issue by Sansameanin** [torilmud/issues#659]
Hello, I logged off Thursday morning at about 9:30 eastern standard time and when I returned at 3pm I saw that the bank account on Sansameanin was wiped clean, all showed 0. I had deposited in the silverymoon bank, I'm afraid to deposit into the bank again in case it happens again.

**Comment by shevarash** [comment]
If this issue was not resolved for you, please send us an email at toril.help@gmail.com
