### ISSUE TITLE
oakvale epic swords

### ISSUE THREAD

**Issue by Alurissi** [torilmud/issues#66]
the proc from both swords is canceling out melee strike, so unless the damage proc is doing more than my 80 damroll strike would, i wouldn't mind seeing this changed to work like any other proc in game, where it's an addition to the round of combat, rather than replacing a regular hit with the proc

**Comment by gruumsh** [comment]
The proc definitely does more than your 80 dam strike would but these days overriding the hit isn't necessary for most weapon procs. 
I don't see anything in the proc text that requires it to erase the attack though, so I'll see what can be done.
