### ISSUE TITLE
Typo in THAC0 help file

### ISSUE THREAD

**Issue by cestrand** [torilmud/issues#662]
In THAC0 help file.

> If you are fighting a monster with an armor class
> of **1**, then you need to roll between 11 and 20 to hit that mob.  If the
> mob's armor class is 8, you only need to roll between 2 and 20 in
> order to hit that monster.

It should be **-1** instead of **1** shouldn't it?

**Comment by Inames** [comment]
thats a ridiculously outdated helpfile and i'm pretty sure it doesn't apply to the game anymore...

**Comment by shevarash** [comment]
Inames is correct - this helpfile will be removed. There's another issue on it already, so I'm closing this one.
