### ISSUE TITLE
Drink water from creek in Lurkwood

### ISSUE THREAD

**Issue by cestrand** [torilmud/issues#665]
![image](https://user-images.githubusercontent.com/6875883/76399147-6e8d3b00-637e-11ea-92ed-210a7627ff3a.png)
I would be nice if I could drink from this crystal clear creek.

**Comment by Inames** [comment]
with the way the game is designed currently that would require adding a no-take water container object on the ground depicting the creek from which to drink and then placing it in every room that references the creek. while possible, mostly a waste of time, and drinking water doesn't do anything for you anyways unless its holy/unholy water and you are the matching alignment, in which case you heal for like 5hp.

**Comment by shevarash** [comment]
This is an interesting idea, but admittedly difficult to implement easily. I'm going to close the issue, but I'll keep these types of immersion building technique in mind for the future. Thank you!
