### ISSUE TITLE
arrow wt3 - pls fix

### ISSUE THREAD

**Issue by Lamnicaes** [torilmud/issues#668]
a gob arrow (No_wear) Dam:3 Hit:1 * (Ammo) * Wt:3 * Zone: Faang (S)

Please adjust the wt of this arrow to the normal wt1. You can't carry them in a quiver at wt3 without overloading.

**Comment by Inames** [comment]
it's the tradeoff to being able to buy arrows with hit/dam from a shop. they are not meant for high end zoning, they are for leveling.
