### ISSUE TITLE
Mounts ruin AOE radius

### ISSUE THREAD

**Issue by Inames** [torilmud/issues#671]
please remove mounts from the aoe radius check, this is kinda ridiculous.

You complete your spell...
Striking someone's mount is an act of cowardice!
Your spell is partially absorbed by an elite narzugon.
You send an elite narzugon reeling with your word of power.
Your spell is partially absorbed by an elite narzugon.
You send an elite narzugon reeling with your word of power.
Striking someone's mount is an act of cowardice!
Striking someone's mount is an act of cowardice!
Striking someone's mount is an act of cowardice!
Your spell is partially absorbed by an elite narzugon.
You send an elite narzugon reeling with your word of power.
Striking someone's mount is an act of cowardice!
Striking someone's mount is an act of cowardice!

**Comment by shevarash** [comment]
Or maybe we should just remove the restriction on striking someone's mount...since it's pretty nonsensical to begin with.

**Comment by Inames** [comment]
I also agree with that, but then it's still not gonna make a difference, because mounts would just exist to soak up aoe hit targets, "mounts" in real combat situations like perhaps this example, need to have some sort of function, or be able to fight and pose a risk to validate a reason to be able to hit them. I mean hell, since there's no "mounted combat" anymore, just change them into non mount flagged mobs and let them participate, add a bit more challenge to a braindead zone to spice it up for 5 minutes.
