### ISSUE TITLE
Consumption not clearing blind

### ISSUE THREAD

**Issue by otebski** [torilmud/issues#679]
< 383h/569H 126v/127V |vs +|sot +|ss +|md +|sph 4|uf 6| |3|3|2|3|1| T: Afez TC: few wounds E:
someone EC: small wounds EP: std P: std > 
You have learned something new about blindfighting!
Someone misses you with its claw. (x2)
You complete your spell... [ CS (Consumption) ]
Your form flares with a brief crimson glow as you purge yourself of afflictions.

< 383h/569H 127v/127V |vs +|sot +|ss +|md +|sph 4|uf 6| |3|3|1|3|1| T: Afez TC: few wounds E:
someone EC: small wounds EP: std P: std > 
l
You need to be able to see your target to do that!

BLK's consumption does not clear blind from Dark Mist's dire raven proc

**Comment by otebski** [comment]
Consume also does not clear blind from Nyth Flare effect, also in Dread Mist

**Comment by shevarash** [comment]
My understanding is that the raven blind procs are intended to be physical effects that can not be cured by magic. I will double check with the area maker though.

**Comment by shevarash** [comment]
Double checked. Confirmed. Those Ravens are vicious.
