### ISSUE TITLE
sub-20 portals

### ISSUE THREAD

**Issue by Alurissi** [torilmud/issues#68]
says it went in, but doesn't work

**Comment by dnavarro** [comment]
Please clarify, @Alurissi

**Comment by Inames** [comment]
@dnavarro - Shar attempted to make gate/hole/well/rift usable to all levels, not just lvl 20+, news said it went in, but the alteration did not work and they still have a level requirement on use. It hasn't been revisited since.

**Comment by Alurissi** [comment]
as inames clarified, shar's post on news allows for sub 20's to enter and join, but that's all it is, a post, doesn't work in either case

**Comment by shevarash** [comment]
This is fixed now as of a few minutes ago.
