### ISSUE TITLE
Powers Ice Tomb

### ISSUE THREAD

**Issue by Inames** [torilmud/issues#684]
> Name             : Ice Tomb [it]
> Type             : Spell                    
> Attack Type      : Auto                     
> Prepare          : Study                    
> Target           : Offense, Character in room
> Activation Time  : 6 seconds 
> Related Skill    : spellcast necromancy
> Restrictions     : Autofire, Garrote, Standing, Can Speak
> 
> Effects:
> -=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
> Target Effect    : Remove fireshield                                  
> Target Effect    : Remove power Fireshield                            
> Target Effect    : Add major paralysis, ice tomb for 1 minute         
>                    Restrictions: NPC, Target HP Max 1000
> Target Effect    : 5% chance to Add major paralysis, ice tomb for 1 minute  
>                    Restrictions: PC
> Target Effect    : Deal offensive level 16 cold damage                
> 

Hey Shev, can you look into this buggy crap thats making mobs that can ice tomb para players with almost 100% effectiveness. It's getting kinda ridiculous.

2x failed Baphomet in a row because para's cascade through the group as soon as 1 or 2 paras get off due to failed bashes/sweeps/etc because of powers requiring 50+ hit to work with any degree of consistency.

Thanks in advance!

**Comment by shevarash** [comment]
Are you saying that the change to make it 5% only is not working?

**Comment by Inames** [comment]
Yes, whatever calculation its doing, it's para'ing players with almost 100% success on every cast. Something is bugged for sure.
