### ISSUE TITLE
Baphoment Tattoo Mis-flagged UNUSED_22

### ISSUE THREAD

**Issue by Inames** [torilmud/issues#692]
Name 'some mystical runes tattooed amongst the eyes'
Keyword 'runes tattooed eyes gem', Item type: ARMOR
Item can be worn on:  EYES 
Item will give you following abilities:  SENSE-LIFE 
Item is: UNUSED_22 NOBITS
Weight: 0, Value: 0
AC-apply is 6
Can affect you as :
    Affects : SPELL_FOCUS_ENCHANTMENT By 4
    Affects : HITPOINTS By 18

**Comment by marthammor** [comment]
This should be fixed. Closing.
