### ISSUE TITLE
A weapon with holy enchantment giving an axiomatic message

### ISSUE THREAD

**Issue by Lilithelle** [torilmud/issues#700]
Your strong axiomatic slash severely wounds the seer ghost.

You recite an intricate divination scroll which turns to dust in your hands.
You feel informed:
Name 'a fatal touch bastard sword'
Keyword 'sword bastard fatal touch', Item type: WEAPON
Item can be worn on:  WIELD 
Item will give you following abilities:  NOBITS
Item is: MAGIC BLESS NO-THIEF NO-MAGE NOBITS
Weight: 4, Value: 70881
Type: Bastard Sword Class: Exotic
Damage:  3D6  Crit Range: 6%  Crit Bonus: 2x
Enchantments:
    Type: Holy             Damage: 100% Frequency: 100% Modifier: 0   Duration: 0  
    Type: Bane             Damage: 100% Frequency: 100% Modifier: 0   Duration: 0  
    Type: Ghost Touch      Damage: 100% Frequency: 100% Modifier: 0   Duration: 0  

Can affect you as :
    Affects : HITROLL By 3
    Affects : DAMROLL By 3

**Comment by OghmaToril** [comment]
Did a little bit of testing with this weapon (and other weapons with these enchantments)

Attacking Golden Warrior gave holy message.
Attacking Seer Ghost gave axiomatic message.  (ghost/incorporeal)
Attacking fiendish ghast gave holy message. (highundead) (should give bane message)

There may be a couple unrelated issues here.
Looking at the item, [val7] should be set to 21 (HighUndead).  Currently it looks like it is set to 0 and [val8] is set to 21.  In real people terms, I don't know if the bane is being applied correctly. This may fix the axiomatic issue as the object shouldn't have a value in [val8].

If this doesn't fix it, it could be a combination of the enchants giving the message.
