### ISSUE TITLE
Issues with Adrenalize

### ISSUE THREAD

**Issue by derwulv** [torilmud/issues#704]
When you activate Adrenilize on illithid it shows as three entries within the status window (see attached screenshot)

It also has no "out" message.
![adren_issue](https://user-images.githubusercontent.com/48165259/81819456-5613db00-94fd-11ea-9abd-373f27e65d9b.png)

**Comment by shevarash** [comment]
This is because of how old non-power skills are used. An upcoming Psionicist class overhaul will address this.
