### ISSUE TITLE
Continuity in Menzoberranzan

### ISSUE THREAD

**Issue by abair** [torilmud/issues#706]
While standing in "At the Base of the Tower of House Xorlarrin", I received this message:

A guard says, "Xun izil dos phuul quarthen, lueth dro.  " as he waves you away
from the gates.

I think it's just there for flavor, but... Since my character is Drow, should't I have understood him?

**Comment by OghmaToril** [comment]
You're correct.  This is just there for flavor and there currently is not a way for it to show readable for drow, but gibberish for other races.

**Comment by abair** [comment]
Understood :)
