### ISSUE TITLE
Staves with single target aggresive spells.

### ISSUE THREAD

**Issue by otebski** [torilmud/issues#713]
Staves with single target aggresive spells cannot be used with another player  (or mount) in room.

**Comment by shevarash** [comment]
Can you provide a log?

**Comment by otebski** [comment]
You recite a vellum scroll which turns to dust in your hands.
You feel informed:
Name 'a macabre marionette of old bones'
Keyword 'marionette macabre old bones', Item type: **STAFF**
Item can be worn on:  HOLD 
Item will give you following abilities:  NOCHARM 
Item is: MAGIC ANTI-GOOD ANTI-NEUTRAL NOBURN NOLOCATE NO-WARRIOR NO-THIEF NOBITS
Weight: 2, Value: 0
Has 10 charges, with 4 charges left.
Level 50 spell of:
**puppet**
Resists:
    Neg   :    5% Mental:    5% 

Can affect you as :
    Affects : HITPOINTS By 20
    Affects : WIS By 9
Magical auras become visible.

< 735h/735H 128v/128V P: std > 
l room
Wayward House Inn (Shadowed)
   This elegant wood building has been constructed on the stone
foundation of the Inn of Wayward Sages.  Charring can still be seen on
the stone from when the original building burned down.  Originally an
inn with less then reputable clientele the inn has become more classy
with a well stocked wine cellar.  A number of tables and chairs lie
about the room casually and a long oak counter fills one end of the
room.
Exits: - North - Up   
A gaping hole in the ground leads into darkness. (magic)
[10] An arrow-shaped piece of the shadows has separated and landed here.
A dagger lies in the muck.
Mej  (AFK) (Barbarian) stands here.
Nigomis  (AFK) (Moon Elf) stands here.
Mazempohol  (Gnome) stands in mid-air here.
A showy merchant sits here looking smug. (x3)
A dapper noble is here socializing. (x3)
Ynndchiarhlizz - The Nexus (Illithid) sits resting.
Havorr Merendil stands behind the counter ready to serve.

< 735h/735H 128v/128V P: std > 

A wormhole crumbles to dust and blows away.
The sky's light begins shining in from above, dissipating the dark shadow above!

< 735h/735H 128v/128V P: std > 
use marionette
**You invoke your a macabre marionette of old bones.**
**Ooops, You would hit Mej, better not!**


It is the same with other staves that have single target aggresive spells.

**Comment by Tiamafas** [comment]
Try use marionette targetname.
Without a target it will probably target the first mob or player in the room by default.
example: use marionette merchant.

**Comment by shevarash** [comment]
This was addressed with the power consumables update.
