### ISSUE TITLE
Typos in several rooms' descriptions in and around the Underdark.

### ISSUE THREAD

**Issue by abair** [torilmud/issues#715]
I'm just gonna copy pasta each room's title and description in here and slap a quick substitution under each:

A Passage Bored through Solid Rock
    This passage constantly keeps changing direction, as if to confuse
travellers where they are axtually heading.  This also serve the purpose of
creating great ambush sites for the drow which patrols this passage.  There are
some faint traces of runes created out of faerie fire on the walls of the
tunnel, somehow indicating warnings about what happens to trespassers.
Exits: - East  - West
s/axtually/actually/
s/serve/serves/
s/drow which patrols/drow which patrol/

                              --------------------

Through a Worm-Burrowed Tunnel
    This tunnel have not been excavated by any sort of humanoid creature, as it
its pretty evident that its the trail left through the rock by some gigantic
worm-like creature.  This creature have burrowed through the rock with ease, as
if it had been nothing more than sand to it.  There are occasional dented and
very old, but still noticably purple scales stuck on protruding rocks from the
granite wall.  This worm-burrowed tunnel seems to change character to the east,
where it connects to a tunnel created by other means.
Exits: - North - East
s/have/has/g
s/noticably/noticeably/
The "it" at the end of the first line should be removed.

                              --------------------

A Twisting Tunnel
    The tunnel seems to turn and twist around it self so many times, it is
almost impossible to keep track of which direction is which.  The tunnel is not
very wide, not more than few feet at its most narrow parts, and the sharp and
rugged granite of the walls seems to get close enough to cause cuts and bruises
on anyone passing through.  The floor of the tunnel is covered with loose
rocks, making it important for any traveler to watch his step with special
care.
Exits: - East  - Down
s/around it self/around itself/

                              --------------------

A Dark Turn in the Tunnel
    The tunnel turns sharply from north to east here.  The tunnel is slighlty
less than four feet wide and it can hardly be more than five feets between roof
and ground..  The rock which makes up the wall of the tunnel seems to be a dark
type of granite.  There is a slight dripping of water coming from the roof of
the hole, which makes the rock rather slippery.
Exits: - North - East
s/feets/feet/

**Comment by OghmaToril** [comment]
These have all been fixed and will go in during a future code move.
