### ISSUE TITLE
Color code issue with Spectral Fade

### ISSUE THREAD

**Issue by abair** [torilmud/issues#716]
When Spectral Fade is cast or wears off, the notification message has an incorrectly formatted color code in it:

< 146h/146H 104p/104P 120v/120V (0) |hb +|bh +|sd +| >
< P: std > sf
You start chanting...

< 146h/146H 104p/104P 120v/120V (0) |hb +|bh +|sd +| >
< P: std >
You complete your spell...
You become misty and transparent as you fade from view.[0m

< 146h/146H 104p/104P 120v/120V (0) |hb +|bh +|sd +| >
< P: std >

...

< 188h/188H 104p/104P 118v/120V (0) |hb +|bh +|sd +| >
< P: std >
You fade back into visibility.[0m

< 188h/188H 104p/104P 120v/120V (0) |hb +|bh +|sd +| >
< P: std >

**Comment by shevarash** [comment]
What client are you using, and what is your terminal set to?

**Comment by abair** [comment]
Client: tintin++ 2.01.8b
The client is running:
    * inside a zsh shell (5.7.1 (x86_64-apple-darwin19.0)) with TERM=screen-256color
    * inside a tmux 3.1b session
    * inside iTerm2 3.3.9
TinTin's color encoding is set to 24 bit true color

I have seen the issue with my Toril terminal set to both ANSI (16 colors) and True Color. Each with TinTin's color mode set to match, and mismatch.

**Comment by shevarash** [comment]
Let us know if this is still happening, thanks!
