### ISSUE TITLE
Possible Typo in THAC0 Help Entry

### ISSUE THREAD

**Issue by abair** [torilmud/issues#719]
Is it correct with a THAC0 = 10 you need a roll of 11 - 20 to hit an opponent
with AC 1 but only a 10 - 20 to hit an opponent of AC 0?  Doesn't that imply
that higher armor class is **harder** to hit?

Here's the example from `help THAC0`:

```
For Example:  let's say your THAC0 is 10, meaning you have to roll
between 10 and 20 on a 20-sided die in order to hit an enemy with an
armor class of 0.  If you are fighting a monster with an armor class
of 1, then you need to roll between 11 and 20 to hit that mob.  If the
mob's armor class is 8, you only need to roll between 2 and 20 in
order to hit that monster.  You can affect your THAC0 by using magical
items that give a positive hitroll bonus.  This bonus will enhance
your THAC0 and therefore your ability to hit a monster.
```

I think the roll for AC 1 should probably be 9 - 20.

**Comment by Inames** [comment]
THAC0 is outdated and irrelevant as far as i know, it needs to be removed from the help files. Ignore it.

**Comment by shevarash** [comment]
Agreed, this help file should be removed.

**Comment by OghmaToril** [comment]
helpfile has been removed.  Will be moved in a future code move
