### ISSUE TITLE
Help Fear missing circle infor

### ISSUE THREAD

**Issue by otebski** [torilmud/issues#720]
Area of effect: <victim>
Aggressive:     Yes
Cumulative:     N/A
Duration:       Instantaneous
Class/Circle:   Shaman/Cleric/Druid <- missing infor about spell circle
Type of spell:  Generic

If successful, "fear" will cause the victim to flee in terror.

See also:  FLEE

**Comment by OghmaToril** [comment]
Fixed and will be moved in a future code move.
