### ISSUE TITLE
Black Dragon Orb from Bahamut misses blind constantly

### ISSUE THREAD

**Issue by MikeyLikes** [torilmud/issues#732]
Hi all - I was very happy to get the orb and start playing with it, but noticed that the blind practically never hit. I decided to get some real data and I used the power on the commoners two north of SM inn as my level 50 lich (27% SF necro if it matters).

Trial 1: 1 blind success in 10 tries
Trial 2: 1 blind success in 20 tries

I'm guessing this is lower than intended for top tier loot and just wanted to raise it to y'all.

**Comment by Lilithelle** [comment]
Was an error of mine in setting the difficult of the saving throw, it will be corrected in the next version of Bahamut.

**Comment by shevarash** [comment]
This has been addressed. If you still feel the success rate is poor, please reopen.
