### ISSUE TITLE
Character stats shouldn't be a luck-based on a roller

### ISSUE THREAD

**Issue by Dartan82** [torilmud/issues#736]
It shouldn't because there is no real ingame work done to equate to character power.

This MUD lacks any progression outside of the stale equipment structure it currently has.  Nobody wears +stat gear because it's garbage.  People want progression.  Just give us a way to add stats to characters so we have something to do outside of farming gear for alts.

**Comment by Lilithelle** [comment]
Prestige for stats?  Or a +1 stat boost for one person on completion of epic zones.  Tiamat = +1 strength, Bahamut = +1 constitution, ChP = +1 agility, ...

**Comment by shevarash** [comment]
That's good feedback, and I tend to agree. I'm closing this because it's not really an actionable issue, but that doesn't mean that we won't move in this direction in the future.
