### ISSUE TITLE
a mithril headed dwarven waraxe graven with runes - Fury Proc Message

### ISSUE THREAD

**Issue by saerian** [torilmud/issues#740]
It looks like the Fury proc message gets cut off...

Your massive flame-enshrouded slash slightly wounds A naked woman.
**Gripping your phaerimm hide handle you squeeze the ironwood haft
of your dwarven waraxe and wade fearlessly into battle.  Magic surges**
Your massive flame-enshrouded slash slightly wounds A naked woman.
Your massive flame-enshrouded slash slightly wounds A naked woman.
Your massive flame-enshrouded slash slightly wounds A naked woman.
Your massive flame-enshrouded slash slightly wounds A naked woman.
Your massive flame-enshrouded slash slightly wounds A naked woman.

**Comment by shevarash** [comment]
I tried this and it worked ok for me. Do you have a gag eating the line perhaps? Here's what it looks like. Feel free to re-open if I'm missing something.

```
You easily dodge an attempt by the golden warrior to hit you.
You dodge the golden warrior's vicious attack.
Gripping your phaerimm hide handle you squeeze the ironwood haft
of your dwarven waraxe and wade fearlessly into battle.  Magic surges
through the glowing golden runes as you chop mercilessly into your opponent.
Your massive slash barely wounds the golden warrior.
Your attack only grazes the golden warrior as he dodges aside!
Your powerful slash barely wounds the golden warrior.
The golden warrior dodges your futile attack.
Your massive slash barely wounds the golden warrior.
Your massive slash barely wounds the golden warrior.
You miss the golden warrior with your slash.
Your massive slash barely wounds the golden warrior.
```
