### ISSUE TITLE
a crimson-edged obsidian blade - vamp broken

### ISSUE THREAD

**Issue by saerian** [torilmud/issues#743]
The vamp part of the enchantment on the blade does not appear to work all the time.

Here it's working:

< 778h/871H 105v/105V (1) |su +|bh +|hs 2|bf +|vf +|vs 5| |0|3|0|0|2| T: Dematuzek TC: small wounds
E: apprentice EC: nasty wounds EP: rcl P: std > 

[Dematuzek : the mystical circlet of the coiled serpent]
Your massive frost-wreathed slash slightly wounds an apprentice bard.
Your massive frost-wreathed slash slightly wounds an apprentice bard.
Your massive frost-wreathed slash badly wounds an apprentice bard.
Your massive frost-wreathed slash badly wounds an apprentice bard.
Your massive frost-wreathed slash severely wounds an apprentice bard.
Your massive frost-wreathed slash severely wounds an apprentice bard.
Your massive frost-wreathed slash severely wounds an apprentice bard.

< 835h/871H 105v/105V (1) |su +|bh +|hs 1|bf +|vf +|vs 4| |0|3|0|0|2| T: Dematuzek TC: few scratches
E: apprentice EC: pretty hurt EP: rcl P: std > 

---

Here it's not. In the last one you can see the 'vampiric' keyword being added to a few hits, and it actually works with those hits, but not the rest.

< 680h/871H 102v/105V (3) |su +|bh +|hs 1|bf 3|vf +|vs +| |0|2|3|0|2| T: Dematuzek TC: small wounds
E: shalyssa EC: small wounds EP: rcl P: std > 

[Dematuzek : the mystical circlet of the coiled serpent]
Your massive frost-wreathed slash barely wounds Shalyssa Lurialar.
Your massive frost-wreathed slash barely wounds Shalyssa Lurialar.
Your massive frost-wreathed slash barely wounds Shalyssa Lurialar.
Your massive frost-wreathed slash barely wounds Shalyssa Lurialar.
Your massive frost-wreathed slash barely wounds Shalyssa Lurialar.
Your crimson-edged obsidian blade pulses crimson in a torrent of unholy might!
An inky black miasma writhes forth from your blade coating Shalyssa Lurialar in Stygian
darkness!
Shalyssa Lurialar seems to be blinded!
Your massive frost-wreathed slash barely wounds Shalyssa Lurialar.
Your massive frost-wreathed slash barely wounds Shalyssa Lurialar.

< 680h/871H 104v/105V (3) |su +|bh +|hs 1|bf 3|vf +|vs +| |0|2|3|0|2| T: Dematuzek TC: small wounds
E: shalyssa EC: few wounds EP: rcl P: std > 

---

< 510h/871H 96v/105V (0) |su +|bh +|hs 1|bf +|vf +|vs 7| |3|0|3|0|2| T: Dematuzek TC: few wounds E:
lavis EC: few wounds EP: rcl P: std > 

[Dematuzek : the mystical circlet of the coiled serpent]
You miss Lavis Ryl with your flaming slash.
Your massive flaming slash barely wounds Lavis Ryl.
Your massive flaming slash barely wounds Lavis Ryl.
Your a crimson-edged obsidian blade explodes in a burst of searing flames!
You score a CRITICAL HIT!
Your massive vampiric flaming slash slightly wounds Lavis Ryl.
Your massive flaming slash barely wounds Lavis Ryl.
Your massive flaming slash barely wounds Lavis Ryl.
Your massive flaming slash barely wounds Lavis Ryl.

< 515h/871H 97v/105V (0) |su +|bh +|hs 1|bf +|vf +|vs 7| |3|0|3|0|2| T: Dematuzek TC: few wounds E:

---

< 762h/871H 105v/105V (1) |su +|bh +|hs 3|bf +|vf +|vs 5| |3|0|3|0|2| T: Dematuzek TC: small wounds
E: apprentice EC: pretty hurt EP: rcl P: std > 

[Dematuzek : the mystical circlet of the coiled serpent]
An apprentice bard dodges your futile attack.
Your massive flaming slash badly wounds an apprentice bard.
Your massive flaming slash badly wounds an apprentice bard.
Your massive flaming slash badly wounds an apprentice bard.

< 762h/871H 105v/105V (1) |su +|bh +|hs 2|bf +|vf +|vs 4| |3|0|3|0|2| T: Dematuzek TC: small wounds
E: apprentice EC: pretty hurt EP: rcl P: std > 

---

< 671h/871H 105v/105V (0) |su 1|bh +|hs +|bf +|vf 6|vs +| |3|0|3|0|2| T: Dematuzek TC: small wounds
E: tathshandra EC: pretty hurt EP: std P: std > 

[Dematuzek : the mystical circlet of the coiled serpent]
Your massive flaming slash slightly wounds Tathshandra Tyrar.
Your massive flaming slash slightly wounds Tathshandra Tyrar.
Your massive flaming slash slightly wounds Tathshandra Tyrar.
Your massive flaming slash slightly wounds Tathshandra Tyrar.
Your massive flaming slash badly wounds Tathshandra Tyrar.
Dark crimson flames leap off of your weapon as you strike Tathshandra Tyrar, searing her flesh.
Tathshandra Tyrar is knocked off her feet by the fiery blast.

< 671h/871H 105v/105V (1) |su 1|bh +|hs 3|bf +|vf 5|vs +| |3|0|3|0|2| T: Dematuzek TC: small wounds
E: tathshandra EC: pretty hurt EP: rcl P: std > 

---

< 809h/871H 105v/105V (2) |su +|bh +|hs 1|bf 3|vf +|vs 3| |3|0|3|0|2| T: Dematuzek TC: few scratches
E: priest EC: nasty wounds EP: rcl P: std > 
[Priest has nasty wounds!]

[Dematuzek : the mystical circlet of the coiled serpent]
Your a crimson-edged obsidian blade explodes in a burst of searing flames!
Your a crimson-edged obsidian blade pulses crimson in a torrent of unholy might!
You score a CRITICAL HIT!
Your massive vampiric flaming slash slightly wounds an elderly priest of Mielikki.
Your crimson-edged obsidian blade pulses crimson in a torrent of unholy might!
An inky black miasma writhes forth from your blade coating an elderly priest of Mielikki
in Stygian darkness!
Nothing seems to happen.
Your massive flaming slash slightly wounds an elderly priest of Mielikki.
Your massive flaming slash barely wounds an elderly priest of Mielikki.
Your massive flaming slash slightly wounds an elderly priest of Mielikki.
Your massive flaming slash slightly wounds an elderly priest of Mielikki.
Your a crimson-edged obsidian blade explodes in a burst of searing flames!
Your a crimson-edged obsidian blade pulses crimson in a torrent of unholy might!
You score a CRITICAL HIT!
Your massive vampiric flaming slash severely wounds an elderly priest of Mielikki.
You miss an elderly priest of Mielikki with your flaming slash.

< 822h/871H 105v/105V (2) |su +|bh +|hs 1|bf 3|vf +|vs 3| |3|0|3|0|2| T: Dematuzek TC: few scratches
E: priest EC: pretty hurt EP: rcl P: std >

**Comment by saerian** [comment]
It appears to work on crit ... is it unintentionally tied to crits like the bursts are?

---

< 747h/871H 105v/105V (2) |su +|bh +|hs 1|bf 3|vf +|vs 4| |0|2|0|0|2| T: Dematuzek TC: small wounds
E: forell EC: nasty wounds EP: rcl P: std > 
Your a crimson-edged obsidian blade explodes in a burst of searing flames!
Your a crimson-edged obsidian blade pulses crimson in a torrent of unholy might!
Your a crimson-edged obsidian blade detonates in a shimmering blast of lawful might!
You score a CRITICAL HIT!
Your massive vampiric flaming slash badly wounds Forell Luckaun.
Your massive flaming slash slightly wounds Forell Luckaun.
Forell Luckaun misses you with his hit.
Forell Luckaun misses you with his hit.

< 755h/871H 105v/105V (2) |su +|bh +|hs 1|bf 3|vf +|vs 4| |0|2|0|0|2| T: Dematuzek TC: small wounds
E: forell EC: nasty wounds EP: rcl P: std >

**Comment by shevarash** [comment]
The vampiric enchantment gives the target a constitution save to resist tis effects. The save chance can be configured per item though, and it is set very, very low on this blade. It should be possible for high con targets to resist the vamp. I'm not seeing any changes to that enchantment or the underlying code in the last move, so I'm curious if you think this changed in the last patch.

**Comment by saerian** [comment]
It absolutely changed with the patch. It's only proc'ing the vamp on crit hits, instead of every hit, so it appears the vampiric enchantment got tied to critical hits like the bust enchantments, when it should be applied to every hit, like flaming.

**Comment by mrizzalazzrazzi** [comment]
I concur with saerian on this. I got the same result as shown below;

---------------------------------------------------------------------------------------------------
Your a crimson-edged obsidian blade explodes in a burst of searing flames!
Your massive vampiric flaming slash slightly wounds a human noble.
Your massive flaming slash slightly wounds a human noble. (x2)

< 533h/643H 185p/185P 125v/129V |3|0|3|3|2| T: Ezura TC: small wounds E: noble EC: few wounds EP:
std P: std > 

Your massive flaming slash slightly wounds a human noble. (x2)

< 515h/643H 185p/185P 129v/129V |3|0|3|3|2| T: Ezura TC: small wounds E: noble EC: few wounds EP:
std P: std > 

Your massive flaming slash slightly wounds a human noble. (x2)

< 516h/643H 185p/185P 129v/129V |3|0|3|3|2| T: Ezura TC: small wounds E: noble EC: nasty wounds EP:
std P: std > 

Your massive flaming slash badly wounds a human noble.
Your massive flaming slash slightly wounds a human noble.

< 516h/643H 185p/185P 129v/129V |3|0|3|3|2| T: Ezura TC: small wounds E: noble EC: nasty wounds EP:
std P: std > 

A human noble, in a show of awesome skill, manages to trip up himself!
Your massive flaming slash badly wounds a human noble. (x3)

< 480h/643H 185p/185P 129v/129V |3|0|3|3|2| T: Ezura TC: few wounds E: noble EC: nasty wounds EP:
rcl P: std > 

Your massive flaming slash severely wounds a human noble.
Your awesome flaming slash badly wounds a human noble.

< 480h/643H 185p/185P 129v/129V |3|0|3|3|2| T: Ezura TC: few wounds E: noble EC: pretty hurt EP: rcl
P: std > 

A human noble clambers to his feet.
Your powerful flaming slash slightly wounds a human noble.
Your massive flaming slash badly wounds a human noble. (x2)

< 481h/643H 185p/185P 129v/129V |3|0|3|3|2| T: Ezura TC: few wounds E: noble EC: pretty hurt EP: std
P: std > 

------------------------------------------------------------------------------------------


The only vampiric I saw is on the burst crit.
The normal hit does not vampiric at all. It seems the normal hit only got flaming over the vampiric.

If the blade is not fix, i guess this blade is getting downgraded and even more, will become trash.

**Comment by gehadron** [comment]
@shevarash  i'm pretty sure before you change the stat on the crimson blade. it does vamp on normal hit + crit. But right now, it doesnt vamp at all on normal hit. Notice my health is not healing on normal hit below:

< **787h**/896H 117v/117V |3|1|2|0|0| T: Polopakov TC: small wounds E: forell EC: few wounds EP: std P:
std > 

Forell Luckaun misses you with his hit.
Forell Luckaun misses you with his hit.
_**Your massive flaming slash barely wounds Forell Luckaun.
Your massive flaming slash barely wounds Forell Luckaun.**_
Forell Luckaun dodges your futile attack.

< **787h**/896H 117v/117V |3|1|2|0|0| T: Polopakov TC: small wounds E: forell EC: few wounds EP: std P:
std >

**Comment by shevarash** [comment]
I found the issue and will be fixing this shortly. Thanks for the detailed bug reports everyone!

**Comment by shevarash** [comment]
The fix for this is live.
