### ISSUE TITLE
Rules Clarification: Zone Claiming (Jot Specifically)

### ISSUE THREAD

**Issue by MikeyLikes** [torilmud/issues#747]
I'm posting this after listening to a conversation the other day.

My question is this. . .it seems like there is a group of people who read the rules as 'if im the first person in Jot, I can claim the whole thing'.

Why doesn't Greycloak work this way?
Why doesn't Skullport (Avatar) work this way?

Can someone explain the policy to me? I'm about to join the wild party to race to fireweed and I want to respect the rules as intended.

FWIW, It doesn't seem like you should be able to claim Jot unless you are there to kill Thrym and Loki - shrug.

**Comment by MikeyLikes** [comment]
Also, see other posts about how to potentially relieve pressure from fireweed which drives most of this problem. This is made worse by the impressive stability of toril these days.

**Comment by Dartan82** [comment]
It's not in the rules.  It's a gentlemen's agreement made many years ago when the branches were created if not the reason why the branches were created.  Not everyone follows the agreement.  Lili and I seem to follow it.  Some players honor it with us, some players don't.  Some are specifically selective about it.  

The only rule that pertains to this scenario is if a mob has been attacked by an player/players who can make the kill.  I would assume if the player dies it isn't up for grabs.  Not sure if some lvl 20 player tags and suicides does it mean he has claim as he wasn't able to kill the mob with the group (himself lvl 20 solo) he tagged with

Last I recalled the only way you can ever claim an entire zone is if you are at keys and have a group.  There were two instances in the last year where a group came in later on myself and an elementalist doing musp invasion as well as Gerin with one or two casters but he was AFK and cleared up to Lvernicus.  Both instances the group leader was aware that people were in zone and clearing.  No matter what the argument was or the rules, immortals stayed out.  So I guess the rules don't really matter anyways.

Would recommend just making jot rares !locate.  Unseelie is completely !locate on the grid rares.

**Comment by MikeyLikes** [comment]
!loc on totem seems like a good idea.

For my part I'm happy to do my best to conform to informal agreements but to be clear, does that mean run in and drop a coin or does it mean first to engage branches or does it mean first to engage rathnik? I have no plans to do this as a level 20.

**Comment by Dartan82** [comment]
First to engage the branches should be good enough.  TBH if you can't solo the branches and just go in to buy time for your group to run astral that's lame but to each their own.  Dropping a coin is probably good to show others someone is there.

**Comment by jokkmeister** [comment]
You should never be able to claim a zone alone. Jot contains a bunch of rares, many of which are used for quests. Claiming the zone just by killing branches is just lame. Everyone should get the same chance on finding the rares just like in other zones. It shoulödn't be based on who has the quickest connection and can use a rifter first.

**Comment by MikeyLikes** [comment]
To be clear, I don't care one whiff what the rule is - just looking for clarity. I kill relatively slowly and don't have the ability to spam through a zone looking for at boot rares like Rathnik. If the rule is 'first to engage Rathnik wins', I'll live with that, but it also means I won't even bother trying. If I can 'claim' a zone by engaging branches, I'll at least give it a shot.

What would suck is clearly my way towards a target one step at a time just to have someone follow my path in and take what I was after.

I agree with Dartan that it seems like many more grid rares should be put on delayed spawns and made !locate.

**Comment by shevarash** [comment]
Here is the rule in question:

```
11.It is illegal to "sit" on mobs. This means you can not kill a
   monster then wait for it to "repop" (load again into the game) so
   you can kill it again. Nor can you send one member of a group to a
   zone to claim any mobs. ALL of your group must be present. If you
   are sitting meming/praying and the mob is not aggro to you, or is
   not damaged in any fashion, it is not YOUR mob.

   Full groups must be prepared to attack a mob and be ready to deal with
   any followers or special conditions attacking it brings, for it to be
   "theirs." one player can not reserve a mob.  The entire group must be
   there, and attacking or have attacked the mob.
```

There are no specific rules about Jotunheim. If you are unable to settle disputes amongst yourselves with this zone, you may use the support channel to request that the staff intervene. In most of those cases, that means that the staff member will make a judgement call based on the specific circumstances.
