### ISSUE TITLE
massmorph

### ISSUE THREAD

**Issue by Uagr** [torilmud/issues#750]
Agros walk in and break it, archers in different rooms shoot through it

**Comment by shevarash** [comment]
Can you provide a little more information, or a log? Does this happen all the time, or just in certain areas?

**Comment by Uagr** [comment]
lol 1850 (650) central while zoning tonight-
___________________________________________
You continue your study.

[RETURN for more, q to quit]< 832h/868H 421p/502P 108v/114V >
< P: sit > 
An alert kobold archer's carefully aimed shot from the west hits Karodonir.

< 833h/868H 421p/502P 108v/114V >
< P: sit > 
Issazan starts casting a spell called 'Vitality'

< 833h/868H 421p/502P 108v/114V >
< P: sit > Approaching the Gates
Exits: -E -W
A small, sharpened stick lies on the ground.
Lilabipple  (Gnome) stands in mid-air here.
Pidibeple  (Gnome) stands in mid-air here.
Zalomirin  (Duergar) stands in mid-air here.(Red Aura)
Edgad  (Drow Elf) stands here.(Red Aura)
Karodonir  (Duergar) stands in mid-air here.(Red Aura)
Uggrax  (Troll) stands here.(Red Aura)
Rodar  (Shield Dwarf) stands in mid-air here.
Esdraelon  (Moon Elf) stands in mid-air here.
Jarro  (Moon Elf) stands here.
Issazan  (Yuan-Ti) stands in mid-air here.(Red Aura)
Nilan  (RP) (Drow Elf) stands here.(Red Aura)
Avestan  (Human) stands in mid-air here.(Red Aura)
Sunay  (RP) (Barbarian) stands in mid-air here.
Cronin  (Barbarian) stands in mid-air here.

< 833h/868H 421p/502P 109v/114V >
< P: sit > 
Avestan starts casting a spell called 'Protect Undead'

< 833h/868H 421p/502P 109v/114V >
< P: sit > 
Uggrax group-says '-->> VITALITY - OUT <<--'

< 834h/868H 422p/502P 110v/114V >
< P: sit > You group-say 'sec'

< 834h/868H 422p/502P 111v/114V >
< P: sit > 
Issazan completes his spell...

< 835h/868H 422p/502P 112v/114V >
< P: sit > 
You have finished memorizing Massmorph.
Your studies are complete.

< 836h/868H 422p/502P 112v/114V >
< P: std > You are already standing.

< 836h/868H 422p/502P 112v/114V >
< P: std > 
Avestan completes his spell...
A dark chill from beyond the grave seems to permeate the air around Avestan.

< 836h/868H 423p/502P 113v/114V >
< P: std > 
Issazan starts casting a spell called 'Vitality'

< 837h/868H 423p/502P 113v/114V >
< P: std > You group-say 'want to see if massmo stops'

< 837h/868H 423p/502P 114v/114V >
< P: std > You start chanting...

< 837h/868H 423p/502P 114v/114V >
< P: std > 
Casting: Massmorph *

< 838h/868H 423p/502P 114v/114V >
< P: std > 
An alert kobold archer's carefully aimed shot from the west hits Rodar.

< 838h/868H 424p/502P 114v/114V >
< P: std > 
An alert kobold archer's carefully aimed shot from the west hits Uggrax.
Casting: Massmorph 

< 839h/868H 424p/502P 114v/114V >
< P: std > 
You complete your spell...
Lilabipple's entire group slowly morphs into a pile of loose pebbles!

< 839h/868H 424p/502P 114v/114V >
< P: std > 
Issazan completes his spell...

< 839h/868H 424p/502P 114v/114V >
< P: std > 
You catch a flash of movement out of the corner of your eye.

< 840h/868H 424p/502P 114v/114V >
< P: std > You sit down and relax.
Issazan starts casting a spell called 'Vitality'

< 841h/868H 424p/502P 114v/114V >
< P: sit > You have memorized the following spells:
(10th circle)  2 - Nightmare
( 9th circle)  3 - Phantasmal Killer
( 8th circle)  1 - Dimensional Fold
               1 - Rainbow Pattern
               2 - Mislead
               1 - Mirror Image
( 7th circle)  1 - Sequester
               1 - Camouflage
               1 - Corpse Glamor
               3 - Phantasmal Blades
( 6th circle)  6 - Displacement
               1 - Nondetection
( 5th circle)  2 - True Sight
               1 - Dimension Door
               4 - Doppleganger
( 4th circle)  1 - Teleport
               1 - Phantom Steed
               1 - Dispel Magic
               1 - Scarlet Outline
               1 - Levitate
               3 - Spook
You continue your study.

[RETURN for more, q to quit]< 841h/868H 425p/502P 114v/114V >
< P: sit > 
Lilabipple opens an ancient tome and begins studying it intently.

< 842h/868H 425p/502P 114v/114V >
< P: sit > 
Issazan completes his spell...

< 843h/868H 426p/502P 114v/114V >
< P: sit > 
You have finished memorizing Massmorph.
Your studies are complete.

< 844h/868H 426p/502P 114v/114V >
< P: std > You are already standing.

< 844h/868H 426p/502P 114v/114V >
< P: std > Approaching the Gates
Exits: -E -W
A small, sharpened stick lies on the ground.
Lilabipple  (Gnome) sits resting in mid-air.
Pidibeple  (Gnome) stands in mid-air here.
Zalomirin  (Duergar) stands in mid-air here.(Red Aura)
Edgad  (Drow Elf) stands here.(Red Aura)
Karodonir  (Duergar) stands in mid-air here.(Red Aura)
Uggrax  (Troll) stands here.(Red Aura)
Rodar  (Shield Dwarf) stands in mid-air here.
Esdraelon  (Moon Elf) stands in mid-air here.
Jarro  (Moon Elf) stands here.
Issazan  (Yuan-Ti) stands in mid-air here.(Red Aura)
Nilan  (RP) (Drow Elf) stands here.(Red Aura)
Avestan  (Human) stands in mid-air here.(Red Aura)
Sunay  (RP) (Barbarian) stands in mid-air here.
Cronin  (Barbarian) stands in mid-air here.
Lilabipple group-says 'handy'

< 844h/868H 426p/502P 114v/114V >
< P: std > 
Issazan starts casting a spell called 'Vitality'

< 845h/868H 426p/502P 114v/114V >
< P: std > 
An alert kobold archer's carefully aimed shot from the west hits Edgad.

< 845h/868H 427p/502P 114v/114V >
< P: std > 
An alert kobold archer's carefully aimed shot from the west hits Rodar.

< 845h/868H 427p/502P 114v/114V >
< P: std > You group-say 'geat'

< 847h/868H 427p/502P 114v/114V >
< P: std > 
Issazan completes his spell...

< 847h/868H 427p/502P 114v/114V >
< P: std > 
Lilabipple group-says 'moving more'

< 848h/868H 428p/502P 114v/114V >
< P: std > 
Karodonir gives a hearty round of applause.

< 848h/868H 428p/502P 114v/114V >
< P: std > 
Lilabipple clambers to her feet.
Lilabipple, looking very frustrated, packs up her book.
Issazan sits down in a comfortable spot.

< 848h/868H 428p/502P 114v/114V >
< P: std > 
The illusion over Lilabipple's group is shattered!
Lilabipple flies east.
Cronin flies east.
Sunay flies east.
You follow Lilabipple east.

A T-Intersection in the Tunnels
Exits: -E -S -W
A small, sharpened stick lies on the ground.
Sunay  (RP) (Barbarian) stands in mid-air here.
Cronin  (Barbarian) stands in mid-air here.
Lilabipple  (Gnome) stands in mid-air here.
Avestan flies in from the west.
Jarro staggers in from the west.
Esdraelon flies in from the west.
Rodar flies in from the west.
Uggrax prowls in from the west.
Karodonir flies in from the west.
Edgad enters from the west.
Zalomirin flies in from the west.
Pidibeple flies in from the west.

< 849h/868H 428p/502P 113v/114V >
< P: std > 
Nilan group-says 'Massmorph DOWN!'
Sunay group-says 'Massmorph DOWN!'
Avestan group-says 'Massmorph DOWN!'
Zalomirin group-says 'Massmorph DOWN!'
Cronin group-says 'Massmorph DOWN!'

< 849h/868H 428p/502P 113v/114V >
< P: std > 
Karodonir group-says 'Massmorph DOWN!'
Jarro group-says 'Massmorph DOWN!'

**Comment by Uagr** [comment]
Its also broke the other way.... not breaking if he comes to my room and i engage
Casting: Massmorph 

< 800h/764H 592p/592P 260v/260V >
< P: std > 
You complete your spell...
Epuh's entire group slowly morphs into an assortment of furniture!

< 800h/764H 592p/592P 260v/260V >
< P: std > You sit down and relax.

< 800h/764H 592p/592P 260v/260V >
< P: sit > You have memorized the following spells:
( 8th circle)  2 - Mislead
               1 - Dimensional Fold
               1 - Rainbow Pattern
               1 - Mirror Image
( 7th circle)  1 - Sequester
               1 - Camouflage
               4 - Shadechill
( 6th circle)  4 - Displacement
               1 - Nondetection
( 5th circle)  2 - True Sight
               1 - Dimension Door
               1 - Doppleganger
               4 - Shadow Burst
( 4th circle)  2 - Scarlet Outline
               1 - Teleport
               3 - Spook
               1 - Levitate
               1 - Phantom Steed
               1 - Dispel Magic
( 3rd circle)  2 - Change Self
               3 - Mass Invisibility
You continue your study.

[RETURN for more, q to quit]< 800h/764H 592p/592P 260v/260V >
< P: sit > 
You have finished memorizing Nightmare.

< 799h/764H 592p/592P 260v/260V >
< P: sit > Saving...

< 799h/764H 592p/592P 260v/260V >
< P: sit > 
                Score information for Epuh

Level: 50   Race: Human   Class: Illusionist  
Hit points: 799(764)  Moves: 260(260)
Experience Progress: 10 % 
Coins carried:    0 platinum     1 gold    52 silver    93 copper
Coins in bank: 6750 platinum  6944 gold  6452 silver  4205 copper
Prestige: 6077   Acheron Kill Count: 0
Name status: Approved
Citizen of:   Waterdeep
Outcast from: Leuthilspar
Playing time: 16 days / 16 hours / 59 minutes
Title: 
Group Name: Epuh and Company
Group Leader: Epuh
Followers:
   a dark shade
   a phantom steed
Status:  Sitting around, resting.
         Memorizing
Detecting:       Invisible Evil Good Magic Life Heat
Protected from:  Evil Good Fire Cold Acid
Enchantments:    Displacement Farsee Invisibility Nondetection No Charm No Summon

Active Powers:
--------------
Invisibility, Displacement, Mirror Image, Nondetection, True Sight, Phantom Armor


< 799h/764H 592p/592P 260v/260V >
< P: sit > Saving...

< 798h/764H 592p/592P 260v/260V >
< P: sit > 
You have finished memorizing Phantasmal Killer.

< 798h/764H 592p/592P 260v/260V >
< P: sit > 
You have finished memorizing Phantasmal Killer.

< 797h/764H 592p/592P 260v/260V >
< P: sit > Saving...

< 797h/764H 592p/592P 260v/260V >
< P: sit > You are using:
<worn as a badge>    a badge of writhing pink flames (magic)
<worn on head>       the scaled helm of the dragonkind (magic) (glowing)
<worn on eyes>       mithril framed spectacles (magic)
<worn in ear>        an opal earring
<worn in ear>        an opal earring
<worn on face>       a swirling onyx face mask
<worn around neck>   a circlet of the purest blue earthstone
<worn around neck>   a torque of aquatic dragon scales (magic)
<worn on body>       a robe of the one eyed (magic)
<worn about body>    the mantle of knowledge (magic)
<component bag>      a pouch of displacement (illuminating)
<worn about waist>   the intricately runed belt of the slaadi lords (magic)
<worn on arms>       a set of gossamer sleeves of the mystic (magic)
<held as shield>     a jagged steel buckler painted with an eye
<worn around wrist>  a green marble bracer of defense
<worn around wrist>  a bracer of armor (magic)
<worn on hands>      a pair of runed balorskin gloves (magic)
<worn on finger>     a severely damaged horned ring (magic)
<worn on finger>     a severely damaged horned ring (magic)
<primary weapon>     a black glass staff encrusted with a crystal orb (magic)
<worn on legs>       some adamantine greaves inlayed with rubies
<worn on feet>       the mystical boots of the traveler (magic) (glowing)

< 797h/764H 592p/592P 260v/260V >
< P: sit > Lizardman Dwelling
Exits: - West 
*A dark shade shifts in and out of reality here.
A phantom steed floats here, fading in and out of the shadows.

< 796h/764H 592p/592P 260v/260V >
< P: sit > 
You have finished memorizing Phantasmal Killer.

< 796h/764H 592p/592P 260v/260V >
< P: sit > 
You scan west...
Entrance to a Lizardman Village
Exits: -N -E -S -W#
Huge puddles of blood cover the ground.
Corpse of a lizardman soldier is lying here.
[2] Corpse of a lizardman warrior is lying here.
A lizardman stands here.(Red Aura)
A lizardman stands here.(Red Aura)

< 796h/764H 592p/592P 260v/260V >
< P: sit > 
You have finished memorizing Nightmare.

< 795h/764H 592p/592P 260v/260V >
< P: sit > 
                Score information for Epuh

Level: 50   Race: Human   Class: Illusionist  
Hit points: 795(764)  Moves: 260(260)
Experience Progress: 10 % 
Coins carried:    0 platinum     1 gold    52 silver    93 copper
Coins in bank: 6750 platinum  6944 gold  6452 silver  4205 copper
Prestige: 6077   Acheron Kill Count: 0
Name status: Approved
Citizen of:   Waterdeep
Outcast from: Leuthilspar
Playing time: 16 days / 16 hours / 59 minutes
Title: 
Group Name: Epuh and Company
Group Leader: Epuh
Followers:
   a dark shade
   a phantom steed
Status:  Sitting around, resting.
         Memorizing
Detecting:       Invisible Evil Good Magic Life Heat
Protected from:  Evil Good Fire Cold Acid
Enchantments:    Displacement Farsee Invisibility Nondetection No Charm No Summon

Active Powers:
--------------
Invisibility, Displacement, Mirror Image, Nondetection, True Sight, Phantom Armor


< 795h/764H 592p/592P 260v/260V >
< P: sit > Saving...

< 795h/764H 592p/592P 260v/260V >
< P: sit > You have finished memorizing Phantasmal Tendrils.
Epuh is in an excellent condition. (Medium)
His form is displaced, and difficult to track!
He is surrounded by a cluster of mirror images.

< 795h/764H 592p/592P 260v/260V >
< P: sit > 
You have finished memorizing Displacement.

< 794h/764H 592p/592P 260v/260V >
< P: sit > 
You have finished memorizing Phantasmal Killer.

< 793h/764H 592p/592P 260v/260V >
< P: sit > 
You have finished memorizing Phantasmal Tendrils.

< 793h/764H 592p/592P 260v/260V >
< P: sit > 
You have finished memorizing Invisibility.

< 792h/764H 592p/592P 260v/260V >
< P: sit > 
A lizardman enters from the west.

< 792h/764H 592p/592P 260v/260V >
< P: sit > Lizardman Dwelling
Exits: - West 
A lizardman stands here.(Red Aura)
*A dark shade shifts in and out of reality here.
A phantom steed floats here, fading in and out of the shadows.

< 792h/764H 592p/592P 260v/260V >
< P: sit > 
You have finished memorizing Summon Shade.

< 792h/764H 592p/592P 260v/260V >
< P: sit > This lizardman seems to be a common villager. Dressed in a small
loincloth, he goes about his business of the day. He hisses occasionally
at the empty air.
A lizardman is a medium-sized level 40 Reptile.
He is in awful condition.


< 792h/764H 592p/592P 260v/260V >
< P: sit > 
You have finished memorizing Massmorph.
Your studies are complete.

< 792h/764H 592p/592P 260v/260V >
< P: std > You are already standing.

< 792h/764H 592p/592P 260v/260V >
< P: std > You pat a lizardman on his head.

< 792h/764H 592p/592P 260v/260V >
< P: std > You snap into visibility.
You start chanting...

< 792h/764H 592p/592P 260v/260V >
< P: std > 
Casting: Phantasmal Killer **

< 791h/764H 592p/592P 260v/260V >
< P: std > 
You complete your spell...
A wavering ethereal form appears beside a lizardman, who drops dead, his mind destroyed.
a lizardman is dead! R.I.P.
You receive 11,000 XP (0.03%) experience.
Your blood freezes as you hear the rattling death cry of a lizardman.

< 791h/764H 592p/592P 260v/260V >
< P: std > The corpse of a lizardman does not contain the coins.

< 791h/764H 592p/592P 260v/260V >
< P: std > You start chanting...

< 791h/764H 592p/592P 260v/260V >
< P: std > 
Casting: Massmorph *

< 790h/764H 592p/592P 260v/260V >
< P: std > 
You complete your spell...
Your group is already massmorphed!

< 790h/764H 592p/592P 260v/260V >
< P: std > You sit down and relax.

< 790h/764H 592p/592P 260v/260V >
< P: sit > You have memorized the following spells:
(10th circle)  2 - Nightmare
               2 - Phantasmal Tendrils
( 9th circle)  3 - Phantasmal Killer
( 8th circle)  2 - Mislead
               1 - Dimensional Fold
               1 - Rainbow Pattern
               1 - Mirror Image
( 7th circle)  1 - Sequester
               1 - Camouflage
               4 - Shadechill
( 6th circle)  5 - Displacement
               1 - Nondetection
               1 - Summon Shade
( 5th circle)  2 - True Sight
               1 - Dimension Door
               1 - Doppleganger
               4 - Shadow Burst
( 4th circle)  2 - Scarlet Outline
               1 - Teleport
               3 - Spook
               1 - Levitate
You continue your study.

[RETURN for more, q to quit]< 790h/764H 592p/592P 260v/260V >
< P: sit > 
                Score information for Epuh

Level: 50   Race: Human   Class: Illusionist  
Hit points: 790(764)  Moves: 260(260)
Experience Progress: 10 % 
Coins carried:    0 platinum     1 gold    52 silver    93 copper
Coins in bank: 6750 platinum  6944 gold  6452 silver  4205 copper
Prestige: 6077   Acheron Kill Count: 0
Name status: Approved
Citizen of:   Waterdeep
Outcast from: Leuthilspar
Playing time: 16 days / 17 hours / 0 minutes
Title: 
Group Name: Epuh and Company
Group Leader: Epuh
Followers:
   a dark shade
   a phantom steed
Status:  Sitting around, resting.
         Memorizing
Detecting:       Invisible Evil Good Magic Life Heat
Protected from:  Evil Good Fire Cold Acid
Enchantments:    Displacement Farsee Nondetection No Charm No Summon

Active Powers:
--------------
Displacement, Mirror Image, Nondetection, True Sight, Phantom Armor


< 790h/764H 592p/592P 260v/260V >
< P: sit > 
You have finished memorizing Phantasmal Killer.

< 789h/764H 592p/592P 260v/260V >
< P: sit > 
You have finished memorizing Massmorph.
Your studies are complete.

< 788h/764H 592p/592P 260v/260V >
< P: std > You are already standing.

**Comment by shevarash** [comment]
This will be addressed in an upcoming overhaul to the Illusionist class.
