### ISSUE TITLE
Zones where trash is commonly skipped

### ISSUE THREAD

**Issue by Dartan82** [torilmud/issues#752]
Southern Forest

**Comment by MikeyLikes** [comment]
New cave city

**Comment by vitaladsr** [comment]
CPV water tunnel/phaerim boss “Destri”
Jot/Musp
Rib
Hullburg
TK lower dungeon

**Comment by Uagr** [comment]
Area's only done for spell quests
Anything not Seelie, CPH, tia, baha, SM, Izans, Scorps, SM
some things I haven't seen in forever hulubrug, gf, SG, ET, Oakvale, MD, yath, Driders, derro, deep dragon

**Comment by vitaladsr** [comment]
> Area's only done for spell quests
> 
> Anything not Seelie, CPH, tia, baha, SM, Izans, Scorps, SM
> 
> some things I haven't seen in forever hulubrug, gf, SG, ET, Oakvale, MD, yath, Driders, derro, deep dragon

Derro may be unlike you remember FYI!

**Comment by shevarash** [comment]
I am unsure what the goal of this issue is. Closing, but please feel free to re-open if there's something that needs addressed here.
