### ISSUE TITLE
Potion effects fail to work while stunned.

### ISSUE THREAD

**Issue by Misarie** [torilmud/issues#754]
A phase spider completes its spell...
A phase spider utters the words, 'iuophwabraz'.
a phase spider brings your worst nightmares into existence to attack you viciously!
YIKES!  Another hit like that, and you've had it!!
You are stunned by the horrific visions!
The world starts spinning, and your ears are ringing!
stand

< 131h/681H 171v/172V |cr +|tr +|bs +| >
< T: Azora TC: pretty hurt E: spider EC: excellent P: std > 

You dodge a phase spider's vicious attack.
You dodge a phase spider's vicious attack.
Upon being struck, a mirror image of a phase spider shatters into a million particles of light!
Upon being struck, a mirror image of a phase spider shatters into a million particles of light!
Your powerful pierce barely wounds a phase spider.
You miss a phase spider with your pierce.

< 131h/681H 172v/172V |cr +|tr +|bs +| >
< T: Azora TC: pretty hurt E: spider EC: few scratches P: std > 
You are already standing.

< 131h/681H 172v/172V |cr +|tr +|bs +| >
< T: Azora TC: pretty hurt E: spider EC: few scratches P: std > 
A phase spider misses you with its sting.
A phase spider misses you with its sting.
Upon being struck, a mirror image of a phase spider shatters into a million particles of light!
You miss a phase spider with your pierce.
A phase spider dodges your futile attack.

< 131h/681H 172v/172V |cr +|tr +|bs +| >
< T: Azora TC: pretty hurt E: spider EC: few scratches P: std > 
esc s;bl;
apply sap dagger sack;apply sap 2.dagger sack
			

                                 
                                 
                                 
       ------- -------           
      |` ` ,-,|,!,|,-,|          
-------       |   |   ----       
   , , , , , , ,@,|,-, ,-,|      
-------       |   |   ----       
      |` ` ,-,|, , ,-,|          
       -------|   ----           
              |, ,|              
               ---               
                                 
			
The Stalagmite Covered Floor of the Deep Chasm
Exits: -N -S -W
A massive stalagmite protrudes from the cavern floor.
You escape southward!

< 131h/681H 171v/172V |cr +|tr +|bs +| >
< P: std > You generously apply poison to an enchanted khanjari dagger.

< 131h/681H 171v/172V |cr +|tr +|bs +| >
< P: std > You generously apply poison to an enchanted khanjari dagger.

< 131h/681H 171v/172V |cr +|tr +|bs +| >
< P: std > 
quaff tankard eyes
As you quaff a tankard of blessed ale, the vial disappears in a bright flash of light.
You are stunned and unable to concentrate enough for that!
You are stunned and unable to concentrate enough for that!
You are stunned and unable to concentrate enough for that!

< 131h/681H 172v/172V |cr +|tr +|bs +| >
< P: std >

**Comment by shevarash** [comment]
This was resolved with the recent consumables update.
