### ISSUE TITLE
Weapon proc rates tweak

### ISSUE THREAD

**Issue by vitaladsr** [torilmud/issues#755]
There are a few weapons out there that I think fall into at least TWO of the following categories and are meant to be pretty legendary, however falling disappointingly short due to a low proc rate.

1. Super rare load
2. Extremely difficult to obtain
3. Not many in game

As a former areas designer and tester of many of my own procs I understand that testing proc rate and damage output is the most important YET the most difficult thing to accurately do. This leads developers to err on the side of caution and then back it off 1 more notch for good measure. As a result many great items are regarded "trash" and I think this one simple tweak could breath new life info areas, quests and content that has been disregarded (some for decades) .. areas and quests that are well designed and fun .. who doesn't want more of that. This is a soloution for "virtually" added new content without the tedious task of designing new content :)

Perhaps players can make a list together if you think its a good idea. Ill start with the item that gave me the idea

Item list:

1. the mystical hammer of frigid destruction (most rare item, end load CPV .. I see it 1 in 20 loads, give or take. I believe its about 5% and contingent on a prearranged treasure chest load)
2.

**Comment by shevarash** [comment]
Surely there are more to add to this list...
