### ISSUE TITLE
Heal after death?

### ISSUE THREAD

**Issue by Uagr** [torilmud/issues#756]
You are dead!

Your soul is transported to The Fugue Plane as your crumbling body succumbs
to the cold sleep of death. Here in Kelemvor's realm all dead souls await
either judgement or escape from this timeless prison.

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

The Top of the Crystal Spire on the Fugue Plane
Exits: None!
A wispy smoke colored portal hovers just above the center of the room.

From here you may either re-enter the game by typing enter portal, or wait
to be resurrected by another player. Type help death for more information.

You can't do that on the Fugue Plane.

You group-say 'they love me'

You can't do that on the Fugue Plane.

You can't do that on the Fugue Plane.

You can't do that on the Fugue Plane.

< 161h/695H 143p/572P 41v/160V >
< P: std > 
Your wounds begin to close as the healing aura around you pulsates.

< 345h/695H 144p/572P 41v/160V >
< P: std > The Top of the Crystal Spire on the Fugue Plane
Exits: None!
A wispy smoke colored portal hovers just above the center of the room.

< 345h/695H 144p/572P 41v/160V >
< P: std > 
Your wounds begin to close as the healing aura around you pulsates.

< 529h/695H 144p/572P 41v/160V >

**Comment by shevarash** [comment]
This has been fixed. Thank you for the bug report.
