### ISSUE TITLE
Feature request - quit check

### ISSUE THREAD

**Issue by Uagr** [torilmud/issues#757]
quit check -simple enough, tells you if you have something that can't be saved if you leave (aka no rent) before you rent/camp.....

**Comment by marthammor** [comment]
While this is something that can be added, the performance hit would be huge to loop through every item a character has to check for a specific flag. That is the reason why the finditem command only searches so far in bags and has lag, to keep people from spamming it and lagging the mud.

**Comment by Uagr** [comment]
I've seen other muds do this no lag no issue, maybe change it so !rent items mean you can't rent/quit either.... then youd definitely find that item :), such as the !rent flag adds the flag to the char, with the item# so when you quit /quit check it says no this item prevents you from renting?

**Comment by shevarash** [comment]
We have another issue open to track this same request.
