### ISSUE TITLE
bugged hide?

### ISSUE THREAD

**Issue by Uagr** [torilmud/issues#758]
<busted hide - no he wasn't invis or invis & hiding, get should have broke hide>
Someone gets a small barrel.
You find Kandzan Swiftfingers hiding here!

Tested w/my rogue
You stop trying to hide.
You get a crudely crafted bone arrow.

**Comment by Uagr** [comment]
casting spells while hidden too

< P: std > Someone completes its spell...
Someone utters the words, 'coldshield'.


A beautiful melody floats through the forest as Faelarae plays her lute flawlessly.
Someone completes its spell...
Someone utters the words, 'qaregpuzre'.
You are using:
<worn as a badge>    a badge of writhing pink flames (magic)
<worn on head>       the iron crown of the frost giant warlords (magic)
**<worn on eyes>       a pair of golden spectacles (magic)**
<worn in ear>        an obsidian earring shaped like a skull
<worn in ear>        a lightning earring
<worn on face>       a sandstorm mask
<worn on body>       some enchanted quickling armor (magic)
<worn about body>    a glimmering cloak of the faerie king (illuminating)
<worn as quiver>     a yetihide quiver of the Flying Boulder tribe (magic)
<worn about waist>   an indented belt layered with teeth
<worn on arms>       vermillion chainmail sleeves (magic)
<worn around wrist>  a shiny mithril bracelet (magic)
<worn around wrist>  a shiny mithril bracelet (magic)
<worn on hands>      a pair of silverish githyanki gauntlets
<worn on finger>     a beautifully enscribed turquoise ring (magic)
<worn on finger>     a flaming ring of the efreeti (magic)
<wielding twohanded> a powerful recurve bow
<worn on legs>       a pair of djinn battle greaves (magic)
<worn on feet>       the mystical boots of the traveler (magic) (glowing)

< 363h/593H 256v/260V >
< P: std > 
A Silver Oak Tree
Exits: - North - East  - South - West 
[15] Corpse of a weevil is lying here.
*A small black dragonet flutters about here.
Faelarae Willowsong sits here weaving a magic tale.
A tiny atomie floats here shifting in and out of sight.(Gold Aura)
A sprite flutters about the trees here.(Gold Aura)

< 363h/593H 257v/260V >
< P: std > 
You boggle at that concept.

< 363h/593H 259v/260V >
< P: std > 
You find a silvery wisp hiding here!
You find a silvery wisp hiding here!

< 365h/593H 260v/260V >
< P: std > The rain is falling less heavily now.

A silvery wisp completes its spell...
A silvery wisp utters the words, 'globe of invulnerability'.
A silvery wisp begins to shimmer.


You find a silvery wisp hiding here!
You find a silvery wisp hiding here!

< 367h/593H 260v/260V >
< P: std > 
You perform a thorough search of the area.
You find a silvery wisp hiding here!
You find a silvery wisp hiding here!

< 369h/593H 260v/260V >
< P: std > A silvery wisp starts casting a spell called 'stoneskin'.


You perform a thorough search of the area.
You complete your search and conclude there is nothing to be found.

< 372h/593H 260v/260V >
< P: std > A silvery wisp completes its spell...
A silvery wisp utters the words, 'stoneskin'.
A silvery wisp's skin seems to turn to stone.

A silvery wisp completes its spell...
A silvery wisp utters the words, 'stoneskin'.

A silvery wisp starts casting a spell called 'protection from undead'.

**Comment by marthammor** [comment]
Mobs are special in that they can stay hidden and perform actions that would break hide for players. The only thing that breaks their hide is them performing an aggressive act, or someone searching them out.
Working as intended.
