### ISSUE TITLE
Invis/Mass invis issues

### ISSUE THREAD

**Issue by Uagr** [torilmud/issues#759]
was practicing skills....found mass invis is broke, and invis has 'issues'

#1) Invised a shadow - he stayed invis while fighting me
#2 ) Mass invis is only targeting me & pet, nobody/else in room.... also how do you invis a invisible shade?

#1 < T: Epuh TC: few scratches E: shadow EC: few wounds P: std > You start chanting...

< T: Epuh TC: few scratches E: shadow EC: few wounds P: std > 
A shadow misses you with its drain.
<SNIP>
A shadow misses you with its drain.

< 722h/729H 572p/572P 260v/260V >
< T: Epuh TC: few scratches E: shadow EC: few wounds P: std > 
Casting: Invisibility 

< T: Epuh TC: few scratches E: shadow EC: few wounds P: std > 
You complete your spell...
A shadow slowly fades out of existence.

< T: Epuh TC: few scratches E: shadow EC: few wounds P: std > A Dark Alcove
Exits: - South
[3] Corpse of a shadow is lying here.
*A shadow stands here, fighting YOU!(Red Aura)
A shadow stands here, fighting YOU!(Red Aura)
A shadow stands here, fighting YOU!(Red Aura)
*A shadow stands here, fighting YOU!(Red Aura)
A shadow stands here, fighting YOU!(Red Aura)
<SNIP>
A shadow stands here, fighting YOU!(Red Aura)

#2 a few mass invis tests in and out of fights, with and without eq in room.
#2 <mass invis - self only?>

< T: Epuh TC: few scratches E: shadow EC: small wounds P: std > You start chanting...

< T: Epuh TC: few scratches E: shadow EC: small wounds P: std > 
A shadow recognizes you, and charges to attack you!
A shadow barely wounds you with its average drain.

< T: Epuh TC: few scratches E: shadow EC: small wounds P: std > 
A shadow recognizes you, and charges to attack you!
A shadow misses you with its drain.

< T: Epuh TC: few scratches E: shadow EC: small wounds P: std > 
A shadow recognizes you, and charges to attack you!
A shadow misses you with its drain.

< T: Epuh TC: few scratches E: shadow EC: small wounds P: std > 
Casting: Mass Invisibility ****

< T: Epuh TC: few scratches E: shadow EC: small wounds P: std > 
A shadow recognizes you, and charges to attack you!
A shadow misses you with its drain.

< T: Epuh TC: few scratches E: shadow EC: small wounds P: std > 
Casting: Mass Invisibility ***

< T: Epuh TC: few scratches E: shadow EC: small wounds P: std > 
A shadow misses you with its drain.
A shadow misses you with its drain.
A shadow barely wounds you with its average drain.
A shadow misses you with its drain.
A shadow misses you with its drain.
A shadow misses you with its drain.
A shadow misses you with its drain.
A shadow misses you with its drain.
A shadow misses you with its drain.
A shadow misses you with its drain.
A shadow misses you with its drain.
A shadow misses you with its drain.
A shadow misses you with its drain.
A shadow misses you with its drain.
A shadow misses you with its drain.
A shadow misses you with its drain.
A shadow misses you with its drain.
A shadow misses you with its drain.
A shadow misses you with its drain.
A shadow misses you with its drain.
A shadow misses you with its drain.
A shadow misses you with its drain.

< T: Epuh TC: few scratches E: shadow EC: small wounds P: std > 
Casting: Mass Invisibility **

< T: Epuh TC: few scratches E: shadow EC: small wounds P: std > 
Casting: Mass Invisibility *

< T: Epuh TC: few scratches E: shadow EC: small wounds P: std > 
You complete your spell...
You vanish.

< T: Epuh TC: few scratches E: shadow EC: small wounds P: std > 
A shadow misses you with its drain.
<SNIP>
A shadow misses you with its drain.
You snap into visibility.
You miss a shadow with your bludgeon.
A shadow misses you with its drain.
<SNIP>
A shadow misses you with its drain.

#2x2 <again>

< T: Epuh TC: small wounds E: shadow EC: pretty hurt P: std > You start chanting...

< T: Epuh TC: small wounds E: shadow EC: pretty hurt P: std > 
Casting: Mass Invisibility ****

< T: Epuh TC: small wounds E: shadow EC: pretty hurt P: std > 
Casting: Mass Invisibility ***
A shadow misses you with its drain.
A shadow misses you with its drain.
<snip>
A shadow misses you with its drain.
Someone misses you with its drain.
A shadow misses you with its drain.
<snip>

< T: Epuh TC: small wounds E: shadow EC: pretty hurt P: std > 
Casting: Mass Invisibility **

< T: Epuh TC: small wounds E: shadow EC: pretty hurt P: std > 
Casting: Mass Invisibility *

< T: Epuh TC: small wounds E: shadow EC: pretty hurt P: std > 
You complete your spell...
You vanish.

< T: Epuh TC: small wounds E: shadow EC: pretty hurt P: std > 
You snap into visibility.
Your average bludgeon brutally wounds a shadow.
A shadow misses you with its drain.
A shadow misses you with its drain.
A shadow misses you with its drain.
A shadow misses you with its drain.
A shadow barely wounds you with its average drain.
A shadow misses you with its drain.
A shadow barely wounds you with its average drain.
Someone misses you with its drain.
A shadow misses you with its drain.
<snip>

#2 <with eq in room>

You drag some iron rations along behind you.
You drag a small barrel along behind you.

< P: std > 
A shadow misses you with its drain.
<snip>
A shadow misses you with its drain.
A shadow barely wounds you with its average drain.
A shadow misses you with its drain.
<snip>

< T: Epuh TC: excellent E: shadow EC: excellent P: std > 
A shadow misses you with its drain.
A shadow misses you with its drain.

< T: Epuh TC: excellent E: shadow EC: excellent P: std > 
A shadow recognizes you, and charges to attack you!
A shadow misses you with its drain.
A shadow misses you with its drain.
Your displaced form snaps back to your physical location!
displace out
A shadow misses you with its drain.

< T: Epuh TC: excellent E: shadow EC: excellent P: std > 
A shadow recognizes you, and charges to attack you!
A shadow misses you with its drain.

< T: Epuh TC: excellent E: shadow EC: excellent P: std > 
A shadow misses you with its drain.

< T: Epuh TC: excellent E: shadow EC: excellent P: std > You start chanting...

< T: Epuh TC: excellent E: shadow EC: excellent P: std > 
Casting: Mass Invisibility ****

< T: Epuh TC: excellent E: shadow EC: excellent P: std > 
A shadow misses you with its drain.
<snip>

< T: Epuh TC: excellent E: shadow EC: excellent P: std > 
Casting: Mass Invisibility ***

< T: Epuh TC: excellent E: shadow EC: excellent P: std > 
Casting: Mass Invisibility **

< T: Epuh TC: excellent E: shadow EC: excellent P: std > 
Casting: Mass Invisibility *

< T: Epuh TC: excellent E: shadow EC: excellent P: std > 
You complete your spell...
You vanish.

< T: Epuh TC: excellent E: shadow EC: excellent P: std > 
Autosaving...

< T: Epuh TC: excellent E: shadow EC: excellent P: std > 
A shadow misses you with its drain.
<snip>
A shadow misses you with its drain.
You snap into visibility.
Your average bludgeon badly wounds a shadow.
A shadow misses you with its drain.

< T: Epuh TC: excellent E: shadow EC: small wounds P: std > A Dark Alcove
Exits: -S
A water barrel has been left here.
A small stack of cracker-like iron rations sits here, waiting to be eaten.
A shadow stands here, fighting YOU!(Red Aura)
A shadow stands here, fighting YOU!(Red Aura)
A shadow stands here, fighting YOU!(Red Aura)
<snip>

> You start chanting...

< T: Epuh TC: small wounds E: shadow EC: small wounds P: std > 
A shadow misses you with its drain.
A shadow barely wounds you with its average drain.
A shadow misses you with its drain.
<snip>

< T: Epuh TC: small wounds E: shadow EC: small wounds P: std > 
Casting: Invisibility 

< T: Epuh TC: small wounds E: shadow EC: small wounds P: std > 
You complete your spell...
A shadow slowly fades out of existence.

< T: Epuh TC: small wounds E: shadow EC: small wounds P: std > You start chanting...

< T: Epuh TC: small wounds E: shadow EC: small wounds P: std > 
A shadow misses you with its drain.
<snip>

< T: Epuh TC: small wounds E: shadow EC: small wounds P: std > 
Casting: Invisibility *

< T: Epuh TC: small wounds E: shadow EC: small wounds P: std > 
Casting: Invisibility 

< T: Epuh TC: small wounds E: shadow EC: small wounds P: std > 
You complete your spell...
A shadow slowly fades out of existence.

< T: Epuh TC: small wounds E: shadow EC: small wounds P: std > A Dark Alcove
Exits: -S
Splattered droplets of blood cover the area.
A water barrel has been left here.
A small stack of cracker-like iron rations sits here, waiting to be eaten.
*A shadow stands here, fighting YOU!(Red Aura)
*A shadow stands here, fighting YOU!(Red Aura)
A shadow stands here, fighting YOU!(Red Aura)
A shadow is lying here, incapacitated.(Red Aura)
A shadow stands here, fighting YOU!(Red Aura)
<SNIP>
A shadow stands here, fighting YOU!(Red Aura)

#2 <also doesn't work out of fights>
You start chanting...

Casting: Minor Creation *

You complete your spell...
A small barrel suddenly appears.

You start chanting...

Casting: Minor Creation *

You complete your spell...
Some iron rations suddenly appears.

An Abandoned Mine Tunnel
Exits: -N -E -W
[2] A small stack of cracker-like iron rations sits here, waiting to be eaten.
[2] A water barrel has been left here.
A cloaked kobold attempts to hide here.(Red Aura)
A dwarven ghost wails loudly here.

You start chanting...

Casting: Mass Invisibility ****

Casting: Mass Invisibility *

You complete your spell...
You vanish.

An Abandoned Mine Tunnel
Exits: -N -E -W
[2] A small stack of cracker-like iron rations sits here, waiting to be eaten.
[2] A water barrel has been left here.
A cloaked kobold attempts to hide here.(Red Aura)
A dwarven ghost wails loudly here.

---------
<shades are always invis...>
> You start chanting...

< T: Epuh TC: excellent E: shadow EC: small wounds P: std > 
Casting: Mass Invisibility ****

< T: Epuh TC: excellent E: shadow EC: small wounds P: std > 
A shadow misses you with its drain.
A shadow misses you with its drain.
A shadow misses a dark shade with its drain.
<SNIP>
A shadow misses a dark shade with its drain.
A shadow misses a dark shade with its drain.
A shadow switches targets..
A shadow misses a dark shade with its drain.
A dark shade misses a shadow with its drain.
A dark shade misses a shadow with its drain.
A shadow misses a dark shade with its drain.
<SNIP>
A shadow misses a dark shade with its drain.
A shadow misses a dark shade with its drain.

< T: Epuh TC: excellent E: shadow EC: small wounds P: std > 
Casting: Mass Invisibility ***

< T: Epuh TC: excellent E: shadow EC: small wounds P: std > 
Casting: Mass Invisibility **

< T: Epuh TC: excellent E: shadow EC: small wounds P: std > 
Casting: Mass Invisibility *

Epuh TC: excellent E: shadow EC: small wounds P: std > 
You complete your spell...
You vanish.
A dark shade slowly fades out of existence.

---------
An Abandoned Mine Tunnel
Exits: -E -W
A slender yuan-ti scouts the area.(Red Aura)

< 713h/729H 572p/572P 256v/260V >
< P: std > You start chanting...

< 713h/729H 572p/572P 257v/260V >
< P: std > 
Casting: Mass Invisibility ****

< 713h/729H 572p/572P 258v/260V >
< P: std > 
Casting: Mass Invisibility ***

< 714h/729H 572p/572P 259v/260V >
< P: std > 
Casting: Mass Invisibility **

< 715h/729H 572p/572P 259v/260V >
< P: std > 
Casting: Mass Invisibility *

< 716h/729H 572p/572P 260v/260V >
< P: std > 
You complete your spell...
You vanish.

< 716h/729H 572p/572P 260v/260V >
< P: std > An Abandoned Mine Tunnel
Exits: -E -W
A slender yuan-ti scouts the area.(Red Aura)

< P: std > "MASS INVISIBILITY"
Spell.

Area of effect: Room
Aggressive:     No
Cumulative:     No
Duration:       Dependent on proficiency of caster
Class/Circle:   Illusionist 3rd, Enchanter 4th
Type of spell:  Illusion

The caster attempts to cast "invisibility" on every creature and object in
the room, including himself/herself.

See also:  INVISIBILITY

**Comment by shevarash** [comment]
Shadows are permanently invis. This is normal.

Mass invisibility only targets your group now.

```
Name             : Mass Invisibility [massi]
Type             : Spell                    
Prepare          : Study                    
Target           : Group
Activation Time  : 8 seconds 
Related Skill    : spellcast illusion   Hit Gain: 0   Miss Gain: 0   NPC Base: 0  %
Restrictions     : Autofire, Garrote, Standing, Can Speak

Effects:
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Group Effect     : Add invisible for 43 minutes 24 seconds            Radius: All 
```
