### ISSUE TITLE
Syntax fix on sleep proc

### ISSUE THREAD

**Issue by Uagr** [torilmud/issues#760]
{Relith closes %s eyes and falls asleep.}
---log----
Dhaern attacks an adult brass dragon, landing three hits.
An adult brass dragon attacks Rigoris, landing a single hit.
An adult brass dragon breathes a cloud of tranquilizing gas!
Relith closes %s eyes and falls asleep.
With no one to accompany you, your song ends!
You stop your song.

The world starts spinning, and your ears are ringing!

< 879h/1118H 444p/444P 160v/160V >
< T: Rigoris TC: excellent E: brass EC: awful P: std > 
Rigoris's weapon begins to pulse with a sinister glow as his soul fills with vengeance.
An adult brass dragon is consumed by the purifying flames as Rigoris lashes out in retribution!
an adult brass dragon is dead! R.I.P.
You receive 14,710 XP (0.04%) experience.
Your blood freezes as you hear the rattling death cry of an adult brass dragon.

< 879h/1118H 444p/444P 160v/160V >
< P: std > You get a small pile of coins from corpse of an adult brass dragon.
There were: 16 platinum coins, 37 gold coins, 25 silver coins.

< 879h/1118H 444p/444P 160v/160V >
< P: std > 
Your wounds continue to bleed out of control!
The world stops spinning.
Lilabipple group-says 'mem'

< 839h/1118H 444p/444P 160v/160V >
< P: std > 
Cronin sits down in a comfortable spot.

< 839h/1118H 444p/444P 160v/160V >
< P: std > 
Cronin takes out his holy symbol and begins praying intently.

< 839h/1118H 444p/444P 160v/160V >
< P: std > 
Kajj sits down in a comfortable spot.
Korra takes out her holy symbol and begins praying intently.

< 839h/1118H 444p/444P 160v/160V >
< P: std > 
Kajj takes out his holy symbol and begins praying intently.

< 839h/1118H 444p/444P 160v/160V >
< P: std > You try to wake him up, but he does not respond!

< 841h/1118H 444p/444P 160v/160V >
< P: std > 
Hisol takes out his holy symbol and begins praying intently.

< 841h/1118H 444p/444P 160v/160V >
< P: std > You try to wake him up, but he does not respond!

< 842h/1118H 444p/444P 160v/160V >
< P: std > You try to wake him up, but he does not respond!

< 842h/1118H 444p/444P 160v/160V >
< P: std > You try to wake him up, but he does not respond!

**Comment by OghmaToril** [comment]
This has been fixed and will go in during a future code move.
