### ISSUE TITLE
"undead" - ignore stun & "heal" themselves

### ISSUE THREAD

**Issue by Uagr** [torilmud/issues#761]
I understand not being stunned by spook.... but nightmare?
Also shouldn't they use heal undead vs heal?
--------------------
The ghost completes his spell...
The ghost utters the words, 'yjrr pzar'.
The ghost summons a holy light and heals his own wounds.
=-----------------------------
Casting: Nightmare ***

< 899h/924H 572p/572P 260v/260V >
< T: dark TC: excellent E: ghost EC: small wounds P: std > 
You complete your spell...
Your spell is partially absorbed by the ghost.
You bring the ghost's worst nightmares into existence to attack him viciously!
The ghost is stunned by the horrific visions!

< 900h/924H 572p/572P 260v/260V >
< T: dark TC: excellent E: ghost EC: few wounds P: std > 
Your attack only grazes the ghost as he dodges aside!
Your weak bludgeon barely wounds the ghost.
The ghost misses a dark shade with his beat.
The ghost misses a dark shade with his beat.
The ghost starts casting an offensive spell.
A dark shade misses the ghost with its drain.
A dark shade misses the ghost with its drain.

< 900h/924H 572p/572P 260v/260V >
--------------
Casting: Nightmare *

< 673h/734H 572p/572P 260v/260V >
< P: std > 
You complete your spell...
Your spell is partially absorbed by the ghost.
You bring the ghost's worst nightmares into existence to attack him viciously!
The ghost is stunned by the horrific visions!
The ghost misses you with his beat.
The ghost misses you with his beat.
The ghost starts casting a spell.

< 673h/734H 572p/572P 260v/260V >
< T: Epuh TC: few scratches E: ghost EC: nasty wounds P: std > You start chanting...

-------------

< 575h/734H 572p/572P 260v/260V >
< T: Epuh TC: small wounds E: ghost EC: nasty wounds P: std > You start chanting...

< 575h/734H 572p/572P 260v/260V >
< T: Epuh TC: small wounds E: ghost EC: nasty wounds P: std > 
The ghost completes his spell...
The ghost utters the words, 'zabrahpdjatz'.
the ghost causes an EARTHQUAKE!
You stagger and almost break your leg!

< 551h/734H 572p/572P 260v/260V >
< T: Epuh TC: small wounds E: ghost EC: nasty wounds P: std > 
Casting: Phantasmal Killer **

< 551h/734H 572p/572P 260v/260V >
< T: Epuh TC: small wounds E: ghost EC: nasty wounds P: std > 
Casting: Phantasmal Killer *

< 551h/734H 572p/572P 260v/260V >
< T: Epuh TC: small wounds E: ghost EC: nasty wounds P: std > 
You complete your spell...
Your spell is partially absorbed by the ghost.
The ghost cries out in agony as your phantasmal killer attacks his mind!
You miss the ghost with your bludgeon.
The ghost misses you with his beat.
The ghost misses you with his beat.
The ghost starts casting an offensive spell.

< 551h/734H 572p/572P 260v/260V >
< T: Epuh TC: small wounds E: ghost EC: nasty wounds P: std > 
With a faint hum, the light from the surrounding area is absorbed into your
staff. Within seconds, the light condenses into a small, semi-solid and very
colorful orb which hovers above the staff, gyrating slowly.
You hurl a small orb of wildly shifting colors at the ghost!
Your spell is partially absorbed by the ghost.

< 551h/734H 572p/572P 260v/260V >
< T: Epuh TC: small wounds E: ghost EC: nasty wounds P: std > You start chanting...

< 551h/734H 572p/572P 260v/260V >
< T: Epuh TC: small wounds E: ghost EC: nasty wounds P: std > 
Casting: Nightmare ***

< 551h/734H 572p/572P 260v/260V >
< T: Epuh TC: small wounds E: ghost EC: nasty wounds P: std > 
Casting: Nightmare **

< 552h/734H 572p/572P 260v/260V >
< T: Epuh TC: small wounds E: ghost EC: nasty wounds P: std > 
Casting: Nightmare *

< 552h/734H 572p/572P 260v/260V >
< T: Epuh TC: small wounds E: ghost EC: nasty wounds P: std > 
You complete your spell...
Your spell is partially absorbed by the ghost.
You bring the ghost's worst nightmares into existence to attack him viciously!
The ghost is stunned by the horrific visions!

< 552h/734H 572p/572P 260v/260V >
< T: Epuh TC: small wounds E: ghost EC: pretty hurt P: std > 
You miss the ghost with your bludgeon.

< 552h/734H 572p/572P 260v/260V >
< T: Epuh TC: small wounds E: ghost EC: pretty hurt P: std > 
The ghost completes his spell...
The ghost utters the words, 'qlqraiz'.
The ghost's cyclone hammers at your body!
OUCH!  That really did HURT!

< 410h/734H 572p/572P 260v/260V >
< T: Epuh TC: few wounds E: ghost EC: pretty hurt P: std

**Comment by Uagr** [comment]
nother exampler lower level mob
< 767h/767H 592p/592P 313v/313V >
< P: std > You start chanting...

< 767h/767H 592p/592P 313v/313V >
< P: std > 
A mindless zombie misses a dark shade with his beat.
A mindless zombie misses a dark shade with his beat.
The zombie lord misses a dark shade with his slash.
The zombie lord misses a dark shade with his slash.
The zombie lord starts casting an offensive spell called 'chain lightning'.
A dark shade misses the zombie lord with its drain.
A dark shade misses the zombie lord with its drain.

< 767h/767H 592p/592P 313v/313V >
< P: std > 
A mindless zombie says 'I must assist my friend!'
A mindless zombie misses a dark shade with his beat.

< 767h/767H 592p/592P 313v/313V >
< P: std > 
Casting: Nightmare **

< 767h/767H 592p/592P 313v/313V >
< P: std > 
A mindless zombie says 'I must assist my friend!'
A mindless zombie misses a dark shade with his beat.

< 767h/767H 592p/592P 313v/313V >
< P: std > 
Casting: Nightmare *

< 767h/767H 592p/592P 313v/313V >
< P: std > 
You complete your spell...
Your spell is partially absorbed by the zombie lord.
You bring the zombie lord's worst nightmares into existence to attack him viciously!
The zombie lord is stunned by the horrific visions!
A mindless zombie is stunned by the horrific visions!

< 767h/767H 592p/592P 313v/313V >
< P: std > 
A mindless zombie misses a dark shade with his beat.
A mindless zombie misses a dark shade with his beat.
A mindless zombie misses a dark shade with his beat.
A mindless zombie misses a dark shade with his beat.
A mindless zombie misses a dark shade with his beat.
A mindless zombie misses a dark shade with his beat.
A dark shade barely wounds the zombie lord with its weak drain.
A dark shade shivers from the cold, as it hits the zombie lord.
A dark shade misses the zombie lord with its drain.

< 767h/767H 592p/592P 313v/313V >
< P: std > You start chanting...

< 767h/767H 592p/592P 313v/313V >
< P: std > 
Casting: Phantasmal Killer **

< 767h/767H 592p/592P 313v/313V >
< P: std > 
A soothing wind blows through the area.
 A mindless zombie misses a dark shade with his beat.
A mindless zombie misses a dark shade with his beat.
A mindless zombie misses a dark shade with his beat.
A mindless zombie misses a dark shade with his beat.
A mindless zombie misses a dark shade with his beat.
A mindless zombie misses a dark shade with his beat.
A dark shade barely wounds the zombie lord with its weak drain.
A dark shade shivers from the cold, as it hits the zombie lord.
A dark shade barely wounds the zombie lord with its weak drain.
A dark shade shivers from the cold, as it hits the zombie lord.

< 767h/767H 592p/592P 313v/313V >
< P: std > 
Casting: Phantasmal Killer *

< 767h/767H 592p/592P 313v/313V >
< P: std > 
The zombie lord completes his spell...
The zombie lord utters the words, 'chain lightning'.
A writhing bolt of lightning leaves the zombie lord's hands...
And blasts into a dark shade!
A dark shade slumps to the ground.
a dark shade is dead! R.I.P.
A dark shade slumps to the ground.
Your blood freezes as you hear the rattling death cry of a dark shade.
The dark shade melts back into the shadows...
A dark shade stops following you.
Then leaps and blasts into YOU!
The spell cast by the zombie lord is partially absorbed!
OUCH!  That really did HURT!
And finally fizzles out.

**Comment by Uagr** [comment]
Must apply to elementals too
< 564h/747H 592p/592P 291v/260V >
< T: Epuh TC: small wounds E: elemental EC: nasty wounds P: std > 
You complete your spell...
Your spell is partially absorbed by a patrolling elemental.
You bring a patrolling elemental's worst nightmares into existence to attack it viciously!
A patrolling elemental is stunned by the horrific visions!

< 564h/747H 592p/592P 291v/260V >
< T: Epuh TC: small wounds E: elemental EC: pretty hurt P: std > You start chanting...

< 564h/747H 592p/592P 291v/260V >
< T: Epuh TC: small wounds E: elemental EC: pretty hurt P: std > 
The phantasmal mist melts back into the ground, and fades away.
TENDRIL DOWN

< 564h/747H 592p/592P 291v/260V >
< T: Epuh TC: small wounds E: elemental EC: pretty hurt P: std > 
Upon being struck, a mirror image of Epuh shatters into a million particles of light!
A patrolling elemental misses you with its smash.
A patrolling elemental starts casting an offensive spell.

**Comment by Uagr** [comment]
last one...
< P: std > 
You complete your spell...
Your spell is partially absorbed by a patrolling elemental.
You bring a patrolling elemental's worst nightmares into existence to attack it viciously!
A patrolling elemental is stunned by the horrific visions!

< 575h/732H 592p/592P 260v/260V >
< P: std > 
Upon being struck, a mirror image of Epuh shatters into a million particles of light!
A patrolling elemental misses you with its smash.
A patrolling elemental starts casting an offensive spell.

**Comment by Lilithelle** [comment]
Undead are supposed to be no stun, this is straight from D&D.  The same with wraithform mobs, air elementals, spirits, ghosts, etc.  They have no brain to stun, their intelligence is innate, it's like their mind has animated that body.
