### ISSUE TITLE
spellcast - bug or helpfile update?

### ISSUE THREAD

**Issue by Uagr** [torilmud/issues#762]
I mean it makes sense... so not sure if bug or just need to update help files.
>>
You complete your spell...
Your eyes tingle and things become much more apparent.
You have learned something new about spellcast divination!

< P: std > "TRUE SIGHT"
Spell.

Area of effect: <victim>
Aggressive:     No
Cumulative:     N/A
Duration:       Dependent on the proficiency of the caster
Class/Circle:   Illusionist 5th
Type of spell:  Illusion

This spell grants the victim a new and improved vision, wherein
they can detect magic, alignment, invisibility, and heat forms.

> "SPELLCAST DIVINATION"
General area of knowledge.

Class/Level:    Enchanter/Invoker/Necromancer/Elementalist 1st
                     Shaman/Cleric/Druid 1st
                                         Bard/Battlechanter/Hexblade 10th

Proficiency in this improves your ability to cast divination and
revelation spells (although you must be proficient in the spell as
well).

Divination spells
-----------------
clairvoyance, detect evil, detect good, detect invisibilty, detect
magic, dispel invisible, faerie fog, identify, locate object,
locate remains, sense life, wizard eye

**Comment by OghmaToril** [comment]
True Sight should be a divination spell.  I've fixed the helpfiles and they'll be moved in with a future code move.
