### ISSUE TITLE
identification scroll issue

### ISSUE THREAD

**Issue by i982** [torilmud/issues#764]
when you use and identification scroll whether the item is there or not it consumes the scroll...

You get a vellum scroll from a portable hole.

< 294h/294H 180v/180V P: std > 
Autosaving...

< 294h/294H 180v/180V P: std > 
recite scroll badge.skull
You don't see them here!
You don't see them here!

< 294h/294H 180v/180V P: std > 
i
You are carrying:
a portable hole (illuminating)

**Comment by Uagr** [comment]
I had a similar issue today with a potion, I was sitting, and quaffed potion, it said you have to stand to do that, but potion was still used, no effects given. Might be related?

**Comment by i982** [comment]
same for armor potions.. if sitting. uses potion. no effects given.

**Comment by shevarash** [comment]
This has been fixed.
