### ISSUE TITLE
Remove hunger message

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#765]
Since it doesn't actually do anything anymore, perhaps remove (comment out) the hungry/thirsty message?

Ilyaki 'Where can one buy food in Scardale?'
You 'I'm sure there's a baker/butcher/general store/etc there, 
however, technically you don't need food anymore'
You 'The 'You are hungry/you are thirsty' message will 
disappear after a few minutes, and there's no penalty for that 
anymore'

comment however:
Gurru 'maybe a toggle, i actually use that to time the tick...'

**Comment by i982** [comment]
was thinking this the other day. if leaving this in game.. can we please just ad your drinking container to the list where you can just drink from the bag its in? no different that the food situation. i dont mind eating drinking. it adds minor immersion.. but yeah.. if gonna leave in at least let us drink the same way we eat.. drink <drink container> <container>

**Comment by Inames** [comment]
I like the toggle option.

i982 - Just make a druid and cast goodberry a couple thousand times, it'll probably last you a year or 2 depending on how much you play. They cover food/drink when you eat them and can be eaten from bag, plus they heal you when you eat them. I made 1000 berries like 5 years ago and still have 100 left, but I don't really play these days.

**Comment by shevarash** [comment]
There is some room to improve the current eat/drink system, and especially how it is presented to new players. We'll use this ticket to track it.

**Comment by gonoph** [comment]
Just had a new player ask about this today...

**Comment by marthammor** [comment]
This _shouldn't_ be an issue anymore for newly created chars unless they eat/drink something. Once they do that though, they'll get messages as normal. Eatting/Drinking sill has benefits so its helpful to know when you're getting hungry or thirsty.
