### ISSUE TITLE
Feeble & Blind don't matter....

### ISSUE THREAD

**Issue by Uagr** [torilmud/issues#768]
**************Feeb & PWB still tracks & casts**********
< 699h/1024H 389p/389P 219v/219V >
< T: earth TC: few scratches E: elemental EC: few scratches > 
Your average bludgeon barely wounds a patrolling elemental.
A fire mephit misses a patrolling elemental with its burn.
A patrolling elemental wounds an elemental rock python harshly with its massive smash.
A patrolling elemental misses an elemental rock python with its smash.
A patrolling elemental starts casting a spell.
An elemental rock python barely wounds a patrolling elemental with its strong smash.
An elemental rock python's attack only grazes a patrolling elemental as it dodges aside!
An elemental rock python barely wounds a patrolling elemental with its average smash.

< 699h/1024H 389p/389P 219v/219V >
< T: earth TC: small wounds E: elemental EC: few scratches > You start chanting...

< 699h/1024H 389p/389P 219v/219V >
< T: earth TC: small wounds E: elemental EC: few scratches > 
Casting: Feeblemind ***

< 699h/1024H 389p/389P 219v/219V >
< T: earth TC: small wounds E: elemental EC: few scratches > 
Casting: Feeblemind **

< 699h/1024H 389p/389P 219v/219V >
< T: earth TC: small wounds E: elemental EC: few scratches > 
A fire mephit barely wounds a patrolling elemental with its average burn.
A patrolling elemental dodges an elemental rock python's attack.
An elemental rock python clambers to its feet.

< 699h/1024H 389p/389P 219v/219V >
< T: earth TC: small wounds E: elemental EC: few scratches > 
Casting: Feeblemind *

< 699h/1024H 389p/389P 219v/219V >
< T: earth TC: small wounds E: elemental EC: few scratches > You're busy spellcasting! 

< 699h/1024H 389p/389P 219v/219V >
< T: earth TC: small wounds E: elemental EC: few scratches > 
You complete your spell...
**A patrolling elemental looks really dumb.**

< 699h/1024H 389p/389P 219v/219V >
< T: earth TC: small wounds E: elemental EC: few scratches > Ok.
A patrolling elemental avoids being bashed by an elemental rock python, who loses its balance and falls.

< 699h/1024H 389p/389P 219v/219V >
< T: earth TC: small wounds E: elemental EC: few scratches > 
You miss a patrolling elemental with your bludgeon.
A fire mephit misses a patrolling elemental with its burn.
An elemental rock python misses a patrolling elemental with its smash.

< 699h/1024H 389p/389P 219v/219V >
< T: earth TC: small wounds E: elemental EC: few scratches > 
A patrolling elemental completes its spell...
**A patrolling elemental utters the words, 'qlqraiz'.**
The spell cast by a patrolling elemental is partially absorbed!
A patrolling elemental's cyclone hammers at your body!
OUCH!  That really did HURT!
A patrolling elemental's cyclone tears at an elemental rock python, whose swings contact only air!
A patrolling elemental's cyclone tears at a fire mephit, whose swings contact only air!

< 560h/1024H 389p/389P 219v/219V >
< T: earth TC: pretty hurt E: elemental EC: few scratches > Your average bludgeon barely wounds a patrolling elemental.
A fire mephit barely wounds a patrolling elemental with its average burn.
An elemental rock python partially blocks a patrolling elemental's attack with its shield!
A patrolling elemental barely wounds an elemental rock python with its weak smash.
An elemental rock python partially blocks a patrolling elemental's attack with its shield!
A patrolling elemental barely wounds an elemental rock python with its weak smash.
A patrolling elemental switches targets..
An elemental rock python barely wounds a patrolling elemental with its strong smash.
An elemental rock python barely wounds a patrolling elemental with its strong smash.
You stare at the sky.

< 561h/1024H 389p/389P 219v/219V >
< T: Ssossassas TC: few wounds E: elemental EC: few scratches > Ok.
An elemental rock python is busy, but will execute your order as soon as possible.

< 561h/1024H 389p/389P 219v/219V >
< T: Ssossassas TC: few wounds E: elemental EC: few scratches > 
A patrolling elemental barely wounds you with its weak smash.
A patrolling elemental wounds you harshly with its massive smash.
OUCH!  That really did HURT!
PANIC!  You couldn't escape!
A fire mephit misses a patrolling elemental with its burn.
An elemental rock python's attack only grazes a patrolling elemental as it dodges aside!
An elemental rock python barely wounds a patrolling elemental with its average smash.
An elemental rock python barely wounds a patrolling elemental with its average smash.

< 484h/1024H 389p/389P 219v/219V >
< T: Ssossassas TC: nasty wounds E: elemental EC: few scratches > Drawbridge Before the Citadel
Exits: -N -S
A plaque is set in the wall of the Citadel next to the door. (glowing)
You flee southward!

< 484h/1024H 389p/389P 218v/219V >
< > The Foyer of the Citadel
Exits: -N -E# -S -W#
An elemental rock python is lying here, fighting a patrolling elemental.
A fire mephit stands, inches above the surface here, fighting a patrolling elemental.
A patrolling earth elemental looks at you with unfriendly eyes.

< 484h/1024H 389p/389P 218v/219V >
< > 
An elemental rock python clambers to its feet.
A fire mephit barely wounds a patrolling elemental with its average burn.
An elemental rock python barely wounds a patrolling elemental with its strong smash.

< 484h/1024H 389p/389P 218v/219V >
< > You assist an elemental rock python heroically.
Your average bludgeon barely wounds a patrolling elemental.

< 484h/1024H 389p/389P 219v/219V >
< T: mephit TC: nasty wounds E: elemental EC: few scratches > 
Your average bludgeon barely wounds a patrolling elemental.
A patrolling elemental misses a fire mephit with its smash.
A fire mephit staggers from a patrolling elemental's powerful smash!
A fire mephit barely wounds a patrolling elemental with its average burn.
An elemental rock python's attack only grazes a patrolling elemental as it dodges aside!
An elemental rock python barely wounds a patrolling elemental with its average smash.
An elemental rock python barely wounds a patrolling elemental with its strong smash.

< 484h/1024H 389p/389P 219v/219V >
< T: mephit TC: nasty wounds E: elemental EC: few scratches > You start chanting...

< 484h/1024H 389p/389P 219v/219V >
< T: mephit TC: nasty wounds E: elemental EC: few scratches > 
Casting: Lava Burst ***
A fire mephit staggers from a patrolling elemental's strong smash!
A fire mephit staggers from a patrolling elemental's average smash!
A fire mephit barely wounds a patrolling elemental with its average burn.
An elemental rock python's attack only grazes a patrolling elemental as it dodges aside!
An elemental rock python barely wounds a patrolling elemental with its average smash.
An elemental rock python barely wounds a patrolling elemental with its strong smash.

< 484h/1024H 389p/389P 219v/219V >
< T: mephit TC: pretty hurt E: elemental EC: few scratches > 
Autosaving...

< 484h/1024H 389p/389P 219v/219V >
< T: mephit TC: pretty hurt E: elemental EC: few scratches > You're busy spellcasting! 

< 484h/1024H 389p/389P 219v/219V >
< T: mephit TC: pretty hurt E: elemental EC: few scratches > 
Casting: Lava Burst **

< 484h/1024H 389p/389P 219v/219V >
< T: mephit TC: pretty hurt E: elemental EC: few scratches > 
Casting: Lava Burst *

< 484h/1024H 389p/389P 219v/219V >
< T: mephit TC: pretty hurt E: elemental EC: few scratches > 
You complete your spell...
The area explodes in a a massive burst of red-hot lava!
Your spell is partially absorbed by a patrolling elemental.
A patrolling elemental blackens and burns as your burst of lava coats its body.

< 484h/1024H 389p/389P 219v/219V >
< T: mephit TC: pretty hurt E: elemental EC: few scratches > 
A patrolling elemental dodges your futile attack.
A patrolling elemental enshrouds a fire mephit in a mist of blood with its strong smash!
A fire mephit is nearly slain by the force of a patrolling elemental's strong smash!
A fire mephit barely wounds a patrolling elemental with its average burn.
An elemental rock python barely wounds a patrolling elemental with its average smash.

< 485h/1024H 389p/389P 219v/219V >
< T: mephit TC: awful E: elemental EC: few scratches > You start chanting...

< 485h/1024H 389p/389P 219v/219V >
< T: mephit TC: awful E: elemental EC: few scratches > 
You complete your spell...
They are too powerful to blind this way

< 485h/1024H 389p/389P 219v/219V >
< T: mephit TC: awful E: elemental EC: few scratches > 
Your average bludgeon barely wounds a patrolling elemental.
A patrolling elemental hits a fire mephit in the throat, it chokes, gasps, and dies.
a fire mephit is dead! R.I.P.
Your blood freezes as you hear the rattling death cry of a fire mephit.
A fire mephit blinks out of existence.
A fire mephit stops following you.
mephit fire kin has quit the game, consent lost.
An elemental rock python barely wounds a patrolling elemental with its massive smash.
An elemental rock python barely wounds a patrolling elemental with its strong smash.
An elemental rock python sends a patrolling elemental sprawling with a powerful bash.

< 485h/1024H 389p/389P 219v/219V >
< T: earth TC: nasty wounds E: elemental EC: small wounds > Ok.
An elemental rock python is busy, but will execute your order as soon as possible.

< 485h/1024H 389p/389P 219v/219V >
< T: earth TC: nasty wounds E: elemental EC: small wounds > You start chanting...

< 485h/1024H 389p/389P 219v/219V >
< T: earth TC: nasty wounds E: elemental EC: small wounds > 
You complete your spell...
**A patrolling elemental won't be seeing much in the near future..**

< 485h/1024H 389p/389P 219v/219V >
< T: earth TC: nasty wounds E: elemental EC: small wounds > 
A patrolling elemental barely wounds an elemental rock python with its weak smash.
An elemental rock python is nearly slain by the force of a patrolling elemental's massive smash!
Your average bludgeon barely wounds a patrolling elemental.
An elemental rock python misses a patrolling elemental with its smash.
An elemental rock python barely wounds a patrolling elemental with its strong smash.

< 485h/1024H 389p/389P 219v/219V >
< T: earth TC: awful E: elemental EC: small wounds > You group-say 'A patrolling elemental perm blind'

< 485h/1024H 389p/389P 219v/219V >
< T: earth TC: awful E: elemental EC: small wounds > 
The flames engulfing a patrolling elemental subside.

< 485h/1024H 389p/389P 219v/219V >
< T: earth TC: awful E: elemental EC: small wounds > 
A patrolling elemental misses an elemental rock python with its smash.
A patrolling elemental hits an elemental rock python in the throat, it chokes, gasps, and dies.
an elemental rock python is dead! R.I.P.
Your blood freezes as you hear the rattling death cry of an elemental rock python.
With a loud crash, the elemental dives into the ground. Only small stones remain where it once stood.
An elemental rock python stops following you.
Your average bludgeon barely wounds a patrolling elemental.

< 485h/1024H 389p/389P 219v/219V >
< T: Ssossassas TC: nasty wounds E: elemental EC: small wounds > You start chanting...

< 485h/1024H 389p/389P 219v/219V >
< T: Ssossassas TC: nasty wounds E: elemental EC: small wounds > 
Casting: Lava Burst ***

< 485h/1024H 389p/389P 219v/219V >
< T: Ssossassas TC: nasty wounds E: elemental EC: small wounds > 
Casting: Lava Burst **

< 485h/1024H 389p/389P 219v/219V >
< T: Ssossassas TC: nasty wounds E: elemental EC: small wounds > 
Casting: Lava Burst *

< 485h/1024H 389p/389P 219v/219V >
< T: Ssossassas TC: nasty wounds E: elemental EC: small wounds > 
A patrolling elemental barely wounds you with its weak smash.
You abort your spell before it's done!
A Short Hallway
Exits: -N -S -W
You flee northward!

< 484h/1024H 389p/389P 218v/219V >
< > The Foyer of the Citadel
Exits: -N -E# -S -W#
A small wooden shield is lying on the ground.
A patrolling elemental sits here.

< 484h/1024H 389p/389P 218v/219V >
< > Drawbridge Before the Citadel
Exits: -N -S
A plaque is set in the wall of the Citadel next to the door. (glowing)

< 484h/1024H 389p/389P 217v/219V >
< > The Foyer of the Citadel
Exits: -N -E# -S -W#
A small wooden shield is lying on the ground.
A patrolling elemental sits here.

< 485h/1024H 389p/389P 217v/219V >
< > You sit down and relax.

< 485h/1024H 389p/389P 217v/219V >
< > You have memorized the following spells:
(10th circle)  2 - Elemental Ward
( 9th circle)  4 - Earthblood
               1 - Elemental Earth Embodiment
( 8th circle)  2 - Power Word Blind
               1 - Elemental Air Embodiment
( 7th circle)  1 - Elemental Water Embodiment
               1 - Dimension Door
               1 - Haste
               3 - Ice Tongue
( 6th circle)  4 - Stoneskin
               1 - Feeblemind
( 5th circle)  2 - Coldshield
               2 - Teleport
               3 - Conjure Elemental
               1 - Infravision
( 4th circle)  4 - Sleep
               4 - Ray of Enfeeblement
               1 - Levitate
( 3rd circle)  6 - Dispel Magic
               2 - Locate Object
               1 - Summon Elemental Kin
You continue your study.

[RETURN for more, q to quit]< 486h/1024H 389p/389P 218v/219V >
< > 
A patrolling elemental clambers to its feet.
**A patrolling elemental starts casting a spell.**

< 487h/1024H 389p/389P 219v/219V >
< > 
You have finished memorizing Feeblemind.

< 488h/1024H 389p/389P 219v/219V >
< > You say 'wtf'

< 489h/1024H 389p/389P 219v/219V >
< > 
You have finished memorizing Feeblemind.

< 490h/1024H 389p/389P 219v/219V >
< > 
A patrolling elemental completes its spell...
A patrolling elemental utters the words, 'judicandus nore'.

< 493h/1024H 389p/389P 219v/219V >
< > 
A patrolling elemental recognizes you, and charges to attack you!
You abandon your studies.
A patrolling elemental barely wounds you with its weak smash.
You scramble madly to your feet!

< 494h/1024H 389p/389P 219v/219V >
< T: Ssossassas TC: nasty wounds E: elemental EC: small wounds > Saving...

< 494h/1024H 389p/389P 219v/219V >
< T: Ssossassas TC: nasty wounds E: elemental EC: small wounds > Your average bludgeon barely wounds a patrolling elemental.
A patrolling elemental barely wounds you with its weak smash.
Drawbridge Before the Citadel
Exits: -N -S
A plaque is set in the wall of the Citadel next to the door. (glowing)
You flee southward!
You are already standing.

< 494h/1024H 389p/389P 218v/219V >
< > A Small Clearing in the Shadow Grove
Exits: -N -E -W
A ghast appears out of the mist, bringing a terrible stench with it.
You flee southward!

< 494h/1024H 389p/389P 217v/219V >
< > Drawbridge Before the Citadel
Exits: -N -S
A plaque is set in the wall of the Citadel next to the door. (glowing)

< 494h/1024H 389p/389P 217v/219V >
< > 
**A patrolling elemental lumbers in from the north.**

< 494h/1024H 389p/389P 219v/219V >
< > 
**A patrolling elemental barely wounds you with its weak smash.**
The Foyer of the Citadel
Exits: -N -E# -S -W#
A small wooden shield is lying on the ground.
You flee northward!

< 493h/1024H 389p/389P 218v/219V >
< > You start chanting...

< 493h/1024H 389p/389P 219v/219V >
< > 
A patrolling elemental lumbers in from the south.

< 493h/1024H 389p/389P 219v/219V >
< > 
Casting: Dispel Magic ***
A patrolling elemental barely wounds you with its weak smash.
You abort your spell before it's done!
A Short Hallway
Exits: -N -S -W
You flee northward!

< 492h/1024H 389p/389P 218v/219V >
< > 
A patrolling elemental lumbers in from the south.

< 493h/1024H 389p/389P 219v/219V >
< > 
A patrolling elemental barely wounds you with its weak smash.
A Small Resting Room
Exits: -E
You flee westward!

**Comment by Lilithelle** [comment]
Actually feeblemind never did stop casting, it's more like it makes it act as though its cast all its spells from its slots.  It does get them back with time, but slowly.  The higher level the mob the more than can pull off while feebed, but each cast depletes it again.  It does stop it from spamming full heal on itself.  The blind did matter, but it cured the blindness. -> A patrolling elemental utters the words, 'judicandus nore'.

**Comment by shevarash** [comment]
^ LIlithelle is correct here.
