### ISSUE TITLE
Powers info is incorrect for efe when adding spellfocus ele

### ISSUE THREAD

**Issue by torkur** [torilmud/issues#77]
It seems to be deleting hitpoints on efe when I wear spellfocus items.  The actual casts seem to gain 3 hitpoints per sf point, so this looks like just a documentation item but please confirm.

< 750h/630H 526p/526P 160v/160V >
< > powers info efe

Name             : Elemental Fire Embodiment
Alias            : efe                      
Type             : Spell                    
Source           : Arcane                   
Prepare          : Study                    
Target           : Character in room
Recharge         : 15 seconds 
Activation Time  : 14 seconds 
Related Skill    : spellcast elemental
Conflicts        : Elemental Earth Embodiment, Elemental Air Embodiment, Elemental Water Embodiment, Elemental Water Embodiment
Restrictions     : Autofire, Garrote, Standing, Can Speak, Maintain, NPC
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Target Effect    : Add template Giant Size for 10 minutes             
Target Effect    : Modify hitpoints by 385 for 10 minutes  
Target Effect    : Heal for 385 hit points                            
Target Effect    : Modify armor by -65 for 10 minutes  
Target Effect    : Add haste, partial immaterial, fly, fireshield, elemental fire for 10 minutes  
Target Effect    : Modify resistance fire by 25 for 10 minutes  
Self Effect      : Add elemental embodiment maintain for 10 minutes  

< 744h/630H 526p/526P 160v/160V >
< > 

< 744h/630H 526p/526P 160v/160V >
< > wear eyepatch
You wear a topaz dragonscale eyepatch over your eyes.
save

< 736h/630H 526p/526P 160v/160V >
< > Saving...

< 735h/645H 526p/526P 160v/160V >
< > powers info efe

Name             : Elemental Fire Embodiment
Alias            : efe                      
Type             : Spell                    
Source           : Arcane                   
Prepare          : Study                    
Target           : Character in room
Recharge         : 15 seconds 
Activation Time  : 14 seconds 
Related Skill    : spellcast elemental
Conflicts        : Elemental Earth Embodiment, Elemental Air Embodiment, Elemental Water Embodiment, Elemental Water Embodiment
Restrictions     : Autofire, Garrote, Standing, Can Speak, Maintain, NPC
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Target Effect    : Add template Giant Size for 10 minutes             
Target Effect    : Modify hitpoints by 364 for 10 minutes  
Target Effect    : Heal for 364 hit points                            
Target Effect    : Modify armor by -65 for 10 minutes  
Target Effect    : Add haste, partial immaterial, fly, fireshield, elemental fire for 10 minutes  
Target Effect    : Modify resistance fire by 25 for 10 minutes  
Self Effect      : Add elemental embodiment maintain for 10 minutes  

< 734h/645H 526p/526P 160v/160V >
< >

**Comment by torkur** [comment]
I was testing this further with some people on the mud.  Embody seems to have a variable in the cast, which is why I'm seeing various hitpoint amounts, BUT now it also doesn't seem to vary with spellfocus ele when we tested further.  This seems weird that you don't gain a benefit on the spell with spellfocus.  Given stability boots and ChP girdle I'd personally like to see elementalist embodys get some spellfocus love so they're clearly better than item procs, but I'm not sure what the immortal plan is for it.  Please take a look.

**Comment by dnavarro** [comment]
That seems reasonable. You are welcome to open a new Issue ticket for that Enhancement request
