### ISSUE TITLE
Songs - update command Request

### ISSUE THREAD

**Issue by Uagr** [torilmud/issues#770]
"songs" currently shows all songs,
Add optional argument for instrument/type of song
songs <option> 

used with instrument as argument
>songs flute
Healing Songs (99):
song of renewal                         (     flute)
song of recovery                        (     flute)
Magical Songs (99):
song of sorcery                         (     flute)

Used with type of songs as argument
>songs healing
Healing Songs (99):
song of regeneration                    (      lyre)
song of healing                         (      lyre)
song of renewal                         (     flute)
song of recovery                        (     flute)

**Comment by shevarash** [comment]
This will be addressed in the upcoming Bard class overhaul.
