### ISSUE TITLE
snow-white boots of speed divine grace and divine offer

### ISSUE THREAD

**Issue by mrizzalazzrazzi** [torilmud/issues#773]
I thought in patch notes 6/19/2020 stated, "snow white boots of speed: Added two new powers: divine grace and divine offering. One gives 3 dam, and the other gives -6 save vs. spell. The two powers can not be used at the same time. This allows the boots to function as either 20hp, +2 hit, +2 dam or 20hp, +2 hit, -6 save vs. spell."

But when i check the powers info it says

Name             : Divine Grace [dgrace]
Type             : Melee                    
Target           : Self
Recharge         : 3 minutes 
Restrictions     : Standing

Effects:
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Target Effect    : Remove power Divine Offering                       
Self Effect      : Modify hitroll by 2 for 3 minutes   

Name             : Divine Offering [doffer]
Type             : Melee                    
Target           : Self
Recharge         : 3 minutes 
Restrictions     : Standing

Effects:
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Target Effect    : Remove power Divine Grace                          
Self Effect      : Modify hitroll by 2 for 3 minutes                  
Self Effect      : Modify damroll by 3 for 3 minutes                  
Self Effect      : Modify save spell by 6 for 3 minutes      

Is it me or this power is given wrongly?

**Comment by saerian** [comment]
> Name : Divine Grace [dgrace]
> Type : Melee
> Target : Self
> Recharge : 3 minutes
> Restrictions : Standing
> 
> Effects:
> -=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
> Target Effect : Remove power Divine Offering
> Self Effect : Modify hitroll by 2 for 3 minutes

This makes the boots 20 hp, 2 hit, -6 sv spe.

> Name : Divine Offering [doffer]
> Type : Melee
> Target : Self
> Recharge : 3 minutes
> Restrictions : Standing
> 
> Effects:
> -=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
> Target Effect : Remove power Divine Grace
> Self Effect : Modify hitroll by 2 for 3 minutes
> Self Effect : Modify damroll by 3 for 3 minutes
> Self Effect : Modify save spell by 6 for 3 minutes

This makes the boots 20 hps, 2 hit, 3 dam. The self effect is +6 sv spe, to nullify the inherent -6 sv spe on the boots.

**Comment by Lilithelle** [comment]
I was asked to make the boots 20hp 2hit with a power to give it +3dam, and a power to give it -6ss (not usable at the same time).  However, it occurred to me that players could activate the power and remove the boots and wear something else to gain the benefits.  So I kept the boots 20hp -6 spell save, one power gives +2 hit, the other gives +3 dam but +6 spell save; same end result, less twinkability.  It works as intended.

**Comment by mrizzalazzrazzi** [comment]
Okay i get it. It's not direct but looking it at different way. Yeah, I got it. Closing this ticket.
