### ISSUE TITLE
Level 6 Magic Missile Scroll Casting as though I were Level 15+

### ISSUE THREAD

**Issue by Lilithelle** [torilmud/issues#777]
You recite an intricate divination scroll which turns to dust in your hands.
You feel informed:
Name 'a minute magical scroll'
Keyword 'minute magical scroll magicmissile', Item type: SCROLL
Item can be worn on:  NOBITS
Item will give you following abilities:  NOBITS
Item is: NOBITSNOBITS
Weight: 0, Value: 5000
Level 6 spells of:
magic missile

< 892h/892H 170v/170V > recite scroll device
You recite a minute magical scroll which turns to dust in your hands.
Your spell is partially absorbed by A large metal device.
You watch with self-pride as the magic missile hits A large metal device.
Your spell is partially absorbed by A large metal device.
You watch with self-pride as the magic missile hits A large metal device.
Your spell is partially absorbed by A large metal device.
You watch with self-pride as the magic missile hits A large metal device.
Your spell is partially absorbed by A large metal device.
You watch with self-pride as the magic missile hits A large metal device.
Your spell is partially absorbed by A large metal device.
You watch with self-pride as the magic missile hits A large metal device.

A level 6 magic missile should only produce 2 missiles not 5.

**Comment by OghmaToril** [comment]
This was resolved in the last patch.
