### ISSUE TITLE
Request/Recommendation - Bards/Bchanters

### ISSUE THREAD

**Issue by Uagr** [torilmud/issues#781]
1) Cut verse time in half
2) cut change song duration in half
3) Fix res song :)

7-10 seconds between verses & between changing songs, is huge, a lot of fights don't last that long. Bard effect is only on verse round, not between rounds (can prove by singing agro and mobs walking in/out).

Make Bards/Bchanters great again MBGA (Illusionists too)

Thanks,

**Comment by shevarash** [comment]
Thank you for the feedback. This will be reviewed again during an upcoming Bard class overhaul.
