### ISSUE TITLE
Feature request - update to world command

### ISSUE THREAD

**Issue by Uagr** [torilmud/issues#783]
Simple enough, add maker to world to show who made it.

**Currently**
 Syntax: world < stats, zones >
This server compiled at 21:21:03 Jul 20 2020.
You are currently in: Bahamut's Palace

**Suggested**:
 Syntax: world < stats, zones >
This server compiled at 21:21:03 Jul 20 2020.
You are currently in: Bahamut's Palace - Maker: Verenestra

**Comment by marthammor** [comment]
Why? What purpose would this serve?

**Comment by Uagr** [comment]
Why do anything? game enhancement

**Comment by marthammor** [comment]
What enhancement would it provide? I'm just failing to see why the zone writer is needed with this specific command when the credits file lists all zones and their maker. The zone name is useful, the maker's name.. not so much.

**Comment by Uagr** [comment]
Saves time for the player instead of cross referencing different files. not sure whats hard about this. it should be easily implementation. There are soo many things that need done, and simple things like this are what we argue about... love it.

**Comment by marthammor** [comment]
Unfortunately, its not an easy thing to implement. The maker information isn't stored anywhere except for the text file that is the credits. The zone name information is pulled from the zone file, which is easy to grab and display. You're right though, there are other things to be done. This isn't one of them, however. Thank you for your suggestion.
