### ISSUE TITLE
Bashed casting?

### ISSUE THREAD

**Issue by Uagr** [torilmud/issues#786]
Corpse of an Ashstone noble is lying here.
A holyman dressed in black robes stands here.
An Ashstone noble stands here flitting about.

< 970h/938H 179v/180V >
< P: std > You slam your shield into an Ashstone noble with tremendous force, **knocking him to the ground!**

< 970h/938H 180v/180V >
< T: Uagr TC: excellent E: noble EC: few scratches P: std > 
Your awesome slash barely wounds an Ashstone noble.
You miss an Ashstone noble with your slash.
An Ashstone noble misses you with his hit.
An Ashstone noble misses you with his hit.

< 970h/938H 180v/180V >
< T: Uagr TC: excellent E: noble EC: few scratches P: std > You are using:
<worn as a badge>    a badge of writhing pink flames
<worn on head>       the iron crown of the frost giant warlords
<worn on eyes>       a monocle of the dwarven gatecrasher
<worn in ear>        an earring of the waters
<worn in ear>        an obsidian earring shaped like a skull
<worn on face>       a sandstorm mask
<worn around neck>   an amulet of combat
<worn around neck>   a molten lava pendant
<worn on body>       some enchanted quickling armor
<worn about body>    a heavy cloak of dragonskin
<worn as quiver>     a wooden quiver
<worn about waist>   a mithril clasped belt
<worn on arms>       vermillion chainmail sleeves
<held as shield>     a crested shield of the dragonslayer
<worn around wrist>  a mithril mesh bracer
<worn around wrist>  a mithril mesh bracer
<worn on hands>      a pair of silverish githyanki gauntlets
<worn on finger>     a flaming ring of the efreeti
<worn on finger>     a studded diamond ring
<primary weapon>     an ebony bladed longsword
<worn on legs>       a pair of djinn battle greaves
<worn on feet>       some boots of tattered quickling flesh

< 970h/938H 180v/180V >
< T: Uagr TC: excellent E: noble EC: few scratches P: std > 
Your mighty slash barely wounds an Ashstone noble.
Your mighty slash barely wounds an Ashstone noble.
An Ashstone noble misses you with his hit.
An Ashstone noble misses you with his hit.

< 969h/938H 180v/180V >
< T: Uagr TC: excellent E: noble EC: few scratches P: std > 
**An Ashstone holyman completes his spell...
An Ashstone holyman utters the words, 'gjwwai'.
You feel a wrenching sensation.**

< 969h/938H 180v/180V >
< T: Uagr TC: excellent E: noble EC: few scratches P: std > 
Your awesome slash barely wounds an Ashstone noble.
You miss an Ashstone noble with your slash.
An Ashstone noble misses you with his hit.
An Ashstone noble misses you with his hit.

< 968h/938H 180v/180V >
< T: Uagr TC: excellent E: noble EC: few scratches P: std > An Airy Building of Light Stonework
Exits: - West 
Corpse of an Ashstone noble is lying here.
A holyman dressed in black robes stands here.
**An Ashstone noble is lying here, fighting YOU!**

**Comment by gruumsh** [comment]
Those are clearly two different mobs and the one casting is clearly standing.

mobs
> A holyman dressed in black robes stands here. (mob 1 standing)
> An Ashstone noble stands here flitting about. (mob 2 in default position, likely standing)

bashing mob 2
> < P: std > You slam your shield into an Ashstone noble with tremendous force, **knocking him to the ground!**

mob 1 casting spells
> **An Ashstone holyman completes his spell... An Ashstone holyman utters the words, 'gjwwai'. You feel a wrenching sensation.**

Mob 1 is standing mob 2 is bashed. 
> < T: Uagr TC: excellent E: noble EC: few scratches P: std > An Airy Building of Light Stonework
> Exits: - West
> Corpse of an Ashstone noble is lying here.
> A holyman dressed in black robes stands here.
> **An Ashstone noble is lying here, fighting YOU!**
