### ISSUE TITLE
Lockpick fail?

### ISSUE THREAD

**Issue by Uagr** [torilmud/issues#788]
happened in Hysssssk, immediately after picking it, door was still locked... i picked it again and it was fine...werirdnessssssss
--------
< 419h/419H 89p/89P 166v/166V >
< > The lock quickly yields to your skills and pops open.
Damn!  But you broke your some lockpicks!

< 419h/419H 89p/89P 166v/166V >
< > It seems to be locked.

**Comment by gruumsh** [comment]
Hard to tell whats going on here without commands echoing, without knowing what room the door is in and what you're wearing that could have interfered. Closing this for now.
