### ISSUE TITLE
doppelganger typos

### ISSUE THREAD

**Issue by torilmud-silvanus** [torilmud/issues#79]
Actual: "doppleganger" is a common typo. 
- [ ] help file: spell
- [ ] help skill_illus
- [ ] powers
- [ ] Run some greps to look for more instances

Expected: "doppelganger"

**Comment by dnavarro** [comment]
oh god grep src and buckle down for a big editing project. and qa this when done, make sure you don't break everything

**Comment by dnavarro** [comment]
This has become increasingly challenging to resolve, due to spellbooks existing in pfiles...

**Comment by shevarash** [comment]
At this point, this will just be fixed in an Illusionist class overhaul...
