### ISSUE TITLE
Typo at 'The Training Circle'

### ISSUE THREAD

**Issue by Kihyno** [torilmud/issues#791]
Just after typing 'enter toril' from the noob room as a ranger:

< P: std > The Training Circle
   The trees and foliage have been grudgingly pushed back to form a wide
circle here.  This area is used by woodsmen and trackers to hone their
combat prowess, and even learn powerful spells granted by Mielikki,
their god.  Despite the often violent training which takes place here,
the place has a general shroud of serenity hanging over it, and seems
quite peaceful.  A small **cirlce** of bright lavender flowers grow in the
middle of the clearing, and a wide variety of other plants and herbs can
be found along the outskirts.  A few large boulders have been placed on
opposite ends of the clearing, upon which are painted majestic
landscapes of distant lands, and a portrait of a beautiful unicorn,
among others.
Exits: - North
The master ranger stands here solemnly.

**Comment by vitaladsr** [comment]
Begrudgingly

**Comment by OghmaToril** [comment]
Fixed and will be moved in a future code move.
