### ISSUE TITLE
Update cast command to help newbies

### ISSUE THREAD

**Issue by Dartan82** [torilmud/issues#792]
Had a newbie from Duris try to figure out how to cast beast sense and couldn't figure it out.

The vast majority of MUDs still use cast spells.  Can we have cast notify a player that the command is discontinued and to use power instead?  I thought it did this at one point.

**Comment by shevarash** [comment]
You can cast powers though?

```
> cast 'beast sense'

You start chanting...
You cast the spell 'Beast Sense'.
You become more aware of your surroundings as your senses heighten.
```

Maybe I already fixed this? If I'm missing something please remind me! Thanks!
