### ISSUE TITLE
invasion/pisssed guards/ignore change/disguise?

### ISSUE THREAD

**Issue by Uagr** [torilmud/issues#794]
So i "invaded" ghore, set off 1 set of alarms, sat at central ghore never hearing another alarm.
So i went to peak around...changed as a stinky drow, and well guess guards don't care...what am I missing? no I wasn't agro to any prior to below.
---------

**Your form shimmers and is disguised as drow.**
cas 'nondetect'
< 747h/747H 592p/592P 313v/313V >
< P: std > You are already affected by that spell!
rest
< 747h/747H 592p/592P 313v/313V >
< P: std > You sit down and relax.
mem
< 747h/747H 592p/592P 313v/313V >
< P: sit > You have memorized the following spells:
(10th circle)  2 - Nightmare
               2 - Phantasmal Tendrils
( 9th circle)  1 - Massmorph
               3 - Phantasmal Killer
               1 - Gate
( 8th circle)  2 - Mislead
               1 - Rainbow Pattern
               1 - Dimensional Fold
               1 - Mirror Image
( 7th circle)  2 - Shadow Flux
               3 - Phantasmal Blades
               1 - Camouflage
( 6th circle)  4 - Displacement
               1 - Summon Shade
               1 - Nondetection
               1 - Clairvoyance
( 5th circle)  2 - True Sight
               4 - Shadow Burst
               1 - Doppleganger
               1 - Dimension Door
( 4th circle)  1 - Teleport
You continue your study.

[RETURN for more, q to quit]< 747h/747H 592p/592P 313v/313V >
< P: sit > Saving...

< 747h/747H 592p/592P 313v/313V >
< P: sit > You have finished memorizing Change Self.
Your studies are complete.
The Center of Ghore
Exits: -N -E -W
The statue of two female trolls crumble here, larger than life.
A giant pool of swamp water overflows here.
A foul smelling troll guard belches in your face.
A foul smelling troll guard belches in your face.
A foul smelling troll guard belches in your face.
A foul smelling troll guard belches in your face.
A foul smelling troll guard belches in your face.
st
< 747h/747H 592p/592P 313v/313V >
< P: std > You are already standing.
scan
< 747h/747H 592p/592P 313v/313V >
< P: std > 
You scan north...
The Central Path of Ghore
Exits: -N -S
An ogre shaman from Faang watches you closely.

You scan east...
A Wide Sloping Trail
Exits: -E -S -W
A common troll with shaggy brown hair prowls around here.
A spotted lizard hides in the muck.

You scan west...
A Wide Sloping Trail
Exits: -E -W
n
< 747h/747H 592p/592P 313v/313V >
< P: std >                      

  |   |   |   |.!.|              
+ | + | + | + |   |        ------
   ,-, ,-, *-* .!.|       |,-,   
+ | + | + | + |   --------|   ---
  |   |   |   |.!.+       |.-.|  
-- --- --- ---|   --------|   |  
  |   |       |.@.|       |.-.|  
--- + ---------   ---------   |--
   ,-, ,-, ,-, .!. ,-, ,-, ,-,|  
---   -------------   --------- #
  |.-.|   |   #   |.-.|   |      
--|   | # | # ----|   |    ------
  |.-.+           |.-.|       |  
                        
The Central Path of Ghore
Exits: -N -S
An ogre shaman from Faang watches you closely.

< 747h/747H 592p/592P 312v/313V >
< P: std > 
A foul smelling troll guard prowls in from the south.
A foul smelling troll guard prowls in from the south.
A foul smelling troll guard prowls in from the south.
A foul smelling troll guard prowls in from the south.
A foul smelling troll guard prowls in from the south.

< 747h/747H 592p/592P 312v/313V >
< P: std > 
Upon being struck, a mirror image of a drow scout shatters into a million particles of light!
Upon being struck, a mirror image of a drow scout shatters into a million particles of light!
Upon being struck, a mirror image of a drow scout shatters into a million particles of light!
Upon being struck, a mirror image of a drow scout shatters into a million particles of light!
You dodge a bash from a foul smelling troll guard, who loses his balance and falls.
**Your disguise falls apart!**

< 747h/747H 592p/592P 313v/313V >
< T: Epuh TC: excellent E: troll EC: excellent P: std >                         

   ,-, ,-, *-* .!.|       |,-,   
+ | + | + | + |   --------|   ---
  |   |   |   |.!.+       |.-.|  
-- --- --- ---|   --------|   |  
  |   |       |.!.|       |.-.|  
--- + ---------   ---------   |--
   ,!, ,!, , , .@. ,!, ,!, ,!,|  
---   -------------   --------- #
  |.-.|   |   #   |.-.|   |      
--|   | # | # ----|   |    ------
  |.-.+           |.-.|       |  
---   ------------|   --------| #
   .-.|   |       |.-. .-. .-.|  
                        
The Center of Ghore
Exits: -N -E -W
The statue of two female trolls crumble here, larger than life.
A giant pool of swamp water overflows here.
You flee southward!
me big wuss, me Fleed southward

< 747h/747H 592p/592P 312v/313V >
< P: std > 
A foul smelling troll guard prowls in from the north.

< 747h/747H 592p/592P 313v/313V >
< P: std > 
A foul smelling troll guard prowls in from the north.

< 747h/747H 592p/592P 313v/313V >
< P: std > 
A foul smelling troll guard prowls in from the north.

< 747h/747H 592p/592P 313v/313V >
< P: std > 
A foul smelling troll guard prowls in from the north.

< 747h/747H 592p/592P 313v/313V >
< P: std > 
Your mental barrier blinks out of existence.

< 747h/747H 592p/592P 313v/313V >
< P: std > 
A foul smelling troll guard prowls in from the north.

< 747h/747H 592p/592P 313v/313V >
< P: std > This town, Ghore, has no system of justice.

**Comment by Uagr** [comment]
tested again, this time, going to smoke to 'change self'... came back... they just walked right past me.

**Comment by vitaladsr** [comment]
Remember swamp pool is a peace room. For testing

**Comment by vitaladsr** [comment]
> tested again, this time, going to smoke to 'change self'... came back... they just walked right past me.

What did you smoke to change self? Asking for a friend 😆

**Comment by vitaladsr** [comment]
> tested again, this time, going to smoke to 'change self'... came back... they just walked right past me.

Hey Jim,

It's been like this for ever. Once invasion alarm goes off you can't sneak/hide or camo/change self .. the guards see right thru it.

But if you enter sneak/hide/camo/etc the alarms won't ring so your safe.

Annam
