### ISSUE TITLE
PSP crystals - can use only one?

### ISSUE THREAD

**Issue by Uagr** [torilmud/issues#795]
PSP Crystal Status:

a massive egg of an astral dreadnaught    0/ 200
a massive egg of an astral dreadnaught    0/ 200
a translucent black crystal                      700/ 700

-----------
If I charge one (fill/part doesn't matter).. and I start to charge a second, the first one loses it's charge... surely this wasn't intended?

*I snipped eq/etc non relevant commands/output*
< P: sit > 
Current charge for [ a translucent black crystal ] - 264/700 psp's.

Current charge for [ a translucent black crystal ] - 272/700 psp's.

< 575h/575H 759p/759P 140v/140V >
< P: sit > 
Current charge for [ a translucent black crystal ] - 280/700 psp's.

< 575h/575H 759p/759P 140v/140V >
< P: sit > 
Current charge for [ a translucent black crystal ] - 288/700 psp's.

< 575h/575H 759p/759P 140v/140V >
< P: sit > 
Current charge for [ a translucent black crystal ] - 296/700 psp's.

< 575h/575H 759p/759P 140v/140V >
< P: sit > 
Current charge for [ a translucent black crystal ] - 304/700 psp's.

< 575h/575H 759p/759P 140v/140V >
< P: sit > 
Current charge for [ a translucent black crystal ] - 312/700 psp's.

< 575h/575H 759p/759P 140v/140V >
< P: sit > 
Current charge for [ a translucent black crystal ] - 320/700 psp's.

< 575h/575H 759p/759P 140v/140V >
< P: sit > 
Current charge for [ a translucent black crystal ] - 328/700 psp's.

< 575h/575H 759p/759P 140v/140V >
< P: sit > 
Current charge for [ a translucent black crystal ] - 336/700 psp's.

< 575h/575H 759p/759P 140v/140V >
< P: sit > 
Current charge for [ a translucent black crystal ] - 344/700 psp's.

< 575h/575H 759p/759P 140v/140V >
< P: sit > 
Current charge for [ a translucent black crystal ] - 352/700 psp's.

< 575h/575H 759p/759P 140v/140V >
< P: sit > 
Current charge for [ a translucent black crystal ] - 360/700 psp's.

< 575h/575H 759p/759P 140v/140V >
< P: sit > 
Current charge for [ a translucent black crystal ] - 368/700 psp's.

< 575h/575H 759p/759P 140v/140V >
< P: sit > 
Current charge for [ a translucent black crystal ] - 376/700 psp's.

< 575h/575H 759p/759P 140v/140V >
< P: sit > You stop meditating.
You stop charging your crystal.
You start charging a massive egg of an astral dreadnaught.

< 575h/575H 759p/759P 140v/140V >
< P: sit > Current charge for [ a massive egg of an astral dreadnaught ] - 4/200 psp's.
You start meditating...

< 575h/575H 759p/759P 140v/140V >
< P: sit > 
Havorr polishes the bar while waiting for the next order.

< 575h/575H 759p/759P 140v/140V >
< P: sit > 
Current charge for [ a massive egg of an astral dreadnaught ] - 12/200 psp's.

< 575h/575H 759p/759P 140v/140V >
< P: sit > 
Current charge for [ a massive egg of an astral dreadnaught ] - 20/200 psp's.

< 575h/575H 759p/759P 140v/140V >
< P: sit > 
Current charge for [ a massive egg of an astral dreadnaught ] - 28/200 psp's.

< 575h/575H 759p/759P 140v/140V >
< P: sit > 
Current charge for [ a massive egg of an astral dreadnaught ] - 36/200 psp's.

< 575h/575H 759p/759P 140v/140V >
< P: sit > 
Current charge for [ a massive egg of an astral dreadnaught ] - 44/200 psp's.

< 575h/575H 759p/759P 140v/140V >
< P: sit > 
Current charge for [ a massive egg of an astral dreadnaught ] - 52/200 psp's.

< 575h/575H 759p/759P 140v/140V >
< P: sit > 
Current charge for [ a massive egg of an astral dreadnaught ] - 60/200 psp's.

< 575h/575H 759p/759P 140v/140V >
< P: sit > 
Current charge for [ a massive egg of an astral dreadnaught ] - 68/200 psp's.

< 575h/575H 759p/759P 140v/140V >
< P: sit > You stop meditating.
You stop charging your crystal.
You start charging a translucent black crystal.

< 575h/575H 759p/759P 140v/140V >
< P: sit > Current charge for [ a translucent black crystal ] - 4/700 psp's.
You start meditating...

< 575h/575H 759p/759P 140v/140V >
< P: sit > You stop meditating.
You stop charging your crystal.
You start charging a massive egg of an astral dreadnaught.

< 575h/575H 759p/759P 140v/140V >
< P: sit > Current charge for [ a massive egg of an astral dreadnaught ] - 4/200 psp's.
You start meditating...

< 575h/575H 759p/759P 140v/140V >
< P: std > PSP Crystal Status:

a massive egg of an astral dreadnaught    4/ 200
a massive egg of an astral dreadnaught    0/ 200
a translucent black crystal                        0/ 700

**Comment by Inames** [comment]
Yes it's intended, you can only use one psp crystal.

**Comment by Nyyrazzilyss** [comment]
It's by design. You can only have a single charged crystal. If you put it in a container, it will also lose it's charge
