### ISSUE TITLE
Non Agro, turns agro no reason, but hold on let me spellup first....

### ISSUE THREAD

**Issue by Uagr** [torilmud/issues#797]
I guess I shouldn't have tried to talk to him.
.....................................

< 419h/419H 89p/89P 164v/166V >
< >                     

                      |.-.+.-.   
                       ----      
                          |.-.   
               ---     ----      
              |.!.|   |.-. .-.            <<<<<<<<<<Yellow !
           ----   -----   -------
          |.!. .@. . .+. .|      
           ----   --------       
              |.!.|              
               ---               
                                 
                                 
                                 
                        
Central Chamber of the Temple of Sess'innek
Exits: -N -E -S -W

< 419h/419H 89p/89P 164v/166V >
< >                     

                          |.-.   
                       ----      
                      |.-.+.-.   
                       ----      
                          |.-.   
               ---     ----      
              |.@.|   |.-. .-.   
           ----   -----   -------
          |.-. . . .-.+.-.|      
           ----   --------       
              |.!.|              
               ---               
                                 
                        
Chamber of the Master Architect
Exits: -S
The master architect of Hyssk stands at a table here.

< 419h/419H 89p/89P 164v/166V >
< > 
The master architect completes his spell...
The master architect utters the words, 'sfahzqhuai yfaw jioculoae'.

< 419h/419H 89p/89P 165v/166V >
< > The architect glances up from his work to see if you are one of his minions.  
Seeing that you are not, he bends his head down again and returns to his work.

< 419h/419H 89p/89P 166v/166V >
< > 
The master architect starts casting a spell.

< 419h/419H 89p/89P 166v/166V >
< >    The yuan-ti master architect is a halfbreed with human limbs but a
snake body, head and tail.  He stands six feet tall and his four foot
tail is stretched out behind him.  His body is thin and he has a narrow
hood like a cobra.  He pores over the plans to build more underground
tunnels and chambers to expand the city of Hyssk.
The master architect is a medium-sized level 48 Yuan-Ti.
He is in excellent condition.
His body seems to be made of stone!
He is encased in killing ice!
He's encased in a shimmering globe!

<held as shield>     a caiman skin shield

You attempt to peek at the inventory:
You can't see anything.

< 419h/419H 89p/89P 166v/166V >
< > No-one by that name here...

< 419h/419H 89p/89P 166v/166V >
< > No-one by that name here...

< 419h/419H 89p/89P 166v/166V >
< > No-one by that name here...

< 419h/419H 89p/89P 166v/166V >
< > No-one by that name here...

< 419h/419H 89p/89P 166v/166V >
< > No-one by that name here...

< 419h/419H 89p/89P 166v/166V >
< > No-one by that name here...

< 419h/419H 89p/89P 166v/166V >
< > No-one by that name here...

< 419h/419H 89p/89P 166v/166V >
< > No-one by that name here...

< 419h/419H 89p/89P 166v/166V >
< > No-one by that name here...

< 419h/419H 89p/89P 166v/166V >
< > No-one by that name here...

< 419h/419H 89p/89P 166v/166V >
< > No-one by that name here...

< 419h/419H 89p/89P 166v/166V >
< > No-one by that name here...

< 419h/419H 89p/89P 166v/166V >
< > No-one by that name here...

< 419h/419H 89p/89P 166v/166V >
< > No-one by that name here...

< 419h/419H 89p/89P 166v/166V >
< > No-one by that name here...

< 419h/419H 89p/89P 166v/166V >
< > The master architect completes his spell...
The master architect utters the words, 'zawsufuq hajqp'.
The master architect's hand starts to glow RED as blood.
No-one by that name here...

< 419h/419H 89p/89P 166v/166V >
< > OUCH!  That really did HURT!
No-one by that name here...

< 337h/419H 89p/89P 166v/166V >
< T: Ssuxu TC: small wounds E: architect EC: excellent > You dodge a bite from the master architect, who quickly recovers from his miss.
No-one by that name here...

< 337h/419H 89p/89P 166v/166V >
< T: Ssuxu TC: small wounds E: architect EC: excellent > No-one by that name here...

< 337h/419H 89p/89P 166v/166V >
< T: Ssuxu TC: small wounds E: architect EC: excellent > Your attack only grazes the master architect as he dodges aside!
Your weak pierce barely wounds the master architect.
You shiver from unnatural cold.
Your weak pierce barely wounds the master architect.
You shiver from unnatural cold.
You dodge the master architect's vicious attack.
You dodge the master architect's vicious attack.
No-one by that name here...

< 335h/419H 89p/89P 166v/166V >
< T: Ssuxu TC: small wounds E: architect EC: excellent > No-one by that name here...

< 334h/419H 89p/89P 166v/166V >
< T: Ssuxu TC: small wounds E: architect EC: excellent >                        

                      |.-.+.-.   
                       ----      
                          |.-.   
               ---     ----      
              |.!.|   |.-. .-.             <<<<<<<<<<Red !
           ----   -----   -------
          |.!. .@. . .+. .|      
           ----   --------       
              |.!.|              
               ---               
                                 
                                 
                                 
                        
Central Chamber of the Temple of Sess'innek
Exits: -N -E -S -W
You escape southward!

< 334h/419H 89p/89P 165v/166V >
< > You boggle at that concept.

< 348h/419H 89p/89P 166v/166V >
< >                     

                          |.-.   
                       ----      
                      |.-.+.-.   
                       ----      
                          |.-.   
               ---     ----      
              |.@.|   |.-. .-.   
           ----   -----   -------
          |.-. . . .-.+.-.|      
           ----   --------       
              |.!.|              
               ---               
                                 
                        
Chamber of the Master Architect
Exits: -S
The master architect of Hyssk stands at a table here.

< 348h/419H 89p/89P 165v/166V >
< > 
The master architect completes his spell...
The master architect utters the words, 'gjwwai'.
the master architect has summoned you!

                        

                          |.-.   
                       ----      
                      |.-.+.-.   
                       ----      
                          |.-.   
               ---     ----      
              |.@.|   |.-. .-.   
           ----   -----   -------
          |.-. . . .-.+.-.|      
           ----   --------       
              |.!.|              
               ---               
                                 
                        
Chamber of the Master Architect
Exits: -S
The master architect of Hyssk stands at a table here.

< 349h/419H 89p/89P 165v/166V >
< >    The yuan-ti master architect is a halfbreed with human limbs but a
snake body, head and tail.  He stands six feet tall and his four foot
tail is stretched out behind him.  His body is thin and he has a narrow
hood like a cobra.  He pores over the plans to build more underground
tunnels and chambers to expand the city of Hyssk.
The master architect is a medium-sized level 48 Yuan-Ti.
He is in excellent condition.
He is encased in killing ice!

<held as shield>     a caiman skin shield

You attempt to peek at the inventory:
You can't see anything.

< 351h/419H 89p/89P 166v/166V >
< >                     

                      |.-.+.-.   
                       ----      
                          |.-.   
               ---     ----      
              |.!.|   |.-. .-.   
           ----   -----   -------
          |.!. .@. . .+. .|      
           ----   --------       
              |.!.|              
               ---               
                                 
                                 
                                 
                        
Central Chamber of the Temple of Sess'innek
Exits: -N -E -S -W

< 352h/419H 89p/89P 165v/166V >
< > You say 'wtf'
< 373h/419H 89p/89P 166v/166V >
< > 
You feel a wrenching sensation.

**Comment by Dartan82** [comment]
it's because you entered while he was casting...

**Comment by Uagr** [comment]
Don't think thats it - i spent a couple minutes with him today.
------------
Entrance to the Temple of Sess'innek
Exits: -E -W

< 334h/419H 89p/89P 151v/166V >
< >                     

                      |.-.+.-.   
                       ----      
                          |.-.   
               ---     ----      
              |.!.|   |.-. .-.   <<<<<<<<<<<<<<<<<<<Non Agro (not red)
           ----   -----   -------
          |.!. .@. . .+. .|      
           ----   --------       
              |.!.|              
               ---               
                                 
                                 
                                 
                        
Central Chamber of the Temple of Sess'innek
Exits: -N -E -S -W

l n
< 335h/419H 89p/89P 151v/166V >
< > Chamber of the Master Architect
Exits: -S
The master architect of Hyssk stands at a table here.

n
< 335h/419H 89p/89P 151v/166V >
< >                     

                          |.-.   
                       ----      
                      |.-.+.-.   
                       ----      
                          |.-.   
               ---     ----      
              |.@.|   |.-. .-.   
           ----   -----   -------
          |.-. . . .-.+.-.|      
           ----   --------       
              |.!.|              
               ---               
                                 
                        
Chamber of the Master Architect
Exits: -S
The master architect of Hyssk stands at a table here.

< 357h/419H 89p/89P 165v/166V >
< > You hop around on one foot.

< 359h/419H 89p/89P 166v/166V >
< > 
The master architect starts casting a spell.

< 372h/419H 89p/89P 166v/166V >
< > 
The master architect completes his spell...
The master architect utters the words, 'abrazak'.

< 408h/419H 89p/89P 166v/166V >
< > 
The master architect starts casting a spell.

< 414h/419H 89p/89P 166v/166V >
< > 
Xyssyth NHC: 'they got the   wost wisdom'

< 419h/419H 89p/89P 166v/166V >
< > 
The master architect completes his spell...
The master architect utters the words, 'qaregpuzre'.
The master architect is surrounded by an aura of deadly cold!


< 419h/419H 89p/89P 166v/166V >
< > 
Xyssyth NHC: 'meaning  the  worst mem times on spells '

< 419h/419H 89p/89P 166v/166V >
< > 
Gozub NHC: 'yeah my times are horrible'

< 419h/419H 89p/89P 166v/166V >
< > You hop around on one foot.

s
< 419h/419H 89p/89P 166v/166V >
< >                     

                      |.-.+.-.   
                       ----      
                          |.-.   
               ---     ----      
              |.!.|   |.-. .-.   <<<<<<<<<<<<<<<<<<<Non Agro (not red)
           ----   -----   -------
          |.!. .@. . .+. .|      
           ----   --------       
              |.!.|              
               ---               
                                 
                                 
                                 
                        
Central Chamber of the Temple of Sess'innek
Exits: -N -E -S -W

**Comment by marthammor** [comment]
This mob does indeed have a social that has a small chance to attack the player when talked to. Working as intended.
