### ISSUE TITLE
Hex Blade feedback\tweaks

### ISSUE THREAD

**Issue by Lamnicaes** [torilmud/issues#798]
Would like to see a condition affect for "Memory of Blades" on Hex Blades, perhaps Frightened for 16 seconds?

Would like to see "Soul Cutter" for their 2h skill set changed to a small aoe attack, like cleave, hitting 3 targets. Their 2h skill set is meant to be more aoe, and this change would be minor, but nice to have.

Thoughts?

**Comment by shevarash** [comment]
Thank you for the feedback. We'll incorporate these ideas into any upcoming Hexblade adjustments.
