### ISSUE TITLE
Earthquake message issue

### ISSUE THREAD

**Issue by shevarash** [torilmud/issues#8]
Icezzexxuy GCC: 'btw some powers, like earthquake, give absolutely 0 indication of whether the spell is actually doing anything if it doesn't result in something, so we get no message for damage being dealt, only messages for mobs being knocked down. it's disconcerting to eaq 5 times in a row and get absolutely 0 mud response'

**Comment by Adriorn** [comment]
What ends up happening is you get knocked over without any indication.

**Comment by Inames** [comment]
I wasn't aware of that particular part of the issue. Don't think I've ever experienced that myself, pretty sure I can see players get knocked down by it as the caster, I'll double check though.

**Comment by shevarash** [comment]
Earthquake will now show the "staggers and almost falls!" message for characters that resist the prone attack. 

Example:

![image](https://cloud.githubusercontent.com/assets/24870638/22630349/2ee70386-ebbe-11e6-8295-99a93759efd2.png)
