### ISSUE TITLE
Warrior Base Hps  are lower than other classes

### ISSUE THREAD

**Issue by druzuul** [torilmud/issues#801]
Double checked my base hps on a Moonelf warrior with 100 con vs a ranger with 100 con at level 50 and warrior has lower hps by 7 hps.  Barbarian warrior vs ranger same again. Age is no longer in the game either.

**Comment by Dartan82** [comment]
Isn't hp gain random on level gain?

**Comment by druzuul** [comment]
yes it was explained first levels to 20 are random :)
