### ISSUE TITLE
Bodyslammed by mobs that aren't even in the same room as me.

### ISSUE THREAD

**Issue by Lilithelle** [torilmud/issues#802]
This happened in Trollbark Forest, this room has archers to the north, west, and east.  Without even entering the room they were able to bodyslam me four times in a row preventing me from leaving the room for a few rounds, while they were shooting me with arrows.  They also bodyslammed me during the fight with ancient shaman.

A Dusty Clearing at the Tree Line
Exits: -N -E -S -W
An ancient troll shaman slowly hunts for herbs here.
Sylvana sneaks in from the south.

< 1016h/1102H 169v/170V > You start chanting...

< 1017h/1102H 169v/170V > 
An ancient troll misses you with her hit.
.
.
.
Sylvana neatly beheads an ancient troll.
an ancient troll is dead! R.I.P.
You receive 5,700 XP (0.02%) experience.
Your blood freezes as you hear the rattling death cry of an ancient troll.

< 881h/1102H 170v/170V > s

A troll sniper's carefully aimed shot from the east hits Sylvana.

< 881h/1102H 170v/170V > 
a troll sniper's aimed shot from the west flies wild and misses you!

< 881h/1102H 170v/170V > 
A troll sniper's carefully aimed shot from the north hits Sylvana.

< 881h/912H 170v/170V > 
A troll sniper lets out an enormous ROAR, and charges towards _YOU_!
a troll sniper sends you sprawling.
st
OUCH!  That really did HURT!

< 824h/912H 170v/170V > 
A troll sniper lets out an enormous ROAR, and charges towards _YOU_!
a troll sniper sends you sprawling.
st
OUCH!  That really did HURT!

< 763h/912H 170v/170V > 
Sylvana clambers to her feet.

< 767h/912H 170v/170V > 
A troll sniper lets out an enormous ROAR, and charges towards _YOU_!
a troll sniper sends you sprawling.
st
OUCH!  That really did HURT!

< 716h/912H 170v/170V > 
A troll sniper lets out an enormous ROAR, and charges towards _YOU_!
a troll sniper sends you sprawling.
st
OUCH!  That really did HURT!

< 664h/912H 170v/170V > 
A troll sniper's carefully aimed shot from the west hits you!

< 633h/912H 170v/170V > 
a troll sniper's aimed shot from the east flies wild and misses you!

< 638h/912H 170v/170V > 
A troll sniper's carefully aimed shot from the west hits you!
OUCH!  That really did HURT!

< 587h/912H 170v/170V > 
a troll sniper's aimed shot from the north flies wild and misses you!

< 587h/912H 170v/170V > 
Sylvana clambers to her feet.

< 590h/912H 170v/170V > 
Sylvana attempts to flee.
Sylvana sneaks east.

< 591h/912H 170v/170V > 
a troll sniper's aimed shot from the west flies wild and misses you!

< 593h/912H 170v/170V > 
a troll sniper's aimed shot from the north flies wild and misses you!

< 594h/912H 170v/170V > You clamber to your feet.

< 595h/912H 170v/170V > A Dry Patch at the Tree Line
Exits: -N -U

**Comment by Inames** [comment]
They just SUPER fat... and they can't walk into your room without "Body Slamming" you cuz they so big... don't judge!

**Comment by vitaladsr** [comment]
> This happened in Trollbark Forest, this room has archers to the north, west, and east.  Without even entering the room they were able to bodyslam me four times in a row preventing me from leaving the room for a few rounds, while they were shooting me with arrows.  They also bodyslammed me during the fight with ancient shaman.
> 
> 
> 
> A Dusty Clearing at the Tree Line
> 
> Exits: -N -E -S -W
> 
> An ancient troll shaman slowly hunts for herbs here.
> 
> Sylvana sneaks in from the south.
> 
> 
> 
> < 1016h/1102H 169v/170V > You start chanting...
> 
> 
> 
> < 1017h/1102H 169v/170V > 
> 
> An ancient troll misses you with her hit.
> 
> .
> 
> .
> 
> .
> 
> Sylvana neatly beheads an ancient troll.
> 
> an ancient troll is dead! R.I.P.
> 
> You receive 5,700 XP (0.02%) experience.
> 
> Your blood freezes as you hear the rattling death cry of an ancient troll.
> 
> 
> 
> < 881h/1102H 170v/170V > s
> 
> 
> 
> A troll sniper's carefully aimed shot from the east hits Sylvana.
> 
> 
> 
> < 881h/1102H 170v/170V > 
> 
> a troll sniper's aimed shot from the west flies wild and misses you!
> 
> 
> 
> < 881h/1102H 170v/170V > 
> 
> A troll sniper's carefully aimed shot from the north hits Sylvana.
> 
> 
> 
> < 881h/912H 170v/170V > 
> 
> A troll sniper lets out an enormous ROAR, and charges towards _YOU_!
> 
> a troll sniper sends you sprawling.
> 
> st
> 
> OUCH!  That really did HURT!
> 
> 
> 
> < 824h/912H 170v/170V > 
> 
> A troll sniper lets out an enormous ROAR, and charges towards _YOU_!
> 
> a troll sniper sends you sprawling.
> 
> st
> 
> OUCH!  That really did HURT!
> 
> 
> 
> < 763h/912H 170v/170V > 
> 
> Sylvana clambers to her feet.
> 
> 
> 
> < 767h/912H 170v/170V > 
> 
> A troll sniper lets out an enormous ROAR, and charges towards _YOU_!
> 
> a troll sniper sends you sprawling.
> 
> st
> 
> OUCH!  That really did HURT!
> 
> 
> 
> < 716h/912H 170v/170V > 
> 
> A troll sniper lets out an enormous ROAR, and charges towards _YOU_!
> 
> a troll sniper sends you sprawling.
> 
> st
> 
> OUCH!  That really did HURT!
> 
> 
> 
> < 664h/912H 170v/170V > 
> 
> A troll sniper's carefully aimed shot from the west hits you!
> 
> 
> 
> < 633h/912H 170v/170V > 
> 
> a troll sniper's aimed shot from the east flies wild and misses you!
> 
> 
> 
> < 638h/912H 170v/170V > 
> 
> A troll sniper's carefully aimed shot from the west hits you!
> 
> OUCH!  That really did HURT!
> 
> 
> 
> < 587h/912H 170v/170V > 
> 
> a troll sniper's aimed shot from the north flies wild and misses you!
> 
> 
> 
> < 587h/912H 170v/170V > 
> 
> Sylvana clambers to her feet.
> 
> 
> 
> < 590h/912H 170v/170V > 
> 
> Sylvana attempts to flee.
> 
> Sylvana sneaks east.
> 
> 
> 
> < 591h/912H 170v/170V > 
> 
> a troll sniper's aimed shot from the west flies wild and misses you!
> 
> 
> 
> < 593h/912H 170v/170V > 
> 
> a troll sniper's aimed shot from the north flies wild and misses you!
> 
> 
> 
> < 594h/912H 170v/170V > You clamber to your feet.
> 
> 
> 
> < 595h/912H 170v/170V > A Dry Patch at the Tree Line
> 
> Exits: -N -U
> 
> 

Ah wow insane

**Comment by shevarash** [comment]
This has been fixed. Thank you for the bug report.
