### ISSUE TITLE
Allow half-orcs into evil hometowns

### ISSUE THREAD

**Issue by Lilithelle** [torilmud/issues#807]
Tislor NHC: 'also can I go to evil areas as a half orc even though I am good?'
Tislor NHC: 'without being attacked by guards?'

It  seems to confuse a lot of new players, and I don't think there would be much harm to it.  They can't even enter Bloodtusk, so orcs reject them.  Heck, even the bigoted elves allow half-elves into their city.

**Comment by marthammor** [comment]
Problem is that they are coded as good race. Orcs are coded as evil race. Half-elves and elves are both good race, so not a good comparison. We can switch half_orcs to evil race, but that introduces issues with equipment, shops, people rented in good race only towns, ect.

**Comment by shevarash** [comment]
This is intended - for now. A revision to this would essentially involve reclassifying towns from evil or good and making them neutral.
