### ISSUE TITLE
Airplane has mobs that have a proc that disarm your weapon

### ISSUE THREAD

**Issue by druzuul** [torilmud/issues#808]
Twice ive had to help people get their weapons back from airplane. They also dont realize they have lost their weapon either.

**Comment by Lilithelle** [comment]
It is not a proc, it uses the social file to have them cast dust devil and whirlwind (powers version).

**Comment by Dartan82** [comment]
is it because nyy's script doesn't detect it

**Comment by shevarash** [comment]
This is intended.
