### ISSUE TITLE
Powers Continual Light doesn't work underwater.

### ISSUE THREAD

**Issue by Lilithelle** [torilmud/issues#809]
< 912h/912H 167v/170V > It is pitch black...

< 912h/912H 167v/170V > world
Syntax: world < stats, zones >
This server compiled at 21:21:03 Jul 20 2020.
You are currently in: Skerttd-Gul

< 912h/912H 169v/170V > power 'conti'
You can't do that underwater!

< 912h/912H 170v/170V > cast 'conti'
You start chanting...

< 912h/912H 170v/170V > 
Casting: Continual Light *****

< 912h/912H 170v/170V > 
Casting: Continual Light ****

< 912h/912H 170v/170V > 
Casting: Continual Light ***

< 912h/912H 170v/170V > 
Casting: Continual Light **

< 912h/912H 170v/170V > 
Casting: Continual Light *

< 912h/912H 170v/170V > 
You complete your spell...
The magical darkness is dispelled!

< 912h/912H 170v/170V > look
At The Top of a Huge Vertical Tunnel
Exits: -U -D

* There is a quest that requires you lead a prisoner out of Skerttd-Gul through the magically darkened rooms, so continual light is necessary.

**Comment by OghmaToril** [comment]
For testing purposes: r99215

**Comment by OghmaToril** [comment]
Fixed and will be moved in during future code move.
