### ISSUE TITLE
Protection Abilities no matching item

### ISSUE THREAD

**Issue by derwulv** [torilmud/issues#810]
I found an issue with "a beautifully enscribed turquoise ring" giving protections in "Score" that don't appear on the item when ID'd

< 814h/814H 155v/155V |sot +|drs +|bc +|fr +|vs +|ss +|md +|sph +|uf +|aotdd +| |3|3|3|3|2| >
< > rec scroll turquoise
You recite an intricate divination scroll which turns to dust in your hands.
You feel informed:
Name 'a beautifully enscribed turquoise ring'
Keyword 'ring beautifully enscribed turquoise', Item type: WORN
Item can be worn on:  FINGER 
Item will give you following abilities:  PR-EVIL PR-GOOD DET-MAGIC 
Item is: MAGIC NOBITS
Weight: 1, Value: 0
Can affect you as :
    Affects : ARMOR By -9
    Affects : HITROLL By 3

< 814h/814H 155v/155V |sot +|drs +|bc +|fr +|vs +|ss +|md +|sph +|uf +|aotdd +| |3|3|3|3|2| >
< > 
An elegant commoner leaves south.

< 814h/814H 155v/155V |sot +|drs +|bc +|fr +|vs +|ss +|md +|sph +|uf +|aotdd +| |3|3|3|3|2| >
< > wear ring
You place a beautifully enscribed turquoise ring on your right ring finger.

< 814h/814H 155v/155V |sot +|drs +|bc +|fr +|vs +|ss +|md +|sph +|uf +|aotdd +| |3|3|3|3|2| >
< > score

                Score information for Zarabolag

Level: 50   Race: Duergar   Class: Blackguard  
Hit points: 814(814)  Moves: 155(155)
Experience Progress: 2333 % 
Coins carried:  142 platinum    53 gold     1 silver     1 copper
Coins in bank:    0 platinum     3 gold     9 silver     0 copper
Prestige: 7805   Acheron Kill Count: 0
Name status: Approved
Citizen of:   Gloomhaven
Outcast from: Griffon's Nest
Playing time: 18 days / 18 hours / 49 minutes
Title: 
Status:  Standing.
Detecting:       Good Magic
Protected from:  Evil Good Fire Cold
Enchantments:    Ultravision

< 814h/814H 155v/155V |sot +|drs +|bc +|fr +|vs +|ss +|md +|sph +|uf +|aotdd +| |3|3|3|3|2| >
< > 
Copus looks over a recent acquisition carefully.

< 814h/814H 155v/155V |sot +|drs +|bc +|fr +|vs +|ss +|md +|sph +|uf +|aotdd +| |3|3|3|3|2| >
< > rem ring
You stop using a beautifully enscribed turquoise ring.

< 814h/814H 155v/155V |sot +|drs +|bc +|fr +|vs +|ss +|md +|sph +|uf +|aotdd +| |3|3|3|3|2| >
< > score

                Score information for Zarabolag

Level: 50   Race: Duergar   Class: Blackguard  
Hit points: 814(814)  Moves: 155(155)
Experience Progress: 2333 % 
Coins carried:  142 platinum    53 gold     1 silver     1 copper
Coins in bank:    0 platinum     3 gold     9 silver     0 copper
Prestige: 7805   Acheron Kill Count: 0
Name status: Approved
Citizen of:   Gloomhaven
Outcast from: Griffon's Nest
Playing time: 18 days / 18 hours / 50 minutes
Title: 
Status:  Standing.
Detecting:       Good
Enchantments:    Ultravision

< 814h/814H 155v/155V |sot +|drs +|bc +|fr +|vs +|ss +|md +|sph +|uf +|aotdd +| |3|3|3|3|2| >
< > 
Copus looks over a recent acquisition carefully.

Further testing if I'm wearing other equipment and then wear the "a beautifully enscribed turquoise ring" I get some additional "Protections"  (see log below)

< 874h/874H 155v/155V |sot +|drs +|bc +|fr +|vs +|ss +|md +|sph +|uf +|aotdd +| |3|3|3|3|2| >
< > eq
You are using:
<worn as a badge>    a badge of a sword spider (illuminating)
<worn on head>       a crown of the death dragon
<worn on eyes>       a glowing red skull eyepatch
<worn in ear>        a ruby studded black dragonscale
<worn in ear>        a ruby studded black dragonscale
<worn on face>       a coautl scale mask
<worn around neck>   an obsidian necklace with shimmering moonstones
<worn around neck>   a necklace of serpent's teeth
<worn on body>       a shimmering suit of dragonhunter armor
<worn about body>    a heavy cloak of dragonskin
<worn as quiver>     a satchel of the traveler
<worn about waist>   a belt of flame enshrouded amethysts
<worn around wrist>  a heavy polished bone bracelet
<worn around wrist>  a bracelet of rakshasa teeth
<worn on hands>      a pair of silverish githyanki gauntlets
<worn on finger>     a band of dark flesh
<wielding twohanded> a four-headed battleaxe of abyssal doom
<worn on feet>       some demonscale boots

< 874h/874H 155v/155V |sot +|drs +|bc +|fr +|vs +|ss +|md +|sph +|uf +|aotdd +| |3|3|3|3|2| >
< > 
Autosaving...

< 874h/874H 155v/155V |sot +|drs +|bc +|fr +|vs +|ss +|md +|sph +|uf +|aotdd +| |3|3|3|3|2| >
< > score

                Score information for Zarabolag

Level: 50   Race: Duergar   Class: Blackguard  
Hit points: 874(874)  Moves: 155(155)
Experience Progress: 2333 % 
Coins carried:  142 platinum    53 gold     1 silver     1 copper
Coins in bank:    0 platinum     3 gold     9 silver     0 copper
Prestige: 7805   Acheron Kill Count: 0
Name status: Approved
Citizen of:   Gloomhaven
Outcast from: Griffon's Nest
Playing time: 18 days / 19 hours / 3 minutes
Title: 
Status:  Standing.
Detecting:       Good
Enchantments:    Ultravision

< 874h/874H 155v/155V |sot +|drs +|bc +|fr +|vs +|ss +|md +|sph +|uf +|aotdd +| |3|3|3|3|2| >
< > 
A refined commoner enters from the south.

< 874h/874H 155v/155V |sot +|drs +|bc +|fr +|vs +|ss +|md +|sph +|uf +|aotdd +| |3|3|3|3|2| >
< > wear ring
You place a beautifully enscribed turquoise ring on your right ring finger.

< 874h/874H 155v/155V |sot +|drs +|bc +|fr +|vs +|ss +|md +|sph +|uf +|aotdd +| |3|3|3|3|2| >
< > score

                Score information for Zarabolag

Level: 50   Race: Duergar   Class: Blackguard  
Hit points: 874(874)  Moves: 155(155)
Experience Progress: 2333 % 
Coins carried:  142 platinum    53 gold     1 silver     1 copper
Coins in bank:    0 platinum     3 gold     9 silver     0 copper
Prestige: 7805   Acheron Kill Count: 0
Name status: Approved
Citizen of:   Gloomhaven
Outcast from: Griffon's Nest
Playing time: 18 days / 19 hours / 3 minutes
Title: 
Status:  Standing.
Detecting:       Good Magic
Protected from:  Evil Good Fire Cold Acid
Enchantments:    Ultravision

< 874h/874H 155v/155V |sot +|drs +|bc +|fr +|vs +|ss +|md +|sph +|uf +|aotdd +| |3|3|3|3|2| >
< > eq
You are using:
<worn as a badge>    a badge of a sword spider (illuminating)
<worn on head>       a crown of the death dragon (magic)
<worn on eyes>       a glowing red skull eyepatch
<worn in ear>        a ruby studded black dragonscale (magic)
<worn in ear>        a ruby studded black dragonscale (magic)
<worn on face>       a coautl scale mask
<worn around neck>   an obsidian necklace with shimmering moonstones (magic)
<worn around neck>   a necklace of serpent's teeth
<worn on body>       a shimmering suit of dragonhunter armor (magic)
<worn about body>    a heavy cloak of dragonskin
<worn as quiver>     a satchel of the traveler
<worn about waist>   a belt of flame enshrouded amethysts (magic)
<worn around wrist>  a heavy polished bone bracelet (magic)
<worn around wrist>  a bracelet of rakshasa teeth
<worn on hands>      a pair of silverish githyanki gauntlets
<worn on finger>     a beautifully enscribed turquoise ring (magic)
<worn on finger>     a band of dark flesh
<wielding twohanded> a four-headed battleaxe of abyssal doom (magic)
<worn on feet>       some demonscale boots (magic)

< 874h/874H 155v/155V |sot +|drs +|bc +|fr +|vs +|ss +|md +|sph +|uf +|aotdd +| |3|3|3|3|2| >
< >

**Comment by druzuul** [comment]
maybe thats detect magic detecting your existing protects.

**Comment by GeneralGormal** [comment]
You need DM to detect many magical effects in the score screen.

**Comment by OghmaToril** [comment]
Gormal and Druzuul are correct.  You always had protection from Fire, Cold, and Acid.  The protects showing in score have always been hidden unless you have Detect Magic.  If you look at attributes or stats, your Fire/Cold/Acid resistances would not change when wearing/removing the ring.
