### ISSUE TITLE
Enhance: Scardale

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#814]
Scardale (or surrounding areas) could use a level limited entrance to the northern part of Undermountain 1.

**Comment by Lilithelle** [comment]
UM1 is pretty dangerous, the manticore have a death proc, the illithids are pretty nasty too.

**Comment by Nyyrazzilyss** [comment]
This might be a bit better: How about moving Splitshield to Scardale? Huge number of mobs for leveling, and easy to get low level equipment (raw, fine leather ...)

**Comment by Lilithelle** [comment]
You can kill dogs and wolves in Splitshield; but if you try to kill any orcs , the guards come to combat and assist the mob.  There are a lot of guards, and they are armed, some backstab.  Not the ideal choice.

**Comment by shevarash** [comment]
Interesting idea, but I think this is ok for now.
