### ISSUE TITLE
Forcing name changes out of the blue or because of a backlog

### ISSUE THREAD

**Issue by druzuul** [torilmud/issues#815]
Where do you draw the line for what is an appropriate name for Toril? In the past week ive had 3 forced name changes after months of playing my characters. Basaro was deemed inappropriate for a Drow blackguard. Irazalif was deemed inappropriate for a Drow warrior, and now Jarro is deemed inappropriate for a Moonelf ranger. 
Most of us invest hours a day building a reputation with our chosen names. We enjoy building that character while gaining riches and perceived notoriety. After spending over 40 days of play time, to have someone decide after all that time, "hey i dont think your name fits in my perceived vision of a moonelf" is a real problem. Ive spent all this time enjoying myself and thinking im bringing my imagination and hopefully fun to this community, only to have someone finally get to the backlog of name approving? I understand the Imms are sacrificing their time for the betterment of the game, but we players are also giving up time also.  If I had an offensive name im sure it would of been flagged or something in at least the first week. 

Perhaps its just as simple as waiting for an imm to ask them to allow me my original name. But the issue is, if it can happen to me, it can happen to you. Flashbacks to mystra

Formerly Jarro

**Comment by GeneralGormal** [comment]
Those changes do seem late given how much you've played them all and none are gay jokes that do get approved

**Comment by jokkmeister** [comment]
Yeah imms are very inconsistant when it comes to name changes and that is a problem. There are plenty of old names that should by all name rules be changed but they are not. SHouldn't matter if a name is 1 week old or several years old, the same rules should apply.
