### ISSUE TITLE
Blind Poison Accidental Nerf

### ISSUE THREAD

**Issue by GeneralGormal** [torilmud/issues#817]
I noticed that blind registers differently in an NPC's status than the other poisons, and (now?) has a 2min duration where the others have 3min.  Is this a result of the powers changes?  Are other poisons affected? Am I just misremembering how everything looked/worked?

Status of an Ashstone noble
---------------------------------------------------------------------------

Effects
---------------------------------------------------------------------------
blind                     skill aware               slowness                  

Spells
---------------------------------------------------------------------------
slowness                  (  2:00)   

Conditions
---------------------------------------------------------------------------
Backstab                  (  1:30)   blind                     (  1:47)

**Comment by shevarash** [comment]
I'm hoping it's the latter, but will investigate.

**Comment by shevarash** [comment]
I looked into this and it appears that blind poison was changed to be a condition (rather than the old spell) several years back. The duration does not appear to have changed in that transfer. Closing for now, but if I'm missing something feel free to re-open.
