### ISSUE TITLE
Goblin King Scepter road

### ISSUE THREAD

**Issue by Dartan82** [torilmud/issues#818]
http://www.torilmud.com/news/patch-notes-3-5-2020/

Goblin King: The bronze scepter that loads here now has a small chance to load each time the king repops.

14 kills and nothing.  Intended to be this rare?

**Comment by GeneralGormal** [comment]
Yes, it's a pretty low chance iirc. 2%?

**Comment by gehadron** [comment]
got 2 out of almost 20 kills i think

**Comment by shevarash** [comment]
Appears to be working, closing ticket.
