### ISSUE TITLE
Bodyslam efficiency

### ISSUE THREAD

**Issue by druzuul** [torilmud/issues#824]
Bodyslam has a coolness factor of 100! but at the moment I think it only does 5d5 damage and lags you for 2 rounds. Added to the fact you cant use a power til the 3rd round the damage trade off is too big to use efficiently compared to starting with sweeping strikes with a 500% weapon along with another power in the 2nd round.  Situationally you can bodyslam a mob and SS a second mob which is probably the greatest usage I can think of. Bodyslam also has the disadvantage of failure against aware mobs. I think all of ice plane is perm aware, amongst other zones.

**Comment by vitaladsr** [comment]
I think the inmates could all use some updating .. and bring back headbutt!!!

**Comment by shevarash** [comment]
All innates will be reviewed an updated as a part of the class upgrade project that is ongoing. Thanks for calling out bodylam in particular, I'll keep it in mind.
