### ISSUE TITLE
Camping removes the (water) flag from rooms

### ISSUE THREAD

**Issue by Lilithelle** [torilmud/issues#829]
Camping removed the (water) flag from the room without even completing the camp.

On an Underground Lake (Water)
Exits: -E -W -U

< 855h/848H 175v/180V |sod +|iw +|cs +|ra +|sb +|ut +|ds +|bs +| > camp
You start setting up camp...

You will be logged out in 15 seconds.

< 855h/848H 177v/180V |sod +|iw +|cs +|ra +|sb +|ut +|ds +|bs +| > l
On an Underground Lake
Exits: -E -W -U

< 855h/848H 178v/180V |sod +|iw +|cs +|ra +|sb +|ut +|ds +|bs +| > w
The West Side of an Underground Lake
Exits: -E -W -U

< 855h/848H 178v/180V |sod +|iw +|cs +|ra +|sb +|ut +|ds +|bs +| > 
Logout cancelled.

< 855h/848H 180v/180V |sod +|iw +|cs +|ra +|sb +|ut +|ds +|bs +| > e
On an Underground Lake
Exits: -E -W -U

**This happened first, but as can be seen above it doesn't even require camping to complete.  The bash that happened below shows its not just that the (water) room isn't being shown, it actually made a previously no bash room bashable.**

The West Side of an Underground Lake (Water)
Exits: -E -W -U

< 908h/908H 177v/180V |sod +|iw +|cs +|ra +|sb +|ut +|ds +|bs +| > camp
You start setting up camp...

You will be logged out in 15 seconds.

< 908h/908H 180v/180V |sod +|iw +|cs +|ra +|sb +|ut +|ds +|bs +| > 
You will be logged out in 5 seconds.

< 908h/908H 180v/180V |sod +|iw +|cs +|ra +|sb +|ut +|ds +|bs +| > You complete setting up your camp and settle in.

Characters:
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
.
.
.
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Type the # or name of a character above to login or choose an action below.
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
(N)ew character     | (L)ink character   | (U)nlink character | (R)eorder
(E)nter description | (D)elete character | (C)hange password  | (Q)uit
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

Your choice: garru
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
                           Account Unlink Removal
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

To support upcoming new game features, the Account Unlink tool will
be removed in the very near future. We suggest that you consolidate
all of your characters under a single account during this time.
Once the unlink command is removed, you will need to contact a staff
member to unlink a character from an account.

Resources

Web Client : http://www.torilmud.com/login
Discord    : https://discord.gg/t7edjzM
News       : http://news.torilmud.com/
Issues     : https://github.com/torilmud/issues
Forums     : http://www.torilmud.org/phpBB3/
Support    : toril.help@gmail.com

You break camp and get ready to move on...

        Welcome to TorilMUD

The West Side of an Underground Lake
Exits: -E -W -U

< 908h/908H 180v/180V |sod +|iw +|cs +|ra +|sb +|ut +|ds +|bs +| > 
a female spriggan skulks in from the west.
a female spriggan misses you with her bludgeon.
a female spriggan misses you with her bludgeon.
a female spriggan sends you sprawling.
st

**Comment by shevarash** [comment]
This has been fixed.
