### ISSUE TITLE
Suggestions for powers updated priest class

### ISSUE THREAD

**Issue by vitaladsr** [torilmud/issues#831]
I have always loved the battle cleric variant in Forgotten Realms vs. the traditional devoted/or shielding cleric. Maybe we can give them a few more melee abilities such as shieldblock, and a few melee powers for hitting, and maybe some extra attacks .. atleast double attack at a certain point :) Below are some excerpts from various FR sites that discuss this type of thing.

**Battle Cleric**

Instead of focusing simply on their role as healers and inspirational icons of their deity, battle clerics preferred to get into the thick of a fight, leading the charge of the faithful. These clerics were almost always physically well-built, building their muscles and fortitude to make them effective melee combatants in their god's service. These clerics still put an emphasis on strong judgement and awareness of both others and oneself, but an additional priority was put on physical power, as was leadership ability and strength of personality.[23]

If you choose to concentrate on melee, you find a good assortment of strikes to your liking. To achieve this build, make Strength your primary score. Make Wisdom your secondary score and assign Charisma as your tertiary score. Make sure to concentrate on powers that work with melee attacks, since these play to your key ability scores.

Feat: _Weapon Focus (Human feat: Action Surge)_
Skills: Diplomacy, Heal, Insight, Religion
At-Will Powers: righteous brand, priest’s shield
Encounter Power: wrathful thunder
Daily Power: avenging flame

Battle Cleric Armaments is also a feat available to clerics with a Strength of 15.

The feat is less useful to Warpriests (who already have proficiency with shields) and Templars with Battle Cleric's Lore (who get a flat +2 shield bonus to AC), both which may be better served with a different feat that provides proficiency (e.g. to a superior weapon).

Clerics with this feat gain armor proficiency with light shields, and weapon proficiency with one military weapon of their choice. [Dr379:55] 

References:
[](https://forgottenrealms.fandom.com/wiki/Cleric)
[](https://dnd4.fandom.com/wiki/Battle_Cleric_Armaments)
[](Source: http://dustin.wikidot.com/cleric#toc2)

**Comment by shevarash** [comment]
Thanks for the feedback. This will be addressed in an upcoming Cleric class overhaul.
