### ISSUE TITLE
Change exp penalty to be more group friendly

### ISSUE THREAD

**Issue by Dartan82** [torilmud/issues#832]
I assume the current group exp penalty is exp from mob divided by players.  Change it to a where a 2 man group gets 90%, 3 man group gets 80%, 4 man group gets 70%, 5 man group gets 60%, 6 man group gets 50%.  This should encourage grouping or at least speed up the leveling process in general.

**Comment by shevarash** [comment]
Thank you for the feedback. I agree that the exp penalty should be changed, and I'm tracking it in an internal issue. Thank you!
