### ISSUE TITLE
Non Auctionable EQ

### ISSUE THREAD

**Issue by druzuul** [torilmud/issues#843]
Just find it rather annoying some eq is not auction houseable for some reason. For example the lastest ive noticed is 
"a fine mithril shield embedded with spikes". 
Also I believe if you remove curse an item it also becomes non auction houseable?

**Comment by GeneralGormal** [comment]
Auctioning uncursed, restrung, or any kind of altered equipment reverts it to it's original state. FYI.

The nosell flag had always been super arbitrary and annoying tho
