### ISSUE TITLE
Rare items and Rare percentages

### ISSUE THREAD

**Issue by druzuul** [torilmud/issues#848]
Rare loads seem to have a very broad range of load percentages.  Im assuming the lower the load percentage the better the item, but sometimes that is not the case, and also doesnt really apply anymore with Bahamut and Tiamat eq.  I dont really see the point of having a really low rare percentage vs a more common rare percentage. If everything just had a flat rare chance what would that be like? 
Rare quest items also seem to have a huge range of load percentages. Making a quest harder to complete due to the low load percentage of a quest item vs the quest just being harder involving harder zones and such rather skill-less. Throwing in really low load percentage items in lowbie zones for great eq seems like a cop out too. Pretty sure a flat percentage load rate on quest rares wouldnt be unreasonable or cause unbalance?  I understand many quests are designed so unused zones were brought back into gameplay.

**Comment by shevarash** [comment]
Thank you for the feedback. If there's a specific rareload you feel should be less rare, let us know.
