### ISSUE TITLE
Hexblade change ideas

### ISSUE THREAD

**Issue by Lamnicaes** [torilmud/issues#849]
-'Armor of the Void' duration increase to 1 min, considering 5th circle, you only get 2 of them and using up Blazing Doom slot.

-Add 'frightened' effect to Memory of Blades.

-'Cloak of Flies' moved to 2nd circle and add 'weakness' effect to the venomous fly sting.

-'Spectral Fade' moved to 4th circle where COF was and change the 'hide' so you stay hidden when moving, as long as you have a perm sneak item(or in the Underdark with a racial UD sneak). Camouflage still drops when you move.

-'Eldritch Chains' added effect changed to Ray of Enfeeblement so it's not the same as COF. 

Thoughts?

**Comment by shevarash** [comment]
Thanks for the ideas! The Hexblade class has been completely overhauled, so I'm closing this ticket

http://www.torilmud.com/news/patch-notes-hexblades-reborn/
