### ISSUE TITLE
Doppelganger (more)

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#85]
A couple more problems with doppelganger, some have previously been listed

1) Doppelganger vs doppleganger. This spelling error is all over the place, including the power alias (dopple) and spell itself
   
You have finished memorizing Doppleganger.

2) Doppelgangers can be created of doppelgangers, both player and npc

A doppelganger of doppel doppelganger now follows A doppelganger of Sagrub.

3) Creating a doppelganger of someone that already has one with the power doesn't always immediately fail with the notation that you can't have more then one. The error message is provided after the spell completes only if you had cast the spell on yourself. No error message is returned if it was being cast on someone else.
  
You complete your spell... [Completed spell: dopple (Doppleganger) ]
You may only have one doppelganger at a time!

4) The helpfile for doppelganger does suggest that they (the doppelgangers) do full damage. This should probably be corrected (They don't actually do damage)

5) There's various reasons that someone could leave the room the doppelganger is located/the doppelganger will be unable to follow. I would suggest whenever that happens, the doppelganger is 'poofed' and the effect remove from the person.

**Comment by Inames** [comment]
I already have a ticket open on number 2.

**Comment by dnavarro** [comment]
- [ ] Triage this ticket and #79 into component tickets

**Comment by shevarash** [comment]
This will be addressed in an upcoming Illusionist class overhaul.
