### ISSUE TITLE
Charmed while hidden, and then still hidden after death

### ISSUE THREAD

**Issue by Innova133** [torilmud/issues#851]
I was attempting to kill a succubus in UM2...was doing well, and then she summoned a balor.  I fled out, sneak, hide.  (verified hidden with katumi).  Went back in, and was insta charmed.  Sat there for a few minutes, then she killed me.  I enter portal, and was still hidden.

Some logs:

The Lair of the Dark Temptress
Exits: -S              [71075]  [Hidden]
A living bed ripples as it moves every so often.
A sultry succubus demon named Naxqe'Isa rolls about her bed playfully.

< 286h/510H 144v/145V P: std >

You stop trying to hide.
A succubus named Naxqe'Isa dodges your futile attack.

< 286h/510H 144v/145V T: Mogole TC: few wounds E: naxqe'isa EC: nasty wounds EP: std P: std > 

You dodge a succubus named Naxqe'Isa's vicious attack.
A succubus named Naxqe'Isa brutally wounds you with her awesome pummel.
With an arcane motion of its hand, a succubus named Naxqe'Isa gates in someone!
A balor demon now follows a succubus named Naxqe'Isa.
A succubus named Naxqe'Isa dodges your futile attack.
Your mighty vampiric pierce barely wounds a succubus named Naxqe'Isa.
Your mighty vampiric pierce barely wounds a succubus named Naxqe'Isa.
You score a CRITICAL HIT!
Your massive vampiric pierce badly wounds a succubus named Naxqe'Isa.

< 259h/510H 145v/145V T: Mogole TC: few wounds E: naxqe'isa EC: pretty hurt EP: std P: std > 
shs
sneak;;hide;;tel katumi hidden

< 259h/510H 145v/145V T: Mogole TC: few wounds E: naxqe'isa EC: pretty hurt EP: std P: std >

You get an ethereal sack from a flattened bag of many layers.

< 259h/510H 145v/145V T: Mogole TC: few wounds E: naxqe'isa EC: pretty hurt EP: std P: std > 
You get a vial of Silvanus's blessing from an ethereal sack.

< 259h/510H 145v/145V T: Mogole TC: few wounds E: naxqe'isa EC: pretty hurt EP: std P: std >

As you quaff a vial of Silvanus's blessing, the vial disappears in a bright flash of light.
Your skin gains the texture and toughness of bark.
Bands of magic armor wrap around you!
You suddenly feel blessed!

< 259h/510H 145v/145V T: Mogole TC: few wounds E: naxqe'isa EC: pretty hurt EP: std P: std >

A balor demon critically wounds you with a massive slash!
OUCH!  That really did HURT!
You dodge a balor demon's vicious attack.
As a balor demon's whip lashes out, it grapples you, and it reels you into its bodily flames, where you are bathed in a column of unholy fire!
You lie on the ground, suffering from bleeding wounds.
A balor demon misses you with its slash.
A balor demon misses you with its slash.
A succubus named Naxqe'Isa misses you with her pummel.
A succubus named Naxqe'Isa misses you with her pummel.
Your attack only grazes a succubus named Naxqe'Isa as she dodges aside!
Your strong vampiric pierce barely wounds a succubus named Naxqe'Isa.
Your attack only grazes a succubus named Naxqe'Isa as she dodges aside!
Your strong vampiric pierce barely wounds a succubus named Naxqe'Isa.
Sorry, you aren't allowed to do that in combat.

< 162h/510H 145v/145V T: Mogole TC: nasty wounds E: naxqe'isa EC: pretty hurt EP: std P: std >

< 162h/510H 144v/145V P: std >

A Soft Turn in a Living Corridor
Exits: -N -S -W        [71074] 

< 162h/510H 144v/145V P: std >

Ok, you'll try to move silently for a while.

< 162h/510H 144v/145V P: std > 
You attempt to hide yourself.

< 162h/510H 145v/145V P: std > 
You tell Katumi 'hidden'

< 162h/510H 145v/145V P: std > 
< 162h/510H 145v/145V P: std > 
l n
The door is open.
The Lair of the Dark Temptress
Exits: -S
You see the red shape of a massive being here.
You see the red shape of a massive being here.

< 163h/510H 145v/145V P: std > 
n
               

The Lair of the Dark Temptress
Exits: -S              [71075]  [Hidden]
A thick pool of sticky blood covers the ground.
A living bed ripples as it moves every so often.
A mighty balor demon flaps its huge wings in fury.
A sultry succubus demon named Naxqe'Isa rolls about her bed playfully.

< 165h/510H 144v/145V P: std > 
l demon
A succubus named Naxqe'Isa speaks to you with telepathy, 'Come to me, my Love! and we can spend eternity together...
You now follow a succubus named Naxqe'Isa.
You are helpless under the wiles of a succubus named Naxqe'Isa.
This mighty balor is a terrifying, towering opponent.  It has dark red
skin, immediately distinguishing it from most of its tanar'ri brethren.
It also has extremely sharp, wicked claws and a maw filled with
grotesque fangs, each of which drips with venom.  Additionally, it
is surrounded by an everpresent wall of searing flames, making the
prospect of taking it on even less savory.
A balor demon is a massive-sized level 55 Tanar'ri.
It is in excellent condition.

<primary weapon>     A balor's sword of lightning
<secondary weapon>   a balor's vicious whip

You attempt to peek at the inventory:
You can't see anything.

< 167h/510H 145v/145V P: std > 
s
Your thoughts are too hazy, soley focused on this seductive creature.
You can do nothing but stand here and tend to her every whim..

< 172h/510H 145v/145V P: std > 
w
Your thoughts are too hazy, soley focused on this seductive creature.
You can do nothing but stand here and tend to her every whim..

< 172h/510H 145v/145V P: std > 
tel katumi hidden
You tell Katumi 'hidden'

< 225h/510H 145v/145V P: std > 

Autosaving...

< 237h/510H 145v/145V P: std > 
gcc should a succubus be able to charm you when you are hidden?  I am currently hidden, but also charmed....
Your thoughts are too hazy, soley focused on this seductive creature.
You can do nothing but stand here and tend to her every whim..

< 238h/510H 145v/145V P: std > 
status
Your thoughts are too hazy, soley focused on this seductive creature.
You can do nothing but stand here and tend to her every whim..

< 239h/510H 145v/145V P: std > 
nhc i can't gcc right now...but should a succubus be able to charm you when you are hidden?  or should I file a bug on that one?
Your thoughts are too hazy, soley focused on this seductive creature.
You can do nothing but stand here and tend to her every whim..

< 259h/510H 145v/145V P: std > 
tel boggoh rofl, i got charmed while hidden....seems like a bug to me...all i can do right now is send tells
You tell Boggoh 'rofl, i got charmed while hidden....seems like a bug to me...all i can do right now is send tells'

< 280h/510H 145v/145V P: std > 
tel boggoh i am still hidden, right?   obviously if you don't answer, then i am
You tell Boggoh 'i am still hidden, right?   obviously if you don't answer, then i am'

< 289h/510H 145v/145V P: std > 
tel boggoh or you are afk....but i will probably keep sending you tells, since there is nothing else i can do
You tell Boggoh 'or you are afk....but i will probably keep sending you tells, since there is nothing else i can do'

< 302h/510H 145v/145V P: std > 
tel boggoh can't  gcc or nhc either
You tell Boggoh 'can't  gcc or nhc either'

< 308h/510H 145v/145V P: std > 

Boggoh GCC: 'yes, mogole'

< 313h/510H 145v/145V P: std > 

A succubus named Naxqe'Isa embraces you and begins to kiss you passionately.
A succubus named Naxqe'Isa embraces you and begins to passionately kiss you. You can feel your life force ebbing away quickly, but you don't care...
You feel yourself falling to the ground.
Your soul leaves your body in the cold sleep of death...
               

You are dead!

Your soul is transported to The Fugue Plane as your crumbling body succumbs[Clearing memorized spells]

[Spellqueue cleared.]
to the cold sleep of death. Here in Kelemvor's realm all dead souls await
either judgement or escape from this timeless prison.

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

The Top of the Crystal Spire on the Fugue Plane
Exits: None!           [93848]  [Hidden]
A wispy smoke colored portal hovers just above the center of the room.
Vesser  (Yuan-Ti) stands here.

From here you may either re-enter the game by typing enter portal, or wait
to be resurrected by another player. Type help death for more information.

< 102h/510H 36v/145V P: std > 
enter portal

Your soul is instantly whisked away from the dreary Fugue Plane when you
enter the wispy smoke colored portal. You are enveloped by a warm yellow
glow as you hurtle with ever increasing speed down a brilliant white shaft
of light. You feel your physical flesh reforming around your battered soul
and your wounds healing in the life-giving radiance. With a flash of light
and pain, you streak down the final stretch of light and arrive back on the
Prime Material plane.

               

Darkest Shadows in the Thieves' Guild
Exits: -W              [93848]  [Hidden]
The almost invisible guildmaster chuckles at you, lurking in the dark shadows.

< 102h/510H 36v/145V P: std > 
gcc rofl:  A succubus named Naxqe'Isa embraces you and begins to passionately kiss you. You can feel your life force ebbing away quickly, but you don't care...
You feel yourself falling to the ground.
You GCC: 'rofl:  A succubus named Naxqe'Isa embraces you and begins to passionately kiss you. You can feel your life force ebbing away quickly, but you don't care...'

< 103h/410H 38v/145V P: std >

Pardon?

< 103h/410H 38v/145V P: std > 
gcc so....that seems like a bug though...i was actually hidden when i got charmed.....would you all agree that doesn't seem right?
You GCC: 'so....that seems like a bug though...i was actually hidden when i got charmed.....would you all agree that doesn't seem right?'

< 120h/410H 59v/145V P: std > 
hole me
tel Ynndchiarhlizz hole me
You tell Ynndchiarhlizz 'hole me'

< 122h/410H 62v/145V P: std > 
eh
enter hole
There is no hole here.

< 123h/410H 63v/145V P: std > 
sc

          Score information for Mogole

Level: 50   Race: Halfling   Class: Rogue       
Hit points: 126(410)  Moves: 67(145)
Experience Progress: 24 % 
Coins carried:   50 platinum   136 gold   148 silver    14 copper
Coins in bank:  842 platinum  3183 gold     7 silver    14 copper
Prestige: 5534   Acheron Kill Count: 0
Name status: Approved
Citizen of:   Beluir
Outcast from: Leuthilspar
Playing time: 7 days / 22 hours / 13 minutes
Title: 
Status:  Standing.
         Resurrection Fatigue
Detecting:       Heat
Enchantments:    No Summon

< 126h/410H 67v/145V P: std > 
jump
You stop trying to hide.
You jump high in the air.

< 129h/410H 71v/145V P: std > 
gcc an apparently i was still hidden after i died
You GCC: 'an apparently i was still hidden after i died'

< 135h/410H 80v/145V P: std > 
hole me
tel Ynndchiarhlizz hole me
You tell Ynndchiarhlizz 'hole me'

< 137h/410H 82v/145V P: std > 
The area darkens and the air shimmers slightly as a wormhole opens here.

**Comment by GeneralGormal** [comment]
It's an old, janky proc and has always worked this way. It's annoying enough that people used to roll female characters precisely to avoid the succubi on ethereal as we used it to move around pre-smoke/squidbots
