### ISSUE TITLE
Whirlwind Smite Typo

### ISSUE THREAD

**Issue by GeneralGormal** [torilmud/issues#861]
Brilliant holy light explodes around **Wobbap** as he swings his weapon in a full circle!
A warden archon is dealt a glancing blow by **your** full-circle smite!
A sword archon is dealt a glancing blow by **your** full-circle smite!
A sword archon is dealt a glancing blow by **your** full-circle smite!
A sword archon is struck by Wobbap's dazzling full-circle smite!
A warden archon is dealt a glancing blow by your full-circle smite!
A warden archon is struck by Wobbap's dazzling full-circle smite!
A sword archon is dealt a glancing blow by your full-circle smite!

**Comment by OghmaToril** [comment]
This is fixed and will be moved in with a future code move.
