### ISSUE TITLE
disconnection or black screen via "help duergar" in game

### ISSUE THREAD

**Issue by boglurker** [torilmud/issues#865]
Using either - h duergar  -& - help duergar - commands in game:

Both display half of what it should and blacks out the screen or cuts out emulation. had to restart client both tries. to confirm.

Only the background for the race is printed on screen the rest is black yet seems still connected to the mud. Strange.

**Comment by OghmaToril** [comment]
I'm not able to replicate this.  If you are using the default paging, there is a paging break that occurs during that particular helpfile.  Is this a paging issue?
