### ISSUE TITLE
Keprum Captain's Quest Room Crashing Mud

### ISSUE THREAD

**Issue by Faedril** [torilmud/issues#868]
A Vertical Magma Shaft With Super Heated Walls
  Near the top of the magma shaft the walls are slightly cooler than down
below and a slight breeze reaches in from the sky above. A thin ledge rings
the wall here allowing a stable place to stand instead of relying on magic
to keep you from falling hundreds of feet into the roiling pool of lava below.
In the western wall another crack pushes off the main shaft like below.
The entire area here feels densely packed with magic.

Either just standing in this room, or using "l room" in this room crashes the mud.  Not sure which.

**Comment by Faedril** [comment]
I think this might be linked to the room proc that moves you up the volcano.  I think the problem occurs when you are doing something... i.e. looking at room or fighting when the room proc goes off.

Just fighting the sinuous worms in the room below seems to have a high chance to cause a crash (its not 100 percent, but its high)

The Surface Of A Lava Pool
   The surface of this pool of lava roils and pops violently, steam pours from
everywhere and spirals its way up the throat of the volcano hundreds of feet
above. The lava itself spins and tosses you waves created from the churning
below you ripple across the surface and splash up the walls. The walls are
covered in black lava rock in various stages of hardening; those closest to
the surface of the pool still hot and soft. Periodically lava explodes out
from the pool and spirals its way up in a violent eruption.
Exits: - Up    - Down 
A sinuous worm weaves through the air here, blazing with flames.

(This is the room 1 up from:)

Under a Deep Pool of Lava
    Lava pools here after pouring in from the western tunnel and fills a huge
area at the bottom of the main vent in a volcano. Periodically bursts of magma
roar through the area and buoy you up towards the surface far above. The sides
of the pool are rounded and covered in recently deposited rock that glows with
warmth. The liquid contents of the room swirl violently and toss you about,
spinning you upside down and around dizzily.
Exits: - West  - Up   
A sinuous worm weaves through the air here, blazing with flames.
A sinuous worm weaves through the air here, blazing with flames.

**Comment by GeneralGormal** [comment]
A Vertical Magma Shaft With Super Heated Walls (No Ground)
Exits: -U -D
A sinuous worm weaves through the air here, blazing with flames.

< 1260h/1260H 269v/270V |ss +|ts +|ap +|ev +|bs 2| |1|2|3|3|0| P: std > You sweep attack a fire worm with unbound fury, knocking it off balance!

< 1260h/1260H 269v/270V |ss 3|ts +|ap +|ev +|bs 2| |1|2|3|3|0| T: Kaelas TC: excellent E: fire EC: few scratches EP: std P: std > 
A momentary brilliant glow originating from your circlet begins
a rapid change in your appearance. Countless serpents begin to uncoil,
slithering and sliding their way down and around your arms, neck,
and torso, granting you a reptilian quickstrike ability! Your eyes gleam
a vivid yellow as the brief enchantment begins to fade. Quickly as
they descended, the serpents twist and twine their way back to the magic
within their circlet.
Your massive slash barely wounds a fire worm.
You score a CRITICAL HIT!
Your massive slash slightly wounds a fire worm.
Your massive slash barely wounds a fire worm.
Your massive slash barely wounds a fire worm.
You score a CRITICAL HIT!
Your massive slash slightly wounds a fire worm.

< 1260h/1260H 269v/270V |ss 3|ts +|ap +|ev +|bs 2| |1|2|3|3|0| T: Kaelas TC: excellent E: fire EC: small wounds EP: std P: std > 
Your massive slash barely wounds a fire worm.
Your massive slash barely wounds a fire worm.
Your massive slash barely wounds a fire worm.
Your massive slash barely wounds a fire worm.
Your massive slash barely wounds a fire worm.
A fire worm misses you with its beat.

< 1260h/1260H 269v/270V |ss 3|ts +|ap +|ev +|bs 2| |1|2|3|3|0| T: Kaelas TC: excellent E: fire EC: small wounds EP: std P: std > ap

Connected to host torilmud.com

**Comment by GeneralGormal** [comment]
I had worms respawning in here that we've never seen happen. They got up over a dozen before crash.

**Comment by marthammor** [comment]
I think this is fixed?

**Comment by Faedril** [comment]
Yep
