### ISSUE TITLE
Room exit loops back to same room

### ISSUE THREAD

**Issue by EvaShark** [torilmud/issues#874]
In "Jumbled Mess of Streets"  in Beluir, the one with exits North, East and West since there are multiple, if you take the West exit you end up back in the exact same room.

**Comment by Lilithelle** [comment]
Looks like room number room 16222 west exit is to room 16222 when it should go to room 16221, n w s from that room gets you to 16221, and east from 16221 goes to 16222.

**Comment by marthammor** [comment]
Fairly sure this is intended. Its a jumbled mess of streets, after all. There are other jumbled room exits in there as well.
