### ISSUE TITLE
You cannot leave Unseelie

### ISSUE THREAD

**Issue by GeneralGormal** [torilmud/issues#883]
A Submerged Path Along Silver Waters (Water)
Exits: -E -S -W
A woman of ethereal beauty floats here, serenely.

< 820h/820H 254v/255V |vs +|ss +|sph +|md +|uf +|drs +|bc +|fr +|sot +|daa +| |3|3|3|3|2| P: std > A field of nearly invisible faerie magic blocks your way!

I'm told this is just waiting copyover, but kind of nutty that this zone has been in for years and you still can't walk back out.

**Comment by GeneralGormal** [comment]
okay the blockers weren't added at release, but it's still been like this a long time.  you can't hole/well/relocate out, the only way to leave is to camp or have a special item like CP jet orb, DT mask, etc.

**Comment by marthammor** [comment]
This was fixed on last update. If its still an issue, reopen a ticket please.
