### ISSUE TITLE
Scrolls are still consumed if you try to recite them on a target that doesn't exit

### ISSUE THREAD

**Issue by GeneralGormal** [torilmud/issues#889]
ou get a leafy sheet of sticky kelp from a portable hole.

< 1255h/1255H 270v/270V |ss +|ts +|ap +|ev +|bs +| |3|2|3|3|1| P: std > You don't see them here!

< 1255h/1255H 270v/270V |ss +|ts +|ap +|ev +|bs +| |3|2|3|3|1| P: std > recite kelp me
You do not have that item.

< 1255h/1255H 270v/270V |ss +|ts +|ap +|ev +|bs +| |3|2|3|3|1| P: std > inv
You are carrying:
a fine suit of remorhaz scale armor
a portable hole
a fine silk haversack stitched with platinum thread

< 1255h/1255H 270v/270V |ss +|ts +|ap +|ev +|bs +| |3|2|3|3|1| P: std > get kelp portable
recite kelp me
You get a leafy sheet of sticky kelp from a portable hole.

< 1255h/1255H 270v/270V |ss +|ts +|ap +|ev +|bs +| |3|2|3|3|1| P: std > You recite a leafy sheet of sticky kelp which turns to dust in your hands.
Your skin gains the texture and toughness of bark.
You have learned something new about spellcast nature!

**Comment by marthammor** [comment]
Fairly sure this was fixed recently, yes?

**Comment by shevarash** [comment]
This has been fixed.
