### ISSUE TITLE
Bodyslammed by mob not in room

### ISSUE THREAD

**Issue by GeneralGormal** [torilmud/issues#892]
A Dusty Clearing at the Tree Line
Exits: -N -S -W
[2] A painted arrow has been discarded here.

< 909h/909H 212v/270V |ss +|ts +|ap +|ev +|bs +| |3|3|3|3|2| P: std > get arrow
get arrow

A troll sniper lets out an enormous ROAR, and charges towards _YOU_!
a troll sniper sends you sprawling.
stand

< 855h/909H 213v/270V |ss +|ts +|ap +|ev +|bs +| |3|3|3|3|2| P: sit > 
@Lilithelle/Garru group-says 'the trolls don't DI, and the plants can't see in the dark'

< 858h/909H 218v/270V |ss +|ts +|ap +|ev +|bs +| |3|3|3|3|2| P: sit > 
l
A troll sniper lets out an enormous ROAR, and charges towards _YOU_!
a troll sniper sends you sprawling.
stand

< 811h/909H 222v/270V |ss +|ts +|ap +|ev +|bs +| |3|3|3|3|2| P: sit > 
@Lilithelle/Garru group-says 'so invis ultra race works well'

< 811h/909H 223v/270V |ss +|ts +|ap +|ev +|bs +| |3|3|3|3|2| P: sit > s

A troll sniper lets out an enormous ROAR, and charges towards _YOU_!
You nimbly avoid a powerful shield bash from a troll sniper!

< 818h/909H 231v/270V |ss +|ts +|ap +|ev +|bs +| |3|3|3|3|2| P: sit > 
a troll sniper's aimed shot  flies wild and misses you!

**Comment by shevarash** [comment]
This has been fixed. Thank you for the bug report.
