### ISSUE TITLE
Knockdown Shot and Concussive Shot have Inccorect hitroll bonus

### ISSUE THREAD

**Issue by GeneralGormal** [torilmud/issues#893]
The other bow powers are all hitroll 200% and these are easy to miss as a result.

Name             : Knockdown Shot [ks]
Type             : Melee                    
Attack Type      : Armor                    
Target           : Offense
Recharge         : 12 seconds 
Implements       : Bow
Restrictions     : Standing, Can See
To-Hit Mods      : Size Diff -10, Level Diff +1, Dex 25%, Hit Roll 100%

Effects:
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Target Effect    : Strike with all weapons for 200% (Weapon, Bow)     
Target Effect    : Change position to Prone                           
                   Restrictions: Ground, Immaterial, Size 3, Target Legs
                   Type Dragon immune
Target Effect    : --> Wait for 8 seconds                             
Miss Effect      : Strike with all weapons for 100% (Weapon, Bow)     

Name             : Concussive Shot [cn]
Type             : Melee                    
Attack Type      : Armor                    
Target           : Offense
Stacks           : Yes
Recharge         : 28 seconds 
Implements       : Bow
Restrictions     : Standing, Can See
To-Hit Mods      : Level Diff +1, Dex 25%, Hit Roll 100%

Effects:
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Target Effect    : Strike with all weapons for 300% (Weapon, Bow)     
Target Effect    : Add stun condition for 8 seconds                   
                   Restrictions: Immaterial, Dragon
Miss Effect      : Strike with all weapons for 100% (Weapon, Bow)

**Comment by shevarash** [comment]
This was fixed.
