### ISSUE TITLE
Necromancer: Wither / Energy Drain

### ISSUE THREAD

**Issue by Fisig** [torilmud/issues#895]
Wither -

Definition:
(1
: to become dry and sapless
especially : to shrivel from or as if from loss of bodily moisture
(2
: to lose vitality, force, or freshness

---In game:

help wither
WITHER
Spell.

Area of effect: <victim>
Aggressive:     Yes
Cumulative:     No
Duration:       Dependent on proficiency of caster
Class/Circle:   Necromancer 4th
Type of spell:  Enchantment   <--- ??

This spell increases the victim's effective armor class and drops
their movement for a period of time, making it easier to hit the
victim and harder for the victim to flee.

powers info wither

Name             : Wither [wt]
Type             : Spell                    
Attack Type      : Auto                     
Prepare          : Study                    
Target           : Offense, Character in room
Activation Time  : 3 seconds 
Related Skill    : spellcast enchantment   <--- ??

Effects:
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Target Effect    : Modify move by -50 for 2 minutes 42 seconds        
                   Save versus spell to avoid  
Target Effect    : --> Modify armor by 40 for 2 minutes 42 seconds    

   Does it really make sense to be an enchantment spell rather then a necromancy spell?

Energy Drain-

powers info Energy Drain

Name             : Energy Drain [ed]
Type             : Spell                    
Attack Type      : Auto                     
Prepare          : Study                    
Target           : Offense, Character in room
Activation Time  : 3 seconds 
Related Skill    : spellcast necromancy
Restrictions     : Autofire, Garrote, Standing, Can Speak

Effects:
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Target Effect    : Deal 5d10 negative damage                          Mod: +32% 
                   Save versus spell for 100%
Self Effect      : --> Vampiric heal 100% of preceding damage, up to 100% of max 

   Seems extreme "Save versus spell for 100%", it does first level damage/healing as a fifth level spell. As it currently is it is a complete waste of a spell slot to memorize this spell. Spells such as cause light/serious/crit have no save at all (Yes I know apples and oranges , but they are both round :P).

@Dagk

**Comment by shevarash** [comment]
You are right! These issues will be addressed in an upcoming Necromancer class overhaul.
