### ISSUE TITLE
Vampiric Touch

### ISSUE THREAD

**Issue by Fisig** [torilmud/issues#897]
h vampiric t
"VAMPIRIC TOUCH"
Spell.

Area of effect: Self
Aggressive:     N/A
Cumulative:     No
Duration:       Dependent on proficiency of caster
Class/Circle:   Necromancer 6th
Type of spell:  Generic

This spell temporarily turns your hands into magical lifeforce leeches.
If in battle and unarmed, your next attack will suck away your opponent's
life force, granting some of it to you.

powers info vampiric t

Name             : Vampiric Touch [vt]
Type             : Spell                    
Prepare          : Study                    
Target           : Self
Activation Time  : 6 seconds 
Related Skill    : spellcast necromancy
Restrictions     : Autofire, Garrote, Standing, Can Speak

Effects:
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Self Effect      : Add vampiric touch for 7 minutes 55 seconds  

This is a sixth level spell. In light of the plethora of other vampiric spells/abilities it would seem to be in need of a reevaluation.

@Dagk

**Comment by shevarash** [comment]
Agreed - see previous issue.
