### ISSUE TITLE
Ranged Shot is Too Strong for NPCS

### ISSUE THREAD

**Issue by GeneralGormal** [torilmud/issues#899]
They can spam this now and just destroy you.  in rooms that block, it's massive damage that didn't exist before.

Within the Praesidium of Ashstone
Exits: -S -W
Huge puddles of blood cover the ground.
[2] Corpse of a practicing warrior is lying here.
[17] A barbed arrow lies here
A practicing warrior is lying here.
A practicing warrior is lying here.
A practicing warrior is lying here.

< 251h/1081H 122v/270V |ss +|ts +|ap 2|ev +|bs +| |1|0|3|1|0| P: std > You attack a practicing warrior with both weapons, landing twin precision strikes.
Tendrils of acidic greenfire leap from your weapon!
Tendrils of acidic greenfire leap from your weapon!

< 251h/1081H 123v/270V |ss +|ts 3|ap 1|ev +|bs +| |1|0|3|1|0| T: Kaelas TC: pretty hurt E: warrior EC: pretty hurt EP: rcl P: std > A practicing warrior's carefully aimed shot from the south hits you!

< 231h/1081H 124v/270V |ss +|ts 3|ap 1|ev +|bs +| |1|0|3|1|0| T: Kaelas TC: pretty hurt E: warrior EC: pretty hurt EP: rcl P: std > A practicing warrior misses you with his slash.
A practicing warrior misses you with his slash.
A practicing warrior staggers about, but manages to get to his feet.
A practicing warrior blocks your futile attempt with his shield!
Your attack only grazes a practicing warrior as he dodges aside!
Your mighty greenfire slash slightly wounds a practicing warrior.
A practicing warrior blocks your futile attempt with his shield!

< 231h/1081H 124v/270V |ss +|ts 3|ap 1|ev +|bs +| |1|0|3|1|0| T: Kaelas TC: pretty hurt E: warrior EC: pretty hurt EP: std P: std > 
A practicing warrior's carefully aimed shot from the south hits you!

< 215h/1081H 124v/270V |ss +|ts 3|ap 1|ev +|bs +| |1|0|3|1|0| T: Kaelas TC: pretty hurt E: warrior EC: pretty hurt EP: std P: std > 
A practicing warrior's senses seem to clear again!

< 215h/1081H 125v/270V |ss +|ts 3|ap 1|ev +|bs +| |1|0|3|1|0| T: Kaelas TC: pretty hurt E: warrior EC: pretty hurt EP: std P: std > fle
A practicing warrior grits his teeth and viciously headbutts YOU in the face!
YIKES!  Another hit like that, and you've had it!!
You wish that your wounds would stop BLEEDING so much!

You're too busy trying to gain the initiative to flee!

< 4h/1081H 125v/270V |ss +|ts 3|ap 1|ev +|bs +| |1|0|3|1|0| T: Kaelas TC: awful E: warrior EC: pretty hurt EP: std P: std > 
a practicing warrior's aimed shot from the south flies wild and misses you!
A momentary brilliant glow originating from your circlet begins
a rapid change in your appearance. Countless serpents begin to uncoil,
slithering and sliding their way down and around your arms, neck,
and torso, granting you a reptilian quickstrike ability! Your eyes gleam
a vivid yellow as the brief enchantment begins to fade. Quickly as
they descended, the serpents twist and twine their way back to the magic
within their circlet.
A practicing warrior parries your futile lunge at him.
A practicing warrior blocks your futile attempt with his shield!
Your massive greenfire slash severely wounds a practicing warrior.
A practicing warrior blocks your futile attempt with his shield!

< 4h/1081H 126v/270V |ss +|ts 3|ap 1|ev +|bs +| |1|0|3|1|0| T: Kaelas TC: awful E: warrior EC: awful EP: std P: std > fle
You're too busy trying to gain the initiative to flee!

< 4h/1081H 126v/270V |ss +|ts 2|ap 1|ev +|bs +| |1|0|3|1|0| T: Kaelas TC: awful E: warrior EC: awful EP: std P: std > 
a practicing warrior's careful precision shot from the south dispatches you in one strike!
With a final blow, you feel yourself falling to the ground.
Your soul leaves your body in the cold sleep of death...

**Comment by GeneralGormal** [comment]
I am blurred, CLR'd, -131 AC in this log, otherwise i'd be instantly dead.

**Comment by theofficejackpot** [comment]
just observing, but it seems the headbutt did all the damage, not ranged shots?  I do think BLUR should protect more from ranged shots though !


you went from 231hp to 215hp with the ranged shot..

< 231h/1081H 124v/270V |ss +|ts 3|ap 1|ev +|bs +| |1|0|3|1|0| T: Kaelas TC: pretty hurt E: warrior EC: pretty hurt EP: std P: std >
A practicing warrior's carefully aimed shot from the south hits you!

< 215h/1081H 124v/270V |ss +|ts 3|ap 1|ev +|bs +| |1|0|3|1|0| T: Kaelas TC: pretty hurt E: warrior EC: pretty hurt EP: std P: std >


then you went from 215HP to 4hp from the headbutt

< 215h/1081H 125v/270V |ss +|ts 3|ap 1|ev +|bs +| |1|0|3|1|0| T: Kaelas TC: pretty hurt E: warrior EC: pretty hurt EP: std P: std > fle
**A practicing warrior grits his teeth and viciously headbutts YOU in the face!
YIKES! Another hit like that, and you've had it!!
You wish that your wounds would stop BLEEDING so much!**

You're too busy trying to gain the initiative to flee!

< 4h/1081H 125v/270V |ss +|ts 3|ap 1|ev +|bs +| |1|0|3|1|0| T: Kaelas TC: awful E: warrior EC: pretty hurt EP: std P: std >

**Comment by shevarash** [comment]
It does appear that the majority of the damage here came from the headbutt, not the ranged shot. Ranged Shot has no damage modifier - it's 100% of the attack, so it's just the standard weapon dice plus mob dam roll. I'm closing this, but if I'm in the wrong here or you have other examples please re-open with details.
```

Name             : Ranged Shot [rs]
Type             : Melee                    
Attack Type      : Armor                    
Target           : Offense, Character in adjacent room
Implements       : Bow
To-Hit Mods      : Level Diff +1, Dex 25%, Hit Roll 200%

Effects:
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Effect           : Strike with implement for 100% (Primary Weapon)    

```

**Comment by GeneralGormal** [comment]
I'm aware that headbutt does more damage, but 20 hp hit  through 75% damage reduction and blur that they can use almost every round translates to 100+ per hit.  If you move into range of a group of archers, they can just one-shot you.
