### ISSUE TITLE
Aggro persisting after death

### ISSUE THREAD

**Issue by xanza-tey** [torilmud/issues#900]
So, was running out from Silverymoon to check on some rare loads. Ran through gate guards without sneak on, and got engaged by guards. Spellguards heard combat and entered, AoE 1 shot me on fireshield (troll, wasn't wearing fire res). 

I entered from fugue and wormed back to the Inn, and was afking a second to heal up and let ress sickness drop, and the spellguards tracked me from the gate, to the inn. 

This is not the first time that spellcasters in particular have done this. I've died trying to solo some stuff (usually same thing, shields just destroy me), and when I've returned to the zone, I've had the caster dim to me and try and continue fighting after I've died and should have cleared aggro. (this was on air plane the last time it happened)

Log is below, hope this helps.

**************************************************************************************************

< 750h/794H 169v/180V |bds +|nop +|cv +|cc +|ub +|ss +|ut +|sk +|hd +|vip +|ua +|dsd 14|wu +|ros +|sod 13| T: Teywuggi TC: few scratches E: soldier EC: few scratches EP: rcl P: std
> 
You scan north...
Northwatch Tower
Exits: -S

You scan east...
Approaching Silverymoon's Sundabar Gate
Exits: -N -W
You see the red shape of a medium being here.

You scan south...
Southwatch Tower
Exits: -N
A mage of the Spellguard stands here observing.

You scan west...
Before the Sundabar Gate
Exits: -N -E -S -W
A robin searches for food here.
A half-elven forester moves through town.
A human merchant from Waterdeep is here selling.
A grey squirrel sniffs the air cautiously.

< 751h/794H 169v/180V |bds +|nop +|cv +|cc +|ub +|ss +|ut +|sk +|hd +|vip +|ua +|dsd 14|wu +|ros +|sod 13| T: Teywuggi TC: few scratches E: soldier EC: few scratches EP: rcl P: std
>

[MELEE: Skullcrusher] SK
You raise your weapon high and bring it crashing down on a soldier of the Knights in Silver's head with a sickening crack.
A soldier of the Knights in Silver is stunned!

< 752h/794H 170v/180V |bds +|nop +|cv +|cc +|ub +|ss +|ut +|sk 3|hd +|vip +|ua +|dsd 14|wu +|ros +|sod 13| T: Teywuggi TC: few scratches E: soldier EC: small wounds EP: rcl P: std
> 

A mage in the Spellguard flies in from the east.

< 753h/794H 171v/180V |bds +|nop +|cv +|cc +|ub +|ss +|ut +|sk 3|hd +|vip +|ua +|dsd 14|wu +|ros +|sod 13| T: Teywuggi TC: few scratches E: soldier EC: small wounds EP: rcl P: std
> 

You partially deflect a mage in the Spellguard's lunge at you.
A mage in the Spellguard barely wounds you with her average hit.

< 746h/794H 172v/180V |bds +|nop +|cv +|cc +|ub +|ss +|ut +|sk 3|hd +|vip +|ua +|dsd 14|wu +|ros +|sod 13| T: Teywuggi TC: few scratches E: soldier EC: small wounds EP: rcl P: std
> 

A mage in the Spellguard flies in from the south.

< 747h/794H 172v/180V |bds +|nop +|cv +|cc +|ub +|ss +|ut +|sk 3|hd +|vip +|ua +|dsd 14|wu +|ros +|sod 13| T: Teywuggi TC: few scratches E: soldier EC: small wounds EP: rcl P: std
> 
A mage in the Spellguard misses you with her hit.

< 747h/794H 172v/180V |bds +|nop +|cv +|cc +|ub +|ss +|ut +|sk 3|hd +|vip +|ua +|dsd 14|wu +|ros +|sod 13| T: Teywuggi TC: few scratches E: soldier EC: small wounds EP: rcl P: std
> 
You deflect a mage in the Spellguard's blow, and strike back at a mage in the Spellguard!
Your weak vampiric flaming slash barely wounds a mage in the Spellguard.
You are burned as you hit a mage in the Spellguard!
You deflect a mage in the Spellguard's blow, and strike back at a mage in the Spellguard!
Your weak vampiric flaming slash barely wounds a mage in the Spellguard.
You are burned as you hit a mage in the Spellguard!
A mage in the Spellguard misses you with her hit.
A mage in the Spellguard misses you with her hit.
Your massive vampiric flaming slash badly wounds a soldier of the Knights in Silver.
Your massive vampiric flaming slash badly wounds a soldier of the Knights in Silver.
Your massive vampiric flaming slash badly wounds a soldier of the Knights in Silver.
You partially deflect a soldier of the Knights in Silver's lunge at you.
A soldier of the Knights in Silver barely wounds you with his average slash.
You parry a soldier of the Knights in Silver's lunge at you.
A soldier of the Knights in Silver misses you with his slash.
A soldier of the Knights in Silver misses you with his slash.
You parry a soldier of the Knights in Silver's lunge at you.
A soldier of the Knights in Silver misses you with his slash.
You partially deflect a soldier of the Knights in Silver's lunge at you.
A soldier of the Knights in Silver barely wounds you with his average slash.
A soldier of the Knights in Silver misses you with his slash.
A soldier of the Knights in Silver misses you with his slash.

< 755h/794H 173v/180V |bds +|nop +|cv +|cc +|ub +|ss +|ut +|sk 3|hd +|vip +|ua +|dsd 14|wu +|ros +|sod 13| T: Teywuggi TC: few scratches E: soldier EC: few wounds EP: rcl P: std > 

Auction: Mixamilon bid 20,500 platinum on item 105819 a darkened black steel longsword

< 757h/794H 173v/180V |bds +|nop +|cv +|cc +|ub +|ss +|ut +|sk 3|hd +|vip +|ua +|dsd 14|wu +|ros +|sod 13| T: Teywuggi TC: few scratches E: soldier EC: few wounds EP: rcl P: std >

[MELEE: Unyielding Avalanche] UA
e

[Currently moving. Spellcasting is temporarily paused.]

You crash forward into your foes and strike out with a barrage of attacks.
You drive a soldier of the Knights in Silver back, exhausting him with a flurry of rapid strikes.
A soldier of the Knights in Silver begins to slow down.
You drive a soldier of the Knights in Silver back, exhausting him with a flurry of rapid strikes.
A soldier of the Knights in Silver begins to slow down.
You drive a soldier of the Knights in Silver back, exhausting him with a flurry of rapid strikes.
A soldier of the Knights in Silver begins to slow down.
You drive a mage in the Spellguard back, exhausting her with a flurry of rapid strikes.
You are burned as you hit a mage in the Spellguard!
YIKES!  Another hit like that, and you've had it!!
A mage in the Spellguard begins to slow down.
You drive a mage in the Spellguard back, exhausting her with a flurry of rapid strikes.
PHEW! Wasn't that hot experience - aura around a mage in the Spellguard _fries_ you!
With a final blow, you feel yourself falling to the ground.
Your soul leaves your body in the cold sleep of death...

You are dead!

Your soul is transported to The Fugue Plane as your crumbling body succumbs[Clearing memorized spells]

[Spellqueue cleared.]
to the cold sleep of death. Here in Kelemvor's realm all dead souls await
either judgement or escape from this timeless prison.

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

The Top of the Crystal Spire on the Fugue Plane
   This large, circular chamber looks out high over the featureless grey
landscape of the Fugue Plane, where dead souls come to await judgement. The
walls are made of clear, transparent crystal and appear featureless and
smooth to the touch. A polished obsidian bench runs the length of the room's
curved walls. Tiny crystal globes ensconced high along the walls emit a soft
white light, which reveals little in this featureless waiting room. Down
below, other disembodied souls can be seen traversing the bleak landscape.
This chamber appears to be reserved for those souls that are favored by a
member of the pantheon. There do not appear to be any exits from this
chamber.
Exits: None!
A wispy smoke colored portal hovers just above the center of the room.

From here you may either re-enter the game by typing enter portal, or wait
to be resurrected by another player. Type help death for more information.

e
< 123h/494H 45v/180V |bds +|nop +|cv +|cc +|ub +|ss +|ut +|sk 1|hd +|vip +|ua 7|dsd 13|wu +|ros +|sod 12| P: std >

You can't do that on the Fugue Plane.
e

< 124h/794H 46v/180V |bds +|nop +|cv +|cc +|ub +|ss +|ut +|sk 1|hd +|vip +|ua 7|dsd 13|wu +|ros +|sod 12| P: std >

You can't do that on the Fugue Plane.

< 124h/794H 46v/180V |bds +|nop +|cv +|cc +|ub +|ss +|ut +|sk 1|hd +|vip +|ua 7|dsd 13|wu +|ros +|sod 12| P: std >

You can't do that on the Fugue Plane.

< 124h/794H 46v/180V |bds +|nop +|cv +|cc +|ub +|ss +|ut +|sk 1|hd +|vip +|ua 7|dsd 13|wu +|ros +|sod 12| P: std > 
enter portal

Your soul is instantly whisked away from the dreary Fugue Plane when you
enter the wispy smoke colored portal. You are enveloped by a warm yellow
glow as you hurtle with ever increasing speed down a brilliant white shaft
of light. You feel your physical flesh reforming around your battered soul
and your wounds healing in the life-giving radiance. With a flash of light
and pain, you streak down the final stretch of light and arrive back on the
Prime Material plane.

The Chamber of Combat Practice
   This is a large chamber, with weapons of various kinds lining the walls. The
center of the room has been left bare, blood stains cover the entire floor. The
smell of sweat and blood is almost overpowering here. The only exit is south.
Exits: - South#
Crunch, guildmaster of the warriors, stands here ready to train you.
A large troll warrior stands here spouting insults.
A large troll warrior stands here spouting insults.

< 123h/794H 45v/180V |bds +|nop +|cv +|cc +|ub +|ss +|ut +|sk +|hd +|vip +|ua 5|dsd 11|wu +|ros +|sod 10| P: std > 

< 124h/744H 45v/180V |bds +|nop +|cv +|cc +|ub +|ss +|ut +|sk +|hd +|vip +|ua 4|dsd 10|wu +|ros +|sod 9| P: std > 
tell ynndchiarhlizz worm me
You tell Ynndchiarhlizz 'worm me'

< 142h/744H 53v/180V |bds +|nop +|cv +|cc +|ub +|ss +|ut +|sk +|hd +|vip +|ua 2|dsd 8|wu +|ros +|sod 7| P: std > 
eq
The area darkens and the air shimmers slightly as a wormhole opens here.

< 142h/744H 53v/180V |bds +|nop +|cv +|cc +|ub +|ss +|ut +|sk +|hd +|vip +|ua 2|dsd 8|wu +|ros +|sod 7| P: std >

You are using:
<worn as a badge>    < the screaming hawk insignia of Keprum's army > (illuminating) (damaged)
<worn on head>       the mystical circlet of the coiled serpent (magic) (damaged)
<worn on eyes>       a rune etched dragonscale of incarnadine hue (magic) (damaged)
<worn in ear>        a tiny earring of congealed blood (magic) (damaged)
<worn in ear>        a tiny earring of congealed blood (magic) (damaged)
<worn on face>       a mask of black ice (magic) (damaged)
<worn around neck>   a spiked iron choker (damaged)
<worn around neck>   a thick titanium band of volance (magic) (damaged)
<worn on body>       a lightweight suit of linked mail body armor (damaged)
<worn about body>    a blued steel pauldron (damaged)
<worn as quiver>     an ancient tooled dragonhide quiver (magic) (damaged)
<worn about waist>   a sturdy belt lined with minotaur skulls (damaged)
<worn on arms>       some blood-splattered sleeves of sewn flesh (magic) (damaged)
<worn around wrist>  a chainmail vambrace studded with rubies (magic) (damaged)
<worn around wrist>  a chainmail vambrace studded with rubies (magic) (damaged)
<worn on hands>      a pair of gauntlets wreathed in electricity (magic) (glowing) (damaged)
<worn on finger>     a beautifully enscribed turquoise ring (magic) (damaged)
<worn on finger>     a loop of blood-red cord (damaged)
<wielding twohanded> a crimson-edged obsidian blade (magic) (damaged)
<worn on legs>       a pair of djinn battle greaves (magic) (damaged)
<worn on feet>       a pair of taut red leather boots with adamantine buckles (magic) (damaged)

< 143h/744H 53v/180V |bds +|nop +|cv +|cc +|ub +|ss +|ut +|sk +|hd +|vip +|ua 2|dsd 8|wu +|ros +|sod 7| P: std > 
get boots bag
You get the mystical boots of the traveler from a gigantic bag of shimmering silk strands.

< 146h/744H 55v/180V |bds +|nop +|cv +|cc +|ub +|ss +|ut +|sk +|hd +|vip +|ua 1|dsd 6|wu +|ros +|sod 5| P: std > 
l
The Chamber of Combat Practice (Shadowed)
Exits: - South#
A gaping hole in the ground leads into darkness. (magic)
Crunch, guildmaster of the warriors, stands here ready to train you.
A large troll warrior stands here spouting insults.
A large troll warrior stands here spouting insults.

< 148h/744H 55v/180V |bds +|nop +|cv +|cc +|ub +|ss +|ut +|sk +|hd +|vip +|ua 1|dsd 6|wu +|ros +|sod 5| P: std > 
enter worm
You enter something and reappear elsewhere...

Wayward House Inn (Shadowed)
   This elegant wood building has been constructed on the stone
foundation of the Inn of Wayward Sages.  Charring can still be seen on
the stone from when the original building burned down.  Originally an
inn with less then reputable clientele the inn has become more classy
with a well stocked wine cellar.  A number of tables and chairs lie
about the room casually and a long oak counter fills one end of the
room.
Exits: - North - Up   
A gaping hole in the ground leads into darkness. (magic)
A simple wooden box sits here.
Corpse of Tiamat is lying here. (magic)
Nanyk  (Drow Elf) stands in mid-air here.
Herple  (Halfling) stands here.
Nyyrazzilyss - Head Jailer of the Valkurian Blades (AFK) (Illithid) sits resting.
A dapper noble is here socializing.
Ynndchiarhlizz - The Nexus (Illithid) sits resting.
Havorr Merendil stands behind the counter ready to serve.
A showy merchant sits here looking smug.
A showy merchant sits here looking smug.
A showy merchant sits here looking smug.
A dapper noble is here socializing.
A dapper noble is here socializing.

< 151h/744H 57v/180V |bds +|nop +|cv +|cc +|ub +|ss +|ut +|sk +|hd +|vip +|ua 1|dsd 6|wu +|ros +|sod 5| P: std > 

[Searching... Match found: Silverymoon, Gem of the North : Wayward House Inn : 48603]
repair all
You spent 32 platinum, and 4 silver coins to repair all of your items.

< 155h/744H 59v/180V |bds +|nop +|cv +|cc +|ub +|ss +|ut +|sk +|hd +|vip +|ua +|dsd 6|wu +|ros +|sod 5| P: std > 
Nanyk flies up.

< 156h/744H 59v/180V |bds +|nop +|cv +|cc +|ub +|ss +|ut +|sk +|hd +|vip +|ua +|dsd 6|wu +|ros +|sod 5| P: std > 
inv
You are carrying:
the mystical boots of the traveler (magic) (glowing)
a heavy tankard made of pewter (illuminating)
a gigantic bag of shimmering silk strands

< 157h/744H 60v/180V |bds +|nop +|cv +|cc +|ub +|ss +|ut +|sk +|hd +|vip +|ua +|dsd 6|wu +|ros +|sod 5| P: std > 
rem boots
You stop using a pair of taut red leather boots with adamantine buckles.

< 160h/744H 61v/180V |bds +|nop +|cv +|cc +|ub +|ss +|ut +|sk +|hd +|vip +|ua +|dsd 5|wu +|ros +|sod 4| P: std > 

The area darkens and the air shimmers slightly as a wormhole opens before Ynndchiarhlizz.

< 162h/744H 62v/180V |bds +|nop +|cv +|cc +|ub +|ss +|ut +|sk +|hd +|vip +|ua +|dsd 5|wu +|ros +|sod 4| P: std > 
wear traveler
You place the mystical boots of the traveler on your feet.

< 165h/744H 64v/180V |bds +|nop +|cv +|cc +|ub +|ss +|ut +|sk +|hd +|vip +|ua +|dsd 4|wu +|ros +|sod 3| P: std > 
ut
You grit your teeth and ignore some of your wounds as your adrenaline surges.

< 268h/744H 65v/280V |bds +|nop +|cv +|cc +|ub +|ss +|ut 15|sk +|hd +|vip +|ua +|dsd 3|wu +|ros +|sod 2| P: std > 

A wormhole suddenly pulses rhythmically!
Siyooni enters a wormhole and disappears among the darkness.

< 271h/744H 66v/280V |bds +|nop +|cv +|cc +|ub +|ss +|ut 15|sk +|hd +|vip +|ua +|dsd 3|wu +|ros +|sod 2| P: std > 

A mage in the Spellguard flies in from the north.

< 285h/744H 72v/280V |bds +|nop +|cv +|cc +|ub +|ss +|ut 12|sk +|hd +|vip +|ua +|dsd 1|wu +|ros +|sod +| P: std > 
Smoke begins to pour out of Nyyrazzilyss's bracer, swirling around you in a dizzying
pattern.  Tiny sparks of dark lightning begin to flash in amongst the black
eddies, briefly bringing illumination to the cloud.  The hollow keening of
an abyssal melody briefly fills the area, as a dark portal begins to form
of smoke and shadow.  A figure steps through the portal, and the swirling
smoke dissipates rapidly.

< 285h/744H 73v/280V |bds +|nop +|cv +|cc +|ub +|ss +|ut 12|sk +|hd +|vip +|ua +|dsd 1|wu +|ros +|sod +| P: std > 
Nyyrazzilyss gives a gray slaad an order.
A gray slaad sends a mage in the Spellguard sprawling with a powerful bash.
A mage in the Spellguard snaps into visibility.
A gray slaad is burned severely as it hits a mage in the Spellguard!

< 285h/744H 73v/280V |bds +|nop +|cv +|cc +|ub +|ss +|ut 12|sk +|hd +|vip +|ua +|dsd 1|wu +|ros +|sod +| P: std > 

Nyyrazzilyss pauses and concentrates deeply as it focuses the powers of its mind.
The three unusual stones of a set of gem studded tentacle rings glow
as Nyyrazzilyss's body ripples and vibrates, warping into fractal images of itself.
Several mirror images of Nyyrazzilyss pop into existence at its side!

< 290h/744H 74v/280V |bds +|nop +|cv +|cc +|ub +|ss +|ut 11|sk +|hd +|vip +|ua +|dsd +|wu +|ros +|sod +| P: std > 
Nyyrazzilyss says 'Protect me'

< 290h/744H 74v/280V |bds +|nop +|cv +|cc +|ub +|ss +|ut 11|sk +|hd +|vip +|ua +|dsd +|wu +|ros +|sod +| P: std > 
You suddenly feel a strong energy shockwave!
Originating from Nyyrazzilyss!
a dapper noble is dead! R.I.P.
Your blood freezes as you hear the rattling death cry of a dapper noble.
an opulent merchant is dead! R.I.P.
Your blood freezes as you hear the rattling death cry of an opulent merchant.
An opulent merchant is outside of the area of the blast!
a dapper noble is dead! R.I.P.
Your blood freezes as you hear the rattling death cry of a dapper noble.
a dapper noble is dead! R.I.P.
Your blood freezes as you hear the rattling death cry of a dapper noble.

< 290h/744H 75v/280V |bds +|nop +|cv +|cc +|ub +|ss +|ut 11|sk +|hd +|vip +|ua +|dsd +|wu +|ros +|sod +| P: std > 

An opulent merchant misses Nyyrazzilyss with his hit.
An opulent merchant misses Nyyrazzilyss with his hit.
A mage in the Spellguard barely wounds a gray slaad with her strong hit.
A mage in the Spellguard barely wounds a gray slaad with her average hit.
A gray slaad barely wounds a mage in the Spellguard with its weak strike.
A gray slaad is burned severely as it hits a mage in the Spellguard!

< 292h/744H 76v/280V |bds +|nop +|cv +|cc +|ub +|ss +|ut 11|sk +|hd +|vip +|ua +|dsd +|wu +|ros +|sod +| P: std > 

Nyyrazzilyss badly wounds an opulent merchant with its weak hit.
An opulent merchant misses Nyyrazzilyss with his hit.
A mage in the Spellguard barely wounds a gray slaad with her strong hit.
A mage in the Spellguard barely wounds a gray slaad with her strong hit.
A gray slaad barely wounds a mage in the Spellguard with its weak strike.
A gray slaad is burned severely as it hits a mage in the Spellguard!
A gray slaad barely wounds a mage in the Spellguard with its weak strike.
A gray slaad is burned severely as it hits a mage in the Spellguard!

< 292h/744H 79v/280V |bds +|nop +|cv +|cc +|ub +|ss +|ut 10|sk +|hd +|vip +|ua +|dsd +|wu +|ros +|sod +| P: std > 

You suddenly feel a strong energy shockwave!
Originating from Nyyrazzilyss!
an opulent merchant is dead! R.I.P.
Your blood freezes as you hear the rattling death cry of an opulent merchant.

< 292h/744H 81v/280V |bds +|nop +|cv +|cc +|ub +|ss +|ut 9|sk +|hd +|vip +|ua +|dsd +|wu +|ros +|sod +| P: std > 

An opulent merchant misses Nyyrazzilyss with his hit.
A mage in the Spellguard barely wounds a gray slaad with her strong hit.
A mage in the Spellguard barely wounds a gray slaad with her powerful hit.
A mage in the Spellguard clambers to her feet.
A gray slaad slightly wounds a mage in the Spellguard with its powerful strike.
A gray slaad is burned severely as it hits a mage in the Spellguard!
A gray slaad slightly wounds a mage in the Spellguard with its strong strike.
A gray slaad is burned severely as it hits a mage in the Spellguard!

< 292h/744H 82v/280V |bds +|nop +|cv +|cc +|ub +|ss +|ut 9|sk +|hd +|vip +|ua +|dsd +|wu +|ros +|sod +| P: std > 

A mage in the Spellguard flies in from the north.

< 292h/744H 83v/280V |bds +|nop +|cv +|cc +|ub +|ss +|ut 9|sk +|hd +|vip +|ua +|dsd +|wu +|ros +|sod +| P: std >

**Comment by Dartan82** [comment]
fireshield death keeping aggro on players has been in so long it is a feature.  Closing issue.

**Comment by shevarash** [comment]
Thank you for the log.

I took another look at the code and found some fairly big errors that I fixed. Due to the nature of this bug it's hard to see if it for _sure_ is all fixed, but I'm pretty confident it will be better now. If it happens again please make a new issue with another log. Thank you again.

These fixes are in the game now, see the patch notes.
