### ISSUE TITLE
New Character Creation Drow Edition... lol

### ISSUE THREAD

**Issue by i982** [torilmud/issues#919]
Entering new character generation mode.
Race selection - Please choose one of the following for your character.
-----------------------------------------------------------------------
a) Human *        (A for help)     i) Ogre            (I for help)
b) Barbarian *    (B for help)     j) Swamp Troll     (J for help)
c) Drow Elf       (C for help)     k) Half Elf        (K for help)
d) Moon Elf       (D for help)     p) Illithid        (P for help)
e) Shield Dwarf*  (E for help)     q) Yuan-Ti         (Q for help)
f) Duergar Dwarf  (F for help)     r) Orc             (R for help)
g) Halfling       (G for help)     s) Half-Orc        (S for help)
h) Gnome          (H for help)

1) General listing of classes available to each race, and other info.
9) Return to login

       (HELP) Use the capital letter of the Race you want help on.
              For Help on Classes, type '1' for general information.

NOTE: If you are new to Toril, or MUDding in general, we suggest
      you begin the game with on of the races marked by a (*) above:
      Human, Barbarian, or Shield Dwarf.

Your selection?
c
Class selection menu
--------------------
a) Warrior
e) Blackguard
f) Cleric
j) Sorcerer
k) Necromancer
r) Enchanter
s) Invoker
v) Illusionist
u) Rogue
w) Hexblade

z) Return to the Race selection menu and re-choose your race and/or
   get more information

Your Selection: 
j

Alignment Selection
-------------------------------------------------------------------------------

Your race/class combination allows you to choose your initial alignment.
Alignment affects the objects you are able to use, creatures which are
aggressive towards you, spells you are vulnerable to, and more.  Your alignment
is fixed initially, however there are means available to allow you to shift
along the two different axis of alignment.

Please select one of the following starting alignments by entering the
first letter of the alignment.  Pick first among Lawful, Neutral and
Chaotic.  Then you will be prompted to select Good, Neutral or Evil.

Please note: Certain races and classes are predispositioned towards
some alignments, and in fact cannot be anything but.  Paladins will
be set to be Lawful Good.  Druids must have the second axis of their
alignment be Neutral.  In the cases of the above, and races with a
predisposition, you will not be prompted to select Good, Neutral or Evil.

If you are uncertain, we recommend you choose N.

L)awful
N)eutral
C)haotic

Your selection: 
c

Hometown Selection
-------------------------------------------------------------------------------
Humans and half-elves are permitted to choose among several towns as their
hometown. Note that the other races have separate hometowns that are not
listed here.

1. Waterdeep - Largest city on the Faerunian continent and the primary home
   of humans. Waterdeep is located on northern west coast of the mainland.

2. Calimport - Southernmost city on the continent, surrounded by desert
   to the north and east, and ocean to the south and west.

3. Leuthilspar - Located on the island of Evermeet and the home of the grey
   elves. Evermeet is isolated from the main continent by a large ocean.

4. Baldur's Gate - Located near the the west coast, Baldur's is a hangout
   for disreputable beings and is frequented by cutthroats and thieves.

5. Silverymoon - Located northeast of Waterdeep, Silverymoon is the largest
   city in the northlands of Toril.  With its rich commercial and artistic
   communities it is truly the Gem of the North.

Please choose among:

Your selection: 
3
That is not a valid hometown for you.  Please select again.

Hometown: 

tired leuthilspar first.. then became very sad that i couldnt be a drow from leuth... woulda rubbed that in Nians face til the end of time... lol

**Comment by shevarash** [comment]
Fixed!
