### ISSUE TITLE
Wild Magic Bugs

### ISSUE THREAD

**Issue by GeneralGormal** [torilmud/issues#930]
TOP consumes twinspell but can't twin it because it would cost 6cp.
If you twinspell an empowered chaos bolt, it doesn't twin the missiles, you get 2 regular chaos bolts.
Wild Magic healing is super weak a lower levels
unicorns need fly and water breath, but also I dunno what these are supposed to do.  Maybe let them cast cure light wounds or something? Give them a proc that can do things because at their level they can't hit anything.
Color change in prompt bar for chaos infusion lingers after you use it up.
Any spell that grants an infusion cannot do so if it gets the killing blow.

More later, but these are just some obvious ones I found.

**Comment by GeneralGormal** [comment]
PSH consumes chaos infusion.

**Comment by GeneralGormal** [comment]
Wild Magic prismatic infusion kind sucks solo, would be nice if it let you use either PE or PS.

**Comment by GeneralGormal** [comment]
When you get a prismatic infusion, it looks like it resets PE, but it's not ready:

![prismatic infusion](https://user-images.githubusercontent.com/38932922/231940848-4686654b-5822-42ec-a7fd-e56917766bf1.png)

**Comment by GeneralGormal** [comment]
WMS consumes Chaos Infusion.

**Comment by GeneralGormal** [comment]
powers info PS shows PSH not PS.

**Comment by shevarash** [comment]
These should all be fixed.
