### ISSUE TITLE
Sorc ET casting after bashed

### ISSUE THREAD

**Issue by theofficejackpot** [torilmud/issues#932]
You start chanting... [Casting: ET ()]

< 674h/674H 184p/184P 150v/150V (1) |ao 4|ec +|sb +|ar 30|est +|cn +|dw +|ts 1|dm 3|cs 10|pls +|lb
+|et +|ash +|drf +|qs 24| T: Kyzapple TC: excellent E: dragor EC: few wounds EP: std P: std > 

Casting: Etherealness **

< 674h/674H 184p/184P 150v/150V (1) |ao 4|ec +|sb +|ar 30|est +|cn +|dw +|ts 1|dm 3|cs 10|pls +|lb
+|et +|ash +|drf +|qs 24| T: Kyzapple TC: excellent E: dragor EC: few wounds EP: std P: std > 

Casting: Etherealness *
Dragor Keenblade badly wounds you with his mighty hit.
**Dragor Keenblade sends you sprawling.**

< 625h/674H 184p/184P 150v/150V (1) |ao 3|ec +|sb +|ar 29|est +|cn +|dw +|ts 1|dm 2|cs 9|pls +|lb
+|et +|ash +|drf +|qs 23| T: Kyzapple TC: few scratches E: dragor EC: few wounds EP: std P: sit > 

**You cast the spell 'Etherealness'.
Your form fades into a ghostly mist as you phase into the Ethereal Border.**

**Comment by GeneralGormal** [comment]
AR does too, it's intended.

**Comment by shevarash** [comment]
(Gormal is correct. Some Sorc spells can be cast in any position.)
