### ISSUE TITLE
Sorc getting bashed after blinding a mob

### ISSUE THREAD

**Issue by theofficejackpot** [torilmud/issues#933]
Question - is this due to the game mechanics overall for mobs that get bashed or a bug? 

You group-say '[Attacking: Woman]'

< 631h/712H 232p/232P 147v/150V (1) |ao +|ec +|sb +|ar +|est +|cn +|dw +|ts 1|dm 15|cs +|pls +|lb
+|et 32|ash +|drf +|qs 9| P: std >

You unleash a fiery blast at a lieutenant of the Knights in Silver, bathing her in searing flames.
**a lieutenant of the Knights in Silver is blinded by the intense heat!
A lieutenant of the Knights in Silver sends you sprawling.**

**Comment by GeneralGormal** [comment]
Those effects happened in the same instant, the problem isn't that he was blind, it's that mobs get a free opener on you when you start combat.  There's a ticket open below about it shev's responded to.

**Comment by shevarash** [comment]
(Gormal is correct.)
