### ISSUE TITLE
Draconic Sorc Bugs

### ISSUE THREAD

**Issue by GeneralGormal** [torilmud/issues#935]
DRF and LB don't smart target.  Engaged with enemies, casting it at the or without a target hits anything in the room.

**Comment by GeneralGormal** [comment]
You can't twinspell LB/DRF
Everything consumes twin:

**Comment by GeneralGormal** [comment]
DRF and LB take your combat action to start the cast and to complete it.

**Comment by GeneralGormal** [comment]
Sorcs of all flavors can target anything, regardless of if it's hidden, invisible to them, they are blind, etc.  Not just dropping DRF on the room (which maybe you should still be able to do? maybe sorcs need a downside?), but single target spells don't have any vision check.

**Comment by GeneralGormal** [comment]
Because Acidic Orb lasts 8 seconds, it's difficult to get more than 1 spell in during the debuff duration given 4s combat rounds.  Make it 10s please!

**Comment by GeneralGormal** [comment]
All sorcs: You cast the spell 'Astral Scrying'.
You cast your sight into the astral realms...
**You failed.**  <-- not sure what this is, but scrye seems to work differently from locate object.
some barrelstalk fungus carried by Rhomas Brison.
a small chunk of mithril ore in some sort of container.
a small chunk of mithril ore in some sort of container.

**Comment by shevarash** [comment]
These should all be fixed.

(I couldn't recreate the astral scrying issue though. Maybe re-open with a log if it still does that after this latest patch)
