### ISSUE TITLE
Toril support email is down

### ISSUE THREAD

**Issue by dnavarro** [torilmud/issues#94]
toril.support@gmail.com is not a valid address.

Proposal: Fix it or remove references to it. References include the github splash page.

Further consideration: What is the specific purpose of this email compared to the help email?

![2017-05-08 20_43_19-support test - donaldjnavarro gmail com - gmail](https://cloud.githubusercontent.com/assets/916506/25831124/d59ba376-342f-11e7-847f-d78da3d78496.png)

**Comment by shevarash** [comment]
I fixed the GH reference to it. I don't know of any other place it is.
