### ISSUE TITLE
trolls regen wielding valhalla

### ISSUE THREAD

**Issue by CountVooku** [torilmud/issues#95]
Trolls do not seem to get racial regen when wielding valhalla in defender mode. They only seem to get the 5hp per hit and not the extra 4-5 they get from regen in that same round.

**Comment by dnavarro** [comment]
Needs looking into to confirm

**Comment by Alurissi** [comment]
I also have noticed that trolls tend to have racial regen overwritten by valhalla, could be an issue with death pact being up, but there are also times when i feel that the regen takes over again, such as when you are in the minus hitpoints, i've recovered from -60 before.....

**Comment by beshaba-toril** [comment]
It's only during combat... Out if combat, normal Regen kicks back in.
Question is, does this only happen with Valhalla or does it also happen
with rune graven/other vampers?

-Besh

**Comment by Inames** [comment]
Unless this has been addressed already without being noted. I will claim that this report is false/mislead. I just tested it and I'm still regening 4-5 hp per round passively on top of my 5hp per hit with valhalla vs 1 mob. Check your ages perhaps? Trolls need to be quite young for passive regen to be optimal.

**Comment by CountVooku** [comment]
Someone else confirmed that they were not gaining racial regen while in combat (in defender mode) with valhalla. They did say they were getting regen when using runed graven. I can't remember who it was at the moment.

**Comment by Inames** [comment]
I'm going to say this without trying to sound like a dick... 95% of people on this game don't understand the mechanics of the game. Get your age dropped to 16 on your troll, go take valhalla and go fight something without valhalla on, or in offense mode till you take some damage, then swap it to defense, and note that you should be gaining 4-5 hp per round from regen, and 5 hp per hit, so with haste and double attack, if you are getting 20hp per round with 3 successful attacks, it's working fine. Note that dodges/parries still count as vamping hits. It was working fine for me last night.

**Comment by Inames** [comment]
Granted there could be some other underlying issue that's only affecting certain people. But in the most simple situation in most basic fashion. There is no issue. And I doubt there's any significant difference between my troll/gear and everyone else's that could be affecting it unless your trolls are just old.

**Comment by CountVooku** [comment]
I went from age 37 down to 17 and it seems like I am getting troll regen now. Thanks for the heads up. Didn't even think about how troll age might affect regen.

**Comment by CountVooku** [comment]
My troll is age 37 and change btw.
