### ISSUE TITLE
In game ANSI testing command

### ISSUE THREAD

**Issue by xanza-tey** [torilmud/issues#957]
Talked about this on gcc a bit, but making the formal request here!

In game method of testing ansi!

Some sort of in-game command (something like how you can test assoc titles) that allows ansi testing.

My particular use-case is for learning the gradient/tint/tone system and testing zone writing pieces, such as equipment strings, mob names, etc.

I'm unclear on if it could be wrapped in the same command, but being able to test traditional &+r or the newer {{ }} systems would be fantastic

Thanks!

**Comment by marthammor** [comment]
This is an option already for staff. If you've been approved for writing a zone, you could ask for a staff member on our testmud to use this feature. I'm not sure what reason anyone else would need for this, really.
Although, I suppose there really isn't a reason non-staff couldn't use it either.

What do you think? @cmoncrief ?

**Comment by xanza-tey** [comment]
I hadn't really seen a process for getting approved to write a zone, so that's a new aspect to me.

I do a lot of my prep work in google docs/sheets far ahead of time in brainstorming layout, storyline, npcs and building out room names/desc's, items and more. So I'll randomly add a piece here and there through the day, or while tinkering around online already.

I was hoping to remove the need to involve other people during that drawn out process of brainstorm by having to boot up a testmud or any other sort of secondary permissions that someone else has to manage down the road. 

Mostly just to remove having to bother other people while I plink away on ideas

**Comment by GeneralGormal** [comment]
Does Kegor's new editor do this?

**Comment by xanza-tey** [comment]
No, it has the basic new {{ }} ansi stuff in it, but doesn't have the full 15mil + all the effects that can be done with saturation/gradient, etc
