### ISSUE TITLE
Glitchy Zone Echoes

### ISSUE THREAD

**Issue by GeneralGormal** [torilmud/issues#969]
I've noticed a few zone echos have gotten glitchy of late, I think Demi also had an issue or two.

This one's from muspel specifically.
![muspelecho](https://github.com/torilmud/issues/assets/38932922/4e515f39-8ee5-4b14-81ba-f77ebd2d7772)

**Comment by theofficejackpot** [comment]
another example:

```
The colors of the world shift and blur before erupting in a blast of prismatic light!
The shockwave of prismatic energy envelops Ultrumm!
 **is blinded by the shifting lights!**
```
missing mob name

**Comment by marthammor** [comment]
> another example:
> 
> ```
> The colors of the world shift and blur before erupting in a blast of prismatic light!
> The shockwave of prismatic energy envelops Ultrumm!
>  **is blinded by the shifting lights!**
> ```
> 
> missing mob name

This isn't a zone echo. I checked the power message though and it looks correct, but is this maybe an issue with a script? The power does not have the *'s in it.

**Comment by marthammor** [comment]
Are people still seeing issues with zone echoes? I sat in muspel for a while and didn't notice anything. I'm also using the classic prompt though, so maybe a new prompt specific thing?

**Comment by shevarash** [comment]
I believe this is all fixed now. IT was due to some memory corruptions that were also crashing us and have now been resolved. If you see it agian please re-open with a new example.
