### ISSUE TITLE
Sorc Prep command of some sort please

### ISSUE THREAD

**Issue by i982** [torilmud/issues#973]
unless there is one..
a prep command to see the cooldown remaining if you arent using the fancy prompt.

just hitting the spell over and over waiting for the cooldown to run out (chromatic disc) for example.. 

just didnt know if there is a prep command like for all the other redone classes.

if there is feel free to reply with it please:)

**Comment by GeneralGormal** [comment]
Type spells or recharge.

Or don't use nyyscript outside of it's intended use (exp train)

**Comment by shevarash** [comment]
`spells` is indeed the right command:

```
You have the following spells available:
 + Hellforged Avatar              
 + Shadowslip                     
 + Hex of Shattered Defenses      
 - Cloak of Flies                    1 minute 28 seconds 
 + Hex of Lingering Doom          
 + Blazing Doom                   
 + Eldritch Chains                
 + Hex of Arcane Disruption       
 + Eldritch Renewal               
 + Spectral Fade                  
 + Spider Scuttle                 
 + Astral Eyes     
 ```
