### ISSUE TITLE
black mithril battle torque - stats are horrible for work needed for the quest

### ISSUE THREAD

**Issue by Faedril** [torilmud/issues#976]
This was a super disappointing reward.

ac 8 4 dam -1 sv spell good warrior only, super super long quest.

competitors.
a heavy neckband with iron studs ac 10 3 dam
a glowing otherplanar neckguard ac 12 3 dam -4 ss
a runed mithril pendant set with a sapphire or ruby ac 5 3 dam 3 max agil 5% elec or 5% fire
a spiked iron choker ac 9 2 2 4% unarmed
volance ac 22 5 dam 30 hps mirror image/fly

quest needs:
6xchainmail masks                                  quest 
a magical chalice			                normal load
a jeweled silver chalice		                Rare
a golden chalice covered with rubies	Rare
a chalice of healing Waters		        normal load
chalice of the elven gods		        Epic quest reward
a chalice of glorious sanctity		        rare Baha item
a golden mug dedicated to Sharindlar   quest - 2 quests plus 2 rares plus 2 normal items
Star Sapphire                                           normal load
Star Emerald                                            normal load
Star Ruby                                                 quest
Exquisite Diamond                                   quest
beautiful Agate                                        normal load
Sparkling Fire Opal                                  qest 2 rare loads

Think about what it takes to start this quest from nothing.

You have to do Erlan's quest.
You have to do Baha
You have to gather 5 normal items
You have to find 2 rares
you have to complete 4 other quests (that all include yet more quests and more rares)
*and* its good only.

give it one of:
5% all physical resists
5% all elemental resists
50 hps
a useful power that either reduces damage or increases hps.
something to at least make it interesting for a warrior class to wear.

Or, take out the baha chalice and the erlan chalice.
the fact that you have to do baha and do erlans should drive this items stats up.
frankly, by the time you collect all this stuff, you'll win a volance.

**Comment by shevarash** [comment]
Forwarded to the zone creator. Thanks!
