### ISSUE TITLE
holy strike power doesn't heal

### ISSUE THREAD

**Issue by GeneralGormal** [torilmud/issues#979]
Name             : Holy Strike [holys]
Type             : Melee
Attack Type      : Auto
Target           : Offense
Recharge         : 12 seconds 
Restrictions     : Standing
Race Allow    (T): Subtype Undead

Effects:
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Target Effect    : Deal 5d10 positive damage
Self Effect      : --> Vampiric heal 100% of preceding damage, up to 100% of max 

Description:
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Deals level 1 offensive damage to melee target, if undead.  Heals the user by the
same amount.  Useable every 12 seconds.

< 584h/709H 170v/170V T: Asani TC: small wounds E: spectre EC: few wounds EP: std P: std > holys
Your dagger glows like the sun, as it is filled with holy radiance.
The radiant aura around your dagger partially dissolves the fiendish spectre.

< 584h/709H 170v/170V T: Asani TC: small wounds E: spectre EC: few wounds EP: std P: std >

**Comment by Lilithelle** [comment]
This has been fixed.
