### ISSUE TITLE
Sequester Quester isn't targetting player properly in Westgate

### ISSUE THREAD

**Issue by GeneralGormal** [torilmud/issues#980]
You give a belt of swirling mist to High Mistmistress Halautha Immerstar.
High Mistmistress Halautha Immerstar says, 'Go west and touch glamer.'

High Mistmistress Halautha Immerstar gives you a belt of swirling mist.
High Mistmistress Halautha Immerstar smiles smugly.

< |cb   +|pe   +|top  +|      |ts   +|psh  +|et   +|      |      |wms  +| >
< |eb   +|ps   +|cs   +|      |qs   +|ar  11|pls  +|      |      |cn   +| >
< 970h/1016H 250v/250V (5) P: std >
High Mistmistress Halautha Immerstar starts casting a spell.

< |cb   +|pe   +|top  +|      |ts   +|psh  +|et   +|      |      |wms  +| >
< |eb   +|ps   +|cs   +|      |qs   +|ar  11|pls  +|      |      |cn   +| >
< 972h/1016H 250v/250V (5) P: std >w
                        

   .-. .-. .-. .-. .-. .-. .-.   
  ---------   -------------------
  |       |.-.|                  
  |       |   |                  
  |       |.-.|                  
  |       |   |-------           
  |       |.-.|.@. .-.|          
  |       |   -----   |          
  |       |.-.#.-. .-.|          
  |       |   --------           
  |       |.-. .-.|              
  ---------   ----               
   .-. .-. .-.|                  
                        
The Hidden House - Room of Mist (Fogged)
Exits: -E
A globe of thick fog floats here.

< |cb   +|pe   +|top  +|      |ts   +|psh  +|et   +|      |      |wms  +| >
< |eb   +|ps   +|cs   +|      |qs   +|ar  10|pls  +|      |      |cn   +| >
< 973h/1016H 249v/250V (5) P: std >touch glamer
You touch a glamer.

< |cb   +|pe   +|top  +|      |ts   +|psh  +|et   +|      |      |wms  +| >
< |eb   +|ps   +|cs   +|      |qs   +|ar  10|pls  +|      |      |cn   +| >
< 974h/1016H 250v/250V (5) P: std >
A glamer casts the spell 'Sequester'.

**Comment by Lilithelle** [comment]
This is fixed in the current version.
