### ISSUE TITLE
Double Dragon Breath

### ISSUE THREAD

**Issue by Faedril** [torilmud/issues#982]
It really looks like its hitting twice.

< 743h/693H 169v/170V |ts +|ss +|ap +|ev +|bs +| |3|2|2|1|0| T: Elterras TC: excellent E: black EC:
few scratches EP: std P: std >

[No longer moving. Spellcasting has resumed]

[MELEE: Sweeping Strike] SS

OUCH!  That really did HURT!
An ancient black dragon misses you with his claw.
An ancient black dragon breathes a stream of corrosive acid!

An ancient black dragon breathes a stream of corrosive acid!
OUCH!  That really did HURT!
An ancient black dragon misses you with his claw.
OUCH!  That really did HURT!
An ancient black dragon breathes a stream of corrosive acid!

An ancient black dragon breathes a stream of corrosive acid!
OUCH!  That really did HURT!
OUCH!  That really did HURT!
The black dragon consort misses you with his claw.
The black dragon consort misses you with his claw.
The black dragon consort misses you with his claw.
The black dragon consort breathes a stream of corrosive acid!

The black dragon consort breathes a stream of corrosive acid!
YIKES!  Another hit like that, and you've had it!!
Your attack glances harmlessly off of the black dragon consort's scales!
Your attack glances harmlessly off of the black dragon consort's scales!
Your spell is partially absorbed by the black dragon consort.
Your massive flame-enshrouded bludgeon barely wounds the black dragon consort.
Your attack is partially absorbed by the black dragon consort's scales!
Your spell is partially absorbed by the black dragon consort.
Your powerful flame-enshrouded slash barely wounds the black dragon consort.
You miss the black dragon consort with your flame-enshrouded bludgeon.
Your attack is partially absorbed by the black dragon consort's scales!
Your spell is partially absorbed by the black dragon consort.
Your powerful flame-enshrouded bludgeon barely wounds the black dragon consort.

**Comment by GeneralGormal** [comment]
This is using Nyy's bot full of a million gags FYI.

**Comment by shevarash** [comment]
Does this happen often or just the once?

**Comment by Faedril** [comment]
Happens alot from what I've seen.
This is from ZMUD today:   
You miss a green guardian dragon with your hit.
A green guardian dragon snaps into visibility.
A green guardian dragon misses you with its claw.
A green guardian dragon misses you with its claw.
A green guardian dragon breathes a cloud of toxic gas!

A green guardian dragon breathes a cloud of toxic gas!
OUCH!  That really did HURT!

**Comment by shevarash** [comment]
This fixed in a recent update. Thanks for the report!
