### ISSUE TITLE
Scardale maxloads

### ISSUE THREAD

**Issue by darqen27** [torilmud/issues#983]
With the recent influx of new players, quests have become difficult to complete as quest items and mobs are not spawning after one player has gone through them.  
I read a while back that maxloads for scardale were increased. 
Was this removed at some point?

**Comment by marthammor** [comment]
This is still the case. All items have a chance to repop when the mob respawns (except one item, which I'll fix now.).

**Comment by darqen27** [comment]
okay, thank you for the quick response.

**Comment by marthammor** [comment]
Going to close this since this is resolved. Thank you!
