### ISSUE TITLE
scardale taxidermist issues

### ISSUE THREAD

**Issue by darqen27** [torilmud/issues#984]
I have been playing a few characters in scardale over the past week, putting in many hours and this taxidermist for the rabbit foot quest is not spawning.

"A tall man, covered in layer upon layer of furs, stands here grinning at you." <---- This is the mob name i found when I looked it up.

He has never spawned in many many hours of scardale. 

I think his spawn rate may need to be adjusted.

**Comment by marthammor** [comment]
He's rare. Working as intended.
