### ISSUE TITLE
Voidcaller Hexblade:  Hexblast is not generating combo points

### ISSUE THREAD

**Issue by Faedril** [torilmud/issues#985]
Based on the website:  http://www.torilmud.com/news/enter-the-voidcaller/
Hexblast: Channels eldritch magic through your weapon to cause some damage and reduce the target's armor. Builds hex power.

From the mud:
Name             : Hexblast [hb]
Type             : Melee                    
Attack Type      : Armor                    
Target           : Offense, Character in room
Stacks           : Yes
Implements       : Dual wield
Restrictions     : Standing, Can See

Effects:
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Target Effect    : Deal 50% of attack power (85) as negative damage   
Target Effect    : --> Modify armor by 10 for 12 seconds              

Description:
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
This attack channels a blast of eldritch magic through the user's weapon to strike
the target. The target will take damage from the attack and also have their armor
class degraded for a short time. 

Was the combo generator missed? Or is voidcaller only getting 1 generator?

**Comment by shevarash** [comment]
Fixed!
