### ISSUE TITLE
gleaming two-handed bastardsword

### ISSUE THREAD

**Issue by darqen27** [torilmud/issues#992]
'a gleaming two-handed bastardsword (Slot: Wielded), Damroll: 4, Hitroll: 4
(Item Type: Weapon) Damage Dice: 4D7, Crit Chance: 6%, Crit Multiplier: 2x, (Class: Martial, Type: 
Greatsword) * Procs: Gleaming Burst * Float, Hidden, Magic, No Burn, No Locate, Two Handed NO-MAGE 
NO-CLERIC NO-THIEF *

Sword has proc listed but proc never pops

**Comment by shevarash** [comment]
It only procs for good aligned characters. Were you perhaps using it on an evil char?
